
-------------Batch Create

SELECT * FROM EPAY_PAYMENT_MST_X
ORDER BY BATCH_NO ASC

/*
SELECT A.DTL_PDB_AMOUNT,B.REV_STMP_AMT,A.DTL_PDB_AMOUNT-B.REV_STMP_AMT AS DTL_NET_AMT,A.DTL_GOVT_DUTE FROM (
SELECT :P_BATCH_NO AS BATCH_NO ,SUM(PDB_AMOUNT) AS DTL_PDB_AMOUNT,SUM(GOVT_DUTY) AS DTL_GOVT_DUTE FROM PAYMENT_DTL_X
WHERE BATCH_NO=:P_BATCH_NO) A,
(SELECT :P_BATCH_NO REV_BATCH_NO,5*SUM(COUNT(BILL_NUMBER)) AS REV_STMP_AMT FROM PAYMENT_DTL_x
WHERE BATCH_NO=:P_BATCH_NO                                            
GROUP BY BILL_NUMBER
HAVING SUM(PDB_AMOUNT+GOVT_DUTY)>=500) B
WHERE A.BATCH_NO=B.REV_BATCH_NO
*/

UPDATE EPAY_PAYMENT_MST_X
SET --LOCATION_CODE='W1',-------- SET OF LOCATION CODE 
    --PAY_DATE='18-FEB-2014',------ SET OF PAYMENT DATE  
   (TOTAL_PDB_AMOUNT,REVENUE_STAMP_AMOUNT,NET_PDB_AMOUNT,TOTAL_GOVT_DUTY)=
       (SELECT A.DTL_PDB_AMOUNT,B.REV_STMP_AMT,A.DTL_PDB_AMOUNT-B.REV_STMP_AMT AS DTL_NET_AMT,A.DTL_GOVT_DUTE FROM (
        SELECT :P_BATCH_NO AS BATCH_NO ,SUM(PDB_AMOUNT) AS DTL_PDB_AMOUNT,SUM(GOVT_DUTY) AS DTL_GOVT_DUTE FROM EPAY_PAYMENT_DTL_X
        WHERE BATCH_NO=:P_BATCH_NO) A,
       (SELECT :P_BATCH_NO REV_BATCH_NO,10*SUM(COUNT(BILL_NUMBER)) AS REV_STMP_AMT FROM EPAY_PAYMENT_DTL_X
        WHERE BATCH_NO=:P_BATCH_NO                                            
        GROUP BY BILL_NUMBER
        HAVING SUM(PDB_AMOUNT+GOVT_DUTY)>=1000) B
        WHERE A.BATCH_NO=B.REV_BATCH_NO)
        ,    STATUS='P'
        ,
    CREATED_ON=SYSDATE,
    CREATED_BY='admin',
    MODIFIED_ON=SYSDATE,
    MODIFIED_BY='admin' 
WHERE BATCH_NO=:P_BATCH_NO
AND LOCATION_CODE=:P_LOCATION_CODE
;

UPDATE EPAY_PAYMENT_DTL_X
SET SCROLL_NO=ROWNUM
, 
    BATCH_CODE='NA',
    STATUS='N',
    CREATED_ON=SYSDATE,
    CREATED_BY='BPDB',
    MODIFIED_NO=SYSDATE,
    MODIFIED_BY='BPDB'
WHERE BATCH_NO=:P_BATCH_NO;

SELECT EPAY_SEQ_PAY_BATCH_NO.NEXTVAL AS NEW_BATCH_NO  FROM DUAL

94983

UPDATE EPAY_PAYMENT_MST_X
SET BATCH_NO=:NEW_BATCH_NO
WHERE BATCH_NO=:P_BATCH_NO

UPDATE EPAY_PAYMENT_DTL_X
SET BATCH_NO=:NEW_BATCH_NO
WHERE BATCH_NO=:P_BATCH_NO

COMMIT;

---------------------------Batch amount check sql


select a.batch_no MST_BATCH_NO,PDTL.BATCH_NO DTL_BATCH_NO,a.TOTAL_PDB_AMOUNT MST_pdb_amount,PDTL.dtl_pdb_amount,
a.TOTAL_GOVT_DUTY MST_govt_duty,PDTL.dtl_govt_duty 
from EPAY_PAYMENT_MST_X a,
    (select b.batch_no,sum(nvl(b.PDB_AMOUNT,0)) dtl_pdb_amount,sum(nvl(b.GOVT_DUTY,0)) dtl_govt_duty
    from EPAY_PAYMENT_DTL_X b
    group by batch_no) pdtl
WHERE a.batch_no=pdtl.batch_no
--AND (a.TOTAL_PDB_AMOUNT<>PDTL.dtl_pdb_amount OR a.TOTAL_GOVT_DUTY<>PDTL.dtl_govt_duty)


select a.batch_no MST_BATCH_NO,PDTL.BATCH_NO DTL_BATCH_NO,a.TOTAL_PDB_AMOUNT MST_pdb_amount,PDTL.dtl_pdb_amount,
a.TOTAL_GOVT_DUTY MST_govt_duty,PDTL.dtl_govt_duty 
from PAYMENT_MST_MANUAL a,
    (select b.batch_no,sum(nvl(b.PDB_AMOUNT,0)) dtl_pdb_amount,sum(nvl(b.GOVT_DUTY,0)) dtl_govt_duty
    from PAYMENT_DTL_MANUAL b
    group by batch_no) pdtl
WHERE a.batch_no=pdtl.batch_no
AND a.TOTAL_PDB_AMOUNT=PDTL.dtl_pdb_amount
AND a.TOTAL_GOVT_DUTY=PDTL.dtl_govt_duty


select PDTL.TOTAL_TRANS,a.batch_no MST_BATCH_NO,PDTL.BATCH_NO DTL_BATCH_NO,a.TOTAL_PDB_AMOUNT MST_pdb_amount,PDTL.dtl_pdb_amount,
a.TOTAL_GOVT_DUTY MST_govt_duty,PDTL.dtl_govt_duty 
from PYMT_MST_DUP_BATCH a,
    (select b.batch_no,sum(nvl(b.PDB_AMOUNT,0)) dtl_pdb_amount,sum(nvl(b.GOVT_DUTY,0)) dtl_govt_duty,COUNT(BILL_NUMBER) AS TOTAL_TRANS
    from PYMT_DTL_DUP_BATCH b
    WHERE BATCH_NO='16808'
    group by batch_no) pdtl
WHERE a.batch_no=pdtl.batch_no
 AND A.BATCH_NO='16808'
 
 
 select PDTL.TOTAL_TRANS,a.batch_no MST_BATCH_NO,PDTL.BATCH_NO DTL_BATCH_NO,a.TOTAL_PDB_AMOUNT MST_pdb_amount,PDTL.dtl_pdb_amount,
a.TOTAL_GOVT_DUTY MST_govt_duty,PDTL.dtl_govt_duty 
from PAYMENT_MST a,
    (select b.batch_no,sum(nvl(b.PDB_AMOUNT,0)) dtl_pdb_amount,sum(nvl(b.GOVT_DUTY,0)) dtl_govt_duty,COUNT(BILL_NUMBER) AS TOTAL_TRANS
    from PAYMENT_DTL b
    WHERE BATCH_NO='16808'
    group by batch_no) pdtl
WHERE a.batch_no=pdtl.batch_no
 AND A.BATCH_NO='16808'


------------------GAP FINDINGG SQL
 
SELECT batch_no+1 FROM dbersice.payment_mst@prodpdb.US.ORACLE.COM mo
WHERE   NOT EXISTS
        (
        SELECT  NULL FROM dbersice.payment_mst@prodpdb.US.ORACLE.COM mi 
        WHERE   mi.batch_no = mo.batch_no + 1
        )
ORDER BY batch_no ASC


SELECT * FROM dbersice.payment_mst@prodpdb.US.ORACLE.COM mo
WHERE BATCH_NO='74992'

SELECT * FROM payment_mst
WHERE BATCH_NO='74992'

SELECT * FROM EP_RECEIPT_BATCH_HDR_PDB
WHERE BATCH_NUM_GP='74992'


------------------------EPAY-------------------------




SELECT BATCH_NO,REF_BATCH_NO,BILL_NUMBER,BATCH_CODE,SCROLL_NO,TRANSACTION_ID,PDB_AMOUNT,GOVT_DUTY,STATUS,CREATED_ON,CREATED_BY,MODIFIED_NO,MODIFIED_BY,MOBILE_NO,E_MAIL_ADDR FROM EPAY_PAYMENT_dtl
where ref_batch_no='39651'

SELECT COLUMN_NAME||',' FROM DBA_TAB_COLUMNS
WHERE TABLE_NAME='EPAY_PAYMENT_MST'
ORDER BY COLUMN_ID


SELECT * FROM PAYMENT_MST@epay_robi
where batch_no='39651'


INSERT INTO EPAY_PAYMENT_DTL_X
SELECT '23524' AS BATCH_NO,BATCH_NO AS REF_BATCH_NO,BILL_NUMBER,BATCH_CODE,SCROLL_NO,TRANSACTION_ID,PDB_AMOUNT,GOVT_DUTY,STATUS,CREATED_ON,CREATED_BY,MODIFIED_NO,MODIFIED_BY,NULL MOBILE_NO,NULL E_MAIL_ADDR FROM PAYMENT_dtl@epay_robi
where batch_no='39651'

INSERT INTO EPAY_PAYMENT_MST_X
SELECT '23524' AS BATCH_NO,BATCH_NO AS REF_BATCH_NO,LOCATION_CODE,PAY_DATE,TOTAL_PDB_AMOUNT,REVENUE_STAMP_AMOUNT,NET_PDB_AMOUNT,TOTAL_GOVT_DUTY,
STATUS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,'97' AS PAY_BANK_CODE,'0081' AS PAY_BRANCH_CODE,USER AS USER_NAME
  FROM PAYMENT_mst@epay_robi
where batch_no='39651'

DELETE FROM EPAY_PAYMENT_dtl_X
WHERE BILL_NUMBER IN (
SELECT BILL_NUMBER FROM EPAY_PAYMENT_dtl
where ref_batch_no='39651')


INSERT INTO EPAY_PAYMENT_DTL
SELECT * FROM EPAY_PAYMENT_DTL_X
where batch_no='94983'


INSERT INTO EPAY_PAYMENT_MST
SELECT * FROM EPAY_PAYMENT_MST_X
where batch_no='94983'


 DELETE FROM EPAY_PAYMENT_DTL
where ref_batch_no='39651'


DELETE  FROM EPAY_PAYMENT_MST
where ref_batch_no='39651'


select * from epay_utility_bill
where bill_number in (
SELECT BILL_NUMBER FROM EPAY_PAYMENT_DTL_X
where batch_no='94983')


SELECT *  FROM EPAY_RECEIPT_BATCH_HDR_PDB
where BATCH_NUM_EPAY='94983'