
DBLINK                    CENTER NAME
------------------------------------------
BILLING_COM         COMILLA

BILLING_CTG          CHITTAGONG

BILLING_RAJ         RAJSHAHI
BILLING_BOG         BOGRA
BILLING_NAO         NAOGAON
BILLING_PAB         PABNA

BILLING_SYL         SYLHET
BILLING_MOU         MOULAVIBAZAR

BILLING_RONG        RANGPUR
BILLING_DIN             DINAJPUR

BILLING_MYMEN           MYMENSING
BILLING_JAM                 JAMALPUR
BILLING_KISHOR              KISHOREGANJ
BILLING_TANG            TANGAIL

-------------------- SQL OF 1 -------------------------


TRUNCATE TABLE EPAY_UTILITY_BILL_GPR_x;


DELETE FROM EPAY_UTILITY_BILL_GPR_x;


COMMIT;


INSERT INTO EPAY_UTILITY_BILL_GPR_x
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_ctg
 WHERE BILL_CYCLE_CODE=:P_BILL_MONTH
--AND TARIFF IN ('A','C','B','D','E','J')
---and customer_num='5535583'
AND DATA_TRANS_LOG='N'
--and customer_num not in (select customer_num from EPAY_DUPLICATE_CUSTOMER)
--AND TO_CHAR(INVOICE_DUE_DATE,'yyyymmdd')>=(SELECT  TO_CHAR(SYSDATE,'yyyymmdd') FROM DUAL)
AND INVOICE_NUM IS NOT NULL
AND  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%CHITTAGONG%');
                                       
                      
COMMIT;


DELETE FROM EPAY_UTILITY_BILL_GPR_x
WHERE ROWID IN (
SELECT ROWID FROM EPAY_UTILITY_BILL_GPR_x
MINUS
SELECT MAX(ROWID) FROM EPAY_UTILITY_BILL_GPR_x
GROUP BY ACCOUNT_NUMBER, BILL_NUMBER, LOCATION_CODE);


COMMIT;


DELETE  FROM EPAY_UTILITY_BILL_GPR_x
WHERE (ACCOUNT_NUMBER,LOCATION_CODE) IN (
SELECT ACCOUNT_NUMBER,LOCATION_CODE FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=:P_BILL_MONTH
)


COMMIT;


INSERT INTO EPAY_UTILITY_BILL
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,'N' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL_GPR_x


delete  FROM EPAY_UTILITY_BILL_GPR_x
WHERE ACCOUNT_NUMBER not IN (SELECT ACCOUNT_NO  from EPAY_CUSTOMER_MASTER_DATA)



COMMIT;


DELETE FROM EPAY_CUST_MASTER_DATA_GPR_X;


TRUNCATE TABLE EPAY_CUST_MASTER_DATA_GPR_X;


COMMIT;

    
INSERT INTO EPAY_CUST_MASTER_DATA_GPR_X
(COMPANY_CODE,ACCOUNT_NO,NAME,LOCATION_CODE,AREAR_CODE,ACTIVATION_DATE,STATUS,CREATED_ON ,DUMPING_FOR, CREATED_BY)
SELECT 'BPDB', CUSTOMER_NUM||CHECK_DIGIT,CUSTOMER_NAME,LOCATION_CODE,AREA_CODE,  TO_DATE(START_BILL_CYCLE,'rrrrmm'),
DECODE (CUSTOMER_STATUS_CODE,'C','A','S','A','I') STATUS,  SYSDATE,    'U','ROBIBPDB' 
FROM BC_CUSTOMERS@BILLING_ctg
WHERE (CUSTOMER_NUM) IN (SELECT SUBSTR(ACCOUNT_NUMBER,1,7) FROM EPAY_UTILITY_BILL_GPR_x);


COMMIT;


INSERT INTO EPAY_CUSTOMER_MASTER_DATA
SELECT * FROM EPAY_CUST_MASTER_DATA_GPR_X
WHERE ( ACCOUNT_NO) IN ( 
SELECT  ACCOUNT_NO FROM EPAY_CUST_MASTER_DATA_GPR_X
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER)
MINUS 
SELECT  ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER)
);


COMMIT;


UPDATE BC_BILL_IMAGE@BILLING_pab
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE=:P_BILL_MONTH
AND (CUSTOMER_NUM,LOCATION_CODE) IN (
SELECT SUBSTR(A.ACCOUNT_NUMBER,1,7),LOCATION_CODE FROM EPAY_UTILITY_BILL_GPR_x A);


COMMIT;
