
INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_BOG
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_BOG
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_BOG
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_BOG
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_BOG
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS ='A'))))));

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_RONG
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_RONG
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_RONG
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_RONG
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_RONG
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS ='A'))))));

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_NAO
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_NAO
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_NAO
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_NAO
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_NAO
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS ='A'))))));

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_TANG
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_TANG
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_TANG
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_TANG
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_TANG
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS ='A'))))));

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_DIN
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_DIN
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_DIN
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_DIN
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_DIN
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS ='A'))))));

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_PAB
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_PAB
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_PAB
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_PAB
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_PAB
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS ='A'))))));

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_MOU
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_MOU
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_MOU
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_MOU
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_MOU
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS ='A'))))));

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_MYMEN
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_MYMEN
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_MYMEN
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_MYMEN
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_MYMEN
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS ='A'))))));

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_SYL
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_SYL
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_SYL
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_SYL
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_SYL
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS ='A'))))));

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_RAJ
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_RAJ
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_RAJ
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_RAJ
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_RAJ
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS ='A'))))));

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_JAM
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_JAM
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_JAM
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_JAM
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_JAM
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS ='A'))))));

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_KISOR
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_KISOR
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_KISOR
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_KISOR
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_KISOR
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS ='A'))))));

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_COM
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_COM
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_COM
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_COM
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_COM
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS ='A'))))));

COMMIT;
