
-----GP RECON DATA------

SELECT * FROM EPAY.VW_EPAY_RECON_UNSUC_OPT_GP

SELECT * FROM EPAY.VW_EPAY_RECON_UNSUC_OPT_ROBI

SELECT * FROM EPAY.VW_EPAY_RECON_UNSUC_OPT_ERR
WHERE LOCATION_CODE='M7'
AND BANK_CODE='97'

--BILL DOSES NOT BPDB-----

SELECT EPAY.DFN_BILLNO_DOES_NOT_EXIST_BPDB (:P_Center_Name) FROM DUAL


---PAYMENT DATA LESS-------

SELECT EPAY.DFN_PAYMENT_DATA_LESS (:P_BILL_MONTH ,:P_BILL_NO ,:P_LOC_CODE ,:P_BANK_CODE ) FROM DUAL


----BANK RECON ERROE CHK-----

SELECT * FROM EPAY.VW_EPAY_RECON_UNSUC_PDB_BNK
ORDER BY STATUS DESC

SELECT EPAY.DFN_EPAY_BANK_RECON_ERR_SLOV (:P_BATCH_NO ,:P_LOCATION_CODE) FROM DUAL


-----MYMEN TANG PROB----------


SELECT LOCATION_CODE,A.* FROM UTILITY_BILL_PDB@EPAY_ROBI A
WHERE BILL_MONTH=(SELECT TO_CHAR (ADD_MONTHS (SYSDATE, -1), 'RRRRMM') FROM DUAL)
AND ACCOUNT_NUMBER ='76250911'


select * from customer_master_data_pdb@epay_robi
where account_no ='76250911'


SELECT * FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=(SELECT TO_CHAR (ADD_MONTHS (SYSDATE, -1), 'RRRRMM') FROM DUAL)
AND ACCOUNT_NUMBER ='76257251'

select * from EPAY_customer_master_data
where account_no ='76250911'

SELECT EPAY.DFN_EPAY_MYM_TANG_DUP_CONS (:P_BILL_MONTH ,:P_LOCATION_CODE ,:P_BILL_GROUP ) FROM DUAL


---169----

---SINGLE DATA UPLOAD----

SELECT EPAY.DFN_SING_DATA_UPL (:P_LOCATION_CODE ,:P_BILL_NUM ) FROM DUAL


-----BANK BATCH REMOVE--

SELECT * FROM VW_1EPAY_BANK_PYMT_UNVALED

SELECT * FROM VW_1EPAY_BANK_PYMT_VALED_ALL

SELECT EPAY.DFN_EPAY_BTCH_REMOVE (:P_Batch_No) FROM DUAL