BILL INFORMATION :

SELECT * FROM  EPAY.V_MONTH_WISE_BILL_DATA_GP
WHERE BILL_MONTH BETWEEN :P_START_BILL_MONTH AND :P_END_BILL_MONTH


SELECT * FROM  EPAY.V_DUE_DATE_WISE_BILL_DATA_ROBI
WHERE BILL_MONTH BETWEEN :P_START_BILL_MONTH AND :P_END_BILL_MONTH






ARREAR INFORMATION :
      
SELECT * FROM  EPAY.V_ARREAR_CUSTOMER_ROBI
WHERE BILL_MONTH BETWEEN :P_START_BILL_MONTH AND :P_END_BILL_MONTH  







RECONCILED INFORMATION :
 
SELECT * FROM  EPAY.V_DAY_WISE_TRANSACTION_ROBI  
WHERE TO_CHAR(PAY_DATE,'RRRRMM') BETWEEN :P_START_PAY_MONTH AND :P_END_PAY_MONTH

SELECT * FROM  EPAY.V_DAY_WISE_RECONCILED_ROBI
WHERE TO_CHAR(PAY_DATE,'RRRRMM') BETWEEN :P_START_PAY_MONTH AND :P_END_PAY_MONTH 

SELECT * FROM  EPAY.V_DAY_WISE_NOTRECONCILED_ROBI
WHERE TO_CHAR(PAY_DATE,'RRRRMM') BETWEEN :P_START_PAY_MONTH AND :P_END_PAY_MONTH 

SELECT * FROM  EPAY.V_DAY_WISE_TOTAL_TRANSFER_ROBI
WHERE TO_CHAR(PAY_DATE,'RRRRMM') BETWEEN :P_START_PAY_MONTH AND :P_END_PAY_MONTH







COLLECTION INFORMATION :

SELECT * FROM  EPAY.V_MONTH_WISE_COLLECTION_ROBI
WHERE PAYMENT_MONTH BETWEEN :P_START_PAY_MONTH AND :P_END_PAY_MONTH

SELECT * FROM  EPAY.V_ZONE_WISE_COLLECTION_ROBI 
WHERE PAYMENT_MONTH BETWEEN :P_START_PAY_MONTH AND :P_END_PAY_MONTH