SELECT B.CUSTOMER_NUM , C.CUSTOMER_NAME,B.CONS_EXTG_NUM Acount_no,
 nvl(ENG_CHRG_SR,0)+NVL(ENG_CHRG_OFPK ,0)+NVL(ENG_CHRG_PK,0)+nvl(MINIMUM_CHRG,0)+nvl(SERVICE_CHRG,0)+ nvl(DEMAND_CHRG,0)
  +NVL(PFC_CHARGE,0)+NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0) Billed_Amount,
  NVL(TOTAL_BILL,0)- 
  (NVL(CURRENT_LPS,0)+NVL(ADJUSTED_LPS,0)+NVL(ARR_ADV_ADJ_LPS,0)
  +NVL(CURRENT_VAT,0)+NVL( ADJUSTED_VAT,0)+NVL(ARR_ADV_ADJ_VAT,0)) Recievable,
  NVL(CURRENT_LPS,0)+NVL(ADJUSTED_LPS,0)+NVL(ARR_ADV_ADJ_LPS,0) Surcharge,
  (nvl(RCPT_PRN_1,0)+nvl(RCPT_PRN_2,0)+nvl(RCPT_PRN_3,0) ) CollAmnt,
  NVL(CURRENT_VAT,0)+NVL( ADJUSTED_VAT,0)+NVL(ARR_ADV_ADJ_VAT,0)Vat,Total_Bill
       from bc_bill_image B,BC_CUSTOMERS C where 
       B.location_code=:LOC_CODE and
       B.CUST_ID=C.CUST_ID AND
B.cust_ID in( SELECT CUST_ID FROM ebc.BC_CUST_TYPE_SETUP_HELP_TEMP
WHERE CUST_ID IN(SELECT CUST_ID FROM BC_CUSTOMERS WHERE 
LOCATION_CODE=:LOC_CODE))--AND  CUSTOMER_TYPE_CODE LIKE('350%') 
--AND B.BILL_CYCLE_CODE=201905
ORDER BY B.CONS_EXTG_NUM ASC


-------------------------------------------------


SELECT B.CUSTOMER_NUM , C.CUSTOMER_NAME,B.CONS_EXTG_NUM Acount_no,B.TARIFF,b.CONS_KWH_SR SOLD_UNIT,
 nvl(ENG_CHRG_SR,0)+nvl(MINIMUM_CHRG,0)+nvl(SERVICE_CHRG,0)+ nvl(DEMAND_CHRG,0)
  +NVL(PFC_CHARGE,0)+NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0) Billed_Amount,
  NVL(TOTAL_BILL,0)- 
  (NVL(CURRENT_LPS,0)+NVL(ADJUSTED_LPS,0)+NVL(ARR_ADV_ADJ_LPS,0)
  +NVL(CURRENT_VAT,0)+NVL( ADJUSTED_VAT,0)+NVL(ARR_ADV_ADJ_VAT,0)) Recievable,
  NVL(CURRENT_LPS,0)+NVL(ADJUSTED_LPS,0)+NVL(ARR_ADV_ADJ_LPS,0) Surcharge,
  (nvl(RCPT_PRN_1,0)+nvl(RCPT_PRN_2,0)+nvl(RCPT_PRN_3,0) ) CollAmnt,
  NVL(CURRENT_VAT,0)+NVL( ADJUSTED_VAT,0)+NVL(ARR_ADV_ADJ_VAT,0)Vat,Total_Bill
       from bc_bill_image B,BC_CUSTOMERS C where 
       B.location_code='L1' and
       B.CUST_ID=C.CUST_ID AND
B.cust_ID in( SELECT CUST_ID FROM BC_CUSTOMERS 
) 
AND BILL_CYCLE_CODE=201905
ORDER BY B.CONS_EXTG_NUM ASC