select c.LOCATION_CODE location,C.AREA_CODE,C.CONS_EXTG_NUM AC,cm.METER_NUM meter,C.WALKING_SEQUENCE PAGE,C.CUSTOMER_NAME NAME
,A.ADDR_DESCR1||'-'||A.ADDR_DESCR2 addres,C.CUSTOMER_NUM,sl.SANCTIONED_LOAD s_load,cl.CONNECTED_LOAD c_load
,MM.USAGE_CATEGORY_CODE TARIFF,C.START_BILL_CYCLE,BI.CONS_KWH_SR UNIT,(NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0)+NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+NVL(DEMAND_CHRG,0)+
       NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)) CURR_BILL,CURRENT_VAT CURR_VAT,(NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0)+NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+NVL(DEMAND_CHRG,0)+
       NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0))+CURRENT_VAT as total_bill, PI.EFF_DATE
from BC_CUSTOMER_METER CM,BC_METER_SUPPLY MS,BC_PHASE_INFO PI,bc_CUSTOMERS C,
bc_customer_category cc,bc_category_master MM,BC_CUSTOMER_ADDR A,BC_CONNECTED_LOAD cl,BC_SANCTIONED_LOAD sl,BC_BILL_IMAGE BI
where C.CUST_ID=sl.CUST_ID
and sl.CUST_ID=cl.CUST_ID
--and cl.EFF_DATE >='01-jan-2015'
AND C.CUST_ID=A.CUST_ID
AND A.ADDR_TYPE='M'
AND A.ADDR_EXP_DATE IS NULL
AND c.CUST_ID=cc.cust_id
AND CM.CUST_ID=BI.CUST_ID
AND C.CUST_ID=BI.CUST_ID
AND A.CUST_ID=BI.CUST_ID
AND cc.EXP_DATE IS NULL
AND cc.CAT_ID=mm.CATEGORY_ID
AND C.CUST_ID=CM.CUST_ID 
AND CM.CONNECTION_ID=MS.CONNECTION_ID 
AND MS.SUPPLY_ID=PI.SUPPLY_ID 
--AND BI.BILL_CYCLE_CODE='201311'
and C.START_BILL_CYCLE='201812'  
--AND C.AREA_CODE LIKE 'N__16'
and C.LOCATION_CODE='L1' 
--AND BI.CONNECT_LOAD>='17'
--AND MM.TARIFF_ID='4'--TARIFF='E'
GROUP BY c.LOCATION_CODE,C.AREA_CODE,C.CONS_EXTG_NUM,cm.METER_NUM,C.WALKING_SEQUENCE,C.CUSTOMER_NAME,sl.SANCTIONED_LOAD,cl.CONNECTED_LOAD
,MM.USAGE_CATEGORY_CODE,A.ADDR_DESCR1||'-'||A.ADDR_DESCR2,C.CUSTOMER_NUM,C.START_BILL_CYCLE,BI.CONS_KWH_SR,(NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0)+NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+NVL(DEMAND_CHRG,0)+
       NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)),CURRENT_VAT,PI.EFF_DATE
ORDER BY C.AREA_CODE,C.CONS_EXTG_NUM,C.WALKING_SEQUENCE,C.CUSTOMER_NAME,sl.SANCTIONED_LOAD,cl.CONNECTED_LOAD
,MM.USAGE_CATEGORY_CODE,A.ADDR_DESCR1||'-'||A.ADDR_DESCR2,C.CUSTOMER_NUM,C.START_BILL_CYCLE,PI.EFF_DATE