

SELECT BI.CUSTOMER_NUM CUSTOMER,C.CUSTOMER_NAME NAME,C.CONS_EXTG_NUM ac_no,BI.TARIFF,CONS_KWH_SR SOLD_UNIT, ROUND((NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0)+NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+NVL(DEMAND_CHRG,0)+
       NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0))) BILL_AMOUNT,ROUND((NVL(ARR_ADV_ADJ_PRN,0)+NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0)+NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+NVL(DEMAND_CHRG,0)+
       NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0))) RECIVEBLE,ROUND(NVL(ARR_ADV_ADJ_LPS,0)+NVL(CURRENT_LPS,0)) SURCHARGE,ROUND(nvl(RCPT_PRN_1,0)+nvl(RCPT_PRN_2,0)+nvl(RCPT_PRN_3,0)+nvl(RCPT_VAT_1,0)+nvl(RCPT_VAT_2,0)+nvl(RCPT_VAT_3,0)) COLLECTION_AMT,
       ROUND((NVL(CURRENT_VAT,0)+NVL(ARR_VAT_1,0)+NVL(ARR_VAT_2,0)+NVL(ARR_VAT_3,0)+NVL(ARR_VAT_4,0)+NVL(ARR_VAT_5,0)+NVL(ARR_VAT_6,0)+NVL(ARR_VAT_7,0)+NVL(ARR_VAT_8,0)+NVL(ARR_VAT_9,0)+NVL(ARR_VAT_10,0)+NVL(ARR_VAT_11,0)+NVL(ARR_VAT_12,0))) VAT,
       TOTAL_BILL
FROM   EBC.BC_BILL_IMAGE BI,EBC.BC_CUSTOMERS C
WHERE BI.CUST_ID=C.CUST_ID
--AND  BI.cust_id =cid(:p_cust_id)
AND BI.INVOICE_NUM IS NOT  NULL
and BI.bill_cycle_code='201905'
AND C.LOCATION_CODE='Q7'
ORDER BY CUSTOMER ASC



select * from BC_BILL_IMAGE
where bill_cycle_code='201905'
and SANC_LOAD>20
and POWER_FACTOR<'0.95'
and invoice_num is not null




select c.CUSTOMER_NUM,c.CUSTOMER_NAME,ca.ADDR_DESCR1||'-'||ca.ADDR_DESCR2 addres,POWER_FACTOR,PFC_CHARGE,ROUND(NVL(PFC_SR_CONS,0)+NVL(PFC_OFPK_CONS,0)+NVL(PFC_PK_CONS,0)) TOTAL_PFC_CONS,total_bill 
from BC_BILL_IMAGE bi,bc_customers c,BC_CUSTOMER_ADDR ca
where bi.CUST_ID=c.CUST_ID
and bi.CUST_ID=ca.CUST_ID
and c.CUST_ID=ca.CUST_ID
AND ca.ADDR_TYPE='M'
AND ca.ADDR_EXP_DATE IS NULL
and bi.bill_cycle_code='201905'
and SANC_LOAD>20
and POWER_FACTOR<'0.95'
and invoice_num is not null
order by 1 

------------------------------------------

SELECT 
b.customer_num||a.check_digit customer_num,SUBSTR(a.customer_name,1,34) Customer_name,  
      b.cons_extg_num Acount_no,b.tariff,b.CONS_KWH_SR SOLD_UNIT,  
   /*NVL(c.principal_amt,0) +*/ nvl(ENG_CHRG_SR,0)+nvl(MINIMUM_CHRG,0)+nvl(SERVICE_CHRG,0)+ nvl(DEMAND_CHRG,0)
  +NVL(PFC_CHARGE,0)+NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0) Billed_Amount,
  NVL(TOTAL_BILL,0)- 
  (NVL(CURRENT_LPS,0)+NVL(ADJUSTED_LPS,0)+NVL(ARR_ADV_ADJ_LPS,0)
  +NVL(CURRENT_VAT,0)+NVL( ADJUSTED_VAT,0)+NVL(ARR_ADV_ADJ_VAT,0)) Recievable,
  NVL(CURRENT_LPS,0)+NVL(ADJUSTED_LPS,0)+NVL(ARR_ADV_ADJ_LPS,0) Surcharge,
  (nvl(RCPT_PRN_1,0)+nvl(RCPT_PRN_2,0)+nvl(RCPT_PRN_3,0) ) CollAmnt,
  NVL(CURRENT_VAT,0)+NVL( ADJUSTED_VAT,0)+NVL(ARR_ADV_ADJ_VAT,0)Vat,Total_Bill
  -- nvl(B.total_bill,0) total_bill 
FROM ebc.BC_BILL_IMAGE b, bc_location_master l,
     BC_CUSTOMERS a, 
   -- BC_CUSTOMER_ADDR d, 
    BC_CUSTOMER_TYPE_CODE e,
    BC_MINISTRY_CODE f,
    --BC_CUSTOMER_TYPE_MST ctm,
    BC_CUSTOMER_OWNER_TYPE o,
    BC_CUSTOMER_CATEGORY cc,
    BC_CATEGORY_MASTER cm,
    VW_MIN_CUST_TYPE V
WHERE b.bill_cycle_code = '201905'
AND b.cust_id = a.cust_id 
AND b.cust_id = cc.cust_id
and l.location_code=b.location_code
--and b.invoice_num=R.invoice_num(+)
AND cc.CAT_ID = cm.CATEGORY_ID
AND cc.EXP_DATE IS NULL 
AND cm.CUSTOMER_TYPE_CODE = e.CUSTOMER_TYPE_CODE
--AND b.LOCATION_CODE = :p_location_code 
AND v.MINISTRY_CODE||v.CUSTOMER_TYPE_CODE=SUBSTR(E.CUSTOMER_TYPE_CODE,1,4) 
AND e.CUSTOMER_OWNER_CODE = o.CUSTOMER_OWNER_CODE 
AND e.ministry_code = f.ministry_code
AND e.ministry_code IS NOT NULL
and a.LOCATION_CODE='L1'
ORDER BY  1,2,4,6,8