
   SELECT null link,   'Month -'||Bill_Month,count(1) No_of_Arr_cust
 from v_utility_bill_pdb a
where CURRENT_SURCHARGE>0
and (account_number,to_char(add_months(to_date(bill_month,'RRRRMM'),-1),'RRRRMM')) in (select account_number,bill_month from v_utility_bill_pdb
where (location_code,bill_number) in (select location_code,bill_number from v_payment_mst a, v_payment_dtl b where a.batch_no=b.batch_no ) 
)
 group by 'Month -'||a.Bill_Month
order by 'Month -'||a.Bill_Month

--------------ARREAR OF BILLING SERVER

DBLINK                 CENTER NAME
------------------------------------------
BILLING_COM         COMILLA

BILLING_RAJ         RAJSHAHI
BILLING_BOG         BOGRA
BILLING_NAO         NAOGAON
BILLING_PAB         PABNA

BILLING_SYL         SYLHET
BILLING_MOU         MOULAVIBAZAR

BILLING_RONG        RONGPUR
BILLING_DIN             DINAJPUR

BILLING_MYMEN           MYMENSING
BILLING_JAM                 JAMALPUR
BILLING_KISHOR              KISORGONG
BILLING_TANG            TANGAIL


DELETE FROM EPAY_UTILITY_BILL_GPR;

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_DIN
 WHERE TARIFF IN ('A','C','B','D','E','J')
AND INVOICE_NUM IS NOT NULL
AND (INVOICE_NUM,BILL_CYCLE_CODE) IN (
SELECT INVOICE_NUM,BILL_CYCLE_CODE FROM BC_BILL_IMAGE@BILLING_DIN
WHERE BILL_CYCLE_CODE='201507'
AND (NVL(ARR_ADV_ADJ_PRN,0)<> 0 OR NVL(ARR_ADV_ADJ_VAT,0)<>0)
AND CUSTOMER_NUM IN (
SELECT CUSTOMER_NUM FROM BC_BILL_IMAGE@BILLING_DIN
WHERE BILL_CYCLE_CODE='201506'
AND INVOICE_NUM IN (
SELECT INVOICE_NUM FROM BC_RECEIPT_HDR@BILLING_DIN
WHERE (BATCH_NUM,BANK_CODE) IN (
SELECT BATCH_NUM,BANK_CODE FROM BC_RECEIPT_BATCH_HDR@BILLING_DIN
WHERE BANK_CODE='97'
--AND TO_CHAR(RECEIPT_DATE,'RRRRMM')>='201507'
AND (LOCATION_CODE,RECEIPT_DATE) IN (
SELECT M.LOCATION_CODE,M.PAY_DATE  FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_MST D
WHERE M.BATCH_NO =D.BATCH_NO  AND M.STATUS IN ('P','T')
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER 
WHERE CENTER_NAME LIKE '%DINAJPUR%'
AND STATUS ='A'))))));

COMMIT;



update EPAY_UTILITY_BILL_GPR
set ARREAR_PRINCIPLE=0, ARREAR_GOVT_DUTY=0, CURRENT_SURCHARGE=0, ARREAR_SURCHARGE=0


COMMIT;


/*
UPDATE UTILITY_BILL_PDB_DMP_X
SET total_bill_amount=ROUND(NVL(CURRENT_PRINCIPLE,0)+NVL(CURRENT_GOVT_DUTY,0)
+NVL(ARREAR_PRINCIPLE,0)+NVL(ARREAR_GOVT_DUTY,0)+NVL(CURRENT_SURCHARGE,0)
+NVL(ARREAR_SURCHARGE,0)+NVL(ADJUSTED_PRINCIPLE,0)+NVL(ADJUSTED_GOVT_DUTY,0)
-NVL(ADVANCE_AMOUNT,0)+NVL(ADJ_ADV_GOVT_DUTY,0))
*/

UPDATE EPAY_UTILITY_BILL_GPR
SET total_bill_amount=ROUND(NVL(CURRENT_PRINCIPLE,0)+NVL(CURRENT_GOVT_DUTY,0)
+NVL(ARREAR_PRINCIPLE,0)+NVL(ARREAR_GOVT_DUTY,0)+NVL(CURRENT_SURCHARGE,0)
+NVL(ARREAR_SURCHARGE,0)+NVL(ADJUSTED_PRINCIPLE,0)+NVL(ADJUSTED_GOVT_DUTY,0)
-NVL(ADVANCE_AMOUNT,0)+NVL(ADJ_ADV_GOVT_DUTY,0)),
adjusted_principle=NVL(adjusted_principle,0)
+ROUND(NVL(CURRENT_PRINCIPLE,0)+NVL(CURRENT_GOVT_DUTY,0)
+NVL(ARREAR_PRINCIPLE,0)+NVL(ARREAR_GOVT_DUTY,0)+NVL(CURRENT_SURCHARGE,0)
+NVL(ARREAR_SURCHARGE,0)+NVL(ADJUSTED_PRINCIPLE,0)+NVL(ADJUSTED_GOVT_DUTY,0)
-NVL(ADVANCE_AMOUNT,0)+NVL(ADJ_ADV_GOVT_DUTY,0))-(NVL(CURRENT_PRINCIPLE,0)
+NVL(CURRENT_GOVT_DUTY,0)+NVL(ARREAR_PRINCIPLE,0)+NVL(ARREAR_GOVT_DUTY,0)
+NVL(CURRENT_SURCHARGE,0)+NVL(ARREAR_SURCHARGE,0)+NVL(ADJUSTED_PRINCIPLE,0)
+NVL(ADJUSTED_GOVT_DUTY,0)-NVL(ADVANCE_AMOUNT,0)+NVL(ADJ_ADV_GOVT_DUTY,0))


COMMIT;



DELETE UTILITY_BILL_PDB@EPAY_ROBI
WHERE (ACCOUNT_NUMBER,BILL_MONTH) IN (SELECT ACCOUNT_NUMBER,BILL_MONTH FROM EPAY_UTILITY_BILL_GPR);


COMMIT;


DELETE EPAY_UTILITY_BILL
WHERE (ACCOUNT_NUMBER,BILL_MONTH) IN (SELECT ACCOUNT_NUMBER,BILL_MONTH FROM EPAY_UTILITY_BILL_GPR);

DELETE EPAY_UTILITY_BILL_DMP
WHERE (ACCOUNT_NUMBER,BILL_MONTH) IN (SELECT ACCOUNT_NUMBER,BILL_MONTH FROM EPAY_UTILITY_BILL_GPR);


COMMIT;


INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT * FROM EPAY_UTILITY_BILL_GPR


COMMIT;


INSERT INTO EPAY_UTILITY_BILL
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,'T' DATA_TRNS_LOG
 FROM EPAY_UTILITY_BILL_GPR


COMMIT;