


SELECT * FROM EPAY_PAYMENT_MST
WHERE PAY_DATE BETWEEN '01-DEC-2016' AND '31-DEC-2016'
AND LOCATION_CODE='J6'



SELECT * FROM VW_EPAY_PAYMENT_MST_DTL MD,EPAY_UTILITY_BILL B
WHERE MD.LOCATION_CODE=B.LOCATION_CODE
AND MD.BILL_NUMBER=B.BILL_NUMBER
--AND MD.PAY_DATE BETWEEN '01-DEC-2016' AND '31-DEC-2016'
AND B.LOCATION_CODE='J6'
AND B.BILL_MONTH='201611'

SELECT * FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201612'
AND LOCATION_CODE='J6'
AND (NVL(ARREAR_PRINCIPLE,0)>0 OR NVL(ARREAR_GOVT_DUTY,0)>0)
AND ACCOUNT_NUMBER IN (
SELECT B.ACCOUNT_NUMBER FROM VW_EPAY_PAYMENT_MST_DTL MD,EPAY_UTILITY_BILL B
WHERE MD.LOCATION_CODE=B.LOCATION_CODE
AND MD.BILL_NUMBER=B.BILL_NUMBER
--AND MD.PAY_DATE BETWEEN '01-DEC-2016' AND '31-DEC-2016'
AND B.LOCATION_CODE='J6'
AND B.BILL_MONTH='201611'
)


SELECT BILL_CYCLE_CODE,LOCATION_CODE,BILL_GROUP ,COUNT(*) FROM BC_BILL_IMAGE@BILLING_JAM
WHERE (NVL(ARR_ADV_ADJ_PRN,0) >0 OR NVL(ARR_ADV_ADJ_VAT,0)>0) 
AND 
 INVOICE_NUM IN (
SELECT SUBSTR(BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201612'
AND LOCATION_CODE='J6'
AND (NVL(ARREAR_PRINCIPLE,0)>0 OR NVL(ARREAR_GOVT_DUTY,0)>0)
AND ACCOUNT_NUMBER IN (
SELECT B.ACCOUNT_NUMBER FROM VW_EPAY_PAYMENT_MST_DTL MD,EPAY_UTILITY_BILL B
WHERE MD.LOCATION_CODE=B.LOCATION_CODE
AND MD.BILL_NUMBER=B.BILL_NUMBER
--AND MD.PAY_DATE BETWEEN '01-DEC-2016' AND '31-DEC-2016'
AND B.LOCATION_CODE='J6'
AND B.BILL_MONTH='201611'
)) GROUP BY  BILL_CYCLE_CODE,LOCATION_CODE,BILL_GROUP 







SELECT * FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO IN (
SELECT BATCH_NO FROM EPAY_PAYMENT_MST
WHERE PAY_DATE BETWEEN '01-DEC-2016' AND '31-DEC-2016'
AND LOCATION_CODE='J6')


AND BATCH_NO IN (SELECT BATCH_NO FROM EPAY_PAYMENT_DTL)