

DELETE FROM EPAY_UTILITY_BILL_INT;

INSERT INTO EPAY_UTILITY_BILL_INT
SELECT A.* FROM EPAY_UTILITY_BILL A
WHERE  NVL(ARREAR_PRINCIPLE,0)+NVL(ARREAR_GOVT_DUTY,0)>0
AND BILL_DUE_DATE>=TRUNC(SYSDATE)
AND BILL_MONTH=:P_BILL_MONTH
AND ACCOUNT_NUMBER IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=:P_BILL_MONTH-1 
AND (LOCATION_CODE,BILL_NUMBER) IN (
SELECT LOCATION_CODE,BILL_NUMBER FROM VW_EPAY_PAYMENT_MST_DTL
WHERE TO_CHAR(PAY_DATE,'RRRRMM') IN (SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-2),'rrrrmm') FROM DUAL)
AND LOCATION_CODE=UPPER(:LOC)
))


COMMIT;


DELETE FROM EPAY_UTILITY_BILL_INT
WHERE ROWID IN (
SELECT ROWID FROM EPAY_UTILITY_BILL_INT
MINUS
SELECT MAX(ROWID) FROM EPAY_UTILITY_BILL_INT
GROUP BY ACCOUNT_NUMBER, BILL_NUMBER, LOCATION_CODE);

UPDATE EPAY_UTILITY_BILL_INT
SET CREATED_ON=SYSDATE;

                    update EPAY_UTILITY_BILL_INT
                    set ARREAR_PRINCIPLE=0, ARREAR_GOVT_DUTY=0, CURRENT_SURCHARGE=0, ARREAR_SURCHARGE=0;

                    UPDATE EPAY_UTILITY_BILL_INT
                    SET total_bill_amount=ROUND(NVL(CURRENT_PRINCIPLE,0)+NVL(CURRENT_GOVT_DUTY,0)
                    +NVL(ARREAR_PRINCIPLE,0)+NVL(ARREAR_GOVT_DUTY,0)+NVL(CURRENT_SURCHARGE,0)
                    +NVL(ARREAR_SURCHARGE,0)+NVL(ADJUSTED_PRINCIPLE,0)+NVL(ADJUSTED_GOVT_DUTY,0)
                    -NVL(ADVANCE_AMOUNT,0)+NVL(ADJ_ADV_GOVT_DUTY,0)),
                    adjusted_principle=NVL(adjusted_principle,0)
                    +ROUND(NVL(CURRENT_PRINCIPLE,0)+NVL(CURRENT_GOVT_DUTY,0)
                    +NVL(ARREAR_PRINCIPLE,0)+NVL(ARREAR_GOVT_DUTY,0)+NVL(CURRENT_SURCHARGE,0)
                    +NVL(ARREAR_SURCHARGE,0)+NVL(ADJUSTED_PRINCIPLE,0)+NVL(ADJUSTED_GOVT_DUTY,0)
                    -NVL(ADVANCE_AMOUNT,0)+NVL(ADJ_ADV_GOVT_DUTY,0))-(NVL(CURRENT_PRINCIPLE,0)
                    +NVL(CURRENT_GOVT_DUTY,0)+NVL(ARREAR_PRINCIPLE,0)+NVL(ARREAR_GOVT_DUTY,0)
                    +NVL(CURRENT_SURCHARGE,0)+NVL(ARREAR_SURCHARGE,0)+NVL(ADJUSTED_PRINCIPLE,0)
                    +NVL(ADJUSTED_GOVT_DUTY,0)-NVL(ADVANCE_AMOUNT,0)+NVL(ADJ_ADV_GOVT_DUTY,0));

                    COMMIT;

                    BANK_CODE='97'

                        DELETE FROM EPAY_UTILITY_BILL
                        WHERE (ACCOUNT_NUMBER,BILL_MONTH) IN (SELECT ACCOUNT_NUMBER,BILL_MONTH FROM EPAY_UTILITY_BILL_INT)
                        
                        DELETE UTILITY_BILL_PDB@EPAY_ROBI
                        WHERE (ACCOUNT_NUMBER,BILL_MONTH) IN (SELECT ACCOUNT_NUMBER,BILL_MONTH FROM EPAY_UTILITY_BILL_INT)
                        
                        
                        INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
                        SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
                        GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
                        BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
                        CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
                        NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
                        CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
                        ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
                        TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
                        TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
                        ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
                        ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY
                        FROM EPAY_UTILITY_BILL_INT
                        

                        INSERT INTO EPAY_UTILITY_BILL
                        SELECT * FROM EPAY_UTILITY_BILL_INT
                        

COMMIT;
