
---COMPLITE SHEDUL

select * from mbill.MIS_AUDIT_TRANS_BATCH_CNTRL
where data_type='AUDIT_SCH_A'
AND RUN_STATUS_CODE='01'
and st_bill_cycle_code='201607'
AND END_bill_cycle_code='201706'
order by run_date desc

---RUNING SHEDUL

select * from MIS_AUDIT_TRANS_BATCH_CNTRL
WHERE RUN_STATUS_CODE<>'01'
and st_bill_cycle_code='201607'
AND END_bill_cycle_code='201706'
order by run_date desc


select LOCATION_CODE,COUNT(*) from MIS_AUDIT_SCHEDULE_A@billing_ctg
WHERE st_bill_cycle_code='201607'
AND END_bill_cycle_code='201706'
GROUP BY LOCATION_CODE
ORDER BY LOCATION_CODE DESC


select COUNT(*) from MIS_AUDIT_SCHEDULE_C1@billing_ctg


GROUP BY LOCATION_CODE
ORDER BY LOCATION_CODE








select * from epay_location_master
where center_name='CHITTAGONG'
ORDER BY LOCATION_CODE 

select LOCATION_CODE,COUNT(*) from MIS_AUDIT_SCHEDULE_A@billing_ctg
GROUP BY LOCATION_CODE
ORDER BY LOCATION_CODE 

select LOCATION_CODE,COUNT(*) from MIS_AUDIT_SCHEDULE_B@billing_ctg
GROUP BY LOCATION_CODE
ORDER BY LOCATION_CODE


select LOCATION_CODE,COUNT(*) from MIS_AUDIT_SCHEDULE_C@billing_ctg
GROUP BY LOCATION_CODE
ORDER BY LOCATION_CODE

select LOCATION_CODE,COUNT(*) from MIS_AUDIT_SCHEDULE_C1@billing_ctg
GROUP BY LOCATION_CODE
ORDER BY LOCATION_CODE

select LOCATION_CODE,COUNT(*) from MIS_AUDIT_SCHEDULE_C2@billing_ctg
GROUP BY LOCATION_CODE
ORDER BY LOCATION_CODE

select LOCATION_CODE,COUNT(*) from MIS_AUDIT_SCHEDULE_D2@billing_ctg
GROUP BY LOCATION_CODE
ORDER BY LOCATION_CODE

select LOCATION_CODE,COUNT(*) from MIS_AUDIT_SCHEDULE_E@billing_ctg
GROUP BY LOCATION_CODE
ORDER BY LOCATION_CODE

select LOCATION_CODE,COUNT(*) from MIS_AUDIT_SCHEDULE_E1@billing_ctg
GROUP BY LOCATION_CODE
ORDER BY LOCATION_CODE

select * from mbill.MIS_AUDIT_TRANS_BATCH_CNTRL
where data_type='AUDIT_SCH_E1'