
insert into MIS_AUDIT_SCHEDULE_B@MBILLSVR_AUDIT
SELECT * FROM MIS_AUDIT_SCHEDULE_B@BILLINGAUDIT

WHERE ST_BILL_CYCLE_CODE='201607'
AND END_BILL_CYCLE_CODE='201706';

commit;

insert into MIS_AUDIT_SCHEDULE_C@AUDIT_SVER
SELECT * FROM MIS_AUDIT_SCHEDULE_C@BILLINGAUDIT
WHERE ST_BILL_CYCLE_CODE='201607'
AND END_BILL_CYCLE_CODE='201706';

commit;

insert into MIS_AUDIT_SCHEDULE_E1@AUDIT_SVER
SELECT * FROM MIS_AUDIT_SCHEDULE_E1@BILLINGAUDIT
WHERE ST_BILL_CYCLE_CODE='201607'
AND END_BILL_CYCLE_CODE='201706';

commit;

insert into MIS_AUDIT_SCHEDULE_D2@AUDIT_SVER
SELECT * FROM MIS_AUDIT_SCHEDULE_D2@BILLINGAUDIT
WHERE ST_BILL_CYCLE_CODE='201607'
AND END_BILL_CYCLE_CODE='201706';

commit;

insert into MIS_AUDIT_SCHEDULE_B@AUDIT_SVER
SELECT * FROM MIS_AUDIT_SCHEDULE_B@BILLINGAUDIT
WHERE ST_BILL_CYCLE_CODE='201607'
AND END_BILL_CYCLE_CODE='201706';

commit;

insert into MIS_AUDIT_SCHEDULE_C1@AUDIT_SVER
SELECT * FROM MIS_AUDIT_SCHEDULE_C1@BILLINGAUDIT
WHERE ST_BILL_CYCLE_CODE='201607'
AND END_BILL_CYCLE_CODE='201706';

commit;

insert into MIS_AUDIT_SCHEDULE_C2@AUDIT_SVER
SELECT * FROM MIS_AUDIT_SCHEDULE_C2@BILLINGAUDIT
WHERE ST_BILL_CYCLE_CODE='201607'
AND END_BILL_CYCLE_CODE='201706';

commit;

insert into MIS_AUDIT_SCHEDULE_E@AUDIT_SVER
SELECT * FROM MIS_AUDIT_SCHEDULE_E@BILLINGAUDIT
WHERE ST_BILL_CYCLE_CODE='201607'
AND END_BILL_CYCLE_CODE='201706';

commit;