
SELECT *  FROM MIS_AUDIT_TRANS_BATCH_CNTRL
WHERE DATA_TYPE='AUDIT_SCH_B0'
AND ST_BILL_CYCLE_CODE='201507'
AND END_BILL_CYCLE_CODE='201606'
AND RUN_STATUS_CODE<>'01'


SELECT *  FROM MIS_AUDIT_TRANS_BATCH_CNTRL
WHERE DATA_TYPE='AUDIT_SCH_B0'
AND ST_BILL_CYCLE_CODE='201507'
AND END_BILL_CYCLE_CODE='201606'
AND RUN_STATUS_CODE='01'

SELECT *  FROM MIS_AUDIT_TRANS_BATCH_CNTRL
WHERE DATA_TYPE='AUDIT_SCH_B'
AND ST_BILL_CYCLE_CODE='201607'
AND END_BILL_CYCLE_CODE='201706'
AND RUN_STATUS_CODE='01'



SELECT * FROM MIS_AUDIT_SCHEDULE_B0@BILLINGAUDIT
WHERE ST_BILL_CYCLE_CODE='201607'
AND END_BILL_CYCLE_CODE='201706';





SELECT LOCATION_CODE,COUNT(*) FROM MIS.MIS_AUDIT_SCHEDULE_BO@BILLINGAUDIT
GROUP BY LOCATION_CODE
order by 1 desc

MIS_AUDIT_SCHEDULE_A
MIS_AUDIT_SCHEDULE_B
MIS_AUDIT_SCHEDULE_C
MIS_AUDIT_SCHEDULE_C1
MIS_AUDIT_SCHEDULE_C1_X
MIS_AUDIT_SCHEDULE_C2
MIS_AUDIT_SCHEDULE_D2
MIS_AUDIT_SCHEDULE_E
MIS_AUDIT_SCHEDULE_E_X
MIS_AUDIT_SCHEDULE_E1

SELECT B.CENTER_NAME,COUNT(*) FROM MIS.MIS_AUDIT_SCHEDULE_A@AUDIT_SVER A,EPAY_LOCATION_MASTER B
WHERE A.LOCATION_CODE=B.LOCATION_CODE
GROUP BY B.CENTER_NAME

SELECT ORG_CODE,PAY_DATE,PAY_PC_CODE,PAY_PC_BR_CODE, COUNT(*) FROM MBP_PAYMENT_DTL_OVC@MBP_23
GROUP BY ORG_CODE,PAY_DATE,PAY_PC_CODE,PAY_PC_BR_CODE


