
SELECT A.PAY_BANK_CODE, B.BANK_NAME ,A.PAY_BRANCH_CODE, C.BRANCH_NAME FROM EPAY_PAYMENT_MST A,EPAY_BANKS B,EPAY_BANK_BRANCHES C
WHERE A.PAY_BANK_CODE=B.BANK_CODE
AND A.PAY_BANK_CODE=C.BANK_CODE
AND A.PAY_BRANCH_CODE=C.BRANCH_CODE
AND  PAY_BANK_CODE NOT IN ('96','97')
GROUP BY A.PAY_BANK_CODE, B.BANK_NAME ,A.PAY_BRANCH_CODE, C.BRANCH_NAME




SELECT PAY_BANK_CODE,B.BANK_NAME FROM EPAY_PAYMENT_MST A,EPAY_BANKS B,EPAY_BANK_BRANCHES C
WHERE A.PAY_BANK_CODE=B.BANK_CODE
AND  PAY_BANK_CODE NOT IN ('96','97')
GROUP BY PAY_BANK_CODE,B.BANK_NAME