
SELECT BI.BILL_CYCLE_CODE, BI.LOCATION_CODE, SUBSTR(AREA_CODE,4,2) BILL_GROUP, TARIFF, COUNT(1) Tot_Customer,SUM(NVL(BI.CONS_KWH_SR,0) + NVL(BI.CONS_KWH_PK,0) + NVL(BI.CONS_KWH_OFPK,0)
           + NVL(BI.OLD_KWH_SR_CONS,0) + NVL(BI.OLD_KWH_PK_CONS,0)
           + NVL(BI.OLD_KWH_OFPK_CONS,0) + NVL(BI.XF_LOSS_SR_CONS,0) + NVL(BI.XF_LOSS_OFPK_CONS,0)
              + NVL(BI.XF_LOSS_PK_CONS,0)+ NVL(BI.PFC_SR_CONS,0) + NVL(BI.PFC_OFPK_CONS,0) + NVL(BI.PFC_PK_CONS,0)
              + NVL(CONS_KWH_MR1,0)+NVL(OLD_KWH_MR1_CONS,0)+NVL(CONS_KWH_MR2,0)+NVL(OLD_KWH_MR2_CONS,0)+NVL(CONS_KWH_MR3,0)+NVL(OLD_KWH_MR3_CONS,0)
              + NVL(CONS_KWH_MR4,0)+NVL(OLD_KWH_MR4_CONS,0)+NVL(PFC_MR1_CONS,0)+NVL(PFC_MR2_CONS,0)+NVL(PFC_MR3_CONS,0)
              + NVL(PFC_MR4_CONS,0)+NVL(XF_LOSS_MR1_CONS,0)+NVL(XF_LOSS_MR2_CONS,0)+NVL(XF_LOSS_MR3_CONS,0)+NVL(XF_LOSS_MR4_CONS,0)
    ) TOT_CONSUMPTION
    FROM BC_BILL_IMAGE BI,BC_USAGE_CATEGORY_CODE T
    WHERE BILL_CYCLE_CODE = :BILL_CYCLE_CODE
    AND LOCATION_CODE  IN ('C3','C8')
    AND BI.TARIFF=T.USAGE_CATEGORY_CODE
    AND SUBSTR(AREA_CODE,4,2)  IN (15,16,22)
GROUP BY TARIFF,SUBSTR(AREA_CODE,4,2),BI.BILL_CYCLE_CODE, BI.LOCATION_CODE
ORDER BY BILL_CYCLE_CODE,BI.LOCATION_CODE,SUBSTR(AREA_CODE,4,2),TARIFF


--------------------------------------

SELECT BI.BILL_CYCLE_CODE, BI.LOCATION_CODE,TARIFF, SUBSTR(AREA_CODE,4,2) BILL_GROUP , COUNT(1) Tot_Customer,SUM(NVL(BI.CONS_KWH_SR,0) + NVL(BI.CONS_KWH_PK,0) + NVL(BI.CONS_KWH_OFPK,0)
           + NVL(BI.OLD_KWH_SR_CONS,0) + NVL(BI.OLD_KWH_PK_CONS,0)
           + NVL(BI.OLD_KWH_OFPK_CONS,0) + NVL(BI.XF_LOSS_SR_CONS,0) + NVL(BI.XF_LOSS_OFPK_CONS,0)
              + NVL(BI.XF_LOSS_PK_CONS,0)+ NVL(BI.PFC_SR_CONS,0) + NVL(BI.PFC_OFPK_CONS,0) + NVL(BI.PFC_PK_CONS,0)
              + NVL(CONS_KWH_MR1,0)+NVL(OLD_KWH_MR1_CONS,0)+NVL(CONS_KWH_MR2,0)+NVL(OLD_KWH_MR2_CONS,0)+NVL(CONS_KWH_MR3,0)+NVL(OLD_KWH_MR3_CONS,0)
              + NVL(CONS_KWH_MR4,0)+NVL(OLD_KWH_MR4_CONS,0)+NVL(PFC_MR1_CONS,0)+NVL(PFC_MR2_CONS,0)+NVL(PFC_MR3_CONS,0)
              + NVL(PFC_MR4_CONS,0)+NVL(XF_LOSS_MR1_CONS,0)+NVL(XF_LOSS_MR2_CONS,0)+NVL(XF_LOSS_MR3_CONS,0)+NVL(XF_LOSS_MR4_CONS,0)
    ) TOT_CONSUMPTION
    FROM BC_BILL_IMAGE BI,BC_USAGE_CATEGORY_CODE T
    WHERE BILL_CYCLE_CODE = :BILL_CYCLE_CODE
    AND LOCATION_CODE ='C3'
    AND BI.TARIFF=T.USAGE_CATEGORY_CODE
    AND SUBSTR(AREA_CODE,4,2) NOT IN (15,16,22)
GROUP BY BI.BILL_CYCLE_CODE, BI.LOCATION_CODE,
GROUPING SETS (
 (TARIFF, SUBSTR(AREA_CODE,4,2)),
  (SUBSTR(AREA_CODE,4,2)),
 () 
)
ORDER BY SUBSTR(AREA_CODE,4,2) NULLS LAST


-------------------------

SELECT  COUNT(1) Tot_Customer,SUM(NVL(BI.CONS_KWH_SR,0) + NVL(BI.CONS_KWH_PK,0) + NVL(BI.CONS_KWH_OFPK,0)
           + NVL(BI.OLD_KWH_SR_CONS,0) + NVL(BI.OLD_KWH_PK_CONS,0)
           + NVL(BI.OLD_KWH_OFPK_CONS,0) + NVL(BI.XF_LOSS_SR_CONS,0) + NVL(BI.XF_LOSS_OFPK_CONS,0)
              + NVL(BI.XF_LOSS_PK_CONS,0)+ NVL(BI.PFC_SR_CONS,0) + NVL(BI.PFC_OFPK_CONS,0) + NVL(BI.PFC_PK_CONS,0)
              + NVL(CONS_KWH_MR1,0)+NVL(OLD_KWH_MR1_CONS,0)+NVL(CONS_KWH_MR2,0)+NVL(OLD_KWH_MR2_CONS,0)+NVL(CONS_KWH_MR3,0)+NVL(OLD_KWH_MR3_CONS,0)
              + NVL(CONS_KWH_MR4,0)+NVL(OLD_KWH_MR4_CONS,0)+NVL(PFC_MR1_CONS,0)+NVL(PFC_MR2_CONS,0)+NVL(PFC_MR3_CONS,0)
              + NVL(PFC_MR4_CONS,0)+NVL(XF_LOSS_MR1_CONS,0)+NVL(XF_LOSS_MR2_CONS,0)+NVL(XF_LOSS_MR3_CONS,0)+NVL(XF_LOSS_MR4_CONS,0)
    ) TOT_CONSUMPTION
    FROM BC_BILL_IMAGE BI,BC_USAGE_CATEGORY_CODE T
    WHERE BILL_CYCLE_CODE = :BILL_CYCLE_CODE
    AND LOCATION_CODE  IN ('C3','C8')
    AND BI.TARIFF=T.USAGE_CATEGORY_CODE
    AND SUBSTR(AREA_CODE,4,2)  IN (15,16,22)