
SELECT * FROM EPAY_BANK_BRANCHES
WHERE BANK_CODE='96'
AND LOCATION_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE BILLING_DBLINK='BILLING_JAM')


select * from bc_bank_branches@BILLING_com
where bank_code='96'


EXECUTE DPG_EPAY_DATA_TRANS.DPD_BANK_BR_DATA_TRANS@EPAY_jam(1)