

select distinct ref_batch_no from VW_EPAY_UNTRANSFER_PYMT_ALL

select * from epay_payment_mst m,epay_banks b
where m.PAY_BANK_CODE=b.BANK_CODE
and m.pay_date = '20-jan-2021' 
and pay_bank_code='54'

select * from epay_payment_mst_int

--CREATE OR REPLACE VIEW EPAY.VW_EPAY_BANK_BRANCH_CONN_LIST AS
SELECT TO_CHAR(M.PAY_DATE,'RRRRMM') PAY_MONTH,B.BANK_NAME,'Epay_Dekstop' CONNECT_TYPE 
FROM EPAY_PAYMENT_MST M,EPAY_BANKS B,EPAY_BANK_BRANCHES BR
WHERE M.PAY_BANK_CODE=B.BANK_CODE
AND M.PAY_BANK_CODE=BR.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND M.LOCATION_CODE=BR.LOCATION_CODE
AND TO_CHAR(PAY_DATE,'RRRRMM') IN ('202012')
AND (M.PAY_BANK_CODE,M.PAY_BRANCH_CODE) IN (
SELECT PAY_BANK_CODE,PAY_BRANCH_CODE FROM EPAY_PAYMENT_MST_INT
WHERE TO_CHAR(PAY_DATE,'RRRRMM') IN ('202012')
)
GROUP BY TO_CHAR(M.PAY_DATE,'RRRRMM'),B.BANK_NAME
UNION ALL
SELECT TO_CHAR(M.PAY_DATE,'RRRRMM') PAY_MONTH,B.BANK_NAME,'Epay_Online' CONNECT_TYPE FROM EPAY_PAYMENT_MST M,EPAY_BANKS B,EPAY_BANK_BRANCHES BR
WHERE M.PAY_BANK_CODE=B.BANK_CODE
AND M.PAY_BANK_CODE=BR.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND M.LOCATION_CODE=BR.LOCATION_CODE
AND TO_CHAR(PAY_DATE,'RRRRMM') IN ('202012')
AND (M.PAY_BANK_CODE,M.PAY_BRANCH_CODE) IN (
SELECT ORG_BANK_CODE, ORG_BANK_BR_CODE
FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE@EPAY_SRL A,EPAYONLINE.EPAY_ORG_BANK_MAP@EPAY_SRL B
WHERE A.PAY_BANK_CODE=B.BANK_CODE
AND A.PAY_BANK_BR_CODE=B.BANK_BR_CODE
AND TO_CHAR(PAY_DATE,'RRRRMM') IN ('202012')
UNION  
SELECT ORG_BANK_CODE, ORG_BANK_BR_CODE
FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE_HIST@EPAY_SRL A,EPAYONLINE.EPAY_ORG_BANK_MAP@EPAY_SRL B
WHERE A.PAY_BANK_CODE=B.BANK_CODE
AND A.PAY_BANK_BR_CODE=B.BANK_BR_CODE
AND TO_CHAR(PAY_DATE,'RRRRMM') IN ('202012')
)
GROUP BY TO_CHAR(M.PAY_DATE,'RRRRMM'),B.BANK_NAME
UNION ALL
SELECT TO_CHAR(M.PAY_DATE,'RRRRMM') PAY_MONTH,B.BANK_NAME,'Api' CONNECT_TYPE FROM EPAY_PAYMENT_MST M,EPAY_BANKS B,EPAY_BANK_BRANCHES BR
WHERE M.PAY_BANK_CODE=B.BANK_CODE
AND M.PAY_BANK_CODE=BR.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND M.LOCATION_CODE=BR.LOCATION_CODE
AND TO_CHAR(PAY_DATE,'RRRRMM') IN ('202012')
AND (M.PAY_BANK_CODE,M.PAY_BRANCH_CODE) IN (
SELECT ORG_PC_CODE, ORG_PC_BR_CODE FROM VW_MBP_API_BNK_BRAN_LIST@EPAY_SRL
WHERE TO_CHAR(PAY_DATE,'RRRRMM') IN ('202012')
)
GROUP BY TO_CHAR(M.PAY_DATE,'RRRRMM'),B.BANK_NAME
ORDER BY 2


---

SELECT ORG_PC_CODE, ORG_PC_BR_CODE FROM VW_MBP_API_BNK_BRAN_LIST@EPAY_SRL
WHERE PAY_DATE = '20-jan-2021' 

SELECT PAY_BANK_CODE,PAY_BANK_BR_CODE FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE@EPAY_SRL
WHERE PAY_DATE = '20-jan-2021' 
UNION
SELECT PAY_BANK_CODE,PAY_BANK_BR_CODE FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE_HIST@EPAY_SRL
WHERE PAY_DATE = '20-jan-2021' 