

SELECT EPAY.FN_EPAY_API_BNK_BTCH_REMOVE(:P_Batch_Num ,:P_PAY_DATE ) FROM DUAL



SELECT * FROM EPAY_BANKS@EPAY_SRL_DCC ORDER BY BANK_NAME DESC

------------BANK CODE BPDB SERVER------

54    Social Islami Bank Limited
16    One Bank Ltd
03    Pubali Bank
15	Ucbl

-------------------------------30------------------

SELECT *  FROM EPAY_PAYMENT_MST@EPAY_SRL_DCC
WHERE LOCATION_CODE='B1'
AND PAY_DATE='11-NOV-2019'
AND PAY_BANK_CODE='13'
AND STATUS='N'



SELECT * FROM EPAY_PAYMENT_DTL@EPAY_SRL_DCC
WHERE REF_BATCH_NO='MBP62137'

INSERT INTO EPAY_PAYMENT_MST_BNK_BKP@EPAY_SRL_DCC
SELECT * FROM EPAY_PAYMENT_MST@EPAY_SRL_DCC
WHERE REF_BATCH_NO='MBP62137'

INSERT INTO EPAY_PAYMENT_DTL_BNK_BKP@EPAY_SRL_DCC
SELECT * FROM EPAY_PAYMENT_DTL@EPAY_SRL_DCC
WHERE REF_BATCH_NO='MBP62137'

COMMIT;


-------------

DELETE FROM EPAY_PAYMENT_DTL@EPAY_SRL_DCC
WHERE REF_BATCH_NO='MBP62137'


DELETE  FROM EPAY_PAYMENT_MST@EPAY_SRL_DCC
WHERE REF_BATCH_NO='MBP62137'
AND STATUS='N'


COMMIT;

-------------------------24-----------------

SELECT * FROM EPAY_PAYMENT_MST
WHERE BATCH_NO='MBP62137'

SELECT *  FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO='MBP62137'

/*ORG_BR_CODE='E2'
AND PAY_DATE='24-FEB-2019'
AND ORG_BANK_CODE='54'
AND STATUS='T'*/



-------------


DELETE  FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO='MBP62137'


DELETE FROM EPAY_PAYMENT_MST
WHERE  BATCH_NO='MBP62137'


COMMIT;




-----------------------------23-------------------------------------------

SELECT * FROM MBP_PC_BRANCH@MBP_23 C

SELECT B.PC_NAME, A.MBP_PC_CODE MBP_BANK_CODE,C.PC_BR_NAME,C.PC_BR_CODE MBP_BRNC_CODE,A.ORG_PC_CODE EPAY_BANK_CODE,A.ORG_PC_BR_CODE EPAY_BRNC_CODE
FROM MBP_ORG_PC_BR_MAP@MBP_23 A,MBP_PAY_COLTR@MBP_23 B,MBP_PC_BRANCH@MBP_23 C
WHERE A.MBP_PC_CODE=B.PC_CODE
AND A.MBP_PC_BR_CODE=C.PC_BR_CODE
AND A.MBP_PC_CODE=C.PC_CODE
AND A.ORG_BR_CODE='B1'

SELECT * FROM VW_MBP_API_BATCH_NOT_GET--@EPAY24
WHERE LOC_CODE='B1'


SELECT * FROM MBP_ORG_PC_BR_MAP@MBP_23
WHERE ORG_BR_CODE='S4'


SELECT * FROM MBP_PAYMENT_DTL_OVC@MBP_23
WHERE PAY_DATE='11-NOV-2019'
AND ORG_BR_CODE='B1'
AND PAY_PC_CODE='10'
AND PAY_PC_BR_CODE='004'



SELECT *  FROM MBP_PAYMENT_DTL_OVC_HIST@MBP_23
WHERE PAY_DATE='11-NOV-2019'
AND ORG_BR_CODE='B1'
AND PAY_PC_CODE='10'
AND PAY_PC_BR_CODE='004'





INSERT INTO MBP_PAYMENT_DTL_OVC@MBP_23
SELECT * FROM MBP_PAYMENT_DTL_OVC_HIST@MBP_23
WHERE PAY_DATE='11-NOV-2019'
AND ORG_BR_CODE='B1'
AND PAY_PC_CODE='10'
AND PAY_PC_BR_CODE='004'


COMMIT;

SELECT * FROM MBP_PAYMENT_DTL_OVC@MBP_23
WHERE PAY_DATE='11-NOV-2019'
AND ORG_BR_CODE='B1'
AND PAY_PC_CODE='10'
AND PAY_PC_BR_CODE='004'



DELETE FROM MBP_PAYMENT_DTL_OVC_HIST@MBP_23
WHERE PAY_DATE='11-NOV-2019'
AND ORG_BR_CODE='B1'
AND PAY_PC_CODE='10'
AND PAY_PC_BR_CODE='004'

COMMIT;


UPDATE MBP_PAYMENT_DTL_OVC@MBP_23
SET STATUS='N'
WHERE PAY_DATE='18-JUL-2019'
AND ORG_BR_CODE='H6'
AND PAY_PC_CODE='77'
AND PAY_PC_BR_CODE='016'
AND STATUS='P'

COMMIT;

SELECT * FROM MBP_RECON_LOG@MBP_23
WHERE PAY_COLL_CODE = '10'
AND PAY_COLL_BR_CODE = '004'
AND PAY_DATE='21-NOV-2019'
 
 
DELETE FROM MBP_RECON_LOG@MBP_23
WHERE PAY_COLL_CODE = '77'
AND PAY_COLL_BR_CODE = '016'
AND PAY_DATE='18-JUL-2019'
 
COMMIT;

SELECT * FROM VW_MBP_API_BATCH_NOT_GET--@EPAY24
WHERE LOC_CODE='B1'