

---------------------169-------------

SELECT M.BATCH_NO, M.LOCATION_CODE, M.PAY_DATE,SUM(D.PDB_AMOUNT) PDB_AMOUNT,SUM(D.GOVT_DUTY) VAT,SUM(D.PDB_AMOUNT+D.GOVT_DUTY) TOT_AMOUNT, M.STATUS, 
M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME,COUNT(D.BILL_NUMBER) TOT_CONS 
FROM EPAY_PAYMENT_MST_INT@EPAYMENT M,EPAY_PAYMENT_DTL_INT@EPAYMENT D, EPAY_BANKS B,EPAY_BANK_BRANCHES BR
WHERE M.BATCH_NO=D.BATCH_NO 
AND M.PAY_BANK_CODE=B.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND B.BANK_CODE=BR.BANK_CODE
AND M.PAY_DATE='26-JUN-2018'
AND M.LOCATION_CODE='W1'
GROUP BY M.BATCH_NO, M.LOCATION_CODE, M.PAY_DATE, M.TOTAL_PDB_AMOUNT,M.NET_PDB_AMOUNT, M.TOTAL_GOVT_DUTY, M.STATUS, 
M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME



---------------------30-----mst--int------


SELECT M.BATCH_NO, M.LOCATION_CODE, M.PAY_DATE,SUM(D.PDB_AMOUNT) PDB_AMOUNT,SUM(D.GOVT_DUTY) VAT,SUM(D.PDB_AMOUNT+D.GOVT_DUTY) TOT_AMOUNT, M.STATUS, 
M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME,COUNT(D.BILL_NUMBER) TOT_CONS 
FROM EPAY_PAYMENT_MST_INT M,EPAY_PAYMENT_DTL_INT D, EPAY_BANKS B,EPAY_BANK_BRANCHES BR
WHERE M.BATCH_NO=D.BATCH_NO 
AND M.PAY_BANK_CODE=B.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND B.BANK_CODE=BR.BANK_CODE
AND M.PAY_DATE='26-JUN-2018'
AND M.LOCATION_CODE='W1'
GROUP BY M.BATCH_NO, M.LOCATION_CODE, M.PAY_DATE, M.TOTAL_PDB_AMOUNT,M.NET_PDB_AMOUNT, M.TOTAL_GOVT_DUTY, M.STATUS, 
M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME

SELECT * FROM VW_1EPAY_BANK_PYMT_UNVALED
WHERE PAY_DATE='26-JUN-2018'
AND LOC='W1'


SELECT * FROM VW_1EPAY_BANK_PYMT_VALED_ALL
WHERE PAY_DATE='26-JUN-2018'
AND LOC='W1'


---------------------30-------mst------

SELECT M.BATCH_NO, M.LOCATION_CODE, M.PAY_DATE,SUM(D.PDB_AMOUNT) PDB_AMOUNT,SUM(D.GOVT_DUTY) VAT,SUM(D.PDB_AMOUNT+D.GOVT_DUTY) TOT_AMOUNT, M.STATUS, 
M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME,COUNT(D.BILL_NUMBER) TOT_CONS 
FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D, EPAY_BANKS B,EPAY_BANK_BRANCHES BR
WHERE M.BATCH_NO=D.BATCH_NO 
AND M.PAY_BANK_CODE=B.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND B.BANK_CODE=BR.BANK_CODE
AND M.PAY_DATE='26-JUN-2018'
AND M.LOCATION_CODE='W1'
GROUP BY M.BATCH_NO, M.LOCATION_CODE, M.PAY_DATE, M.TOTAL_PDB_AMOUNT,M.NET_PDB_AMOUNT, M.TOTAL_GOVT_DUTY, M.STATUS, 
M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME





-------------------------------------------------------------------------------------------------------------------------------------------------------------------


SELECT M.BATCH_NO, M.LOCATION_CODE, M.PAY_DATE, M.TOTAL_PDB_AMOUNT,M.NET_PDB_AMOUNT, M.TOTAL_GOVT_DUTY, M.STATUS, 
M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME FROM EPAY_PAYMENT_MST_INT@EPAYMENT M,EPAY_BANKS B,EPAY_BANK_BRANCHES BR
WHERE M.PAY_BANK_CODE=B.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND B.BANK_CODE=BR.BANK_CODE
AND M.PAY_DATE='26-JUN-2018'
AND M.LOCATION_CODE='W1'


---------------------30-----mst--int------

SELECT M.BATCH_NO, M.LOCATION_CODE, M.PAY_DATE, M.TOTAL_PDB_AMOUNT,M.NET_PDB_AMOUNT, M.TOTAL_GOVT_DUTY, M.STATUS, 
M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME FROM EPAY_PAYMENT_MST_INT M,EPAY_BANKS B,EPAY_BANK_BRANCHES BR
WHERE M.PAY_BANK_CODE=B.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND B.BANK_CODE=BR.BANK_CODE
AND M.PAY_DATE='14-JUN-2018'
AND M.LOCATION_CODE='W4'


---------------------30-------mst------

SELECT M.BATCH_NO, M.LOCATION_CODE, M.PAY_DATE, M.TOTAL_PDB_AMOUNT,M.NET_PDB_AMOUNT, M.TOTAL_GOVT_DUTY, M.STATUS, 
M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME FROM EPAY_PAYMENT_MST M,EPAY_BANKS B,EPAY_BANK_BRANCHES BR
WHERE M.PAY_BANK_CODE=B.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND B.BANK_CODE=BR.BANK_CODE
AND M.PAY_DATE='14-JUN-2018'
AND M.LOCATION_CODE='W4'