

SELECT * FROM VW_EPAY_RECON_UNSUC_PDB_BNK@EPAY_SRL_DCC
WHERE BANK_CODE='54'
AND LOC='N2'
AND PAY_DATE='26-FEB-2020'


SELECT EPAY.FN_EPAY_API_BNK_BTCH_REMOVE(:P_Batch_Num ,:P_PAY_DATE ) FROM DUAL



select * from VW_MBP_API_BATCH_NOT_GET
where loc_code='N2'