
SELECT DFN_BILLING_BTCH_REMOVE (:P_BATCH_NO,:P_LOCATION_CODE) FROM DUAL


select 
'SELECT DFN_BILLING_BTCH_REMOVE ('''||BATCH_NO||''','''||LOCATION_CODE||''') FROM DUAL' from (
select distinct batch_no,location_code from EPAY_PAYMENT_MST
WHERE PAY_DATE='26-NOV-2018' AND PAY_BANK_CODE='96'
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='MOULAVIBAZAR'))

SELECT * FROM   EPAY_PAYMENT_MST
WHERE PAY_DATE='28-JUN-2018' 
AND PAY_BANK_CODE='96'
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='RANGPUR')


SELECT * FROM   PAYMENT_MST@EPAY_GP
WHERE PAY_DATE='28-JUN-2018' 
--AND PAY_BANK_CODE='96'
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='CHITTAGONG')

(E1,E4,E5,W3,W5,W6,N1,S1,)----DUE


SELECT
'select EPAY.DFN_BILLING_BTCH_REMOVE ('''||BATCH_NO||''','''||LOCATION_CODE||''') from dual' ||CHR(10)||CHR(10)||'COMMIT;' ||CHR(10) AS "RETURN_QUERY" FROM (
SELECT BATCH_NO,LOCATION_CODE FROM EPAY_PAYMENT_MST
WHERE PAY_DATE='01-DEC-2019'
AND PAY_BANK_CODE='96'
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='MOULAVIBAZAR')
GROUP BY BATCH_NO,LOCATION_CODE
ORDER BY LOCATION_CODE
)