
INSERT INTO EPAY_ACCOUNTID_GLCODE_MAP

select * from BC_ACCOUNTID_GLCODE_MAP@billing_ctg
where bank_code='94'

INSERT INTO BC_ACCOUNTID_GLCODE_MAP@billing_ctg
select B.BANK_BRANCH_ID BANK_ACCOUNT_ID,A.BILLING_BANK_CODE||A.BILLING_BRANCH_CODE BANK_ACCOUNT_NUM,B.BANK_BRANCH_ID,A.BILLING_BRANCH_CODE, A.BILLING_BANK_CODE, 'C' BANK_TYPE,'0' GL_CC_ID, 
'00' GL_RAO, '00000000' GL_UNIT, 'C' GL_UNITTYPE,'0000' GL_ACCOUNT,'00000' GL_SUBACCOUNT, 'A' STATUS, SYSDATE, 'SYSADMIN', NULL, NULL, 'C' REC_STATUS, 
A.LOCATION_CODE 
from epay_BANK_BRANCHES A,BC_BANK_BRANCHES@billing_ctg B
where A.BILLING_BANK_CODE=B.BANK_CODE
AND A.BILLING_BRANCH_CODE=B.BRANCH_CODE
AND A.location_code in (
select location_code from epay_location_master where center_name='CHITTAGONG')
AND A.BANK_CODE='94'
AND A.LOCATION_CODE<>'E3'
ORDER BY B.BANK_BRANCH_ID

COMMIT;



select * from epay_BANK_BRANCHES
where location_code in (
select location_code from epay_location_master where center_name='CHITTAGONG')
AND BANK_CODE='94'



INSERT INTO EPAY_ACCOUNTID_GLCODE_MAP
select BANK_ACCOUNT_ID, BANK_ACCOUNT_NUM, BANK_BRANCH_ID, BRANCH_CODE, BANK_CODE, 
BANK_TYPE, GL_CC_ID, GL_RAO, GL_UNIT, GL_UNITTYPE, GL_ACCOUNT, GL_SUBACCOUNT, STATUS, 
CREATE_DATE, CREATE_BY, UPDATE_DATE, UPDATE_BY, REC_STATUS, LOCATION_CODE 
from BC_ACCOUNTID_GLCODE_MAP@billing_syl
where bank_code='94'

COMMIT;



INSERT INTO EPAY_ACCOUNTID_GLCODE_MAP
select BANK_ACCOUNT_ID, BANK_ACCOUNT_NUM, BANK_BRANCH_ID, BRANCH_CODE, BANK_CODE, 
BANK_TYPE, GL_CC_ID, GL_RAO, GL_UNIT, GL_UNITTYPE, GL_ACCOUNT, GL_SUBACCOUNT, STATUS, 
CREATE_DATE, CREATE_BY, UPDATE_DATE, UPDATE_BY, REC_STATUS, LOCATION_CODE  
from BC_ACCOUNTID_GLCODE_MAP@BILLING_CTG
WHERE (BRANCH_CODE, BANK_CODE, LOCATION_CODE) IN (
select BRANCH_CODE,BANK_CODE,LOCATION_CODE from BC_ACCOUNTID_GLCODE_MAP@BILLING_CTG
MINUS
select BRANCH_CODE,BANK_CODE,LOCATION_CODE from EPAY_ACCOUNTID_GLCODE_MAP
where location_code in (
select location_code from epay_location_master where billing_dblink='BILLING_CTG')
)

COMMIT;