

SELECT A.LOCATION_CODE,B.DESCR LOCATION_NAME,  COUNT(*) TOT_CONSUMER
FROM BC_BILL_IMAGE@BILLING_bog A, BC_LOCATION_MASTER@BILLING_bog B 
WHERE A.LOCATION_CODE=B.LOCATION_CODE
AND A.BILL_CYCLE_CODE='201808' 
AND A.TARIFF='LT-A' 
AND A.CONS_KWH_SR<=75 
GROUP BY A.LOCATION_CODE,B.DESCR
ORDER BY 1 ASC



SELECT A.LOCATION_CODE,B.DESCR LOCATION_NAME,  COUNT(*) TOT_CONSUMER
FROM BC_BILL_IMAGE@BILLING_bog A, BC_LOCATION_MASTER@BILLING_bog B 
WHERE A.LOCATION_CODE=B.LOCATION_CODE
AND A.BILL_CYCLE_CODE='201808' 
AND A.TARIFF='LT-A' 
AND A.CONS_KWH_SR<=75 
GROUP BY A.LOCATION_CODE,B.DESCR
ORDER BY 1 ASC

SELECT * FROM BC_LOCATION_MASTER@BILLING_DIN