
SELECT * FROM BC_CUSTOMER_METER
WHERE CUST_ID IN (
SELECT CUST_ID FROM BC_CUSTOMERS
WHERE LOCATION_CODE=:P_LOCATION_CODE
and SPL_TYPE='CPR'
)
AND SPL_TYPE='CPR'


SELECT * FROM EBC.BC_CUSTOMER_METER CM, EBC.BC_CUSTOMERS C
WHERE CM.CUST_ID =C.CUST_ID
AND CM.CUSTOMER_NUM=C.CUSTOMER_NUM
AND C.LOCATION_CODE=:P_LOCATION_CODE
AND  CM.SPL_TYPE='CPR'


SELECT C.LOCATION_CODE,COUNT(*) MOTHER_METTER FROM EBC.BC_CUSTOMER_METER CM, EBC.BC_CUSTOMERS C
WHERE CM.CUST_ID =C.CUST_ID
AND CM.CUSTOMER_NUM=C.CUSTOMER_NUM
AND C.LOCATION_CODE LIKE NVL(:P_LOCATION_CODE,'%')
AND  CM.SPL_TYPE='CPR'
GROUP BY C.LOCATION_CODE
ORDER BY 1