
SELECT * FROM BC_TARIFF_GROUP_ID@BILLING_RONG
WHERE TARIFF_ID>=100
ORDER BY TARIFF_ID

select a.REMARKS,a.TARIFF_ID,TIME_CYCLE_CODE,CHARGE_BASE,LVAL,UVAL,RATE,EFF_DATE,EXP_DATE,EFF_START_BILL_CYCLE 
from BC_TARIFF_GROUP_ID@BILLING_RONG a,BC_TARIFF_RATE_MASTER@BILLING_RONG b
where a.TARIFF_ID=b.TARIFF_ID
and b.TARIFF_ID = 220
--and a.TARIFF_ID>='100'
 AND EFF_START_BILL_CYCLE = '202003'
 and b.TIME_CYCLE_CODE in ('1','2','3')
and b.CHARGE_BASE in ('01','02','03','16')
 order by a.TARIFF_ID
 
 
 SELECT * FROM BC_TARIFF_RATE_MASTER@BILLING_RONG b
 WHERE b.TARIFF_ID = 220
  AND EFF_START_BILL_CYCLE = '202003'