
INSERT INTO DBERSICE.UTILITY_BILL_PDB@PRODPDB
SELECT  COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
SYSDATE AS CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY.EPAY_UTILITY_BILL@EPAY_PDB
WHERE (ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE) IN (
SELECT ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE FROM EPAY.EPAY_UTILITY_BILL@EPAY_PDB
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_PDB WHERE CENTER_NAME IN ('SYLHET','MOULAVIBAZAR'))
MINUS
SELECT ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE FROM DBERSICE.UTILITY_BILL_PDB@PRODPDB
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_PDB WHERE CENTER_NAME IN ('SYLHET','MOULAVIBAZAR'))
);

COMMIT;




INSERT INTO UTILITY_BILL_PDB---@PRODPDB
SELECT  COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
SYSDATE AS CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY.EPAY_UTILITY_BILL@EPAY_PDB
WHERE (ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE) IN (
SELECT ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE FROM EPAY.EPAY_UTILITY_BILL@EPAY_PDB
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_PDB WHERE CENTER_NAME IN ('SYLHET','MOULAVIBAZAR'))
MINUS
SELECT ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE FROM UTILITY_BILL_PDB--@PRODPDB
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_PDB WHERE CENTER_NAME IN ('SYLHET','MOULAVIBAZAR'))
);
