
----------------PAYMENT   CHECK

SELECT * FROM EPAY_UTILITY_BILL
WHERE ACCOUNT_NUMBER=:P_ACCOUNT_NUMBER
AND BILL_MONTH='201508'


SELECT * FROM EPAY_PAYMENT_MST M, EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND  M.PAY_BANK_CODE='97'
AND (D.BILL_NUMBER,M.LOCATION_CODE) IN (
SELECT BILL_NUMBER,LOCATION_CODE FROM EPAY_UTILITY_BILL
WHERE ACCOUNT_NUMBER=:P_ACCOUNT_NUMBER
UNION
SELECT BILL_NUMBER,LOCATION_CODE FROM EPAY_UTILITY_BILL_DMP
WHERE ACCOUNT_NUMBER=:P_ACCOUNT_NUMBER
) ORDER BY PAY_DATE DESC



SELECT D.bill_number,SUM(NVL(D.PDB_AMOUNT,0)) AMT,SUM(NVL(D.GOVT_DUTY,0)) AS VAT FROM PAYMENT_MST@EPAY_ROBI M, PAYMENT_DTL@EPAY_ROBI D
WHERE M.BATCH_NO=D.BATCH_NO
--AND  M.PAY_BANK_CODE='97'
AND (D.BILL_NUMBER,M.LOCATION_CODE) IN (
SELECT BILL_NUMBER,LOCATION_CODE FROM UTILITY_BILL_pdb@epay_robi
WHERE ACCOUNT_NUMBER=:P_ACCOUNT_NUMBER
) 
GROUP BY D.BILL_NUMBER


----------------POSTING   CHECK


SELECT H.* FROM EBC.BC_RECEIPT_BATCH_HDR@BILLING_bog R, EBC.BC_RECEIPT_HDR@BILLING_bog H
WHERE R.BATCH_NUM=H.BATCH_NUM
AND R.LOCATION_CODE=H.LOCATION_CODE
AND (H.RECEIPT_DATE,H.INVOICE_NUM,H.LOCATION_CODE,R.BANK_CODE) IN ( 
SELECT PAY_DATE,SUBSTR(BILL_NUMBER,1,8),LOCATION_CODE,PAY_BANK_CODE FROM EPAY_PAYMENT_MST M, EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND  M.PAY_BANK_CODE='97'
AND (D.BILL_NUMBER,M.LOCATION_CODE) IN (
SELECT BILL_NUMBER,LOCATION_CODE FROM EPAY_UTILITY_BILL
WHERE ACCOUNT_NUMBER=:P_ACCOUNT_NUMBER
UNION
SELECT BILL_NUMBER,LOCATION_CODE FROM EPAY_UTILITY_BILL_DMP
WHERE ACCOUNT_NUMBER=:P_ACCOUNT_NUMBER
)) ORDER BY H.RECEIPT_DATE DESC


----------------RECEIPT_OFFSET  CHECK


SELECT H.* FROM BC_RECEIPT_BATCH_HDR@BILLING_bog R, BC_RECEIPT_HDR@BILLING_bog H
WHERE R.BATCH_NUM=H.BATCH_NUM
AND R.LOCATION_CODE=H.LOCATION_CODE
AND (H.RECEIPT_DATE,H.INVOICE_NUM,H.LOCATION_CODE,R.BANK_CODE,H.RECEIPT_OFFSET,H.VAT_OFFSET) IN ( 
SELECT PAY_DATE,SUBSTR(BILL_NUMBER,1,8),LOCATION_CODE,PAY_BANK_CODE,D.PDB_AMOUNT,D.GOVT_DUTY FROM EPAY_PAYMENT_MST M, EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND  M.PAY_BANK_CODE='97'
AND (D.BILL_NUMBER,M.LOCATION_CODE) IN (
SELECT BILL_NUMBER,LOCATION_CODE FROM EPAY_UTILITY_BILL
WHERE ACCOUNT_NUMBER=:P_ACCOUNT_NUMBER
UNION
SELECT BILL_NUMBER,LOCATION_CODE FROM EPAY_UTILITY_BILL_DMP
WHERE ACCOUNT_NUMBER=:P_ACCOUNT_NUMBER
)
)

