
--------------billing-----------

SELECT INVOICE_DUE_DATE,COUNT(1) FROM BC_BILL_IMAGE@BILLING_NAO
WHERE LOCATION_CODE=UPPER(:P_LOC_CODE)
AND BILL_CYCLE_CODE=:P_BILL_MONTH
AND BILL_GROUP =:P_BILL_GROUP
GROUP BY INVOICE_DUE_DATE

------------pdb--------------

SELECT BILL_DUE_DATE,COUNT(*) FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201809'
AND LOCATION_CODE=UPPER(:P_LOC_CODE)
AND ACCOUNT_NUMBER IN (
SELECT CUSTOMER_NUM||CONS_CHK_DIGIT FROM BC_BILL_IMAGE@BILLING_NAO
WHERE BILL_CYCLE_CODE='201809'
AND BILL_CYCLE_CODE=:P_BILL_MONTH
AND LOCATION_CODE=UPPER(:P_LOC_CODE)
AND BILL_GROUP =:P_BILL_GROUP
)GROUP BY BILL_DUE_DATE


--------------SRL-------------------

SELECT BILL_DUE_DATE,COUNT(*) FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH='201809'
AND LOCATION_CODE=UPPER(:P_LOC_CODE)
AND ACCOUNT_NUMBER IN (
SELECT CUSTOMER_NUM||CONS_CHK_DIGIT FROM BC_BILL_IMAGE@BILLING_NAO
WHERE BILL_CYCLE_CODE='201809'
AND BILL_CYCLE_CODE=:P_BILL_MONTH
AND LOCATION_CODE=UPPER(:P_LOC_CODE)
AND BILL_GROUP =:P_BILL_GROUP
)GROUP BY BILL_DUE_DATE


-------------ROBI------------------

SELECT BILL_DUE_DATE,COUNT(*) FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='201809'
AND LOCATION_CODE=UPPER(:P_LOC_CODE)
AND ACCOUNT_NUMBER IN (
SELECT CUSTOMER_NUM||CONS_CHK_DIGIT FROM BC_BILL_IMAGE@BILLING_NAO
WHERE BILL_CYCLE_CODE='201809'
AND BILL_CYCLE_CODE=:P_BILL_MONTH
AND LOCATION_CODE=UPPER(:P_LOC_CODE)
AND BILL_GROUP =:P_BILL_GROUP
)GROUP BY BILL_DUE_DATE