


INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE (ACCOUNT_NUMBER,BILL_NUMBER) IN (
SELECT ACCOUNT_NUMBER,BILL_NUMBER FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=:P_BILL_MONTH
--AND LOCATION_CODE='G5'
AND LOCATION_CODE IN ('G6','G7')
AND BILL_DUE_DATE>=TRUNC(SYSDATE)
AND DATA_TRANS_LOG='N'
MINUS
SELECT ACCOUNT_NUMBER,BILL_NUMBER FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE ='G5'
);

COMMIT;



UPDATE EPAY_UTILITY_BILL
SET DATA_TRANS_LOG='T'
WHERE BILL_MONTH='201705'
AND LOCATION_CODE='G5'
AND DATA_TRANS_LOG='N'
AND BILL_DUE_DATE>=TRUNC(SYSDATE)


COMMIT;


INSERT INTO UTILITY_BILL_PDB@EPAY_GP
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE (ACCOUNT_NUMBER,BILL_NUMBER) IN (
SELECT ACCOUNT_NUMBER,BILL_NUMBER FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=:P_BILL_MONTH
--AND LOCATION_CODE='G5'
AND LOCATION_CODE IN ('G6','G7')
AND BILL_DUE_DATE>=TRUNC(SYSDATE)
AND DATA_TRANS_LOG='N'
MINUS
SELECT ACCOUNT_NUMBER,BILL_NUMBER FROM UTILITY_BILL_PDB@EPAY_GP
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE ='G5'
);

COMMIT;

COMMIT;
