
SELECT 'EXECUTE EMP.dpd_despatch_rollback ('||CUST_ID||','||''''||BILL_CYCLE_CODE||''''||')' ||chr(10) FROM BC_METER_READING_CARD_DTL
WHERE BILL_CYCLE_CODE='201810'
AND CUST_ID IN (SELECT CUST_ID FROM BC_CUSTOMERS WHERE LOCATION_CODE='P2' AND AREA_CODE='D3609')
