
DBLINK                    CENTER NAME
------------------------------------------

DELETE FROM EPAY_UTILITY_BILL_GPR_X;

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_GPR_X
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_ctg
 WHERE BILL_CYCLE_CODE=:P_BILL_MONTH
--AND TARIFF IN ('A','C','B','D','E','J')
and substr(customer_num,1,1)<>'3'
AND TO_CHAR(INVOICE_DUE_DATE,'yyyymmdd')>=(SELECT  TO_CHAR(SYSDATE,'yyyymmdd') FROM DUAL)
AND INVOICE_NUM IS NOT NULL
AND  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%CHITTAGONG%');
                                       
                      
COMMIT;


DELETE FROM EPAY_UTILITY_BILL_GPR_X
WHERE ROWID IN (
SELECT ROWID FROM EPAY_UTILITY_BILL_GPR_X
MINUS
SELECT MAX(ROWID) FROM EPAY_UTILITY_BILL_GPR_X
GROUP BY ACCOUNT_NUMBER, BILL_NUMBER, LOCATION_CODE);


COMMIT;

--------------------ROBI---------------------

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT * FROM EPAY_UTILITY_BILL_GPR_X
WHERE  (ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE) IN (
SELECT  ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE FROM EPAY_UTILITY_BILL_GPR_X
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER)
MINUS
SELECT  ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER));

COMMIT;

------------------------GP----------------------

INSERT INTO DBERSICE.UTILITY_BILL_PDB@EPAY_GP
SELECT * FROM EPAY_UTILITY_BILL_GPR_X
WHERE (ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE) IN (
SELECT ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE FROM EPAY_UTILITY_BILL_GPR_X
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER)
MINUS
SELECT ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE FROM DBERSICE.UTILITY_BILL_PDB@EPAY_GP
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER));

COMMIT;

------------------------------PDB---------------------

INSERT INTO EPAY_UTILITY_BILL
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,'T' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL_GPR_X
WHERE (ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE) IN (
SELECT ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE FROM EPAY_UTILITY_BILL_GPR_X
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER)
MINUS
SELECT ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER));
 

COMMIT;

UPDATE BC_BILL_IMAGE@BILLING_CTG
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE=:P_BILL_MONTH
AND INVOICE_NUM IN (
SELECT SUBSTR(A.BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL_GPR_X A);


COMMIT;
