
SELECT 'SYLHET' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_SYL
WHERE BILL_CYCLE_CODE='202110'
AND INVOICE_NUM IS NOT NULL
GROUP BY DATA_TRANS_LOG;

COMMIT;


SELECT 'TANGAIL' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_TANG
WHERE BILL_CYCLE_CODE='202110'
AND INVOICE_NUM IS NOT NULL
GROUP BY DATA_TRANS_LOG;

COMMIT;

SELECT 'COMILLA' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_COM
WHERE BILL_CYCLE_CODE='202110'
AND INVOICE_NUM IS NOT NULL
GROUP BY DATA_TRANS_LOG;

COMMIT;


SELECT 'JAMALPUR' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_JAM
WHERE BILL_CYCLE_CODE='202110'
AND INVOICE_NUM IS NOT NULL
GROUP BY DATA_TRANS_LOG;

COMMIT;


SELECT 'MYMENSING' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_MYMEN
WHERE BILL_CYCLE_CODE='202110'
AND INVOICE_NUM IS NOT NULL
GROUP BY DATA_TRANS_LOG;

COMMIT;

SELECT 'CHITTAGONG' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_CTG
WHERE BILL_CYCLE_CODE='202110'
AND INVOICE_NUM IS NOT NULL
GROUP BY DATA_TRANS_LOG;

COMMIT;

SELECT 'KISHOREGANJ' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_KISHOR
WHERE BILL_CYCLE_CODE='202110'
AND INVOICE_NUM IS NOT NULL
GROUP BY DATA_TRANS_LOG;

COMMIT;

SELECT 'MOULOVIBAZAR' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_MOU
WHERE BILL_CYCLE_CODE='202110'
AND INVOICE_NUM IS NOT NULL
GROUP BY DATA_TRANS_LOG;

COMMIT;

/*

SELECT 'DINAJPUR' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_DIN
WHERE BILL_CYCLE_CODE='202110'
AND INVOICE_NUM IS NOT NULL
GROUP BY DATA_TRANS_LOG;

commit;

SELECT 'RANGPUR' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_RONG
WHERE BILL_CYCLE_CODE='202110'
AND INVOICE_NUM IS NOT NULL
GROUP BY DATA_TRANS_LOG;

commit;



SELECT 'NAOGAON' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_NAO
WHERE BILL_CYCLE_CODE='202110'
--AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_NAO)
GROUP BY DATA_TRANS_LOG;

commit;

SELECT 'RAJSHAHI' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_RAJ
WHERE BILL_CYCLE_CODE='202110'
--AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_RAJ)
GROUP BY DATA_TRANS_LOG;

commit;

SELECT 'BOGRA' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_BOG
WHERE BILL_CYCLE_CODE='202110'
--AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_BOG)
GROUP BY DATA_TRANS_LOG;

commit;
*/

/*
SELECT 'PABNA' CENTER_NAME,DECODE(DATA_TRANS_LOG,'T','Data Upload','N','Not Uploasd') as status,COUNT(*) NO_OF_CONS FROM BC_BILL_IMAGE@BILLING_PAB
WHERE BILL_CYCLE_CODE='202110'
--AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_PAB)
GROUP BY DATA_TRANS_LOG;

commit;
*/

/*
SELECT  DECODE(PM.PAY_BANK_CODE,'97','ROBI','96','GP' ) OPT_NAME, PM.LOCATION_CODE||'-'||LM.LOCATION_NAME DIVITION,PM.PAY_DATE,PM.NET_PDB_AMOUNT,PM.TOTAL_GOVT_DUTY VAT,PM.REVENUE_STAMP_AMOUNT,PM.TOTAL_PDB_AMOUNT,TRUNC(PM.CREATED_ON) RECON_DATE
 FROM EPAY.EPAY_PAYMENT_MST PM,EPAY.EPAY_LOCATION_MASTER LM
WHERE PM.LOCATION_CODE=LM.LOCATION_CODE
AND PM.PAY_DATE='30-OCT-2019'
AND PM.PAY_BANK_CODE='97'
AND LM.CENTER_NAME='COMILLA'
*/