select org_code,STATUS,count(*) from epay_payment_mst
where org_bank_code='94'
and status<>'T'
group by org_code,STATUS

select * from epay_payment_mst
where org_bank_code='94'
and status<>'T'
--AND PAY_DATE='22-JUN-2020'
--AND ORG_CODE='BPDB'

select COUNT(*) from epay_payment_DTL--@epay_srL
WHERE BATCH_NO IN (
select BATCH_NO from epay_payment_mst--@epay_srl
where org_bank_code='94'
--and status<>'T'
and org_code='NESCO'
AND PAY_DATE='22-JUN-2020'
AND ORG_BR_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_SRL_DCC 
WHERE CENTER_NAME IN ('RANGPUR','DINAJPUR','BOGRA','NAOGAON'))
)

SELECT 23762-23,762 FROM DUAL

SELECT COUNT(*) FROM MBP_CUST_PMNT_HIST@MBP_23
WHERE PAY_DATE='20-JUN-2020'
AND ORG_CODE='NESCO'


------

SELECT A.ORG_CODE,A.PAY_DATE,B.TOT_CONS_23,A.TOT_CONS_24,(B.TOT_CONS_23-A.TOT_CONS_24) DIFF FROM (
select ORG_CODE,PAY_DATE,COUNT(*) TOT_CONS_24 from epay_payment_mst M,epay_payment_DTL D
where M.BATCH_NO = D.BATCH_NO
AND M.org_bank_code='94'
and org_code=UPPER(:P_org_code)
AND TO_CHAR(PAY_DATE,'RRRRMM') ='202006'
GROUP BY ORG_CODE,PAY_DATE
)A,(
SELECT ORG_CODE,PAY_DATE,COUNT(*) TOT_CONS_23 FROM MBP_CUST_PMNT_HIST@MBP_23
WHERE org_code=UPPER(:P_org_code)
AND TO_CHAR(PAY_DATE,'RRRRMM') ='202006'
GROUP BY ORG_CODE,PAY_DATE
)B
WHERE A.ORG_CODE = B.ORG_CODE
AND A.PAY_DATE = B.PAY_DATE
ORDER BY 2 DESC
--GROUP BY A.ORG_CODE,A.PAY_DATE


select M.PAY_DATE,M.ORG_BR_CODE,M.ORG_BANK_CODE,COUNT(*)  from epay_payment_mst M,epay_payment_DTL D
where M.BATCH_NO = D.BATCH_NO
and org_code=UPPER(:P_org_code)
AND ORG_BANK_CODE<>'94'
AND TO_CHAR(PAY_DATE,'RRRRMM') ='202006'
GROUP BY M.PAY_DATE,M.ORG_BR_CODE,M.ORG_BANK_CODE
ORDER BY PAY_DATE DESC

select * from v$sql
where PARSING_SCHEMA_NAME='EPAY'
AND SQL_ID IN ('cykrcqu0aavh5','205y3vqa74myz')

select * from DBA_HIST_ACTIVE_SESS_HISTORY
WHERE SQL_ID ='cykrcqu0aavh5'

SELECT PAY_DATE,ORG_BR_CODE,PAY_PC_CODE,COUNT(*) FROM  MBP_PAYMENT_DTL_OVC_HIST@MBP_23 
WHERE TO_CHAR(PAY_DATE,'RRRRMM') ='202006'
GROUP BY PAY_DATE,ORG_BR_CODE,PAY_PC_CODE
ORDER BY PAY_DATE DESC




select PAY_DATE,ORG_CODE,ORG_BR_CODE,ORG_BANK_CODE,ORG_BANK_BRANCH_CODE,count(1) from EPAY_PAYMENT_MST
where pay_date between '01-jun-2020' and '30-jun-2020'
--and ORG_BANK_CODE='94'
group by PAY_DATE,ORG_CODE,ORG_BR_CODE,ORG_BANK_CODE,ORG_BANK_BRANCH_CODE
having count(1)>1