
SELECT BANK_NAME,BRANCH_NAME,LOC,LOC_NAME FROM VW_1EPAY_BANK_PYMT_VALED_ALL
WHERE LOC IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='TANGAIL')
GROUP BY BANK_NAME,BRANCH_NAME,LOC,LOC_NAME



SELECT BANK_NAME,BRANCH_NAME,LOCATION_CODE,LOCATION_NAME,MN_PAY_DATE,MX_PAY_DATE FROM VW_1EPAY_INS_BNK_BRNS_LST
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='TANGAIL')
GROUP BY BANK_NAME,BRANCH_NAME,LOCATION_CODE,LOCATION_NAME,MN_PAY_DATE,MX_PAY_DATE