SELECT  M.LOCATION_CODE, L.LOCATION_NAME,BR.BRANCH_NAME,SUM(NVL(PDB_AMOUNT,0)) PDB_AMOUNT,SUM(NVL(GOVT_DUTY,0)) VAT,SUM(NVL(PDB_AMOUNT,0))+SUM(NVL(GOVT_DUTY,0)) TOTAL_AMOUNT,COUNT(*) TOT_CONSUMER
FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D,EPAY_BANK_BRANCHES BR,EPAY_LOCATION_MASTER L
WHERE M.BATCH_NO=D.BATCH_NO
AND M.PAY_BANK_CODE=BR.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND M.LOCATION_CODE=L.LOCATION_CODE
AND BR.LOCATION_CODE=L.LOCATION_CODE
AND M.PAY_BANK_CODE='02'
AND M.PAY_DATE BETWEEN '01-MAR-2018' AND '31-MAR-2018'
GROUP BY M.LOCATION_CODE,L.LOCATION_NAME,BR.BRANCH_NAME
ORDER BY 1



SELECT  M.PAY_BRANCH_CODE 
FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D,EPAY_BANK_BRANCHES BR
WHERE M.BATCH_NO=D.BATCH_NO
AND M.PAY_BANK_CODE=BR.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND M.PAY_BANK_CODE='02'
AND M.PAY_DATE BETWEEN '01-MAR-2018' AND '31-MAR-2018'
GROUP BY M.PAY_BRANCH_CODE 


SELECT  * 
FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND M.PAY_BANK_CODE='02'
AND M.PAY_DATE BETWEEN '01-MAR-2018' AND '31-MAR-2018'
AND M.PAY_BRANCH_CODE='0011'


0011