
SELECT B.BANK_NAME,BR.BRANCH_NAME FROM EPAY_PAYMENT_MST M,EPAY_BANKS B,EPAY_BANK_BRANCHES BR
WHERE M.PAY_BANK_CODE=B.BANK_CODE
AND M.PAY_BANK_CODE=BR.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND B.BANK_CODE=BR.BANK_CODE
AND M.LOCATION_CODE=BR.LOCATION_CODE
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='MYMENSING')
AND M.PAY_BANK_CODE NOT IN ('96','97')
--AND CREATED_BY NOT IN ('MBP')
GROUP BY B.BANK_NAME,BR.BRANCH_NAME
ORDER BY 1

EPAY

MBP

SELECT * FROM EPAY_PAYMENT_MST M
WHERE M.PAY_BANK_CODE NOT IN ('96','97')
AND CREATED_BY NOT IN ('EPAYONLINE','MBP')