
SELECT ACCOUNT_NUMBER FROM (SELECT * FROM EPAY_UTILITY_BILL UNION SELECT * FROM EPAYMENT.EPAY_UTILITY_BILL_HSTR)
WHERE ACCOUNT_NUMBER =:P_ACCOUNT_NUMBER
AND BILL_MONTH LIKE NVL(:P_BILL_MONTH,'%')



----------- PAID BILL-----------

SELECT A.ACCOUNT_NUMBER,A.BILL_NUMBER,B.NAME,A.BILL_MONTH,A.CURRENT_GOVT_DUTY, A.TOTAL_BILL_AMOUNT FROM  EPAY_UTILITY_BILL A,EPAY_CUSTOMER_MASTER_DATA B
WHERE A.ACCOUNT_NUMBER=B.ACCOUNT_NO
AND A.LOCATION_CODE=B.LOCATION_CODE
AND  A.ACCOUNT_NUMBER =:P_ACCOUNT_NUMBER
AND A.BILL_MONTH LIKE NVL(:P_BILL_MONTH,'%')
AND (A.LOCATION_CODE,A.BILL_NUMBER) IN (
SELECT LOCATION_CODE,BILL_NUMBER FROM VW_EPAY_PAYMENT_MST_DTL)
ORDER BY A.BILL_MONTH DESC

--------------NOT PAID----------

SELECT A.ACCOUNT_NUMBER,A.BILL_NUMBER,B.NAME,A.BILL_MONTH,A.CURRENT_GOVT_DUTY, A.TOTAL_BILL_AMOUNT FROM  EPAY_UTILITY_BILL A,EPAY_CUSTOMER_MASTER_DATA B
WHERE A.ACCOUNT_NUMBER=B.ACCOUNT_NO
AND A.LOCATION_CODE=B.LOCATION_CODE
AND  (A.ACCOUNT_NUMBER,A.BILL_NUMBER,A.LOCATION_CODE) IN (
SELECT ACCOUNT_NUMBER,BILL_NUMBER,LOCATION_CODE FROM  EPAY_UTILITY_BILL 
WHERE ACCOUNT_NUMBER =:P_ACCOUNT_NUMBER
AND BILL_MONTH LIKE NVL(:P_BILL_MONTH,'%')
MINUS
SELECT ACCOUNT_NUMBER,BILL_NUMBER,LOCATION_CODE FROM  EPAY_UTILITY_BILL 
WHERE ACCOUNT_NUMBER =:P_ACCOUNT_NUMBER
AND BILL_MONTH LIKE NVL(:P_BILL_MONTH,'%')
--AND BILL_MONTH IN (SELECT TO_CHAR (ADD_MONTHS (SYSDATE,1), 'RRRRMM') FROM DUAL)
AND (LOCATION_CODE,BILL_NUMBER) IN (
SELECT LOCATION_CODE,BILL_NUMBER FROM VW_EPAY_PAYMENT_MST_DTL))



----------- PAID BILL-----------

SELECT A.ACCOUNT_NUMBER,A.BILL_NUMBER,B.NAME,A.BILL_MONTH,A.CURRENT_GOVT_DUTY, A.TOTAL_BILL_AMOUNT FROM  EPAY_UTILITY_BILL A,EPAY_CUSTOMER_MASTER_DATA B
WHERE A.ACCOUNT_NUMBER=B.ACCOUNT_NO
AND A.LOCATION_CODE=B.LOCATION_CODE
AND  A.ACCOUNT_NUMBER =:P_ACCOUNT_NUMBER
AND A.BILL_MONTH LIKE NVL(:P_BILL_MONTH,'%')
AND (A.LOCATION_CODE,A.BILL_NUMBER) IN (
SELECT LOCATION_CODE,BILL_NUMBER FROM VW_EPAY_PAYMENT_MST_DTL)
ORDER BY A.BILL_MONTH DESC

--------------NOT PAID----------

SELECT A.ACCOUNT_NUMBER,A.BILL_NUMBER,B.NAME,A.BILL_MONTH,A.CURRENT_GOVT_DUTY, A.TOTAL_BILL_AMOUNT
FROM (SELECT * FROM  EPAY_UTILITY_BILL UNION SELECT * FROM  EPAYMENT.EPAY_UTILITY_BILL_HSTR) A,EPAY_CUSTOMER_MASTER_DATA B
WHERE A.ACCOUNT_NUMBER=B.ACCOUNT_NO
AND A.LOCATION_CODE=B.LOCATION_CODE
AND  (A.ACCOUNT_NUMBER,A.BILL_NUMBER,A.LOCATION_CODE) IN (
SELECT ACCOUNT_NUMBER,BILL_NUMBER,LOCATION_CODE FROM  EPAY_UTILITY_BILL 
WHERE ACCOUNT_NUMBER  LIKE NVL (:P_ACCOUNT_NUMBER,'%')
AND BILL_MONTH =:P_BILL_MONTH
MINUS
SELECT ACCOUNT_NUMBER,BILL_NUMBER,LOCATION_CODE FROM  EPAY_UTILITY_BILL 
WHERE ACCOUNT_NUMBER LIKE NVL (:P_ACCOUNT_NUMBER,'%')
AND BILL_MONTH =:P_BILL_MONTH
--AND BILL_MONTH IN (SELECT TO_CHAR (ADD_MONTHS (SYSDATE,1), 'RRRRMM') FROM DUAL)
AND (LOCATION_CODE,BILL_NUMBER) IN (
SELECT LOCATION_CODE,BILL_NUMBER FROM (SELECT * FROM VW_EPAY_PAYMENT_MST_DTL UNION  SELECT * FROM EPAYMENT.VW_EPAY_PAYMENT_MST_DTL_HIST))


SELECT LOCATION_CODE,BILL_NUMBER FROM (SELECT * FROM VW_EPAY_PAYMENT_MST_DTL UNION  SELECT * FROM EPAYMENT.VW_EPAY_PAYMENT_MST_DTL_HIST)



select * from VW_EPAY_PAYMENT_MST_DTL



SELECT * FROM  EPAY_UTILITY_BILL 
WHERE ACCOUNT_NUMBER =:P_ACCOUNT_NUMBER
AND BILL_MONTH BETWEEN TO_CHAR (ADD_MONTHS (SYSDATE,-1), 'RRRRMM') FROM DUAL and

IN (SELECT TO_CHAR (ADD_MONTHS (SYSDATE,-1), 'RRRRMM') FROM DUAL) 

UNION 
AND BILL_MONTH IN (SELECT TO_CHAR (ADD_MONTHS (SYSDATE,-12), 'RRRRMM') FROM DUAL) 

SELECT TO_CHAR (ADD_MONTHS (SYSDATE,-1), 'RRRRMM') FROM DUAL UNION SELECT TO_CHAR (ADD_MONTHS (SYSDATE, -12), 'RRRRMM') FROM DUAL
 
SELECT TO_CHAR(ADD_MONTHS( CURRENT_DATE, 6 )) from dual
 

  
  SELECT MONTHS_BETWEEN (
   TO_CHAR (ADD_MONTHS (SYSDATE,0), 'RRRRMM'),
    TO_CHAR (ADD_MONTHS (SYSDATE, -11), 'RRRRMM'))  "Months"
    FROM DUAL