

INSERT INTO EBC.BC_CATEGORY_MASTER
 (CATEGORY_ID,SANCTIONED_LOAD_CATEGORY_CODE,VOLTAGE_CATEGORY_CODE,USAGE_CATEGORY_CODE,CUSTOMER_TYPE_CODE,
SEASONAL_CATEGORY_CODE,NO_OF_COPIES,CREATE_DATE,CREATE_BY,REC_STATUS,BUS_TYPE_CODE,SPL_CODE,TARIFF_ID,STATUS)
VALUES 
(20919,'02','V02','MT-6','05','99',1,TO_DATE ('01/09/2018 20:18:07', 'MM/DD/YYYY HH24:MI:SS'),'SYSADMIN','C',
'79','57',230,'A')