


        SELECT PA.PACKAGE_ID,PA.PACKAGE_NAME 
        FROM CBPRO_PACKAGE_MST PA, CBPRO_PRODUCT_MST PR,ADMIN_USER_MST U
        WHERE PA.ORG_CODE=PR.ORG_CODE
        AND PA.PRODUCT_ID=PR.PRODUCT_ID
        AND PA.ORG_CODE=U.ORG_CODE
        AND PR.ORG_CODE=U.ORG_CODE
        AND PA.ORG_CODE=P_Org_Code
        AND PA.PRODUCT_ID=P_Product_Id
        AND U.USER_ID=P_User_Id
        ORDER BY 1 ASC;



SELECT * FROM CBPRO_PACKAGE_CATEGORY_MST C,CBPRO_PRODUCT_MST PR,CBPRO_PACKAGE_MST PA,ADMIN_USER_MST U
WHERE C.ORG_CODE=PR.ORG_CODE
AND C.PRODUCT_ID=PR.PRODUCT_ID
AND C.ORG_CODE=PA.ORG_CODE
AND C.PACKAGE_ID=PA.PACKAGE_ID
AND PR.ORG_CODE=PA.ORG_CODE
AND PR.PRODUCT_ID=PA.PRODUCT_ID
AND C.ORG_CODE=U.ORG_CODE
AND PR.ORG_CODE=U.ORG_CODE
AND PA.ORG_CODEU.ORG_CODE


SELECT * FROM CBPRO_PACKAGE_MST PA, CBPRO_PRODUCT_MST PR,ADMIN_USER_MST U
WHERE PA.ORG_CODE=PR.ORG_CODE
AND PA.PRODUCT_ID=PR.PRODUCT_ID
AND PA.ORG_CODE=U.ORG_CODE
AND PR.ORG_CODE=U.ORG_CODE
AND PA.PRODUCT_ID=
AND PA.ORG_CODE=
AND U.USER_ID=

---GRID-----

SELECT * FROM CBPRO_CUSTOMER_CATEGORY CC,CBPRO_CUSTOMERS C,CBPRO_PRODUCT_MST PR,
                        CBPRO_PACKAGE_MST PA,CBPRO_PACKAGE_CATEGORY_MST PC,ADMIN_USER_MST U
WHERE CC.ORG_CODE=C.ORG_CODE
AND CC.CUST_ID=C.CUST_ID
AND CC.ORG_CODE=PR.ORG_CODE
AND CC.PRODUCT_ID=PR.PRODUCT_ID
AND CC.ORG_CODE=PA.ORG_CODE
AND CC.PACKAGE_ID=PA.PACKAGE_ID
AND CC.ORG_CODE=PC.ORG_CODE
AND CC.CATEGORY_ID=PC.CATEGORY_ID
AND CC.PRODUCT_ID=PC.PRODUCT_ID
AND CC.PACKAGE_ID=PC.PACKAGE_ID
AND CC.ORG_CODE=U.ORG_CODE



SELECT * FROM CBPRO_PACKAGE_CATEGORY_MST C,CBPRO_PRODUCT_MST PR,CBPRO_PACKAGE_MST PA,ADMIN_USER_MST U
WHERE C.ORG_CODE=PR.ORG_CODE
AND C.PRODUCT_ID=PR.PRODUCT_ID
AND C.ORG_CODE=PA.ORG_CODE
AND C.PACKAGE_ID=PA.PACKAGE_ID
AND PR.ORG_CODE=PA.ORG_CODE
AND PR.PRODUCT_ID=PA.PRODUCT_ID
AND C.ORG_CODE=U.ORG_CODE
AND PR.ORG_CODE=U.ORG_CODE
AND PA.ORG_CODEU.ORG_CODE

SELECT CC.CUST_CAT_ID,CC.ORG_CODE,C.CUST_NAME,PR.PRODUCT_NAME,PA.PACKAGE_NAME,PC.CATEGORY_NAME FROM CBPRO_CUSTOMER_CATEGORY CC,CBPRO_CUSTOMERS C,CBPRO_PRODUCT_MST PR,
                        CBPRO_PACKAGE_MST PA,CBPRO_PACKAGE_CATEGORY_MST PC,ADMIN_USER_MST U
WHERE CC.ORG_CODE=C.ORG_CODE
AND CC.CUST_ID=C.CUST_ID
AND CC.ORG_CODE=PR.ORG_CODE
AND CC.PRODUCT_ID=PR.PRODUCT_ID
AND CC.ORG_CODE=PA.ORG_CODE
AND CC.PACKAGE_ID=PA.PACKAGE_ID
AND CC.ORG_CODE=PC.ORG_CODE
AND CC.CATEGORY_ID=PC.CATEGORY_ID
AND CC.PRODUCT_ID=PC.PRODUCT_ID
AND CC.PACKAGE_ID=PC.PACKAGE_ID
AND CC.ORG_CODE=U.ORG_CODE
ORDER BY 1 ASC;