
SELECT * FROM BC_CUSTOMERS C
WHERE C.START_BILL_CYCLE='201901'
AND C.LOCATION_CODE='L1'



SELECT C.LOCATION_CODE,C.AREA_CODE,C.CONS_EXTG_NUM AC,C.CUSTOMER_NAME,C.WALKING_SEQUENCE PAGE,C.CUSTOMER_NUM||C.CHECK_DIGIT CUSTOMER_NUM,C.START_BILL_CYCLE,
CM.METER_NUM,CA.ADDR_DESCR1||','||CA.ADDR_DESCR2||','||CA.ADDR_DESCR3 AS ADDRESS,ct.USAGE_CATEGORY_CODE TARIFF,CL.CONNECTED_LOAD C_LOAD,SL.SANCTIONED_LOAD S_LOAD,MS.EFF_DATE 
FROM BC_CUSTOMERS C,BC_CUSTOMER_METER CM,BC_CUSTOMER_ADDR CA,bc_category_master CT,BC_CONNECTED_LOAD CL,BC_SANCTIONED_LOAD SL,BC_METER_SUPPLY MS
WHERE C.CUST_ID=CM.CUST_ID
AND C.CUST_ID=CA.CUST_ID
AND CA.ADDR_TYPE='M'
AND CA.ADDR_EXP_DATE IS NULL
AND CT.CATEGORY_ID IN (SELECT CAT_ID FROM bc_customer_category a where C.CUST_ID=a.CUST_ID AND a.EXP_DATE IS NULL)
AND C.CUST_ID=CL.CUST_ID
AND C.CUST_ID=SL.CUST_ID
AND CM.CONNECTION_ID=MS.CONNECTION_ID
AND C.START_BILL_CYCLE='201207'
AND C.LOCATION_CODE='L1'
