

SELECT  IM.PAY_BANK_CODE||'-'||B.BANK_NAME AS BANK_NAME,Z.COMP_CNTR_CODE||'-'||Z.COMP_CNTR_NAME AS COMP_CENTER_NAME,
                L.LOCATION_CODE||'-'||INITCAP(L.LOCATION_NAME) AS LOCATION_NAME,TO_CHAR(IM.PAY_DATE,'DD-MON-YYYY') AS PAY_date,
                SUM(NVL(ID.PDB_AMOUNT,0)+NVL(ID.GOVT_DUTY,0)) AS UTILITY_AMOUNT,
                SUM(NVL(ID.PDB_AMOUNT,0)) AS PDB_AMOUNT,SUM(NVL(ID.GOVT_DUTY,0)) VAT,COUNT(1) AS NO_OF_CON 
                FROM EPAY_PAYMENT_MST IM,EPAY_PAYMENT_DTL ID,EPAY_LOCATION_MASTER L,EPAY_BANKS B,
                EPAY_BANK_BRANCHES BR,EPAY_USER_MST U,V_Z_C_C_L Z
                WHERE IM.BATCH_NO=ID.BATCH_NO
                AND IM.LOCATION_CODE=L.LOCATION_CODE
                AND IM.LOCATION_CODE=Z.LOCATION_CODE
                AND L.LOCATION_CODE=Z.LOCATION_CODE
                AND IM.LOCATION_CODE=BR.LOCATION_CODE
                AND IM.PAY_BANK_CODE=B.BANK_CODE
                AND IM.PAY_BANK_CODE=U.BANK_CODE
                 AND IM.STATUS IN ('P','T')
                AND L.STATUS='A'
                AND B.BANK_CODE=BR.BANK_CODE
                AND Z.COMP_CNTR_CODE LIKE DECODE(:P_COMP_CNTR_CODE,'ALL','%',:P_COMP_CNTR_CODE)
                AND B.BANK_CODE=:P_BANK_CODE
                AND U.USER_NAME=:app_user
                AND im.PAY_DATE>=:P_START_PAY_DATE
                AND im.PAY_DATE<=:P_END_PAY_DATE
                GROUP BY IM.PAY_BANK_CODE||'-'||B.BANK_NAME,Z.COMP_CNTR_CODE||'-'||Z.COMP_CNTR_NAME,
                L.LOCATION_CODE||'-'||INITCAP(L.LOCATION_NAME),TO_CHAR(IM.PAY_DATE,'DD-MON-YYYY')
                ORDER BY 4 ASC,3 ASC     