SELECT COUNT(*) FROM (
SELECT TO_NUMBER(INVOICE_NUM) AS INVOICE_NUM FROM BC_BILL_IMAGE@BILLING_syl
WHERE BILL_CYCLE_CODE='201511'
--AND INVOICE_DUE_DATE>=TRUNC(SYSDATE)
MINUS
SELECT TO_NUMBER(SUBSTR(BILL_NUMBER,1,8)) AS INVOICE_NUM FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201511'
--AND BILL_DUE_DATE>=TRUNC(SYSDATE) 
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME=upper('sylhet')
)
)



SELECT COUNT(*) FROM (
SELECT TO_NUMBER(INVOICE_NUM) AS INVOICE_NUM FROM BC_BILL_IMAGE@BILLING_DIN
WHERE BILL_CYCLE_CODE='201511'
AND INVOICE_DUE_DATE>=TRUNC(SYSDATE)
MINUS
SELECT TO_NUMBER(SUBSTR(BILL_NUMBER,1,8)) AS INVOICE_NUM FROM UTILITY_BILL_pdb@epay_robi
WHERE BILL_MONTH='201511'
AND BILL_DUE_DATE>=TRUNC(SYSDATE) 
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='DINAJPUR'
)
)