SELECT * FROM EPAY_PAYMENT_MST
WHERE TO_CHAR(PAY_DATE,'rrrrmm')='201708'
AND PAY_BANK_CODE='97'
AND 1=(SELECT CASE WHEN PDB_PAY_CNT=ROBI_PAY_CNT THEN 1 ELSE 2 END AS RESULT FROM (
             SELECT COUNT(*) PDB_PAY_CNT FROM EPAY_PAYMENT_MST
             WHERE TO_CHAR(PAY_DATE,'rrrrmm')='201708'
             AND PAY_BANK_CODE='97'  ) PDB,
            (SELECT COUNT(*) ROBI_PAY_CNT FROM PAYMENT_MST@EPAY_ROBI
             WHERE TO_CHAR(PAY_DATE,'rrrrmm')='201708'
             AND STATUS='T'  ) ROBI
            )


select * from VW_ZONE_WISE_COLL_PDB
where payment_month='201708'
and bank_code='97'
AND 1=(SELECT CASE WHEN PDB_PAY_CNT=ROBI_PAY_CNT THEN 1 ELSE 2 END AS RESULT FROM (
             SELECT COUNT(*) PDB_PAY_CNT FROM EPAY_PAYMENT_MST
             WHERE TO_CHAR(PAY_DATE,'rrrrmm')='201707'
             AND PAY_BANK_CODE='97'  ) PDB,
            (SELECT COUNT(*) ROBI_PAY_CNT FROM PAYMENT_MST@EPAY_ROBI
             WHERE TO_CHAR(PAY_DATE,'rrrrmm')='201708'
             AND STATUS='T'  ) ROBI
            )