
EXECUTE EPAY_PYMT_NOT_EQUAL;

INSERT INTO EPAY_PAYMENT_MST
SELECT * FROM EPAY_PAYMENT_MST_X

INSERT INTO EPAY_PAYMENT_DTL
SELECT * FROM EPAY_PAYMENT_DTL_X


INSERT INTO EPAY_PAYMENT_MST
SELECT * FROM EPAY_PAYMENT_MST_XX

INSERT INTO EPAY_PAYMENT_DTL
SELECT * FROM EPAY_PAYMENT_DTL_XX


---------------------------------------------------------------


DELETE FROM EPAY_PYMT_NOT_MATCH;

COMMIT;

INSERT INTO EPAY_PYMT_NOT_MATCH 
SELECT EPAY.BATCH_NO,EPAY.REF_BATCH_NO,EPAY.LOCATION_CODE,BC.BANK_CODE,BC.BATCH_NUM,EPAY.RECEIPT_DATE,EPAY.NO_OF_CONS,BC.BC_NO_OF_CONS,
DECODE(SIGN(EPAY.NO_OF_CONS-BC.BC_NO_OF_CONS),1,'Not Match of cons ')||to_char(EPAY.NO_OF_CONS-BC.BC_NO_OF_CONS) as status FROM (
SELECT BATCH_NO,REF_BATCH_NO,LOCATION_CODE,PAY_BANK_CODE,BATCH_NUM_PDB,RECEIPT_DATE,NO_OF_CONS FROM (
select  M.BATCH_NO,M.REF_BATCH_NO,M.PAY_BANK_CODE,R.BATCH_NUM_PDB,R.RECEIPT_DATE,M.LOCATION_CODE from EPAY_PAYMENT_MST M,EPAY_LOCATION_MASTER L,EPAY_RECEIPT_BATCH_HDR_PDB R
WHERE M.LOCATION_CODE=L.LOCATION_CODE
AND L.LOCATION_CODE=R.LOCATION_CODE
AND M.LOCATION_CODE=R.LOCATION_CODE 
AND M.BATCH_NO=R.BATCH_NUM_EPAY
AND M.PAY_DATE=R.RECEIPT_DATE
AND M.STATUS='T'
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='DINAJPUR'
)
AND M.PAY_BANK_CODE=R.BANK_CODE
AND TO_CHAR(M.PAY_DATE,'RRRRMM')>='201501'
AND M.PAY_BANK_CODE='97') MST,(
select BATCH_NO AS RCT_BATCH_NO,COUNT(1) AS NO_OF_CONS from EPAY_PAYMENT_DTL
GROUP BY BATCH_NO) DTL
WHERE MST.BATCH_NO=DTL.RCT_BATCH_NO) EPAY,(
SELECT H.BATCH_NUM,H.RECEIPT_DATE,H.LOCATION_CODE,H.BANK_CODE,COUNT(1) AS BC_NO_OF_CONS FROM BC_RECEIPT_BATCH_HDR@BILLING_DIN R, BC_RECEIPT_HDR@BILLING_DIN H
WHERE R.BATCH_NUM=H.BATCH_NUM
AND R.LOCATION_CODE=H.LOCATION_CODE
AND R.BANK_CODE=H.BANK_CODE
AND TO_CHAR(R.RECEIPT_DATE,'RRRRMM')>='201501'
AND R.BANK_CODE='97'
GROUP BY H.BATCH_NUM,H.RECEIPT_DATE,H.LOCATION_CODE,H.BANK_CODE) BC
WHERE EPAY.BATCH_NUM_PDB=BC.BATCH_NUM
AND EPAY.LOCATION_CODE=BC.LOCATION_CODE
AND EPAY.RECEIPT_DATE=BC.RECEIPT_DATE
AND EPAY.PAY_BANK_CODE=BC.BANK_CODE
AND EPAY.NO_OF_CONS<>BC.BC_NO_OF_CONS
ORDER BY EPAY.RECEIPT_DATE DESC,EPAY.LOCATION_CODE ASC;


COMMIT;



SELECT * FROM EPAY_PYMT_NOT_MATCH


EXECUTE EPAY_PYMT_NOT_EQUAL;


          
                            SELECT * FROM EPAY_ERR_LOG
                            WHERE RUN_ID=78666
                            
                            DELETE FROM EPAY_ERR_LOG
                            WHERE RUN_ID=78666
                            
                            
                            INSERT INTO EPAY_PAYMENT_MST
                            SELECT * FROM EPAY_PAYMENT_MST_X
                            
                                          INSERT INTO EPAY_PAYMENT_DTL
                            SELECT * FROM EPAY_PAYMENT_DTL_X
                            
                            
                            ------------------------------------
                            
                            
                             INSERT INTO EPAY_PAYMENT_MST
                            SELECT * FROM EPAY_PAYMENT_MST_XX
                            
                            
                             INSERT INTO EPAY_PAYMENT_DTL
                            SELECT * FROM EPAY_PAYMENT_DTL_XX
                            
                            
                            DELETE FROM EPAY_PAYMENT_MST_X
                            
                            
                            DELETE FROM EPAY_PAYMENT_DTL_X
                            
                            
                            DELETE FROM EPAY_PAYMENT_MST_XX
                            
                            
                            DELETE FROM EPAY_PAYMENT_DTL_XX


COMMIT;



SELECT SUM(EPAY.NO_OF_CONS-BC.BC_NO_OF_CONS) AS TOTAL FROM (
SELECT BATCH_NO,LOCATION_CODE,PAY_BANK_CODE,BATCH_NUM_PDB,RECEIPT_DATE,NO_OF_CONS FROM (
select  M.BATCH_NO,M.PAY_BANK_CODE,R.BATCH_NUM_PDB,R.RECEIPT_DATE,M.LOCATION_CODE from EPAY_PAYMENT_MST M,EPAY_LOCATION_MASTER L,EPAY_RECEIPT_BATCH_HDR_PDB R
WHERE M.LOCATION_CODE=L.LOCATION_CODE
AND L.LOCATION_CODE=R.LOCATION_CODE
AND M.LOCATION_CODE=R.LOCATION_CODE 
AND M.BATCH_NO=R.BATCH_NUM_EPAY
AND M.PAY_DATE=R.RECEIPT_DATE
AND M.STATUS='T'
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='RAJSHAHI'
)
AND M.PAY_BANK_CODE=R.BANK_CODE
AND TO_CHAR(M.PAY_DATE,'RRRRMM')>='201501'
AND M.PAY_BANK_CODE='97') MST,(
select BATCH_NO AS RCT_BATCH_NO,COUNT(1) AS NO_OF_CONS from EPAY_PAYMENT_DTL
GROUP BY BATCH_NO) DTL
WHERE MST.BATCH_NO=DTL.RCT_BATCH_NO) EPAY,(
SELECT H.BATCH_NUM,H.RECEIPT_DATE,H.LOCATION_CODE,H.BANK_CODE,COUNT(1) AS BC_NO_OF_CONS FROM BC_RECEIPT_BATCH_HDR@BILLING_RAJ R, BC_RECEIPT_HDR@BILLING_RAJ H
WHERE R.BATCH_NUM=H.BATCH_NUM
AND R.LOCATION_CODE=H.LOCATION_CODE
AND R.BANK_CODE=H.BANK_CODE
AND TO_CHAR(R.RECEIPT_DATE,'RRRRMM')>='201501'
AND R.BANK_CODE='97'
GROUP BY H.BATCH_NUM,H.RECEIPT_DATE,H.LOCATION_CODE,H.BANK_CODE) BC
WHERE EPAY.BATCH_NUM_PDB=BC.BATCH_NUM
AND EPAY.LOCATION_CODE=BC.LOCATION_CODE
AND EPAY.RECEIPT_DATE=BC.RECEIPT_DATE
AND EPAY.PAY_BANK_CODE=BC.BANK_CODE
AND EPAY.NO_OF_CONS<>BC.BC_NO_OF_CONS
ORDER BY EPAY.RECEIPT_DATE DESC,EPAY.LOCATION_CODE ASC