
ECOM_PRODUCT_DELIVERY_DTL
ECOM_PRODUCT_ORDER_DTL
ECOM_PRODUCT_ORDER_MST




SELECT * FROM ECOM_CUSTOMER_MST


SELECT * FROM ECOM_PRODUCT_ORDER_DTL O, ECOM_PRODUCT_DELIVERY_DTL D, ECOM_PRODUCT_ORDER_MST M,ECOM_CUSTOMER_MST C
WHERE O.ORDER_DTL_ID=D.ORDER_DTL_ID
AND M.CUST_ID=C.CUST_ID



SELECT COUNT(*) TOTAL_ORDER 
FROM ECOM_PRODUCT_ORDER_DTL O, ECOM_PRODUCT_DELIVERY_DTL D,ECOM_PRODUCT_ORDER_MST M,ECOM_CUSTOMER_MST CU
WHERE O.ORDER_DTL_ID=D.ORDER_DTL_ID
AND D.ORDER_ID=M.ORDER_ID
AND M.CUST_ID=CU.CUST_ID
AND M.CUST_ID=:P_CUST_ID


SELECT SUM(ORDER_AMT) TOTAL_ORDER_AMOUNT FROM ECOM_PRODUCT_ORDER_MST
WHERE CUST_ID=:P_CUST_ID



SELECT COUNT(*) TOTAL_ORDER 
FROM ECOM_PRODUCT_ORDER_DTL O, ECOM_PRODUCT_DELIVERY_DTL D,ECOM_PRODUCT_ORDER_MST M,ECOM_CUSTOMER_MST CU
WHERE O.ORDER_DTL_ID=D.ORDER_DTL_ID
AND D.ORDER_ID=M.ORDER_ID
AND M.CUST_ID=CU.CUST_ID
AND M.CUST_ID=:P_CUST_ID