SELECT * FROM EPAY_BANKS
WHERE BANK_CODE='31'

SELECT * FROM EPAY_BANK_BRANCHES
WHERE BANK_CODE='31'
AND BRANCH_CODE='0004'


UPDATE EPAY_BANK_BRANCHES
SET BRANCH_NAME=INITCAP(BRANCH_NAME)
WHERE BANK_CODE='31'
AND BRANCH_CODE='0004'

SELECT * FROM EPAY_BANKS_MAP
WHERE BANK_CODE='31'

SELECT * FROM BC_BANKS@BILLING_MYMEN
WHERE BANK_CODE='32'

SELECT * FROM  BC_BANK_BRANCHES@BILLING_MYMEN
WHERE BANK_CODE='32'

and branch_code='3201'

SELECT * FROM BC_BANK_BRANCHES@BILLING_CTG
WHERE BANK_CODE='18'
and branch_code='3201'


SELECT * FROM EPAY_BANK_BRANCHES--@BILLING_CTG
WHERE BANK_CODE='34'

SELECT * FROM EPAY_BANKS_MAP
WHERE BANK_CODE='34'


SELECT A.BANK_CODE,A.BRANCH_CODE,A.BRANCH_NAME, A.STATUS,A.ADDRESS_LINE1,A.ADDRESS_LINE2,A.ADDRESS_LINE3,B.LOCATION_CODE 
        FROM EBC.BC_BANK_BRANCHES@BILLING_MYMEN A,BC_ACCOUNTID_GLCODE_MAP@BILLING_MYMEN B
        WHERE A.BANK_CODE=B.BANK_CODE
        AND A.BRANCH_CODE=B.BRANCH_CODE
                AND B.LOCATION_CODE='M1';
        
        
        
        EXECUTE DPG_EPAY_DATA_TRANS.DPD_BANK_BR_DATA_TRANS@EPAY_MYMEN(1);
        
        