
SELECT B.CENTER_NAME,COUNT(*) TOTAL_CONSUMER FROM EPAY_UTILITY_BILL A,EPAY_LOCATION_MASTER B
WHERE A.LOCATION_CODE=B.LOCATION_CODE
AND A.DATA_TRANS_LOG3='N'
AND BILL_MONTH='201805'
GROUP BY B.CENTER_NAME
ORDER BY 1