
BOGRA    4702
CHITTAGONG    11233
COMILLA    92277
JAMALPUR    1036
KISHOREGANJ    11822
MOULAVIBAZAR    37930
MYMENSING    21917
NAOGAON    2
PABNA    1575
RAJSHAHI    4338
RANGPUR    9820
SYLHET    30813
TANGAIL    6051


------PDB---------

SELECT L.CENTER_NAME,COUNT(*) FROM EPAY_UTILITY_BILL U,EPAY_LOCATION_MASTER L
WHERE U.LOCATION_CODE=L.LOCATION_CODE
AND U.BILL_MONTH='201807'
and u.data_trans_log3='N'
--AND U.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
--WHERE ZONE_CODE IN ('2','3','4','7'))
GROUP BY L.CENTER_NAME
ORDER BY 1

------SRL--24--------

SELECT L.CENTER_NAME,COUNT(*) FROM EPAY_UTILITY_BILL@EPAY_SRL U,EPAY_LOCATION_MASTER L
WHERE U.LOCATION_CODE=L.LOCATION_CODE
AND U.BILL_MONTH='201806'
--AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
--WHERE ZONE_CODE IN ('2','3','4','7'))
GROUP BY L.CENTER_NAME
ORDER BY 1

------SRL--169--------

SELECT L.CENTER_NAME,COUNT(*) FROM EPAY_UTILITY_BILL@EPAYMENT U,EPAY_LOCATION_MASTER L
WHERE U.LOCATION_CODE=L.LOCATION_CODE
AND U.BILL_MONTH='201806'
--AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
--WHERE ZONE_CODE IN ('2','3','4','7'))
GROUP BY L.CENTER_NAME
ORDER BY 1

----robi
SELECT L.CENTER_NAME,COUNT(*) FROM UTILITY_BILL_PDB@EPAY_ROBI U,EPAY_LOCATION_MASTER L
WHERE U.LOCATION_CODE=L.LOCATION_CODE
AND U.BILL_MONTH='201806'
--AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
--WHERE ZONE_CODE IN ('2','3','4','7'))
GROUP BY L.CENTER_NAME
ORDER BY 1

----GP

SELECT L.CENTER_NAME,COUNT(*) FROM UTILITY_BILL_PDB@EPAY_GP U,EPAY_LOCATION_MASTER L
WHERE U.LOCATION_CODE=L.LOCATION_CODE
AND U.BILL_MONTH='201806'
--AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
--WHERE ZONE_CODE IN ('2','3','4','7'))
GROUP BY L.CENTER_NAME
ORDER BY 1



AND ACCOUNT_NUMBER='70501869'


SELECT * FROM EPAY_LOC_ONLINE_OPT_MAP

WHERE ONLINE_OPT='EPAY_SRL'


SELECT L.CENTER_NAME,COUNT(*) FROM EPAY_UTILITY_BILL U,EPAY_LOCATION_MASTER L
WHERE U.LOCATION_CODE=L.LOCATION_CODE
AND U.BILL_MONTH<>'201802'
AND U.DATA_TRANS_LOG3='N'
AND U.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('5','6'))
GROUP BY L.CENTER_NAME
ORDER BY 1

SELECT L.CENTER_NAME,COUNT(*) FROM EPAY_UTILITY_BILL@EPAY_SRL U,EPAY_LOCATION_MASTER L
WHERE U.LOCATION_CODE=L.LOCATION_CODE
AND U.BILL_MONTH<>'201802'
AND L.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('5','6'))
GROUP BY L.CENTER_NAME
ORDER BY 1


select

BOGRA    1525477
DINAJPUR    1291666
NAOGAON    906959
PABNA    1032199
RAJSHAHI    2566409
RANGPUR    3079567

BOGRA    777652
DINAJPUR    659313
NAOGAON    466794
PABNA    774685
RAJSHAHI    1318253
RANGPUR    1574531