---DUE_DATE_EXTANTION_LOG
SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'rrrrmm') FROM DUAL


SELECT DATA_TYPE,REC_TYPE,REC_COUNT,TOT_BILL_AMT,LOCATION_CODE,RUN_DATE,ONLINE_OPT 
FROM VW_RUN_LOG
WHERE ONLINE_OPT=upper('srl')
--and DATA_TYPE='BILLINFO'
group by DATA_TYPE,REC_TYPE,REC_COUNT,TOT_BILL_AMT,LOCATION_CODE,RUN_DATE,ONLINE_OPT
ORDER BY RUN_DATE DESC


--epay_run_log
SELECT * FROM VW_RUN_LOG
WHERE ONLINE_OPT=upper('robi')
and DATA_TYPE='BILLINFO'
ORDER BY RUN_DATE DESC


select 900112 -2170901 from dual

select count(*) from utility_bill_pdb@epay_robi
where bill_month='202107'
--AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER where center_name='KISHOREGANJ')
--1633472


select count(*) from utility_bill_pdb@epay_gp
where bill_month='202105'

select count(*) from epay_utility_Bill
where bill_month='202105'
--and data_trans_log1='N'

select * from EPAY_BATCH_CONTROL
where ONLINE_OPT='ROBI'
and trunc(run_date)=trunc(sysdate)
and DATA_TYPE in ('BILLINFO') --CUSTINFO,BILLINFO
order by run_date desc

select * from EPAY_ERR_LOG
where ONLINE_OPT=upper('gp')
and trunc(run_date)=trunc(sysdate)
and DATA_TYPE='BILLINFO'
order by run_date desc

select count(*) from EPAY_ERR_LOG

select 
'delete from EPAY_ERR_LOG
where to_char(run_date,''rrrrmm'')=''202001''
and location_code ='''||loc||''';' ||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) "QUERY"
from (select distinct location_code loc from epay_location_master order by location_code DESC
)
--1.====================== DIFFERNCE PDB TO SRL(24) NESCO DATA ==========================


SELECT A.CENTER_NAME,TOT_CONS_30,TOT_CONS_24,(NVL(TOT_CONS_30,0)-NVL(TOT_CONS_24,0)) DIFF FROM (
SELECT L.CENTER_NAME,COUNT(*) TOT_CONS_30 FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201909'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('5','6'))
--AND B.DATA_TRANS_LOG3='T'
GROUP BY L.CENTER_NAME
ORDER BY 1)A,(
SELECT L.CENTER_NAME ,COUNT(*) TOT_CONS_24 FROM EPAY_UTILITY_BILL@EPAY_SRL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201909'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('5','6'))
--AND B.DATA_TRANS_LOG3='T'
GROUP BY L.CENTER_NAME
ORDER BY 1)B
WHERE A.CENTER_NAME=B.CENTER_NAME


--2.====================== DIFFERNCE PDB TO SRL(169) EPAYMENT DATA ==========================

SELECT A.CENTER_NAME,TOT_CONS_30,TOT_CONS_169,(NVL(TOT_CONS_30,0)-NVL(TOT_CONS_169,0)) DIFF FROM (
SELECT L.CENTER_NAME,COUNT(*) TOT_CONS_30 FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201909'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('2','3','4','7'))
--AND B.DATA_TRANS_LOG3='T'
GROUP BY L.CENTER_NAME
ORDER BY 1)A,(
SELECT L.CENTER_NAME ,COUNT(*) TOT_CONS_169 FROM EPAY_UTILITY_BILL@EPAYMENT B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201909'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('2','3','4','7'))
--AND B.DATA_TRANS_LOG3='T'
GROUP BY L.CENTER_NAME
ORDER BY 1)B
WHERE A.CENTER_NAME=B.CENTER_NAME


--3.====================== DIFFERNCE PDB TO SRL(24) EPAYMENT DATA ==========================

SELECT A.CENTER_NAME,TOT_CONS_30,TOT_CONS_24,(NVL(TOT_CONS_30,0)-NVL(TOT_CONS_24,0)) DIFF FROM (
SELECT L.CENTER_NAME,COUNT(*) TOT_CONS_30 FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201909'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('2','3','4','7'))
--AND B.DATA_TRANS_LOG3='T'
GROUP BY L.CENTER_NAME
ORDER BY 1)A,(
SELECT L.CENTER_NAME ,COUNT(*) TOT_CONS_24 FROM EPAY_UTILITY_BILL@EPAY_SRL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201909'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('2','3','4','7'))
--AND B.DATA_TRANS_LOG3='T'
GROUP BY L.CENTER_NAME
ORDER BY 1)B
WHERE A.CENTER_NAME=B.CENTER_NAME



--4.====================== DIFFERNCE PDB TO GP EPAY DATA ==========================

SELECT A.CENTER_NAME,TOT_CONS_30,TOT_CONS_GP,(NVL(TOT_CONS_30,0)-NVL(TOT_CONS_GP,0)) DIFF FROM (
SELECT L.CENTER_NAME,COUNT(*) TOT_CONS_30 FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201910'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('2','4'))
--AND B.DATA_TRANS_LOG3='T'
GROUP BY L.CENTER_NAME
ORDER BY 1)A,(
SELECT L.CENTER_NAME ,COUNT(*) TOT_CONS_GP FROM UTILITY_BILL_PDB@EPAY_GP B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201910'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('2','4'))
--AND B.DATA_TRANS_LOG3='T'
GROUP BY L.CENTER_NAME
ORDER BY 1)B
WHERE A.CENTER_NAME=B.CENTER_NAME


SELECT COUNT(*) TOT_CONS_GP FROM UTILITY_BILL_PDB@EPAY_GP
where bill_month='201910'

--5.====================== DIFFERNCE PDB TO ROBI EPAY DATA ==========================

SELECT A.CENTER_NAME,TOT_CONS_30,TOT_CONS_ROBI,(NVL(TOT_CONS_30,0)-NVL(TOT_CONS_ROBI,0)) DIFF FROM (
SELECT L.CENTER_NAME,COUNT(*) TOT_CONS_30 FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201909'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC)
--AND B.DATA_TRANS_LOG3='T'
GROUP BY L.CENTER_NAME
ORDER BY 1)A,(
SELECT L.CENTER_NAME ,COUNT(*) TOT_CONS_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201909'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC)
--AND B.DATA_TRANS_LOG3='T'
GROUP BY L.CENTER_NAME
ORDER BY 1)B
WHERE A.CENTER_NAME=B.CENTER_NAME


----------------------------------------------------

SELECT  l.CENTER_NAME,count(*) FROM VW_RUN_LOG a,epay_location_master l
WHERE a.LOCATION_CODE=l.LOCATION_CODE
and  a.ONLINE_OPT='SRL'
and a.DATA_TYPE='BILLINFO'
group by l.CENTER_NAME
ORDER BY 1 DESC



=========24 bpdb=========

SELECT  DECODE(DATA_TRANS_LOG3,'T','DATA_UPLOAD','N','NOT_UPLOAD') STATUS, COUNT(*) TOT_CONS FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH IN (SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'rrrrmm') BILL_MONTH FROM DUAL)
AND LOCATION_CODE not IN (
SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_NESCO)
GROUP BY DATA_TRANS_LOG3


DATA_UPLOAD	799269
NOT_UPLOAD	17871

========================NESCO===============================


SELECT  DECODE(DATA_TRANS_LOG3,'T','DATA_UPLOAD','N','NOT_UPLOAD') STATUS, COUNT(*) TOT_CONS FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH IN (SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'rrrrmm') BILL_MONTH FROM DUAL)
AND LOCATION_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_NESCO)
GROUP BY DATA_TRANS_LOG3


DATA_UPLOAD	471634
NOT_UPLOAD	152149

SELECT COUNT(*) FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH IN (SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'rrrrmm') BILL_MONTH FROM DUAL)
AND LOCATION_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_NESCO)

960680

select A.ONLINE_OPT,A.DATA_TYPE,a.run_date  from VW_RUN_LOG a
where data_type='BILLINFO'
group by A.ONLINE_OPT,A.DATA_TYPE,A.RUN_DATE
order by run_date desc

-------robi--------

SELECT DECODE(DATA_TRANS_LOG1,'T','DATA_UPLOAD','N','NOT_UPLOAD') STATUS,COUNT(*) TOT_CONS FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH ='201902' --IN (SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'rrrrmm') BILL_MONTH FROM DUAL)
GROUP BY DATA_TRANS_LOG1

DATA_UPLOAD    1740487
NOT_UPLOAD    28845

SELECT COUNT(*) FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='201810'

1022535

-------gp--------

SELECT DECODE(DATA_TRANS_LOG2,'T','DATA_UPLOAD','N','NOT_UPLOAD') STATUS,COUNT(*) TOT_CONS FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH ='201903' --IN (SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'rrrrmm') BILL_MONTH FROM DUAL)
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('2','4','5'))
GROUP BY DATA_TRANS_LOG2

DATA_UPLOAD    247555
NOT_UPLOAD    23301


SELECT COUNT(*) FROM UTILITY_BILL_PDB@EPAY_GP
WHERE BILL_MONTH='201903'

248122

-------srl--------

SELECT DECODE(DATA_TRANS_LOG3,'T','DATA_UPLOAD','N','NOT_UPLOAD') STATUS,COUNT(*) TOT_CONS FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH ='201810' --IN (SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'rrrrmm') BILL_MONTH FROM DUAL)
GROUP BY DATA_TRANS_LOG3

DATA_UPLOAD    2702751
NOT_UPLOAD    2962


SELECT COUNT(*) FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH='201810'
and COMPANY_CODE in ('BPDB','NESCO')

2703009

-------epayment--------

SELECT DECODE(DATA_TRANS_LOG4,'T','DATA_UPLOAD','N','NOT_UPLOAD') STATUS,COUNT(*) TOT_CONS FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH IN (SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'rrrrmm') BILL_MONTH FROM DUAL)
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('2','3','4','7'))
GROUP BY DATA_TRANS_LOG4

DATA_UPLOAD    45755
NOT_UPLOAD    238805

SELECT COUNT(*) FROM EPAY_UTILITY_BILL@EPAYMENT
WHERE BILL_MONTH IN (SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'rrrrmm') BILL_MONTH FROM DUAL)
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('2','3','4','7'))

1056840



========================SRL-SVR===============================


SELECT DECODE(DATA_TRANS_LOG3,'T','DATA_UPLOAD','N','NOT_UPLOAD') STATUS,COUNT(*) TOT_CONS FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH ='201810' --IN (SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'rrrrmm') BILL_MONTH FROM DUAL)
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('2','3','4','7'))
GROUP BY DATA_TRANS_LOG3


SELECT  COUNT(*) FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH='201810'
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('2','3','4','7'))

1026024



SELECT  COUNT(*) FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201810'

SELECT  COUNT(*) FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH='201810'
and COMPANY_CODE in ('BPDB','NESCO')

1838517

select 1458498-1443657 from dual



SELECT RUN_STATUS_CODE,DATA_TYPE,LOCATION_CODE,RUN_DATE,ONLINE_OPT FROM EPAY_BATCH_CONTROL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_NESCO)
AND ONLINE_OPT='SRL'
AND TRUNC(RUN_DATE)>=TRUNC(SYSDATE-1)
AND DATA_TYPE IN ('CUSTINFO','BILLINFO')
GROUP BY RUN_STATUS_CODE,DATA_TYPE,LOCATION_CODE,RUN_DATE,ONLINE_OPT
ORDER BY RUN_DATE DESC


ROBI, GP , EPAY_SRL


SELECT RUN_STATUS_CODE,DATA_TYPE,LOCATION_CODE,RUN_DATE,ONLINE_OPT FROM EPAY_BATCH_CONTROL
WHERE  ONLINE_OPT='SRL'
AND TRUNC(RUN_DATE)>=TRUNC(SYSDATE-1)
AND DATA_TYPE IN ('CUSTINFO','BILLINFO')
GROUP BY RUN_STATUS_CODE,DATA_TYPE,LOCATION_CODE,RUN_DATE,ONLINE_OPT
ORDER BY RUN_DATE DESC





SELECT L.CENTER_NAME, COUNT(*) FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE 
AND B.BILL_MONTH='201810'
GROUP BY L.CENTER_NAME


SELECT L.CENTER_NAME, COUNT(*) FROM EPAY_UTILITY_BILL@EPAY_SRL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE 
AND B.BILL_MONTH='201810'
GROUP BY L.CENTER_NAME
