
--------------30-----------

DELETE EPAY_UTILITY_BILL_INT;

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_INT@EPAY_DCC
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0,'N' AS DATA_TRANS_LOG,'N' AS DATA_TRANS_LOG1,'N' AS DATA_TRANS_LOG2,
 'N' AS DATA_TRANS_LOG3,'N' AS DATA_TRANS_LOG4,'N' AS DATA_TRANS_LOG5 
 FROM BC_BILL_IMAGE@BILLING_MYMEN
 WHERE BILL_CYCLE_CODE=:P_BILL_MONTH 
 AND LOCATION_CODE='M6' 
 
 
 COMMIT;
 
 
DELETE FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=:BILL_MONTH
AND  (ACCOUNT_NUMBER) IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL_INT)

commit;

INSERT INTO EPAY_UTILITY_BILL
SELECT * FROM EPAY_UTILITY_BILL_INT


COMMIT;


--------------------DUPLICATE DATA---M6----T1-----------------------

DELETE FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=:BILL_MONTH
AND  (ACCOUNT_NUMBER) IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL_INT)


----------169-----to-------24---------------

INSERT INTO EPAY_UTILITY_BILL@EPAY_SRL
SELECT 
CASE WHEN(SELECT COUNT(*) FROM EPAY_LOC_ONLINE_OPT_NESCO@EPAY_DCC WHERE LOCATION_CODE='E3')=0 THEN COMPANY_CODE ELSE 'NESCO' END AS COMPANY_CODE,
ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,'N' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA@EPAY_SRL WHERE LOCATION_CODE='E3') 
AND  DATA_TRANS_LOG3='N'
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201804'
AND LOCATION_CODE='E3'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH='201804'
AND LOCATION_CODE='E3')
and BILL_MONTH='201804'
AND LOCATION_CODE='E3';

COMMIT;


----30----T0-------169-----

INSERT INTO EPAY_UTILITY_BILL
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,'N' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL
WHERE  DATA_TRANS_LOG4='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA@EPAYMENT WHERE LOCATION_CODE='E4') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL@EPAY_DCC
WHERE BILL_MONTH='201804'
AND LOCATION_CODE='E4'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201804'
AND LOCATION_CODE='E4')
and BILL_MONTH='201804'
AND LOCATION_CODE='E4';

COMMIT;




---------30-----TO--------24---------------

INSERT INTO EPAY_UTILITY_BILL@EPAY_SRL
SELECT 
CASE WHEN(SELECT COUNT(*) FROM EPAY_LOC_ONLINE_OPT_NESCO@EPAY_DCC WHERE LOCATION_CODE='E3')=0 THEN COMPANY_CODE ELSE 'NESCO' END AS COMPANY_CODE,
ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,'N' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL@EPAY_DCC
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA@EPAY_SRL WHERE LOCATION_CODE='E3') 
AND  DATA_TRANS_LOG3='N'
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL@EPAY_DCC
WHERE BILL_MONTH='201804'
AND LOCATION_CODE='E3'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH='201804'
AND LOCATION_CODE='E3')
and BILL_MONTH='201804'
AND LOCATION_CODE='E3';

COMMIT;
