SELECT ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE FROM epay_UTILITY_BILL
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE=:p_lOCATION

MINUS

SELECT ACCOUNT_NUMBER,BILL_NUMBER,BILL_MONTH,LOCATION_CODE FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE=:p_lOCATION