

select EPAY.DFN_DATA_UP_PDB_TO_OPT (:P_LOCATION_CODE ,:P_OPT ) from dual

SELECT COUNT(*) FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=:P_NTH
AND LOCATION_CODE=:P_LOC

SELECT COUNT(*) FROM EPAY_UTILITY_BILL@EPAYMENT
WHERE BILL_MONTH=:P_NTH
AND LOCATION_CODE=:P_LOC