DBLINK                    CENTER NAME
------------------------------------------
BILLING_COM         COMILLA
BILLING_CTG          CHITTAGONG

BILLING_RAJ         RAJSHAHI
BILLING_BOG         BOGRA
BILLING_NAO         NAOGAON
BILLING_PAB         PABNA

BILLING_SYL         SYLHET
BILLING_MOU         MOULAVIBAZAR

BILLING_RONG        RANGPUR
BILLING_DIN             DINAJPUR

BILLING_MYMEN           MYMENSING
BILLING_JAM                 JAMALPUR
BILLING_KISHOR              KISHOREGANJ
BILLING_TANG            TANGAIL



-------------------- Bill Data Upload SQL -------------------------


TRUNCATE TABLE EPAY_UTILITY_BILL_SUP1;


INSERT INTO EPAY_UTILITY_BILL_SUP1
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
INVOICE_DUE_DATE BILL_DUE_DATE, 
NULL BILLAMT_AFTERDUEDATE, 
INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
SYSDATE CREATED_ON    , 
USER CREATED_BY   , 
NULL  MODIFIED_ON , 
NULL MODIFIED_BY, 
'N' NOTIFICATION_SENT_STATUS, 
    (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0)+NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
    NVL(DEMAND_CHRG,0)+NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+
    NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
NVL(CURRENT_VAT,0) CURRENT_GOVT_DUTY, 
NVL(ARR_ADV_ADJ_PRN,0)  ARREAR_PRINCIPLE, 
NVL(ARR_ADV_ADJ_VAT,0) ARREAR_GOVT_DUTY, 
0 LATE_PAYMENT_SURCHARGE, 
NVL(TOTAL_BILL,0) TOTAL_BILL_AMOUNT, 
LOCATION_CODE, 
BILL_CYCLE_CODE BILL_MONTH, 
TARIFF, CUST_STATUS CUSTOMER_TYPE, 
NVL(CURRENT_LPS,0) CURRENT_SURCHARGE, 
NVL(ARR_ADV_ADJ_LPS,0) ARREAR_SURCHARGE, 
NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
NVL(ADJUSTED_VAT,0) ADJUSTED_GOVT_DUTY, 
0  ADVANCE_AMOUNT,0 ADJ_ADV_GOVT_DUTY
               FROM  BC_BILL_IMAGE@BILLING_CTG
WHERE BILL_CYCLE_CODE=:P_BILL_MONTH
--AND DATA_TRANS_LOG='N'
AND TO_CHAR(INVOICE_DUE_DATE,'yyyymmdd')>=(SELECT  TO_CHAR(SYSDATE,'yyyymmdd') FROM DUAL)
AND INVOICE_NUM IS NOT NULL
AND  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                        WHERE CENTER_NAME LIKE '%CHITTAGONG%');
                                           
                          
COMMIT;



DELETE FROM EPAY_UTILITY_BILL_SUP1
WHERE ROWID IN (
SELECT ROWID FROM EPAY_UTILITY_BILL_SUP1
MINUS
SELECT MAX(ROWID) FROM EPAY_UTILITY_BILL_SUP1
GROUP BY ACCOUNT_NUMBER, BILL_NUMBER, LOCATION_CODE, BILL_MONTH);


COMMIT;




TRUNCATE TABLE EPAY_CUSTOMER_MASTER_DATA_SUP1;

    
INSERT INTO EPAY_CUSTOMER_MASTER_DATA_SUP1
(COMPANY_CODE,ACCOUNT_NO,NAME,LOCATION_CODE,AREAR_CODE,ACTIVATION_DATE,STATUS,CREATED_ON ,DUMPING_FOR, CREATED_BY)
SELECT 'BPDB', CUSTOMER_NUM||CHECK_DIGIT,CUSTOMER_NAME,LOCATION_CODE,AREA_CODE,  TO_DATE(START_BILL_CYCLE,'rrrrmm'),
DECODE (CUSTOMER_STATUS_CODE,'C','A','S','A','I') STATUS,  SYSDATE,    'U',USER
FROM BC_CUSTOMERS@BILLING_CTG
WHERE (CUSTOMER_NUM) IN (SELECT SUBSTR(ACCOUNT_NUMBER,1,7) FROM EPAY_UTILITY_BILL_SUP1)


SELECT
'INSERT INTO EPAY_CUSTOMER_MASTER_DATA_SUP1
(COMPANY_CODE,ACCOUNT_NO,NAME,LOCATION_CODE,AREAR_CODE,ACTIVATION_DATE,STATUS,CREATED_ON ,DUMPING_FOR, CREATED_BY)
SELECT ''BPDB'', CUSTOMER_NUM||CHECK_DIGIT,CUSTOMER_NAME,LOCATION_CODE,AREA_CODE,  TO_DATE(START_BILL_CYCLE,''rrrrmm''),
DECODE (CUSTOMER_STATUS_CODE,''C'',''A'',''S'',''A'',''I'') STATUS,  SYSDATE,''U'',USER
FROM BC_CUSTOMERS'||DB_LINK||'
WHERE CUSTOMER_NUM IN (SELECT SUBSTR(ACCOUNT_NUMBER,1,7) FROM EPAY_UTILITY_BILL_SUP1 WHERE LOCATION_CODE='''||LOC||''')
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) "RETURN_QUERY"
FROM (SELECT DISTINCT L.LOCATION_CODE LOC,'@'||BILLING_DBLINK DB_LINK  FROM EPAY_UTILITY_BILL_SUP1 G,EPAY_LOCATION_MASTER L
WHERE G.LOCATION_CODE=L.LOCATION_CODE)
ORDER BY LOC


COMMIT;


DELETE FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
WHERE ROWID IN ( 
SELECT ROWID FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
MINUS 
SELECT MAX(ROWID) FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
GROUP BY COMPANY_CODE, ACCOUNT_NO, LOCATION_CODE);


COMMIT;


----------------------------ROBI Customer Data Upload SQL--------------------


SELECT 
'INSERT INTO CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI
SELECT * FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
WHERE ACCOUNT_NO IN ( 
SELECT  ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
WHERE LOCATION_CODE='''||LOC||'''
MINUS 
SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI
WHERE  LOCATION_CODE='''||LOC||''')
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='ROBI'))
ORDER BY LOC


----------------------------GP Customer Data Upload SQL--------------------


SELECT 
'INSERT INTO DBERSICE.CUSTOMER_MASTER_DATA_PDB@EPAY_GP
SELECT * FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
WHERE ACCOUNT_NO IN ( 
SELECT  ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
WHERE LOCATION_CODE='''||LOC||'''
MINUS 
SELECT ACCOUNT_NO FROM DBERSICE.CUSTOMER_MASTER_DATA_PDB@EPAY_GP
WHERE  LOCATION_CODE='''||LOC||''')
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='GP'))
ORDER BY LOC



----------------------------SRL Customer Data Upload SQL--------------------


SELECT 
'INSERT INTO EPAY_CUSTOMER_MASTER_DATA@EPAY_SRL
SELECT * FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
WHERE ACCOUNT_NO IN ( 
SELECT  ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
WHERE LOCATION_CODE='''||LOC||'''
MINUS 
SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA@EPAY_SRL
WHERE  LOCATION_CODE='''||LOC||''')
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='SRL'))
ORDER BY LOC





----------------------------BPDB Customer Data Upload SQL--------------------


SELECT 
'INSERT INTO EPAY_CUSTOMER_MASTER_DATA
SELECT * FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
WHERE ACCOUNT_NO IN ( 
SELECT  ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA_SUP1
WHERE LOCATION_CODE='''||LOC||'''
MINUS 
SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA
WHERE  LOCATION_CODE='''||LOC||''')
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC FROM EPAY_CUSTOMER_MASTER_DATA_SUP1)
ORDER BY LOC




---------------------------------Bill Data Upload Query---------------------------------



----------------------------ROBI Bill Data Upload SQL--------------------

SELECT 
'INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL_SUP1
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='''||LOC||''') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL_SUP1
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||'''
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''');'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL_SUP1
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='ROBI'))
ORDER BY LOC



----------------------------GP Bill Data Upload SQL--------------------


SELECT 
'INSERT INTO DBERSICE.UTILITY_BILL_PDB@EPAY_GP
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
SYSDATE CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL_SUP1
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM DBERSICE.CUSTOMER_MASTER_DATA_PDB@EPAY_GP WHERE LOCATION_CODE='''||LOC||''') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL_SUP1
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||'''
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM DBERSICE.UTILITY_BILL_PDB@EPAY_GP
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''');'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL_SUP1
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='GP'))
ORDER BY LOC



----------------------------SRL Bill Data Upload SQL--------------------


SELECT 
'INSERT INTO EPAY_UTILITY_BILL@EPAY_SRL
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,''N'' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL_SUP1
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA@EPAY_SRL WHERE LOCATION_CODE='''||LOC||''') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL_SUP1
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||'''
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''');'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL_SUP1
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='SRL'))
ORDER BY LOC


----------------------------BPDB Bill Data Upload SQL--------------------


SELECT 
'INSERT INTO EPAY_UTILITY_BILL
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,''T'' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL_SUP1
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA WHERE LOCATION_CODE='''||LOC||''') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL_SUP1
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||'''
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''');'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL_SUP1)
ORDER BY LOC






SELECT
'UPDATE BC_BILL_IMAGE'||DB_LINK||'
SET DATA_TRANS_LOG=''T''
WHERE LOCATION_CODE='''||LOC||'''
AND (BILL_CYCLE_CODE,INVOICE_NUM) IN (SELECT BILL_MONTH,SUBSTR(BILL_NUMBER,1,LENGTH(BILL_NUMBER)-1) FROM EPAY_UTILITY_BILL_SUP1 
                                                               WHERE LOCATION_CODE='''||LOC||''');'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) "QUERY"
FROM (SELECT DISTINCT L.LOCATION_CODE LOC,:P_BILL_MONTH BILL_MONTH,'@'||BILLING_DBLINK DB_LINK  FROM EPAY_UTILITY_BILL_SUP1 G,EPAY_LOCATION_MASTER L
WHERE G.LOCATION_CODE=L.LOCATION_CODE)
ORDER BY LOC




