7,817

SELECT * FROM EPAY_CUSTOMER_MASTER_DATA
WHERE LOCATION_CODE='C1'
AND SUBSTR(AREAR_CODE,4,5)='01'


select bill_due_date from epay_utility_bill
where bill_month='201709'
and LOCATION_CODE='C1'
and account_number in (
SELECT account_no FROM EPAY_CUSTOMER_MASTER_DATA
WHERE LOCATION_CODE='C1'
AND SUBSTR(AREAR_CODE,4,5)='01'
)group by bill_due_date
order by bill_due_date asc

6,811

6,826


select invoice_due_date from bc_bill_image@billing_com
where bill_cycle_code='201709'
and location_code='C1'
and bill_group='01'
group by invoice_due_date
order by invoice_due_date asc



SELECT * FROM MAIL_DBLINK_MST
WHERE SERVER_NAME='Billing'

SELECT DISTINCT UPPER(CENTER_NAME) CENTER_NAME,INITCAP(CENTER_NAME) INT_CEN_NAME,BILLING_DBLINK FROM EPAY.EPAY_LOCATION_MASTER@EPAY_DCC 
                     --WHERE CENTER_NAME IN ('SYLHET','BOGRA')
                     ORDER BY UPPER(CENTER_NAME) ASC
                     
                     
    SELECT * FROM BC_BILL_IMAGE@BILLING_MOU 
    
    DISTINCT UPPER(CENTER_NAME) CENTER_NAME,INITCAP(CENTER_NAME) INT_CEN_NAME,BILLING_DBLINK FROM EPAY.EPAY_LOCATION_MASTER@EPAY_DCC 
                     
SELECT LOCATION_CODE,BILL_GROUP,INVOICE_DUE_DATE 
FROM BC_BILL_IMAGE@BILLING_MOU
WHERE BILL_CYCLE_CODE='201709' 
GROUP BY LOCATION_CODE,BILL_GROUP,INVOICE_DUE_DATE         
ORDER BY BILL_GROUP ASC           



SELECT B.LOCATION_CODE,SUBSTR(C.AREAR_CODE,4,5) BILL_GROUP,B.BILL_DUE_DATE 
FROM EPAY_UTILITY_BILL@EPAY_DCC B,EPAY_CUSTOMER_MASTER_DATA@EPAY_DCC C
WHERE B.ACCOUNT_NUMBER=C.ACCOUNT_NO
AND B.LOCATION_CODE=C.LOCATION_CODE
AND B.BILL_MONTH='201709'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_DCC WHERE CENTER_NAME='MOULAVIBAZAR')
GROUP BY B.LOCATION_CODE,SUBSTR(C.AREAR_CODE,4,5),B.BILL_DUE_DATE
ORDER BY SUBSTR(C.AREAR_CODE,4,5) ASC


SELECT * FROM EPAY_CUSTOMER_MASTER_DATA@EPAY_DCC


SELECT * FROM LOCATION_CODE
WHERE BILL_MONTH='201709'
AND LOCATION_CODE IN (
SELECT LOCATION_CODE,BILL_GROUP,INVOICE_DUE_DATE FROM BC_BILL_IMAGE@BILLING_MOU
WHERE BILL_CYCLE_CODE='201709' 
GROUP BY LOCATION_CODE,BILL_GROUP,INVOICE_DUE_DATE         
ORDER BY BILL_GROUP ASC  )
                     


SELECT B.LOCATION_CODE,SUBSTR(C.AREAR_CODE,4,5) BILL_GROUP,B.BILL_DUE_DATE 
FROM EPAY_UTILITY_BILL@EPAY_DCC B,EPAY_CUSTOMER_MASTER_DATA@EPAY_DCC C,EPAY_LOCATION_MASTER@EPAY_DCC
WHERE B.ACCOUNT_NUMBER=C.ACCOUNT_NO
AND B.LOCATION_CODE=C.LOCATION_CODE
AND B.LOCATION_CODE=L.LOCATION_CODE
AND C.LOCATION_CODE=
AND B.BILL_MONTH='201709'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_DCC WHERE CENTER_NAME='MOULAVIBAZAR')
GROUP BY B.LOCATION_CODE,SUBSTR(C.AREAR_CODE,4,5),B.BILL_DUE_DATE
ORDER BY SUBSTR(C.AREAR_CODE,4,5) ASC