

SELECT INVOICE_DUE_DATE,COUNT(*) FROM BC_BILL_IMAGE@BILLING_TANG
WHERE BILL_CYCLE_CODE='201710'
AND LOCATION_CODE='T2'
AND BILL_GROUP='01'
GROUP BY INVOICE_DUE_DATE

SELECT * FROM BC_BILL_IMAGE@BILLING_TANG
WHERE BILL_CYCLE_CODE='201710'
AND LOCATION_CODE='T2'
AND BILL_GROUP='01'

SELECT MODIFIED_ON, BILL_DUE_DATE,COUNT(*) FROM UTILITY_BILL_pdb@epay_robi
WHERE BILL_MONTH='201710'
AND LOCATION_CODE='T2'
and company_code='BPDB'
AND SUBSTR(BILL_NUMBER,1,8) IN (
SELECT INVOICE_NUM FROM BC_BILL_IMAGE@BILLING_TANG
WHERE BILL_CYCLE_CODE='201710'
AND LOCATION_CODE='T2'
AND BILL_GROUP='01'
)GROUP BY MODIFIED_ON,BILL_DUE_DATE

05-Nov-17 3:40:37 PM

SELECT MODIFIED_ON, BILL_DUE_DATE,COUNT(*) FROM epay_UTILITY_BILL
WHERE BILL_MONTH='201710'
AND LOCATION_CODE='T2'
and company_code='BPDB'
AND SUBSTR(BILL_NUMBER,1,8) IN (
SELECT INVOICE_NUM FROM BC_BILL_IMAGE@BILLING_TANG
WHERE BILL_CYCLE_CODE='201710'
AND LOCATION_CODE='T2'
AND BILL_GROUP='01'
)GROUP BY MODIFIED_ON,BILL_DUE_DATE