

SELECT  PDB.BILL_MONTH,PDB.LOCATION_CODE,BILLING.BILL_GROUP,PDB.BILL_DUE_DATE PDB_BILL_DUE_DATE,BILLING.INVOICE_DUE_DATE BILLING_BILL_DUE_DATE,
NO_OF_CONS_PDB,NO_OF_CONS_BILLING FROM (
SELECT UB.LOCATION_CODE,CM.BILL_GROUP,UB.BILL_DUE_DATE,UB.BILL_MONTH,COUNT(*) NO_OF_CONS_PDB
FROM EPAY_UTILITY_BILL UB,BC_BILL_IMAGE@BILLING_MYMEN CM
WHERE UB.ACCOUNT_NUMBER=CM.CUSTOMER_NUM||CM.CONS_CHK_DIGIT
AND UB.LOCATION_CODE=CM.LOCATION_CODE
AND UB.BILL_MONTH=cm.bill_cycle_code
AND UB.BILL_MONTH='201709'
AND UB.LOCATION_CODE='M1'
--AND UB.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='MYMENSING')
GROUP BY UB.LOCATION_CODE,CM.BILL_GROUP,UB.BILL_DUE_DATE,UB.BILL_MONTH) PDB,
(
SELECT LOCATION_CODE,BILL_GROUP,INVOICE_DUE_DATE,BILL_CYCLE_CODE,COUNT(*) NO_OF_CONS_BILLING FROM BC_BILL_IMAGE@BILLING_MYMEN
WHERE BILL_CYCLE_CODE='201709'
AND LOCATION_CODE='M1'
GROUP BY LOCATION_CODE,BILL_GROUP,INVOICE_DUE_DATE,BILL_CYCLE_CODE
) BILLING
WHERE PDB.LOCATION_CODE=BILLING.LOCATION_CODE
AND PDB.BILL_GROUP=BILLING.BILL_GROUP
AND PDB.BILL_MONTH=BILLING.BILL_CYCLE_CODE
AND BILLING.INVOICE_DUE_DATE>=TRUNC(SYSDATE)
AND PDB.BILL_DUE_DATE<>BILLING.INVOICE_DUE_DATE
ORDER BY 1 ASC



SELECT  'SELECT DFN_BILL_DUE_DATE_EXTEND('''||PDB.BILL_MONTH||''',UPPER('''||PDB.LOCATION_CODE||'''),'''||PDB.BILL_DUE_DATE||''','''||
    BILLING.INVOICE_DUE_DATE||''') STATUS FROM DUAL;'||CHR(10) FROM (
SELECT UB.LOCATION_CODE,CM.BILL_GROUP,UB.BILL_DUE_DATE,UB.BILL_MONTH,COUNT(*) NO_OF_CONS_PDB
FROM EPAY_UTILITY_BILL UB,BC_BILL_IMAGE@BILLING_MYMEN CM
WHERE UB.ACCOUNT_NUMBER=CM.CUSTOMER_NUM||CM.CONS_CHK_DIGIT
AND UB.LOCATION_CODE=CM.LOCATION_CODE
AND UB.BILL_MONTH=cm.bill_cycle_code
AND UB.BILL_MONTH='201709'
AND UB.LOCATION_CODE='M1'
--AND UB.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='MYMENSING')
GROUP BY UB.LOCATION_CODE,CM.BILL_GROUP,UB.BILL_DUE_DATE,UB.BILL_MONTH) PDB,
(
SELECT LOCATION_CODE,BILL_GROUP,INVOICE_DUE_DATE,BILL_CYCLE_CODE,COUNT(*) NO_OF_CONS_BILLING FROM BC_BILL_IMAGE@BILLING_MYMEN
WHERE BILL_CYCLE_CODE='201709'
AND LOCATION_CODE='M1'
GROUP BY LOCATION_CODE,BILL_GROUP,INVOICE_DUE_DATE,BILL_CYCLE_CODE
) BILLING
WHERE PDB.LOCATION_CODE=BILLING.LOCATION_CODE
AND PDB.BILL_GROUP=BILLING.BILL_GROUP
AND PDB.BILL_MONTH=BILLING.BILL_CYCLE_CODE
AND BILLING.INVOICE_DUE_DATE>=TRUNC(SYSDATE)
AND PDB.BILL_DUE_DATE<>BILLING.INVOICE_DUE_DATE
ORDER BY 1 ASC


SELECT  

 FROM (
SELECT UB.LOCATION_CODE,SUBSTR(CM.AREAR_CODE,4,5) BILL_GROUP,TO_CHAR(UB.BILL_DUE_DATE,'dd-mon-yyyy') BILL_DUE_DATE,UB.BILL_MONTH,COUNT(*) NO_OF_CONS_PDB
FROM EPAY_UTILITY_BILL UB,EPAY_CUSTOMER_MASTER_DATA CM
WHERE UB.ACCOUNT_NUMBER=CM.ACCOUNT_NO
AND UB.LOCATION_CODE=CM.LOCATION_CODE
AND UB.BILL_MONTH='201709'
AND UB.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='MYMENSING')
GROUP BY UB.LOCATION_CODE,SUBSTR(CM.AREAR_CODE,4,5),TO_CHAR(UB.BILL_DUE_DATE,'dd-mon-yyyy'),UB.BILL_MONTH) PDB,
(
SELECT LOCATION_CODE,BILL_GROUP,TO_CHAR(INVOICE_DUE_DATE,'dd-mon-yyyy') INVOICE_DUE_DATE,BILL_CYCLE_CODE,COUNT(*) NO_OF_CONS_BILLING 
FROM BC_BILL_IMAGE@BILLING_MYMEN
WHERE BILL_CYCLE_CODE='201709'
GROUP BY LOCATION_CODE,BILL_GROUP,TO_CHAR(INVOICE_DUE_DATE,'dd-mon-yyyy'),BILL_CYCLE_CODE
) BILLING
WHERE PDB.LOCATION_CODE=BILLING.LOCATION_CODE
AND PDB.BILL_GROUP=BILLING.BILL_GROUP
AND PDB.BILL_MONTH=BILLING.BILL_CYCLE_CODE
AND BILLING.INVOICE_DUE_DATE>=TRUNC(SYSDATE)
AND PDB.BILL_DUE_DATE<>BILLING.INVOICE_DUE_DATE
ORDER BY 1 ASC
