SELECT 
'INSERT INTO DBERSICE.UTILITY_BILL_PDB@EPAY_GP
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
SYSDATE AS CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='''||:P_BILL_MONTH||'''
AND BILL_DUE_DATE>=TRUNC(SYSDATE)
AND DATA_TRANS_LOG=''T''
AND LOCATION_CODE='''||LOCATION_CODE||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10)
FROM (
SELECT LOCATION_CODE FROM EPAY_LOCATION_master
where CENTER_NAME IN ('CHITTAGONG')) oRder by location_code



SELECT 
'INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
SYSDATE AS CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='''||:P_BILL_MONTH||'''
AND BILL_DUE_DATE>=TRUNC(SYSDATE)
AND DATA_TRANS_LOG=''T''
AND LOCATION_CODE='''||LOCATION_CODE||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10)
FROM (
SELECT LOCATION_CODE FROM EPAY_LOCATION_master
where CENTER_NAME IN ('CHITTAGONG')) oRder by location_code


SELECT 
'INSERT INTO EPAY_UTILITY_BILL@EPAY_SRL
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
SYSDATE AS CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,''N'' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='''||:P_BILL_MONTH||'''
AND BILL_DUE_DATE>=TRUNC(SYSDATE)
AND DATA_TRANS_LOG=''N''
AND LOCATION_CODE='''||LOCATION_CODE||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10)
FROM (
SELECT LOCATION_CODE FROM EPAY_LOCATION_master
where CENTER_NAME IN ('CHITTAGONG')) oRder by location_code



---------------------------------
 SELECT 
'INSERT INTO '||USER_NAME||'UTILITY_BILL_PDB@'||ONLINE_OPT_DBLINK||'
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
SYSDATE CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL_GPR
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOCATION_CODE||''';'
||CHR(10)||CHR(10)||'COMMIT;'||CHR(10)||CHR(10) AS "QUERY"
FROM (
SELECT O.ONLINE_OPT_DBLINK,O.USER_NAME,M.LOCATION_CODE,I.BILL_MONTH,TO_CHAR(SYSDATE,'RRRRMMDD') DUE_DATE ,COUNT(1)
    FROM EPAY_LOC_ONLINE_OPT_MAP M,EPAY_ONLINE_OPERATOR O ,EPAY_UTILITY_BILL_GPR I
WHERE M.ONLINE_OPT=O.ONLINE_OPT
AND M.STATUS='A'
AND O.STATUS='A'
AND M.ONLINE_OPT<>'SRL'
AND M.LOCATION_CODE=I.LOCATION_CODE
GROUP BY O.ONLINE_OPT_DBLINK,O.USER_NAME,M.LOCATION_CODE,I.BILL_MONTH ,TO_CHAR(SYSDATE,'RRRRMMDD')
)
 --ORDER BY LOCATION_CODE;
 UNION 
  SELECT 
'INSERT INTO '||USER_NAME||'EPAY_UTILITY_BILL@'||ONLINE_OPT_DBLINK||'
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
SYSDATE CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,''N'' AS DATA_TRANS_LOG FROM EPAY_UTILITY_BILL_GPR
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOCATION_CODE||''';'
||CHR(10)||CHR(10)||'COMMIT;'||CHR(10)||CHR(10) AS "QUERY"
FROM (
SELECT O.ONLINE_OPT_DBLINK,O.USER_NAME,M.LOCATION_CODE,I.BILL_MONTH,TO_CHAR(SYSDATE,'RRRRMMDD') DUE_DATE ,COUNT(1)
    FROM EPAY_LOC_ONLINE_OPT_MAP M,EPAY_ONLINE_OPERATOR O ,EPAY_UTILITY_BILL_GPR I
WHERE M.ONLINE_OPT=O.ONLINE_OPT
AND M.STATUS='A'
AND O.STATUS='A'
AND M.ONLINE_OPT='SRL'
AND M.LOCATION_CODE=I.LOCATION_CODE
GROUP BY O.ONLINE_OPT_DBLINK,O.USER_NAME,M.LOCATION_CODE,I.BILL_MONTH ,TO_CHAR(SYSDATE,'RRRRMMDD')
)
 ORDER BY 1;