select * from v$active_session_history;

select SQL_ID,SQL_FULLTEXT , FIRST_LOAD_TIME,LAST_LOAD_TIME,MODULE  FROM gv$sql 
where PARSING_SCHEMA_NAME='HR';


SELECT H.SAMPLE_TIME,U.USERNAME,H.PROGRAM,H.MODULE,S.SQL_TEXT, H.MACHINE FROM
    DBA_HIST_ACTIVE_SESS_HISTORY H,DBA_USERS U,DBA_HIST_SQLTEXT S
    --WHERE SAMPLE_TIME>=SYSDATE-30
    WHERE H.USER_ID = U.USER_ID
    AND H.SQL_ID = S.SQL_ID
    AND U.USERNAME='HR'
    
