
SELECT M.PAY_DATE,M.ORG_BR_CODE,D.ACCOUNT_NUMBER,D.ORG_PRN_AMOUNT PRN_AMOUNT,D.VAT_AMOUNT,SUM(D.ORG_PRN_AMOUNT+D.VAT_AMOUNT) TOTAL_AMOUNT FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND M.ORG_BANK_CODE='400'
AND TO_CHAR(M.PAY_DATE,'rrrrmm')='201911'
GROUP BY M.PAY_DATE,M.ORG_BR_CODE,D.ACCOUNT_NUMBER,D.ORG_PRN_AMOUNT,D.VAT_AMOUNT
ORDER BY  M.PAY_DATE ASC



SELECT M.ORG_BR_CODE,SUM(NVL(D.ORG_PRN_AMOUNT,0)) PRN_AMOUNT,SUM(NVL(D.VAT_AMOUNT,0)) VAT_AMOUNT,SUM(NVL(D.ORG_PRN_AMOUNT,0)+NVL(D.VAT_AMOUNT,0)) TOTAL_AMOUNT FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND M.ORG_BANK_CODE='400'
AND TO_CHAR(M.PAY_DATE,'rrrrmm')='201907'
GROUP BY M.ORG_BR_CODE
ORDER BY  M.ORG_BR_CODE ASC