

DELETE FROM EPAY_UTILITY_BILL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='CHITTAGONG'
) AND SUBSTR(ACCOUNT_NUMBER,1,1)='3';

COMMIT;

DELETE FROM EPAY_CUSTOMER_MASTER_DATA
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='CHITTAGONG'
) AND SUBSTR(ACCOUNT_No,1,1)='3';

commit;