
INSERT INTO EPAY.EPAY_UTILITY_BILL@DESCOPST_SRL
(COMPANY_CODE, ACCOUNT_NUMBER, BILL_NUMBER, GENERATED_DATE, BILL_STATUS, BILL_DUE_DATE, BILLAMT_AFTERDUEDATE,
BILLENDDATE_FORPAYMENT, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, NOTIFICATION_SENT_STATUS, CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY, ARREAR_PRINCIPLE, ARREAR_GOVT_DUTY, LATE_PAYMENT_SURCHARGE, TOTAL_BILL_AMOUNT, LOCATION_CODE, BILL_MONTH, 
TARIFF, CUSTOMER_TYPE, CURRENT_SURCHARGE, ARREAR_SURCHARGE, ADJUSTED_PRINCIPLE, ADJUSTED_GOVT_DUTY, ADVANCE_AMOUNT, ADJ_ADV_GOVT_DUTY, DATA_TRANS_LOG)
SELECT 'DESCOPOST',CUR_BILL.ACCOUNT_NO,CUR_BILL.BILL_NO,TO_DATE(TO_CHAR(CUR_BILL.ISSUE_DATE,'MM/DD/RRRR'),'MM/DD/RRRR'),'N',TO_DATE(TO_CHAR(CUR_BILL.DUE_DATE,'MM/DD/RRRR'),'MM/DD/RRRR'),0,
TO_DATE(TO_CHAR(CUR_BILL.DUE_DATE,'MM/DD/RRRR'),'MM/DD/RRRR'),SYSDATE,USER,NULL,NULL,'N',NVL(CUR_BILL.TOTAL_AMOUNT,0)-NVL(CUR_BILL.VAT_TOTAL,0),
NVL(CUR_BILL.VAT_TOTAL,0),0,0,0,NVL(CUR_BILL.TOTAL_AMOUNT,0),CUR_BILL.DEPT_ID,CUR_BILL.YEAR||LPAD(CUR_BILL.MONTH,2,'0'),
CUR_BILL.TARIFF,NULL,NVL(CUR_BILL.LPC,0),0,0,0,0,0,'N'  
FROM BILL_CALCULATION_201811_17 CUR_BILL

commit;



SELECT * FROM EPAY.EPAY_UTILITY_BILL@DESCOPST_SRL
WHERE BILL_MONTH='201811'
AND COMPANY_CODE='DESCOPOST'
AND LOCATION_CODE='16'