
SELECT rownum sl_no,C.CUSTOMER_NAME||', '||D.ADDR_DESCR2||', '||D.CITY Name_Address,C.CONS_EXTG_NUM Account_No,A.METER_NUM,A.METER_CONNECT_DATE,
trunc(c.CREATE_DATE) Center_trnsfer_date,substr(C.AREA_CODE,4) book,C.WALKING_SEQUENCE page_no,C.CUSTOMER_NUM,' ' comments 
FROM BC_CUSTOMER_METER A,bc_customers c,BC_CUSTOMER_ADDR d
WHERE A.CUST_ID=C.CUST_ID
and A.CUST_ID=D.CUST_ID
and C.CUST_ID=D.CUST_ID
and D.ADDR_TYPE='B'
AND d.ADDR_EXP_DATE IS NULL
and a.METER_INSTALL_DATE>='01-JAN-2018'
AND a.METER_INSTALL_DATE <='29-NOV-2018' 



order by rownum,substr(C.AREA_CODE,4),WALKING_SEQUENCE




SELECT * FROM BC_CUSTOMER_METER A,BC_CUSTOMER_ADDR d
WHERE A.CUST_ID=D.CUST_ID
--and A.CUST_ID=D.CUST_ID
--and C.CUST_ID=D.CUST_ID
and D.ADDR_TYPE='B'
AND d.ADDR_EXP_DATE IS NULL
and a.METER_INSTALL_DATE>='01-JAN-2018'
AND a.METER_INSTALL_DATE <='29-NOV-2018' 

SELECT * FROM BC_CUSTOMER_METER A
WHERE 
--and A.CUST_ID=D.CUST_ID
--and C.CUST_ID=D.CUST_ID
 a.METER_INSTALL_DATE>='01-JAN-2018'
AND a.METER_INSTALL_DATE <='29-NOV-2018' 