

select nvl(PARENT,0) PARENT,nvl(MOD_ID,0) MOD_ID,nvl(MOD_APP,'#') MOD_APP,nvl(EXT,' ') EXT,nvl(ROOTLEAF,' ') ROOTLEAF,nvl(MOD_NAME,' ') MOD_NAME,
nvl(MTYPE,' ') MTYPE,nvl(MOD_CODE,' ') MOD_CODE from EMP.EMP_MODULES_LIST
where  (ROOTLEAF='R' or ( ROOTLEAF='L' and  mod_code in (select mod_code from EMP.EMP_USER_ACCESS
   where user_name=:p_user_name)))
order by mod_id asc;




------

select nvl(PARENT,0) PARENT,nvl(MOD_ID,0) MOD_ID,nvl(MOD_APP,'#') MOD_APP,nvl(EXT,' ') EXT,nvl(ROOTLEAF,' ') ROOTLEAF,nvl(MOD_NAME,' ') MOD_NAME,
nvl(MTYPE,' ') MTYPE,nvl(MOD_CODE,' ') MOD_CODE from EMP.EMP_MODULES_LIST
where  (ROOTLEAF='R' or ( ROOTLEAF='L' and  mod_code in (select mod_code from EMP.EMP_USER_ACCESS A,EMP.EMP_USER_MST U
   where A.ROLE_ID=U.ROLE_ID
   AND U.user_name=:p_user_name)))
order by mod_id asc;





-----
SELECT a.MENU_ITEM_ID,a.PARENT_MENU_ITEM_ID,a.MENU_DESCRIPTION,a.MENU_URL,a.MENU_ICON FROM EMP.EMP_ADMIN_MENU_MST a
    WHERE a.MENU_ITEM_ID IN(
    SELECT a.PARENT_MENU_ITEM_ID FROM EMP.EMP_ADMIN_MENU_MST a
    WHERE a.MENU_ITEM_ID IN(
    SELECT a.PARENT_MENU_ITEM_ID FROM EMP.EMP_ADMIN_MENU_MST a,EMP.EMP_ADMIN_ROLE_MENU_MAP b,EMP.EMP_USER_MST c
    where C.USER_NAME=:p_User_Id
    and C.ROLE_ID=B.ROLE_ID
    and A.MENU_ITEM_ID=B.MENU_ITEM_ID))
    UNION
    SELECT a.MENU_ITEM_ID,a.PARENT_MENU_ITEM_ID,a.MENU_DESCRIPTION,a.MENU_URL,a.MENU_ICON FROM EMP.EMP_ADMIN_MENU_MST a
    WHERE a.MENU_ITEM_ID IN(
    SELECT a.PARENT_MENU_ITEM_ID FROM EMP.EMP_ADMIN_MENU_MST a,EMP.EMP_ADMIN_ROLE_MENU_MAP b,EMP.EMP_USER_MST c
    where C.USER_NAME=:p_User_Id
    and C.ROLE_ID=B.ROLE_ID
    and A.MENU_ITEM_ID=B.MENU_ITEM_ID)
    UNION
    SELECT a.MENU_ITEM_ID,a.PARENT_MENU_ITEM_ID,a.MENU_DESCRIPTION,a.MENU_URL,a.MENU_ICON  FROM EMP.EMP_ADMIN_MENU_MST a,EMP.EMP_ADMIN_ROLE_MENU_MAP b,EMP.EMP_USER_MST c
    where C.USER_NAME=:p_User_Id
    and C.ROLE_ID=B.ROLE_ID
    and A.MENU_ITEM_ID=B.MENU_ITEM_ID
    UNION
    SELECT a.MENU_ITEM_ID,a.PARENT_MENU_ITEM_ID,a.MENU_DESCRIPTION,a.MENU_URL,a.MENU_ICON  FROM EMP.EMP_ADMIN_MENU_MST a
    WHERE a.MENU_ITEM_ID IN(
    SELECT a.PARENT_MENU_ITEM_ID FROM EMP.EMP_ADMIN_MENU_MST a,EMP.EMP_ADMIN_ROLE_MENU_MAP b
    where B.ROLE_ID=:p_Role_Id
    and A.MENU_ITEM_ID=B.MENU_ITEM_ID)
    UNION
    SELECT a.MENU_ITEM_ID,a.PARENT_MENU_ITEM_ID,a.MENU_DESCRIPTION,a.MENU_URL,a.MENU_ICON  FROM EMP.EMP_ADMIN_MENU_MST a,EMP.EMP_ADMIN_ROLE_MENU_MAP b
    where B.ROLE_ID=:p_Role_Id
    and A.MENU_ITEM_ID=B.MENU_ITEM_ID;