SELECT COMP_CNTR_NAME,EPAY_BANK_CODE,BANK_NAME,EPAY_BANK_BRANCH_CODE,BRANCH_NAME,LOC_CODE,LOCATION_NAME FROM VW_1EPAY_OFLINE_BANK_USER_LIST
GROUP BY COMP_CNTR_NAME,EPAY_BANK_CODE,BANK_NAME,EPAY_BANK_BRANCH_CODE,BRANCH_NAME,LOC_CODE,LOCATION_NAME
ORDER BY 1,2



SELECT B.BANK_CODE,B.BANK_NAME,BR.BRANCH_CODE,BR.BRANCH_NAME,L.LOCATION_CODE,L.LOCATION_NAME FROM EPAY_BANKS B,EPAY_BANK_BRANCHES BR,EPAY_LOCATION_MASTER L
WHERE B.BANK_CODE=BR.BANK_CODE
AND BR.LOCATION_CODE=L.LOCATION_CODE
AND B.BANK_CODE NOT IN('96','97') 
GROUP BY B.BANK_CODE,B.BANK_NAME,BR.BRANCH_CODE,BR.BRANCH_NAME,L.LOCATION_CODE,L.LOCATION_NAME
ORDER BY 1




SELECT M.LOCATION_CODE, M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME FROM EPAY_PAYMENT_MST M,EPAY_BANKS B,EPAY_BANK_BRANCHES BR
WHERE M.PAY_BANK_CODE=B.BANK_CODE
AND M.PAY_BANK_CODE=BR.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND M.LOCATION_CODE=BR.LOCATION_CODE
AND B.BANK_CODE=BR.BANK_CODE
--AND M.PAY_DATE BETWEEN '15-FEB-2018' AND '13-MAR-2018'
AND M.PAY_BANK_CODE NOT IN ('96','97')
GROUP BY M.LOCATION_CODE,M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME
--ORDER BY 2
MINUS
SELECT  M.LOCATION_CODE, M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME FROM EPAY_PAYMENT_MST M,EPAY_BANKS B,EPAY_BANK_BRANCHES BR
WHERE M.PAY_BANK_CODE=B.BANK_CODE
AND M.PAY_BANK_CODE=BR.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND M.LOCATION_CODE=BR.LOCATION_CODE
AND B.BANK_CODE=BR.BANK_CODE
AND M.PAY_DATE BETWEEN '15-FEB-2018' AND '13-MAR-2018'
AND M.PAY_BANK_CODE NOT IN ('96','97')
GROUP BY M.LOCATION_CODE,M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME
ORDER BY 3




SELECT L.LOCATION_CODE,B.BANK_CODE,B.BANK_NAME,BR.BRANCH_CODE,BR.BRANCH_NAME FROM EPAY_BANKS B,EPAY_BANK_BRANCHES BR,EPAY_LOCATION_MASTER L
WHERE B.BANK_CODE=BR.BANK_CODE
AND BR.LOCATION_CODE=L.LOCATION_CODE
AND B.BANK_CODE NOT IN('96','97','77') 
GROUP BY L.LOCATION_CODE,B.BANK_CODE,B.BANK_NAME,BR.BRANCH_CODE,BR.BRANCH_NAME
--ORDER BY 1,2
MINUS
SELECT  M.LOCATION_CODE, M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME FROM EPAY_PAYMENT_MST M,EPAY_BANKS B,EPAY_BANK_BRANCHES BR
WHERE M.PAY_BANK_CODE=B.BANK_CODE
AND M.PAY_BANK_CODE=BR.BANK_CODE
AND M.PAY_BRANCH_CODE=BR.BRANCH_CODE
AND M.LOCATION_CODE=BR.LOCATION_CODE
AND B.BANK_CODE=BR.BANK_CODE
--AND M.PAY_DATE BETWEEN '15-FEB-2018' AND '21-MAR-2018'
AND M.PAY_BANK_CODE NOT IN ('96','97')
GROUP BY M.LOCATION_CODE,M.PAY_BANK_CODE,B.BANK_NAME,M.PAY_BRANCH_CODE,BR.BRANCH_NAME
ORDER BY 3