

SELECT * FROM VW_EPAY_RECON_UNSUC_PDB_BNK@EPAY_SRL_DCC
WHERE LOC='K2'
AND PAY_DATE='27-FEB-2020'



SELECT REF_BATCH_NO FROM EPAY_PAYMENT_MST@EPAY_SRL_DCC
WHERE BATCH_NO='508650'


INSERT INTO EPAY_PAYMENT_MST_BNK_BKP@EPAY_SRL_DCC
SELECT * FROM EPAY_PAYMENT_MST@EPAY_SRL_DCC
WHERE REF_BATCH_NO='EON31960'

INSERT INTO EPAY_PAYMENT_DTL_BNK_BKP@EPAY_SRL_DCC
SELECT * FROM EPAY_PAYMENT_DTL@EPAY_SRL_DCC
WHERE REF_BATCH_NO='EON31960'


COMMIT;



DELETE FROM EPAY_PAYMENT_DTL@EPAY_SRL_DCC
WHERE REF_BATCH_NO='EON31960'


DELETE FROM EPAY_PAYMENT_MST@EPAY_SRL_DCC
WHERE REF_BATCH_NO='EON31960'
AND STATUS<>'T'

COMMIT;

DELETE FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO='EON31960'

DELETE FROM EPAY_PAYMENT_MST
WHERE BATCH_NO='EON31960'

COMMIT;


SELECT * FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE_HIST
WHERE PAY_DATE='27-FEB-2020'
AND ORG_BR_CODE='K2'



INSERT INTO EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE_EX
SELECT * FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE_HIST
WHERE PAY_DATE='27-FEB-2020'
AND ORG_BR_CODE='K2'


INSERT INTO EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE
SELECT * FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE_HIST
WHERE PAY_DATE='27-FEB-2020'
AND ORG_BR_CODE='K2'

COMMIT;


SELECT * FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE
WHERE PAY_DATE='27-FEB-2020'
AND ORG_BR_CODE='K2'

DELETE FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE_HIST
WHERE PAY_DATE='27-FEB-2020'
AND ORG_BR_CODE='K2'

COMMIT;

DELETE FROM EPAYONLINE.EPAY_DAY_END_LOG
WHERE PAY_DATE='27-FEB-2020'
AND PAY_BANK_CODE='01'
AND PAY_BANK_BR_CODE='0008'

COMMIT;

SELECT * FROM EPAYONLINE.EPAY_DAY_END_LOG
WHERE PAY_DATE='27-FEB-2020'
AND PAY_BANK_CODE='01'
AND PAY_BANK_BR_CODE='0008'


