


SELECT D.ORG_CODE,D.PAY_DATE,M.BANK_CODE,M.BANK_NAME,B.BRANCH_CODE,B.BRANCH_NAME,COUNT(*) TOT_CONSUMER
 FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE D,EPAYONLINE.EPAY_BANK_MST M,EPAYONLINE.EPAY_BANK_BRANCH B
WHERE D.BANK_CODE=M.BANK_CODE
AND M.BANK_CODE=B.BANK_CODE
AND D.BANK_BR_CODE=B.BRANCH_CODE
AND D.PAY_DATE =TRUNC((SYSDATE-1))
GROUP BY D.ORG_CODE,D.PAY_DATE,M.BANK_CODE,M.BANK_NAME,B.BRANCH_CODE,B.BRANCH_NAME


SELECT * FROM EPAYONLINE.EPAY_DAY_END_LOG
WHERE PAY_DATE =TRUNC((SYSDATE-1))
AND PAY_BANK_BR_CODE='0005'