
SELECT * FROM UTILITY_BILL_PDB@EPAY_GP
WHERE BILL_MONTH between '201907' and '201908'
AND ACCOUNT_NUMBER='26866811'


select b.BILL_MONTH A_BILL_MONTH,b.LOCATION_CODE A_LOCATION_CODE,b.ACCOUNT_NUMBER A_ACCOUNT_NUMBER,b.BILL_NUMBER A_BILL_NUMBER,b.TOTAL_BILL_AMOUNT A_TOT_AMT 
from epay_payment_mst pm,epay_payment_dtl pd,epay_utility_bill  b,epay_location_master l
where pm.BATCH_NO=pd.BATCH_NO
and pm.LOCATION_CODE=b.LOCATION_CODE
and pd.BILL_NUMBER = b.BILL_NUMBER
and pm.LOCATION_CODE = l.LOCATION_CODE
and b.LOCATION_CODE=l.LOCATION_CODE
and pm.PAY_BANK_CODE='96'
and  TO_CHAR(pm.PAY_DATE,'RRRRMM')='201908'
and l.CENTER_NAME='MOULAVIBAZAR'
and b.BILL_MONTH='201907'



SELECT UB.BILL_MONTH B_BILL_MONTH,UB.LOCATION_CODE B_LOCATION_CODE,UB.ACCOUNT_NUMBER B_ACCOUNT_NUMBER,UB.BILL_NUMBER B_BILL_NUMBER,UB.TOTAL_BILL_AMOUNT B_TOT_AMT
FROM EPAY_UTILITY_BILL UB
WHERE UB.BILL_MONTH='201908'
AND ACCOUNT_NUMBER IN (
select b.ACCOUNT_NUMBER from epay_payment_mst pm,epay_payment_dtl pd,epay_utility_bill  b,epay_location_master l
where pm.BATCH_NO=pd.BATCH_NO
and pm.LOCATION_CODE=b.LOCATION_CODE
and pd.BILL_NUMBER = b.BILL_NUMBER
and pm.LOCATION_CODE = l.LOCATION_CODE
and b.LOCATION_CODE=l.LOCATION_CODE
and pm.PAY_BANK_CODE='96'
and  TO_CHAR(pm.PAY_DATE,'RRRRMM')='201908'
and l.CENTER_NAME='MOULAVIBAZAR'
and b.BILL_MONTH='201907'
)



SELECT A.A_BILL_MONTH,A.A_LOCATION_CODE,A.A_ACCOUNT_NUMBER,A.A_BILL_NUMBER,A.A_TOT_AMT,B.B_BILL_MONTH,B.B_BILL_NUMBER,B.B_TOT_AMT FROM (
select b.BILL_MONTH A_BILL_MONTH,b.LOCATION_CODE A_LOCATION_CODE,b.ACCOUNT_NUMBER A_ACCOUNT_NUMBER,b.BILL_NUMBER A_BILL_NUMBER,b.TOTAL_BILL_AMOUNT A_TOT_AMT 
from epay_payment_mst pm,epay_payment_dtl pd,epay_utility_bill  b,epay_location_master l
where pm.BATCH_NO=pd.BATCH_NO
and pm.LOCATION_CODE=b.LOCATION_CODE
and pd.BILL_NUMBER = b.BILL_NUMBER
and pm.LOCATION_CODE = l.LOCATION_CODE
and b.LOCATION_CODE=l.LOCATION_CODE
and pm.PAY_BANK_CODE='96'
and  TO_CHAR(pm.PAY_DATE,'RRRRMM')='201908'
and l.CENTER_NAME='MOULAVIBAZAR'
and b.BILL_MONTH='201907')A,(
SELECT UB.BILL_MONTH B_BILL_MONTH,UB.LOCATION_CODE B_LOCATION_CODE,UB.ACCOUNT_NUMBER B_ACCOUNT_NUMBER,UB.BILL_NUMBER B_BILL_NUMBER,UB.TOTAL_BILL_AMOUNT B_TOT_AMT
FROM EPAY_UTILITY_BILL UB
WHERE UB.BILL_MONTH='201908'
AND ACCOUNT_NUMBER IN (
select b.ACCOUNT_NUMBER from epay_payment_mst pm,epay_payment_dtl pd,epay_utility_bill  b,epay_location_master l
where pm.BATCH_NO=pd.BATCH_NO
and pm.LOCATION_CODE=b.LOCATION_CODE
and pd.BILL_NUMBER = b.BILL_NUMBER
and pm.LOCATION_CODE = l.LOCATION_CODE
and b.LOCATION_CODE=l.LOCATION_CODE
and pm.PAY_BANK_CODE='96'
and  TO_CHAR(pm.PAY_DATE,'RRRRMM')='201908'
and l.CENTER_NAME='MOULAVIBAZAR'
and b.BILL_MONTH='201907'
))B
WHERE A.A_ACCOUNT_NUMBER=B.B_ACCOUNT_NUMBER
AND A.A_LOCATION_CODE=B.B_LOCATION_CODE
GROUP BY A.A_BILL_MONTH,A.A_LOCATION_CODE,A.A_ACCOUNT_NUMBER,A.A_BILL_NUMBER,A.A_TOT_AMT,B.B_BILL_MONTH,B.B_BILL_NUMBER,B.B_TOT_AMT