


select ZONE_NAME, COMP_CNTR_NAME, CIRCLE_NAME, tot_cons from (
SELECT ZONE_NAME,COMP_CNTR_NAME,CIRCLE_NAME,COUNT(*) tot_cons FROM VW_Z_C_C_L V,DA_CUSTOMER_MASTER_DATA C
WHERE V.LOCATION_CODE = C.LOCATION_CODE
GROUP BY (ZONE_NAME),cube(COMP_CNTR_NAME,CIRCLE_NAME)
ORDER BY ZONE_NAME,COMP_CNTR_NAME nulls last,CIRCLE_NAME nulls last) a
where a.COMP_CNTR_NAME is  null
and a.CIRCLE_NAME  is  null
union
SELECT ZONE_NAME,COMP_CNTR_NAME,CIRCLE_NAME,COUNT(*) FROM VW_Z_C_C_L V,DA_CUSTOMER_MASTER_DATA C
WHERE V.LOCATION_CODE = C.LOCATION_CODE
GROUP BY (ZONE_NAME),COMP_CNTR_NAME,cube(CIRCLE_NAME)
ORDER BY ZONE_NAME,COMP_CNTR_NAME ,CIRCLE_NAME nulls last
