
CREATE INDEX EPAYMENT.EPAY_UTILITY_BILL_HSTR_INDX1 ON EPAYMENT.EPAY_UTILITY_BILL_HSTR
(BILL_NUMBER, LOCATION_CODE)
LOGGING
TABLESPACE EPAYINDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


D:\APP\ADMINISTRATOR\ORADATA\EBPS\EPAYINDEX02.DBF

D:\APP\ADMINISTRATOR\ORADATA\EBPS\EPAYHISTINDX01.DBF


CREATE TABLESPACE EPAYHISTINDX DATAFILE  'D:\APP\ADMINISTRATOR\ORADATA\EBPS\EPAYHISTINDX01.DBF' SIZE 2048 M;


CREATE TABLESPACE EPAYHISTDATA DATAFILE  'D:\APP\ADMINISTRATOR\ORADATA\EBPS\EPAYHISTDATA01.DBF' SIZE 4096 M;


select 1024*4 from dual;