SELECT 'Grameen Phone Ltd' AS OPERATOR_NAME,B.ACCOUNT_NUMBER,A.BILL_NUMBER,A.LOCATION_CODE,A.PAY_DATE PAYMENT_DATE,PDB_AMOUNT,GOVT_DUTY,PDB_AMOUNT+GOVT_DUTY AS TOTAL_AMOUNT FROM VW_EPAY_PAYMENT_MST_DTL A,EPAY_UTILITY_BILL B
WHERE (A.BILL_NUMBER,A.LOCATION_CODE) IN (
SELECT BILL_NUMBER,LOCATION_CODE FROM TWO_OPT_PYMT
) AND A.PAY_BANK_CODE='96'
AND A.BILL_NUMBER=B.BILL_NUMBER
AND A.LOCATION_CODE=B.LOCATION_CODE


SELECT 'Axiata Bangladesh Ltd (ROBI)' AS OPERATOR_NAME,B.ACCOUNT_NUMBER,A.BILL_NUMBER,A.LOCATION_CODE,A.PAY_DATE PAYMENT_DATE,PDB_AMOUNT,GOVT_DUTY,PDB_AMOUNT+GOVT_DUTY AS TOTAL_AMOUNT FROM VW_EPAY_PAYMENT_MST_DTL A,EPAY_UTILITY_BILL B
WHERE (A.BILL_NUMBER,A.LOCATION_CODE) IN (
SELECT BILL_NUMBER,LOCATION_CODE FROM TWO_OPT_PYMT
) AND A.PAY_BANK_CODE='97'
AND A.BILL_NUMBER=B.BILL_NUMBER
AND A.LOCATION_CODE=B.LOCATION_CODE