

SELECT BANK_CODE,BRANCH_CODE,LOCATION_CODE FROM EPAY_BANK_BRANCHES
WHERE BANK_BRANCH_STATUS='A'
AND INST_DATE IS NULL

SELECT PAY_BRANCH_CODE,MIN(PAY_DATE) FROM EPAY_PAYMENT_MST
WHERE PAY_BANK_CODE NOT IN ('97','96')
GROUP BY PAY_BRANCH_CODE
ORDER BY MIN(PAY_DATE) ASC

SELECT PAY_BANK_CODE,PAY_BRANCH_CODE,LOCATION_CODE,MIN(PAY_DATE) FROM EPAY_PAYMENT_MST
WHERE PAY_BANK_CODE NOT IN ('97','96')
AND (PAY_BANK_CODE,PAY_BRANCH_CODE,LOCATION_CODE) IN ( 
SELECT BANK_CODE,BRANCH_CODE,LOCATION_CODE FROM EPAY_BANK_BRANCHES
WHERE BANK_BRANCH_STATUS='A'
AND INST_DATE IS NULL)
GROUP BY PAY_BANK_CODE,PAY_BRANCH_CODE,LOCATION_CODE
ORDER BY MIN(PAY_DATE) ASC






SELECT PAY_BANK_CODE,PAY_BRANCH_CODE,LOCATION_CODE,MIN(PAY_DATE) FROM EPAY_PAYMENT_MST
WHERE PAY_BANK_CODE NOT IN ('97','96')
AND (PAY_BANK_CODE,PAY_BRANCH_CODE,LOCATION_CODE) IN ( 
SELECT BANK_CODE,BRANCH_CODE,LOCATION_CODE FROM EPAY_BANK_BRANCHES
WHERE BANK_BRANCH_STATUS='A'
AND INST_DATE IS NULL
)
GROUP BY PAY_BANK_CODE,PAY_BRANCH_CODE,LOCATION_CODE
ORDER BY MIN(PAY_DATE) ASC