
ALLOC_MST_ID,ALLOC_NO,ALLOC_DATE,REQ_NO,ALLOC_USER_NO,ALLOC_COST_TYPE,
            REQUISITION_BY,REQ_LETTER_NO,REQ_FROM,REQ_TO,REQ_TYPE,PURPOSE,CREATE_BY,CREATE_DATE
 -------------------           
            
  ISU_MST_ID, ISU_NO, ISU_DATE, ISU_USER_NO, REQ_NO, ALLOC_NO, ISU_COST_TYPE,ISSUE_TYPE
 , AUTHO_LETTER_NO, AUTHO_LETTER_DT, TYPE_CARRIER, STATUS          
 
-------------- 
 ALLOC_DTL_ID,ALLOC_MST_ID,ALLOC_NO,REQ_NO,ITEM_CODE,PO_NO,PR_RATE,
                    MSR_UNIT,CUR_CODE,CUR_CONV_RATE,REQ_QTY,ALLOC_QTY,CREATE_BY,CREATE_DATE
                    
 ISU_DTL_ID, ISU_MST_ID, REQ_NO, ALLOC_NO, ISU_NO, ITEM_CODE, PO_NO, PR_RATE, MSR_UNIT, CUR_CODE, CUR_CONV_RATE, REQ_QTY,
  ALLOC_QTY, 
  
ISU_QTY, ISU_ENTRY_OP, ISU_ENTRY_DT, TRANS_ID, DB_CODE, CR_CODE, ISSUED_ITEM_CATEGORY, AUXILIARY_ITEM, MAIN_ITEM_REF, STATUS, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE       


ISU_MST_ID NUMBER
ISU_NO VARCHAR2
ISU_DATE DATE
ISU_USER_NO VARCHAR2
REQ_NO VARCHAR2
ALLOC_NO VARCHAR2
ISU_COST_TYPE VARCHAR2
ISU_SO_NO VARCHAR2
ISU_SO_AMND VARCHAR2
ISU_SO_AMND_DT DATE
ISU_REMARKS VARCHAR2
ISU_AUTHO_STATUS VARCHAR2
ISU_AUTHORIZE VARCHAR2
ISU_AUTHORIZE_DT DATE
CARRIED_BY VARCHAR2
CARRIED_DATE DATE
DELIVERY_NO VARCHAR2
DELIVERY_DATE DATE
AUCTION_VHICL_NUM VARCHAR2
AUC_ISU_WO_NO VARCHAR2
AUC_ISU_WO_DATE DATE
ISSUE_TYPE VARCHAR2
ISSUED_ORGANIZATION VARCHAR2
REQ_UNUSED_FLAG VARCHAR2
SCANNED_HD_CPY VARCHAR2
GATE_PASSNO VARCHAR2
GATE_DATE DATE
AUTHO_LETTER_NO VARCHAR2
AUTHO_LETTER_DT DATE
TYPE_CARRIER VARCHAR2
STATUS VARCHAR2
CREATE_BY VARCHAR2
CREATE_DATE DATE
UPDATE_BY VARCHAR2
UPDATE_DATE DATE            


p_ISU_DTL_ID IN Array_ISU_DTL_ID,
p_ISU_MST_ID IN Array_ISU_MST_ID,
p_REQ_NO IN Array_REQ_NO,
p_ALLOC_NO IN Array_ALLOC_NO,
p_ISU_NO IN Array_ISU_NO,
p_ITEM_CODE IN Array_ITEM_CODE,
p_PO_NO IN Array_PO_NO,
p_PR_RATE IN Array_PR_RATE,
p_MSR_UNIT IN Array_MSR_UNIT,
p_CUR_CODE IN Array_CUR_CODE,
p_CUR_CONV_RATE IN Array_CUR_CONV_RATE,
p_REQ_QTY IN Array_REQ_QTY,
p_ALLOC_QTY IN Array_ALLOC_QTY,
p_ISU_QTY IN Array_ISU_QTY,
p_ISU_ENTRY_OP IN Array_ISU_ENTRY_OP,
p_ISU_ENTRY_DT IN Array_ISU_ENTRY_DT,
p_TRANS_ID IN Array_TRANS_ID,
p_DB_CODE IN Array_DB_CODE,
p_CR_CODE IN Array_CR_CODE,
p_ISSUED_ITEM_CATEGORY IN Array_ISSUED_ITEM_CATEGORY,
p_AUXILIARY_ITEM IN Array_AUXILIARY_ITEM,
p_MAIN_ITEM_REF IN Array_MAIN_ITEM_REF,
p_STATUS IN Array_STATUS,
p_CREATE_BY IN Array_CREATE_BY,
p_CREATE_DATE IN Array_CREATE_DATE,
p_UPDATE_BY IN Array_UPDATE_BY,
p_UPDATE_DATE IN Array_UPDATE_DATE,


p_ISU_DTL_ID(AL),
p_ISU_MST_ID(AL),
p_REQ_NO(AL),
p_ALLOC_NO(AL),
p_ISU_NO(AL),
p_ITEM_CODE(AL),
p_PO_NO(AL),
p_PR_RATE(AL),
p_MSR_UNIT(AL),
p_CUR_CODE(AL),
p_CUR_CONV_RATE(AL),
p_REQ_QTY(AL),
p_ALLOC_QTY(AL),
p_ISU_QTY(AL),
p_ISU_ENTRY_OP(AL),
p_ISU_ENTRY_DT(AL),
p_TRANS_ID(AL),
p_DB_CODE(AL),
p_CR_CODE(AL),
p_ISSUED_ITEM_CATEGORY(AL),
p_AUXILIARY_ITEM(AL),
p_MAIN_ITEM_REF(AL),
p_STATUS(AL),
p_CREATE_BY(AL),
p_CREATE_DATE(AL),
p_UPDATE_BY(AL),
p_UPDATE_DATE(AL),