

SELECT IR.ISU_RTN_NO,L.LOC_DESC AS RETURN_FROM,IR.RETURN_TO, IR.RETURN_TYPE,IR.ISSUE_RETURN_SLIP_NO,IR.ISU_RTN_DT,
IM.ITEM_DESC||'-'||D.ITEM_CODE AS ITEM_DESC,  M.MSR_UNIT_DESC,D.RET_QNTY,D.ITEM_STATUS
FROM ST_ISU_RTN_MST IR,ST_LOCATION L,ST_ISU_RTN_DTL D,ST_ITEM_MST IM,MEASURE_UNIT M
WHERE IR.RETURN_FROM=L.LOC_CODE
AND IR.ISU_RTN_MST_ID=D.ISU_RTN_MST_ID
AND D.ITEM_CODE=IM.ITEM_CODE
AND D.MSR_UNIT=M.MSR_UNIT_CODE










      SELECT
        ISU_MST_ID,ISU_NO,TO_CHAR(ISU_DATE,'DD/MM/RRRR')AS ISU_DATE,ISU_USER_NO,REQ_NO,ALLOC_NO,ISU_FROM,L.LOC_DESC, ISU_TO,ISU_COST_TYPE,A.ISSUE_TYPE,B.ISSUE_TYPE_DESCR, ISU_AUTHO_STATUS,
        DELIVERY_NO,DELIVERY_DATE
        FROM ST_ISU_MST A,ST_ISSUE_TYPE B,ST_LOCATION L 
        WHERE ISU_USER_NO=p_ISU_USER_NO
        AND ISU_DATE=TO_DATE(p_ISU_DATE,'DD/MM/RRRR')
        AND A.ISSUE_TYPE=B.ISSUE_TYPE(+)
        AND A.ISU_FROM=L.LOC_CODE;



