
CREATE TABLE LEAA.LEAA_DESIGNATION (
DESI_ID NUMBER,
DESI_CODE VARCHAR2(5),
DESI_DESC VARCHAR2(100),
STATUS VARCHAR2(1),
CREATE_BY VARCHAR2(100),
CREATE_DATE DATE,
UPDATE_BY VARCHAR2(100),
UPDATE_DATE  DATE
)