
SELECT * FROM DBERSICE.UTILITY_BILL_PDB@EPAY_GP
WHERE BILL_MONTH='201510'
AND LOCATION_CODE='I1'
AND BILL_NUMBER='304644058'


SELECT * FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201510'
AND LOCATION_CODE='I1'
AND BILL_NUMBER='304644058'




UPDATE EPAY_UTILITY_BILL
SET 
WHERE BILL_MONTH='201510'
AND LOCATION_CODE=:P_LOCATION_CODE
AND BILL_NUMBER=:P_BILL_NUMBER
FROM DBERSICE.UTILITY_BILL_PDB@EPAY_GP