SELECT BI.CUSTOMER_NUM||BI.CONS_CHK_DIGIT CUSTOMER_NUM,C.CUSTOMER_NAME,CD.ADDR_DESCR1||'-'||CD.ADDR_DESCR2 AS ADDRESS,DECODE(CUSTOMER_STATUS_CODE,'C', 'CONNECTE','D', 'PARMANENT DISCONNECTED') CUSTOMER_STATUS,
BI.LOCATION_CODE,BI.BILL_CYCLE_CODE ,BI.TOTAL_BILL  
FROM BC_BILL_IMAGE BI,BC_CUSTOMERS C,BC_CUSTOMER_ADDR CD
WHERE BI.CUST_ID=C.CUST_ID
AND BI.CUST_ID=CD.CUST_ID
AND CD.ADDR_TYPE='B'
AND (BI.CUSTOMER_NUM,BI.BILL_CYCLE_CODE) IN (
SELECT CUSTOMER_NUM,MAX(BILL_CYCLE_CODE) FROM BC_BILL_IMAGE
WHERE BILL_CYCLE_CODE<'201909'
--AND LOCATION_CODE=:p_Location_Code
AND CUST_ID NOT IN (
SELECT CUST_ID FROM BC_RECEIPT_HDR
WHERE RECEIPT_TYPE_CODE='REC')
GROUP BY CUSTOMER_NUM
)ORDER BY LOCATION_CODE

