

select p.ORG_BR_CODE,L.LOCATION_NAME  from EPAY_PAYMENT_MST P,EPAY_LOCATION_MASTER L
where P.ORG_BR_CODE=L.LOCATION_CODE
AND PAY_DATE between '01-AUG-2019' and '31-AUG-2019'
and ORG_CODE='WZPDCL'
group by P.ORG_BR_CODE,L.LOCATION_NAME
order by ORG_BR_CODE


select p.ORG_BR_CODE,L.LOCATION_NAME  from EPAY_PAYMENT_MST@EPAY_WZPDCL P,EPAY_LOCATION_MASTER@EPAY_WZPDCL L
where P.ORG_BR_CODE=L.LOCATION_CODE
AND PAY_DATE between '01-JUL-2019' and '31-JUL-2019'
and ORG_CODE='WZPDCL'
group by P.ORG_BR_CODE,L.LOCATION_NAME
order by ORG_BR_CODE