UPDATE BC_BILL_IMAGE@BILLING_BOG
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE='201512'
AND INVOICE_NUM IN (
SELECT SUBSTR(A.BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL_GPR_x A
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%BOGRA%'));

COMMIT;


UPDATE BC_BILL_IMAGE@BILLING_PAB
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE='201512'
AND INVOICE_NUM IN (
SELECT SUBSTR(A.BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL_GPR_x A
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%PABNA%'));

COMMIT;


UPDATE BC_BILL_IMAGE@BILLING_SYL
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE='201512'
AND INVOICE_NUM IN (
SELECT SUBSTR(A.BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL_GPR_x A
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%SYLHET%'));

COMMIT;


UPDATE BC_BILL_IMAGE@BILLING_TANG
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE='201512'
AND INVOICE_NUM IN (
SELECT SUBSTR(A.BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL_GPR_x A
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%TANGAIL%'));

COMMIT;


UPDATE BC_BILL_IMAGE@BILLING_NAO
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE='201512'
AND INVOICE_NUM IN (
SELECT SUBSTR(A.BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL_GPR_x A
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%NAOGAON%'));

COMMIT;


UPDATE BC_BILL_IMAGE@BILLING_RONG
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE='201512'
AND INVOICE_NUM IN (
SELECT SUBSTR(A.BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL_GPR_x A
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%RANGPUR%'));

COMMIT;


UPDATE BC_BILL_IMAGE@BILLING_JAM
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE='201512'
AND INVOICE_NUM IN (
SELECT SUBSTR(A.BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL_GPR_x A
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%JAMALPUR%'));

COMMIT;


UPDATE BC_BILL_IMAGE@BILLING_RAJ
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE='201512'
AND INVOICE_NUM IN (
SELECT SUBSTR(A.BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL_GPR_x A
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%RAJSHAHI%'));

COMMIT;


UPDATE BC_BILL_IMAGE@BILLING_DIN
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE='201512'
AND INVOICE_NUM IN (
SELECT SUBSTR(A.BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL_GPR_x A
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%DINAJPUR%'));

COMMIT;


UPDATE BC_BILL_IMAGE@BILLING_MYMEN
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE='201512'
AND INVOICE_NUM IN (
SELECT SUBSTR(A.BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL_GPR_x A
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%MYMENSING%'));

COMMIT;


UPDATE BC_BILL_IMAGE@BILLING_KISHOR
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE='201512'
AND INVOICE_NUM IN (
SELECT SUBSTR(A.BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL_GPR_x A
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%KISHOREGANJ%'));

COMMIT;


UPDATE BC_BILL_IMAGE@BILLING_MOU
SET DATA_TRANS_LOG='T'
WHERE BILL_CYCLE_CODE='201512'
AND INVOICE_NUM IN (
SELECT SUBSTR(A.BILL_NUMBER,1,8) FROM EPAY_UTILITY_BILL_GPR_x A
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                       WHERE CENTER_NAME LIKE '%MOULAVIBAZAR%'));

COMMIT;

