UPDATE EPAY_PAYMENT_MST_INT M
SET (TOTAL_PDB_AMOUNT,REVENUE_STAMP_AMOUNT,NET_PDB_AMOUNT,TOTAL_GOVT_DUTY)=(
SELECT SUM(NVL(PDB_AMOUNT,0)),SUM(CASE  WHEN NVL(PDB_AMOUNT,0)+NVL(GOVT_DUTY,0)>=500 THEN 10  ELSE 0  END),
SUM(NVL(PDB_AMOUNT,0))-SUM(CASE  WHEN NVL(PDB_AMOUNT,0)+NVL(GOVT_DUTY,0)>=500 THEN 10  ELSE 0  END),SUM(NVL(GOVT_DUTY,0))
 FROM EPAY_PAYMENT_DTL_INT D
WHERE D.BATCH_NO=:P_BATCH_NO
AND D.BATCH_NO=M.BATCH_NO)
WHERE M.BATCH_NO=:P_BATCH_NO


COMMIT;


UPDATE EPAY_PAYMENT_MST M
SET (TOTAL_PDB_AMOUNT,REVENUE_STAMP_AMOUNT,NET_PDB_AMOUNT,TOTAL_GOVT_DUTY)=(
SELECT SUM(NVL(PDB_AMOUNT,0)),SUM(CASE  WHEN NVL(PDB_AMOUNT,0)+NVL(GOVT_DUTY,0)>=500 THEN 10  ELSE 0  END),
SUM(NVL(PDB_AMOUNT,0))-SUM(CASE  WHEN NVL(PDB_AMOUNT,0)+NVL(GOVT_DUTY,0)>=500 THEN 10  ELSE 0  END),SUM(NVL(GOVT_DUTY,0))
 FROM EPAY_PAYMENT_DTL D
WHERE D.BATCH_NO=:P_BATCH_NO
AND D.BATCH_NO=M.BATCH_NO)
WHERE M.BATCH_NO=:P_BATCH_NO


COMMIT;

-----------24---------

UPDATE EPAY_PAYMENT_MST M
SET (TOTAL_ORG_AMOUNT,REVENUE_STAMP_AMOUNT,NET_ORG_AMOUNT,TOTAL_VAT_AMT)=(
SELECT SUM(NVL(ORG_PRN_AMOUNT,0)),SUM(CASE  WHEN NVL(ORG_PRN_AMOUNT,0)+NVL(VAT_AMOUNT,0)>=500 THEN 10  ELSE 0  END),
SUM(NVL(ORG_PRN_AMOUNT,0))-SUM(CASE  WHEN NVL(ORG_PRN_AMOUNT,0)+NVL(VAT_AMOUNT,0)>=500 THEN 10  ELSE 0  END),SUM(NVL(VAT_AMOUNT,0))
 FROM EPAY_PAYMENT_DTL D
WHERE D.BATCH_NO=:P_BATCH_NO
AND D.BATCH_NO=M.BATCH_NO)
WHERE M.BATCH_NO=:P_BATCH_NO


COMMIT;