
-----------books wise---------

SELECT D.BILL_CYCLE_CODE,V.COMP_CNTR_NAME,C.LOCATION_CODE,V.LOCATION_NAME,C.AREA_CODE,
            COUNT (D.CARD_GEN_DATE) TOTAL_CARD_GEN,COUNT(D.DATA_UPLOAD_DATE) TOTAL_DATA_UP,COUNT(D.APPS_DATA_DOWN_DATE) TOT_APPS_DATA_DOWN,
            COUNT(D.APPS_DATA_UPLOAD_DATE) TOT_APPS_DATA_UP,COUNT(D.DATA_DOWNLOAD_DATE) TOTAL_DATA_DOWN
       FROM MBILL_DATA_LOG D, MBILL_CUSTOMERS C, V_Z_C_C_L V
      WHERE D.CUST_ID = C.CUST_ID
            AND D.BILL_CYCLE_CODE IN
                   (SELECT TO_CHAR (SYSDATE, 'RRRRMM') BILL_CYCLE_CODE FROM DUAL
                    UNION
                    SELECT TO_CHAR (ADD_MONTHS (SYSDATE, -1), 'RRRRMM') BILL_CYCLE_CODE FROM DUAL)
            AND C.LOCATION_CODE = V.LOCATION_CODE
            and C.LOCATION_CODE='H7'
            and substr(C.AREA_CODE,4)='03'
   GROUP BY D.BILL_CYCLE_CODE,V.COMP_CNTR_NAME,C.LOCATION_CODE,V.LOCATION_NAME,C.AREA_CODE
   ORDER BY D.BILL_CYCLE_CODE DESC, V.COMP_CNTR_NAME ASC;
   
   
   ---------------------bill group wise--------
   
   SELECT D.BILL_CYCLE_CODE,V.COMP_CNTR_NAME,C.LOCATION_CODE,V.LOCATION_NAME,substr(C.AREA_CODE,4) bill_group,
            COUNT (D.CARD_GEN_DATE) TOTAL_CARD_GEN,COUNT(D.DATA_UPLOAD_DATE) TOTAL_DATA_UP,COUNT(D.APPS_DATA_DOWN_DATE) TOT_APPS_DATA_DOWN,
            COUNT(D.APPS_DATA_UPLOAD_DATE) TOT_APPS_DATA_UP,COUNT(D.DATA_DOWNLOAD_DATE) TOTAL_DATA_DOWN
       FROM MBILL_DATA_LOG D, MBILL_CUSTOMERS C, V_Z_C_C_L V
      WHERE D.CUST_ID = C.CUST_ID
            AND D.BILL_CYCLE_CODE IN
                   (SELECT TO_CHAR (SYSDATE, 'RRRRMM') BILL_CYCLE_CODE FROM DUAL
                    UNION
                    SELECT TO_CHAR (ADD_MONTHS (SYSDATE, -1), 'RRRRMM') BILL_CYCLE_CODE FROM DUAL)
            AND C.LOCATION_CODE = V.LOCATION_CODE
   GROUP BY D.BILL_CYCLE_CODE,V.COMP_CNTR_NAME,C.LOCATION_CODE,V.LOCATION_NAME,substr(C.AREA_CODE,4)
   ORDER BY D.BILL_CYCLE_CODE DESC, V.COMP_CNTR_NAME ASC;
   
   
   
   ----------location wise-------------
   
     SELECT D.BILL_CYCLE_CODE,V.COMP_CNTR_NAME,C.LOCATION_CODE,V.LOCATION_NAME,
            COUNT (D.CARD_GEN_DATE) TOTAL_CARD_GEN,COUNT(D.DATA_UPLOAD_DATE) TOTAL_DATA_UP,COUNT(D.APPS_DATA_DOWN_DATE) TOT_APPS_DATA_DOWN,
            COUNT(D.APPS_DATA_UPLOAD_DATE) TOT_APPS_DATA_UP,COUNT(D.DATA_DOWNLOAD_DATE) TOTAL_DATA_DOWN
       FROM MBILL_DATA_LOG D, MBILL_CUSTOMERS C, V_Z_C_C_L V
      WHERE D.CUST_ID = C.CUST_ID
            AND D.BILL_CYCLE_CODE IN
                   (SELECT TO_CHAR (SYSDATE, 'RRRRMM') BILL_CYCLE_CODE FROM DUAL
                    UNION
                    SELECT TO_CHAR (ADD_MONTHS (SYSDATE, -1), 'RRRRMM') BILL_CYCLE_CODE FROM DUAL)
            AND C.LOCATION_CODE = V.LOCATION_CODE
   GROUP BY D.BILL_CYCLE_CODE,V.COMP_CNTR_NAME,C.LOCATION_CODE,V.LOCATION_NAME
   ORDER BY D.BILL_CYCLE_CODE DESC, V.COMP_CNTR_NAME ASC;