SELECT COUNT(*) FROM MBILL_DATA_LOG
WHERE CUST_ID IN (SELECT CUST_ID FROM MBILL_CUSTOMERS WHERE LOCATION_CODE='C3' AND SUBSTR(AREA_CODE,4,2)=:P_BG)
AND BILL_CYCLE_CODE='201809'
AND DATA_DOWNLOAD_DATE IS NOT NULL
AND TRUNC(DATA_DOWNLOAD_DATE) = TRUNC(SYSDATE)
ORDER BY DATA_DOWNLOAD_DATE DESC