

select count(*) from MBILL_DATA_LOG
where cust_id in (select cust_id from mbill_customers where location_code in (
select location_code from EPAY_LOCATION_MASTER
where center_name='KISORGONG'))
and bill_cycle_code='201811'




SELECT COUNT(*) FROM BC_METER_READING_CARD_DTL@BILLING_RONG
WHERE BILL_CYCLE_CODE='201812'
AND CUST_ID IN (SELECT CUST_ID FROM MBILL_CUSTOMERS@MBILLSVR WHERE LOCATION_CODE IN (
SELECT LOCATION_CODE FROM MBILL_LOCATION_MASTER
))




SELECT COUNT(*) FROM MBILL_DATA_LOG@MBILLSVR
WHERE BILL_CYCLE_CODE='201812'
AND CUST_ID IN (SELECT CUST_ID FROM MBILL_CUSTOMERS@MBILLSVR WHERE LOCATION_CODE IN (
SELECT LOCATION_CODE FROM MBILL_LOCATION_MASTER
))



SELECT COUNT(*) FROM MBILL_METER_READING_CARD_DTL@MBILLSVR
WHERE BILL_CYCLE_CODE='201812'
AND CUST_ID IN (SELECT CUST_ID FROM MBILL_CUSTOMERS@MBILLSVR WHERE LOCATION_CODE IN (
SELECT LOCATION_CODE FROM MBILL_LOCATION_MASTER
))



SELECT * FROM MBILL_METER_READING_CARD_DTL@MBILLSVR

WHERE BILL_CYCLE_CODE='201812'