

SELECT EPAY.DFN_MBP_BTCH_REMOVE (:P_Bank_Code,:P_Pay_Date,UPPER(:P_Location_Code)) FROM DUAL;

------MBP Batch Generate-------

EXECUTE MBP.DPG_MBP_BTCH_GEN.DPD_MBP_BTCH_GEN_CONT@MBP_23;


SELECT * FROM VW_EPAY_UNTRNS_DATA_MBP

------MBP Batch Validation-------

EXECUTE DPG_EPAY_MBP_PYMT_VALIDATION.DPD_EPAY_MBP_PYMT_VALID_CONT;


 
--------------Data transfer between SRL to DCC ------------

SELECT * FROM VW_EPAY_UNTRNS_DATA_MBP


EXECUTE DPG_EPAY_PYMT_DATA_TRNS_SRL.DPD_EPAY_PY_DATA_TRNS_SRL_CON@EPAY_SRL_DCC;

