
------------CHK

SELECT * FROM EPAY_BANKS
ORDER BY BANK_CODE 


SELECT * FROM EPAY_PAYMENT_MST
WHERE PAY_DATE='18-NOV-2018'
AND PAY_BANK_CODE='54'
AND LOCATION_CODE='W5'

387514    MBP25591

SELECT * FROM EPAY_PAYMENT_DTL
WHERE REF_BATCH_NO='MBP25591'

--------------------

DELETE FROM EPAY_PAYMENT_DTL
WHERE REF_BATCH_NO='MBP25591'


DELETE FROM EPAY_PAYMENT_MST
WHERE REF_BATCH_NO='MBP25591'

COMMIT;

----------------------------------SRL-24----------------------

-------CHK

SELECT * FROM EPAY_PAYMENT_MST@EPAY_SRL
WHERE BATCH_NO='MBP25591'


SELECT * FROM EPAY_PAYMENT_DTL@EPAY_SRL
WHERE BATCH_NO='MBP25591'

-------------

DELETE FROM EPAY_PAYMENT_DTL@EPAY_SRL
WHERE BATCH_NO='MBP25591'


DELETE FROM EPAY_PAYMENT_MST@EPAY_SRL
WHERE BATCH_NO='MBP25591'


COMMIT;

-----------------------------MBP-23-----------------






SELECT * FROM MBP_PAYMENT_DTL_OVC_HIST
WHERE PAY_DATE = '18-NOV-2018'
AND ORG_BR_CODE = 'W5'
AND PAY_PC_CODE = '77'


UPDATE MBP_PAYMENT_DTL_OVC_HIST
SET STATUS='N'
WHERE PAY_DATE = '11-NOV-2018'
AND ORG_BR_CODE = 'W5'
AND PAY_PC_CODE = '77'
AND STATUS='P'



INSERT INTO MBP_PAYMENT_DTL_OVC
SELECT * FROM MBP_PAYMENT_DTL_OVC_HIST
WHERE PAY_DATE = '11-NOV-2018'
AND ORG_BR_CODE = 'W5'
AND PAY_PC_CODE = '77'

COMMIT;

SELECT * FROM MBP_PAYMENT_DTL_OVC
WHERE PAY_DATE = '11-NOV-2018'
AND ORG_BR_CODE = 'W5'
AND PAY_PC_CODE = '77'



DELETE FROM MBP_PAYMENT_DTL_OVC_HIST
WHERE PAY_DATE = '11-NOV-2018'
AND ORG_BR_CODE = 'W5'
AND PAY_PC_CODE = '77'

COMMIT;


SELECT * FROM MBP_RECON_LOG
WHERE PAY_DATE = '18-NOV-2018'
AND ORG_CODE='BPDB'
AND PAY_COLL_CODE = '77'
AND PAY_COLL_BR_CODE='015'


DELETE FROM MBP_RECON_LOG
WHERE PAY_DATE = '18-NOV-2018'
AND ORG_CODE='BPDB'
AND PAY_COLL_CODE = '77'
AND PAY_COLL_BR_CODE='015'

COMMIT;



