
SELECT * FROM MBP_CUST_PMNT
WHERE PAY_DATE=TRUNC(SYSDATE-1)

SELECT * FROM  MBP_CUST_PMNT_HIST

MY_CASH PC_CODE---->09
DBBL PC_CODE----->01


SELECT 'MY_CASH' OPERATOR,PAY_DATE, SUM(TOT_AMT) TOT_AMOUNT,COUNT(*) TOT_CONSUMER FROM MBP_CUST_PMNT@MBP_23
WHERE PAY_DATE='03-JAN-2018'
AND PC_CODE='09'
GROUP BY PAY_DATE


SELECT 'DBBL' OPERATOR,PAY_DATE, SUM(TOT_AMT) TOT_AMOUNT,COUNT(*) TOT_CONSUMER FROM MBP_CUST_PMNT
WHERE PAY_DATE='27-DEC-2017'
AND PC_CODE ='01'
GROUP BY PAY_DATE


SELECT 'MY_CASH' OPERATOR,PAY_DATE, SUM(TOT_AMT) TOT_AMOUNT,COUNT(*) TOT_CONSUMER FROM MBP_CUST_PMNT_HIST@MBP_23
WHERE PAY_DATE='01-JAN-2018'
AND PC_CODE='09'
GROUP BY PAY_DATE




SELECT 'DBBL' OPERATOR,PAY_DATE, SUM(TOT_AMT) TOT_AMOUNT,COUNT(*) TOT_CONSUMER FROM MBP_CUST_PMNT_HIST
WHERE PAY_DATE='25-DEC-2017'
AND PC_CODE ='01'
GROUP BY PAY_DATE



SELECT PAY_DATE,DECODE(PC_CODE,'01','ROCKET','09','MY CASH') OPERATOR,PC_CODE,SUM(TOT_AMT) TOT_AMOUNT,COUNT(*) TOT_CONSUMER 
FROM MBP_CUST_PMNT_HIST
--WHERE PAY_DATE=TRUNC(SYSDATE-1)
WHERE PC_CODE IN ('01','09')
GROUP BY PAY_DATE,PC_CODE
ORDER  BY 1 DESC, 3 ASC

DISTINCT PC_CODE

SELECT PAY_DATE,DECODE(PC_CODE,'77','Social Islami Bank Limited','13','One Bank Limited') OPERATOR,PC_CODE,SUM(PRN_AMOUNT) PRN_AMOUNT,SUM(VAT_AMOUNT) VAT,SUM(PRN_AMOUNT+VAT_AMOUNT) TOTAL,COUNT(*) TOT_CONSUMER  
FROM MBP_PAYMENT_DTL_OVC_HIST
GROUP BY PAY_DATE,PC_CODE
ORDER BY 1 DESC

SELECT ORG_CODE,PAY_DATE,DECODE(PC_CODE,'01','ROCKET','09','MY_CASH') OPERATOR,PC_CODE,SUM(TOT_AMT) TOT_AMOUNT,COUNT(*) TOT_CONSUMER 
FROM MBP_CUST_PMNT_HIST@MBP_23
WHERE ORG_CODE='WZPDCL'
GROUP BY ORG_CODE,PAY_DATE,PC_CODE
ORDER BY 2 DESC