
SELECT ORG_CODE,ORG_BR_CODE,PAY_DATE,PAY_PC_CODE,PAY_PC_BR_CODE FROM MBP_PAYMENT_DTL_OVC_HIST
WHERE TO_CHAR(PAY_DATE,'RRRRMM')='202004'  
--AND PAY_PC_CODE='10'
AND (PAY_PC_BR_CODE,PAY_DATE) NOT IN (
SELECT PAY_COLL_BR_CODE,PAY_DATE FROM MBP_RECON_LOG
WHERE  TO_CHAR(PAY_DATE,'RRRRMM')='202004' 
--AND PAY_PC_CODE='10'
--GROUP BY ORG_CODE,ORG_BR_CODE,PAY_DATE,PAY_PC_CODE,PAY_PC_BR_CODE
)
UNION
SELECT ORG_CODE,ORG_BR_CODE,PAY_DATE,PAY_PC_CODE,PAY_PC_BR_CODE FROM MBP_PAYMENT_DTL_OVC
WHERE TO_CHAR(PAY_DATE,'RRRRMM')='202004'  
--AND PAY_PC_CODE='10'
AND (PAY_PC_BR_CODE,PAY_DATE) NOT IN (
SELECT PAY_COLL_BR_CODE,PAY_DATE FROM MBP_RECON_LOG
WHERE TO_CHAR(PAY_DATE,'RRRRMM')='202004'
--AND PAY_PC_CODE='10'
--GROUP BY ORG_CODE,ORG_BR_CODE,PAY_DATE,PAY_PC_CODE,PAY_PC_BR_CODE
)