select * from
(WITH MANU_MAST1 AS
(SELECT MANU_DESC COLVAL,MANU_ID FROM ebps.MANU_MAST)
SELECT  TRIM(REGEXP_SUBSTR(T1.COLVAL, '([^,])+', 1, T2.COLUMN_VALUE)) A,MANU_ID
FROM MANU_MAST1 T1 CROSS JOIN
TABLE
(
CAST
(
MULTISET (SELECT LEVEL FROM DUAL 
CONNECT BY LEVEL <= REGEXP_COUNT(T1.COLVAL, '([^,])+')) AS SYS.ODCINUMBERLIST
)
) T2) p,(select RAO_CODE,RAO_DESC from  EPAY_RAO_MST) q where p.a=q.RAO_CODE;


WITH TMPTAB AS
(SELECT MANU_DESC COLVAL,MANU_ID FROM MANU_MAST)
SELECT  TRIM(REGEXP_SUBSTR(T1.COLVAL, '([^,])+', 1, T2.COLUMN_VALUE)) A,ID
FROM TMPTAB T1 CROSS JOIN
TABLE
(
CAST
(
MULTISET (SELECT LEVEL FROM DUAL 
CONNECT BY LEVEL <= REGEXP_COUNT(T1.COLVAL, '([^,])+')) AS SYS.ODCINUMBERLIST
)
) T2;