


SELECT EBC.FN_MOD_I_TARIFF(:P_BILL_CYCLE) FROM DUAL


SELECT * FROM BC_MONTH_MOD_REPORT_SUMMERY
where USAGE_CATEGORY_CODE='I'
and BILL_CYCLE_CODE=:P_BILL_CYCLE



SELECT * FROM BC_MONTH_MOD_REPORT
where USAGE_CATEGORY_CODE='I'
and BILL_CYCLE_CODE=:P_BILL_CYCLE



SELECT * FROM BC_MONTH_MOD_REPORT_SUMMERY
where USAGE_CATEGORY_CODE='I'
and BILL_CYCLE_CODE='201811'



SELECT * FROM BC_MONTH_MOD_REPORT
where USAGE_CATEGORY_CODE='I'
and BILL_CYCLE_CODE='201811'




delete BC_MONTH_MOD_REPORT_SUMMERY
where USAGE_CATEGORY_CODE='I'
and BILL_CYCLE_CODE='201908'



delete BC_MONTH_MOD_REPORT
where USAGE_CATEGORY_CODE='I'
and BILL_CYCLE_CODE='201908'

commit;
