

SELECT BI.CUSTOMER_NUM,C.CUSTOMER_NAME,CD.ADDR_DESCR1||'-'||CD.ADDR_DESCR2 AS ADDRESS,DECODE(CUSTOMER_STATUS_CODE,'C', 'CONNECTE','D', 'PARMANENT DISCONNECTED') CUSTOMER_STATUS,
BI.LOCATION_CODE,BI.BILL_CYCLE_CODE ,BI.TOTAL_BILL  
FROM BC_BILL_IMAGE BI,BC_CUSTOMERS C,BC_CUSTOMER_ADDR CD
WHERE BI.CUST_ID=C.CUST_ID
AND BI.CUST_ID=CD.CUST_ID
AND CD.ADDR_TYPE='B'
AND (BI.CUSTOMER_NUM,BI.BILL_CYCLE_CODE) IN (
SELECT CUSTOMER_NUM,MAX(BILL_CYCLE_CODE) FROM BC_BILL_IMAGE
WHERE BILL_CYCLE_CODE<'201901'
AND LOCATION_CODE='H6'
AND CUST_ID NOT IN (
SELECT CUST_ID FROM BC_RECEIPT_HDR
WHERE RECEIPT_TYPE_CODE='REC')
GROUP BY CUSTOMER_NUM
)ORDER BY LOCATION_CODE






SELECT * FROM BC_BILL_IMAGE
WHERE BILL_CYCLE_CODE<'201901'
AND LOCATION_CODE='H6'
AND CUST_ID NOT IN (
SELECT CUST_ID FROM BC_RECEIPT_HDR
where RECEIPT_TYPE_CODE='REC')


SELECT * FROM BC_BILL_IMAGE
WHERE BILL_CYCLE_CODE<'201901'
AND LOCATION_CODE='H6'
AND CUST_ID NOT IN (
SELECT CUST_ID FROM BC_RECEIPT_HDR
where RECEIPT_TYPE_CODE='REC')



SELECT CUSTOMER_NUM,max(bill_cycle_code),NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)) ,(NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0)+NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+NVL(DEMAND_CHRG,0)+
       NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0))+CURRENT_VAT as total_bill FROM BC_BILL_IMAGE
WHERE BILL_CYCLE_CODE<'201901'
AND LOCATION_CODE='H6'
--and bill_cycle_code is max
AND CUST_ID NOT IN (
SELECT CUST_ID FROM BC_RECEIPT_HDR
where RECEIPT_TYPE_CODE='REC')
GROUP BY CUSTOMER_NUM,total_bill


SELECT CUSTOMER_NUM,BILL_CYCLE_CODE,(NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0)+NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+NVL(DEMAND_CHRG,0)
+NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_VAT,0)
+NVL(ADJUSTED_LPS,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0))+NVL(CURRENT_VAT,0)+NVL(CURRENT_LPS,0)+NVL(ARR_ADV_ADJ_PRN,0)+NVL(ARR_ADV_ADJ_VAT,0)
+NVL(ARR_ADV_ADJ_LPS,0)  TOTAL_BILL_AMOUNT 
FROM BC_BILL_IMAGE
WHERE BILL_CYCLE_CODE<'201901'
AND LOCATION_CODE='H6'
AND CUST_ID NOT IN (
SELECT CUST_ID FROM BC_RECEIPT_HDR
WHERE RECEIPT_TYPE_CODE='REC')
GROUP BY CUSTOMER_NUM,BILL_CYCLE_CODE,CUSTOMER_NUM,ENG_CHRG_SR,ENG_CHRG_OFPK,ENG_CHRG_PK,MINIMUM_CHRG,SERVICE_CHRG,DEMAND_CHRG,XF_RENT,XF_LOSS_CHRG,
PFC_CHARGE,ENG_CHRG_MR1,ENG_CHRG_MR2,ADJUSTED_PRN,ADJUSTED_VAT,ADJUSTED_LPS,ENG_CHRG_MR3,ENG_CHRG_MR4,CURRENT_VAT,
CURRENT_LPS,ARR_ADV_ADJ_PRN,ARR_ADV_ADJ_VAT,ARR_ADV_ADJ_LPS