
----------------24 theke--------------

SELECT P.ORG_BR_CODE,L.LOCATION_NAME,P.ACC_NUM,P.BILL_NUM,P.PAY_DATE,P.PRIN_AMT,P.VAT_AMT,SUM(P.PRIN_AMT+P.VAT_AMT) TOTAL_AMT 
FROM MBP_CUST_PMNT@MBP_23 P,EPAY_LOCATION_MASTER L
WHERE P.ORG_BR_CODE=L.LOCATION_CODE
AND P.ORG_CODE='WZPDCL'
AND P.PC_CODE='09'
AND P.PAY_DATE BETWEEN '01-AUG-2019' AND '31-AUG-2019'
GROUP BY P.ORG_BR_CODE,L.LOCATION_NAME,P.ACC_NUM,P.BILL_NUM,P.PAY_DATE,P.PRIN_AMT,P.VAT_AMT
UNION
SELECT P.ORG_BR_CODE,L.LOCATION_NAME,P.ACC_NUM,P.BILL_NUM,P.PAY_DATE,P.PRIN_AMT,P.VAT_AMT,SUM(P.PRIN_AMT+P.VAT_AMT) TOTAL_AMT 
FROM MBP_CUST_PMNT_HIST@MBP_23 P,EPAY_LOCATION_MASTER L
WHERE P.ORG_BR_CODE=L.LOCATION_CODE
AND P.ORG_CODE='WZPDCL'
AND P.PC_CODE='09'
AND P.PAY_DATE BETWEEN  '01-AUG-2019' AND '31-AUG-2019'
GROUP BY P.ORG_BR_CODE,L.LOCATION_NAME,P.ACC_NUM,P.BILL_NUM,P.PAY_DATE,P.PRIN_AMT,P.VAT_AMT
ORDER BY PAY_DATE


-----------23 theke-----------


SELECT P.ORG_BR_CODE,L.LOCATION_NAME,P.ACC_NUM,P.BILL_NUM,P.PAY_DATE,P.PRIN_AMT,P.VAT_AMT,SUM(P.PRIN_AMT+P.VAT_AMT) TOTAL_AMT 
FROM MBP_CUST_PMNT P,EPAY_LOCATION_MASTER@MBP_23 L
WHERE P.ORG_BR_CODE=L.LOCATION_CODE
AND P.ORG_CODE='WZPDCL'
AND P.PC_CODE='09'
AND P.PAY_DATE BETWEEN '01-Sep-2018' AND '10-Sep-2018'
GROUP BY P.ORG_BR_CODE,L.LOCATION_NAME,P.ACC_NUM,P.BILL_NUM,P.PAY_DATE,P.PRIN_AMT,P.VAT_AMT
UNION
SELECT P.ORG_BR_CODE,L.LOCATION_NAME,P.ACC_NUM,P.BILL_NUM,P.PAY_DATE,P.PRIN_AMT,P.VAT_AMT,SUM(P.PRIN_AMT+P.VAT_AMT) TOTAL_AMT 
FROM MBP_CUST_PMNT_HIST P,EPAY_LOCATION_MASTER@MBP_23 L
WHERE P.ORG_BR_CODE=L.LOCATION_CODE
AND P.ORG_CODE='WZPDCL'
AND P.PC_CODE='09'
AND P.PAY_DATE BETWEEN '01-Sep-2018' AND '10-Sep-2018'
GROUP BY P.ORG_BR_CODE,L.LOCATION_NAME,P.ACC_NUM,P.BILL_NUM,P.PAY_DATE,P.PRIN_AMT,P.VAT_AMT
ORDER BY PAY_DATE