
select * from DUE_DATE_EXTANTION_LOG@epayment

select * from VW_NESCO_BTCH_NOT_GEN@epay_srl

SELECT EPAY.DFN_EPAY_MYM_TANG_DUP_CONS (:P_BILL_MONTH ,:P_LOCATION_CODE ,:P_BILL_GROUP,:p_opt ) FROM DUAL


SELECT LOCATION_CODE,TOTAL_BILL_AMOUNT,A.*  FROM UTILITY_BILL_PDB@EPAY_ROBI A
WHERE BILL_MONTH=(SELECT TO_CHAR (ADD_MONTHS (SYSDATE, -1), 'RRRRMM') FROM DUAL)
AND ACCOUNT_NUMBER ='76253244'

25764614

SELECT * FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=(SELECT TO_CHAR (ADD_MONTHS (SYSDATE, -1), 'RRRRMM') FROM DUAL)
AND ACCOUNT_NUMBER ='76446114'

select total_bill,a.* from bc_bill_image@billing_mymen a
where bill_cycle_code='202106'
and customer_num||CONS_CHK_DIGIT='76446114'




SELECT LOCATION_CODE,A.*  FROM UTILITY_BILL_PDB@EPAY_gp A
WHERE BILL_MONTH=(SELECT TO_CHAR (ADD_MONTHS (SYSDATE, -1), 'RRRRMM') FROM DUAL)
AND ACCOUNT_NUMBER ='76446114'

select * from customer_master_data_pdb@epay_robi
where account_no ='76256821'

select * from epay_customer_master_data--@epay_srl
where account_no ='83612984'


SELECT * FROM EPAY_UTILITY_BILL@epay_srl
WHERE BILL_MONTH=(SELECT TO_CHAR (ADD_MONTHS (SYSDATE, -1), 'RRRRMM') FROM DUAL)
AND ACCOUNT_NUMBER ='76446114'

select total_bill,a.* from bc_bill_image@billing_syl a
where bill_cycle_code='202007'
and customer_num||CONS_CHK_DIGIT='43395591'

select * from bc_invoice_hdr@billing_mymen
where cust_num='7777876'
--and bill_cycle_code='202005'
order by bill_cycle_code desc


------------------
INSERT INTO UTILITY_bILL_PDB@EPAY_ROBI
select * from EPAY_DUPLICATE_CONS_TM
where bill_month='202011'
and account_Number in (
select CUSTOMER_NUM from DUPLICATE_CONS_MYM where TAN_LOCATION_CODE='T3'
and substr(MYM_AREA_CODE,4)='04'
)


------------------
select * from bc_receipt_hdr@billing_kishor
where cust_num='70344662'
and location_code='K2'
order by receipt_date desc

and receipt_date='26-nov-2019'


select * from bc_receipt_hdr@billing_tang
where cust_num='7589715'
order by receipt_date desc

select * from bc_invoice_hdr@billing_com
where cust_num='3129140'
and bill_cycle_code='202005'
order by bill_cycle_code desc


select * from customer_master_data_pdb@epay_robi
where account_no ='76257251'


select * from payment_dtl@epay_robi
where bill_number='2388651303'



select * from epay_utility_bill
where bill_month='201812' 
and account_number IN ('61713739','61709478')

select * from epay_customer_master_data
where account_no='75905756'



select * from EPAY_LOCATION_MASTER
WHERE LOCATION_CODE='Q5'


TRUNCATE TABLE EPAY_UTILITY_BILL_TNG_MY;


INSERT INTO EPAY_DUPLICATE_CONS_TM
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
INVOICE_DUE_DATE BILL_DUE_DATE, 
NULL BILLAMT_AFTERDUEDATE, 
INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
SYSDATE CREATED_ON    , 
USER CREATED_BY   , 
NULL  MODIFIED_ON , 
NULL MODIFIED_BY, 
'N' NOTIFICATION_SENT_STATUS, 
    (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0)+NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
    NVL(DEMAND_CHRG,0)+NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+
    NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
NVL(CURRENT_VAT,0) CURRENT_GOVT_DUTY, 
NVL(ARR_ADV_ADJ_PRN,0)  ARREAR_PRINCIPLE, 
NVL(ARR_ADV_ADJ_VAT,0) ARREAR_GOVT_DUTY, 
0 LATE_PAYMENT_SURCHARGE, 
NVL(TOTAL_BILL,0) TOTAL_BILL_AMOUNT, 
LOCATION_CODE, 
BILL_CYCLE_CODE BILL_MONTH, 
TARIFF, CUST_STATUS CUSTOMER_TYPE, 
NVL(CURRENT_LPS,0) CURRENT_SURCHARGE, 
NVL(ARR_ADV_ADJ_LPS,0) ARREAR_SURCHARGE, 
NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
NVL(ADJUSTED_VAT,0) ADJUSTED_GOVT_DUTY, 
0  ADVANCE_AMOUNT,0 ADJ_ADV_GOVT_DUTY
               FROM  BC_BILL_IMAGE@BILLING_MYMEN
WHERE BILL_CYCLE_CODE=:P_BILL_MONTH
AND (CUSTOMER_NUM||CONS_CHK_DIGIT,LOCATION_CODE) IN (
SELECT CUSTOMER_NUM,TAN_LOCATION_CODE FROM DUPLICATE_CONS_MYM
)
AND TO_CHAR(INVOICE_DUE_DATE,'yyyymmdd')>=(SELECT  TO_CHAR(SYSDATE,'yyyymmdd') FROM DUAL)
AND INVOICE_NUM IS NOT NULL

--MYM_LOCATION_CODE,TAN_LOCATION_CODE

COMMIT;



INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
(COMPANY_CODE, ACCOUNT_NUMBER, BILL_NUMBER, GENERATED_DATE, BILL_STATUS, BILL_DUE_DATE, 
BILLAMT_AFTERDUEDATE, BILLENDDATE_FORPAYMENT, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, 
NOTIFICATION_SENT_STATUS, CURRENT_PRINCIPLE, CURRENT_GOVT_DUTY, ARREAR_PRINCIPLE, ARREAR_GOVT_DUTY, 
LATE_PAYMENT_SURCHARGE, TOTAL_BILL_AMOUNT, LOCATION_CODE, BILL_MONTH, TARIFF, CUSTOMER_TYPE, 
CURRENT_SURCHARGE, ARREAR_SURCHARGE, ADJUSTED_PRINCIPLE, ADJUSTED_GOVT_DUTY,
 ADVANCE_AMOUNT, ADJ_ADV_GOVT_DUTY)
SELECT COMPANY_CODE, ACCOUNT_NUMBER, BILL_NUMBER, GENERATED_DATE, BILL_STATUS, BILL_DUE_DATE, 
BILLAMT_AFTERDUEDATE, BILLENDDATE_FORPAYMENT, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, 
NOTIFICATION_SENT_STATUS, CURRENT_PRINCIPLE, CURRENT_GOVT_DUTY, ARREAR_PRINCIPLE, ARREAR_GOVT_DUTY, 
LATE_PAYMENT_SURCHARGE, TOTAL_BILL_AMOUNT, LOCATION_CODE, BILL_MONTH, TARIFF, CUSTOMER_TYPE, 
CURRENT_SURCHARGE, ARREAR_SURCHARGE, ADJUSTED_PRINCIPLE, ADJUSTED_GOVT_DUTY,
 ADVANCE_AMOUNT, ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL_TNG_MY A
WHERE (ACCOUNT_NUMBER, BILL_NUMBER, LOCATION_CODE, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_NUMBER, LOCATION_CODE, BILL_MONTH FROM EPAY_UTILITY_BILL_TNG_MY
WHERE BILL_MONTH='202002'
MINUS
SELECT ACCOUNT_NUMBER, BILL_NUMBER, LOCATION_CODE, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202002');

COMMIT;

--*******************--

INSERT INTO EPAY_UTILITY_BILL_TNG_MY
SELECT COMPANY_CODE, ACCOUNT_NUMBER, BILL_NUMBER, GENERATED_DATE, BILL_STATUS, BILL_DUE_DATE, 
BILLAMT_AFTERDUEDATE, BILLENDDATE_FORPAYMENT, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, 
NOTIFICATION_SENT_STATUS, CURRENT_PRINCIPLE, CURRENT_GOVT_DUTY, ARREAR_PRINCIPLE, ARREAR_GOVT_DUTY, 
LATE_PAYMENT_SURCHARGE, TOTAL_BILL_AMOUNT, LOCATION_CODE, BILL_MONTH, TARIFF, CUSTOMER_TYPE, 
CURRENT_SURCHARGE, ARREAR_SURCHARGE, ADJUSTED_PRINCIPLE, ADJUSTED_GOVT_DUTY,
 ADVANCE_AMOUNT, ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL_TNG_MY A
WHERE (ACCOUNT_NUMBER,LOCATION_CODE, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER,LOCATION_CODE, BILL_MONTH FROM EPAY_UTILITY_BILL_TNG_MY
WHERE BILL_MONTH='201910'
MINUS
SELECT ACCOUNT_NUMBER,LOCATION_CODE,BILL_MONTH FROM EPAY_UTILITY_BILL_TNG_MY
WHERE BILL_MONTH='201910');


COMMIT;



INSERT INTO EPAY_UTILITY_BILL_TNG_MY
SELECT * FROM EPAY_UTILITY_BILL_GPR_X

AND  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
                                        WHERE CENTER_NAME LIKE '%PABNA%');
                                           
                          
COMMIT;


DELETE FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='201912'
AND ACCOUNT_NUMBER IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL_GPR_X)
AND BILL_STATUS<>'T'

COMMIT;


DELETE FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH='201902'
AND ACCOUNT_NUMBER IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL_GPR_X)


COMMIT;


DELETE FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201905'
AND ACCOUNT_NUMBER IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL_GPR_X)


COMMIT;


UPDATE customer_master_data_pdb@epay_robi
SET LOCATION_CODE='M3'
WHERE ACCOUNT_NO IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL_GPR_X)

COMMIT;


UPDATE epay_customer_master_data
SET LOCATION_CODE='M3'
WHERE ACCOUNT_NO IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL_GPR_X)

COMMIT;



----------------------------ROBI Bill Data Upload SQL--------------------

SELECT 
'INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL_GPR_X
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='''||LOC||''') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL_GPR_X
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||'''
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''')
and BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL_GPR_X
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='ROBI'))
ORDER BY LOC


SELECT 
'INSERT INTO EPAY_UTILITY_BILL
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,''N'' DATA_TRANS_LOG,''T'' DATA_TRANS_LOG1,''N'' DATA_TRANS_LOG2,''T'' DATA_TRANS_LOG3,''T'' DATA_TRANS_LOG4,''N'' DATA_TRANS_LOG5
 FROM EPAY_UTILITY_BILL_GPR_X
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA WHERE LOCATION_CODE='''||LOC||''') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL_GPR_X
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||'''
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''')
and BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL_GPR_X)
ORDER BY LOC



DELETE FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH='201812'
AND ACCOUNT_NUMBER IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL_GPR_X)

COMMIT;


SELECT 
'INSERT INTO EPAY_UTILITY_BILL@EPAY_SRL
SELECT 
CASE WHEN(SELECT COUNT(*) FROM EPAY_LOC_ONLINE_OPT_NESCO WHERE LOCATION_CODE='''||LOC||''')=0 THEN COMPANY_CODE ELSE ''NESCO'' END AS COMPANY_CODE,
ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,''N'' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL_GPR_X
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA@EPAY_SRL WHERE LOCATION_CODE='''||LOC||''') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL_GPR_X
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||'''
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''')
and BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL_GPR_X
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='SRL'
))
ORDER BY LOC





TRUNCATE TABLE EPAY_CUST_MASTER_DATA_GPR_X

INSERT INTO EPAY_CUST_MASTER_DATA_GPR_X
(COMPANY_CODE,ACCOUNT_NO,NAME,LOCATION_CODE,AREAR_CODE,ACTIVATION_DATE,STATUS,CREATED_ON ,DUMPING_FOR, CREATED_BY)
SELECT 'BPDB', CUSTOMER_NUM||CHECK_DIGIT,CUSTOMER_NAME,LOCATION_CODE,AREA_CODE,  TO_DATE(START_BILL_CYCLE,'rrrrmm'),
DECODE (CUSTOMER_STATUS_CODE,'C','A','S','A','I') STATUS,  SYSDATE,    'U',USER
FROM BC_CUSTOMERS@BILLING_TANG
where location_code='T1'
and substr(area_code,4)='06'


INSERT INTO EPAY_UTILITY_BILL_GPR_X
select * from EPAY_UTILITY_BILL_TNG_MY
where location_code='M3'
and bill_due_date='18-jun-2019'
and bill_month='201905'
