SELECT CUSTOMER_NUM,AREA_CODE,ADJUSTED_CONS FROM BC_BILL_IMAGE
WHERE ADJUSTED_CONS<'0'
AND LOCATION_CODE=:LOC
AND BILL_CYCLE_CODE=:BILL_CYCLE
ORDER BY ADJUSTED_CONS ASC

select * from BC_BILL_IMAGE
where cust_id=cid(66265455)
order by bill_cycle_code desc


SELECT c.CUSTOMER_NAME,bi.CUSTOMER_NUM||bi.CONS_CHK_DIGIT CUSTOMER_NUMber,bi.AREA_CODE,bi.WALKING_SEQUENCE page_no,bi.ADJUSTED_CONS,ca.ADDR_DESCR1||','||ca.ADDR_DESCR2||','||ca.ADDR_DESCR3 adress,ca.PHONE_NUM phone_number 
FROM BC_BILL_IMAGE bi,bc_customers c,BC_CUSTOMER_ADDR ca
WHERE bi.CUST_ID=c.CUST_ID
and bi.LOCATION_CODE = c.LOCATION_CODE
and bi.CUST_ID = ca.CUST_ID
and ca.ADDR_TYPE='B'
and bi.ADJUSTED_CONS<'0'
AND bi.LOCATION_CODE=:LOC
AND bi.BILL_CYCLE_CODE=:BILL_CYCLE
ORDER BY ADJUSTED_CONS ASC




SELECT A.CUSTOMER_NAME,A.CUSTOMER_NUMber,A.AREA_CODE,A.page_no,A.ADJUSTED_CONS,B.APR_2020,A.MAY_2020,A.adress,A.phone_number FROM (
SELECT c.CUSTOMER_NAME,bi.CUSTOMER_NUM||bi.CONS_CHK_DIGIT CUSTOMER_NUMber,bi.AREA_CODE,bi.WALKING_SEQUENCE page_no,bi.ADJUSTED_CONS,bi.cons_kwh_sr MAY_2020,ca.ADDR_DESCR1||','||ca.ADDR_DESCR2||','||ca.ADDR_DESCR3 adress,ca.PHONE_NUM phone_number 
FROM BC_BILL_IMAGE bi,bc_customers c,BC_CUSTOMER_ADDR ca
WHERE bi.CUST_ID=c.CUST_ID
and bi.LOCATION_CODE = c.LOCATION_CODE
and bi.CUST_ID = ca.CUST_ID
and ca.ADDR_TYPE='B'
and bi.ADJUSTED_CONS<'0'
AND bi.LOCATION_CODE=:LOC
AND bi.BILL_CYCLE_CODE=:BILL_CYCLE)A,(
SELECT CUSTOMER_NUM||CONS_CHK_DIGIT CUSTOMER_NUM,cons_kwh_sr APR_2020 FROM BC_BILL_IMAGE
WHERE BILL_CYCLE_CODE='202004'
AND CUSTOMER_NUM||CONS_CHK_DIGIT IN (
SELECT bi.CUSTOMER_NUM||bi.CONS_CHK_DIGIT 
FROM BC_BILL_IMAGE bi,bc_customers c,BC_CUSTOMER_ADDR ca
WHERE bi.CUST_ID=c.CUST_ID
and bi.LOCATION_CODE = c.LOCATION_CODE
and bi.CUST_ID = ca.CUST_ID
and ca.ADDR_TYPE='B'
and bi.ADJUSTED_CONS<'0'
AND bi.LOCATION_CODE=:LOC
AND bi.BILL_CYCLE_CODE=:BILL_CYCLE
))B
WHERE A.CUSTOMER_NUMBER=B.CUSTOMER_NUM