
SELECT COUNT(*) TOTAL_CONSUMER,SUM(NVL(ORG_PRN_AMOUNT,0)+NVL(VAT_AMOUNT,0)) TOTAL_AMOUNT FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO iN (
SELECT BATCH_NO FROM EPAY_PAYMENT_MST
WHERE ORG_BANK_CODE='01'
AND PAY_DATE BETWEEN :START_DATE AND :END_DATE
)




SELECT COUNT(*) TOTAL_CONSUMER,SUM(NVL(PRN_AMOUNT,0)+NVL(VAT_AMOUNT,0)) TOTAL_AMOUNT FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE@EPAY_SRL_24
WHERE ORG_CODE='WZPDCL'
AND BANK_CODE='01'
AND PAY_DATE BETWEEN :START_DATE AND :END_DATE
UNION
SELECT COUNT(*) TOTAL_CONSUMER,SUM(NVL(PRN_AMOUNT,0)+NVL(VAT_AMOUNT,0)) TOTAL_AMOUNT FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE_HIST@EPAY_SRL_24
WHERE ORG_CODE='WZPDCL'
AND BANK_CODE='01'
AND PAY_DATE BETWEEN :START_DATE AND :END_DATE