
    L5 MBP11356
    L4 MBP11355
    
    SELECT * FROM EPAY_PAYMENT_DTL@EPAY_SRL
    WHERE BATCH_nO='MBP11355'
    
    
    SELECT * FROM EPAY_UTILITY_BILL@EPAY_SRL
    WHERE LOCATION_CODE='L4'
    AND BILL_MONTH='201805'
    AND ACCOUNT_NUMBER IN (
    SELECT ACCOUNT_NUMBER FROM EPAY_PAYMENT_DTL@EPAY_SRL
    WHERE BATCH_nO='MBP11355'
    )
    
    
     SELECT ACCOUNT_NUMBER FROM EPAY_PAYMENT_DTL@EPAY_SRL
    WHERE BATCH_nO='MBP11355'
    MINUS    
    SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL@EPAY_SRL
    WHERE LOCATION_CODE='L4'
    AND BILL_MONTH='201805'
    AND ACCOUNT_NUMBER IN (
    SELECT ACCOUNT_NUMBER FROM EPAY_PAYMENT_DTL@EPAY_SRL
    WHERE BATCH_nO='MBP11355'
    )
    
    
INSERT INTO EPAY_UTILITY_BILL@EPAY_SRL
SELECT 'NESCO' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  0 BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 ,'N' DATA_TRANS_LOG
 FROM BC_BILL_IMAGE@BILLING_PAB
 WHERE BILL_CYCLE_CODE=:P_BILL_MONTH
AND CUSTOMER_NUM||CONS_CHK_DIGIT IN (
SELECT ACCOUNT_NUMBER FROM EPAY_PAYMENT_DTL@EPAY_SRL
    WHERE BATCH_nO='MBP11355'
    MINUS    
    SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL@EPAY_SRL
    WHERE LOCATION_CODE='L4'
    AND BILL_MONTH='201805'
    AND ACCOUNT_NUMBER IN (
    SELECT ACCOUNT_NUMBER FROM EPAY_PAYMENT_DTL@EPAY_SRL
    WHERE BATCH_nO='MBP11355'
    ))
AND LOCATION_CODE='L4'