





SELECT B_CENTER_NAME,B_TOT_CONS,A_CENTER_NAME,A_TOT_CONS,SUM(B_TOT_CONS-A_TOT_CONS) DIFFERENCE FROM (
SELECT  L.CENTER_NAME A_CENTER_NAME, COUNT(*) A_TOT_CONS FROM EPAY_UTILITY_BILL@NESCO_RAJ B,EPAY_LOCATION_MASTER@NESCO_RAJ L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND  B.BILL_MONTH ='201901'
GROUP BY L.CENTER_NAME
UNION
SELECT  'Total Consumer :', SUM(COUNT(*)) A_TOT_CONS FROM EPAY_UTILITY_BILL@NESCO_RAJ B,EPAY_LOCATION_MASTER@NESCO_RAJ L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND  B.BILL_MONTH ='201901'
GROUP BY L.CENTER_NAME)A,(
SELECT  L.CENTER_NAME B_CENTER_NAME, COUNT(*) B_TOT_CONS FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER@NESCO_RAJ L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND  B.BILL_MONTH ='201901'
GROUP BY L.CENTER_NAME
UNION
SELECT  'Total Consumer :', SUM(COUNT(*)) B_TOT_CONS FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER@NESCO_RAJ L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND  B.BILL_MONTH ='201901'
GROUP BY L.CENTER_NAME)B
WHERE A_CENTER_NAME=B_CENTER_NAME
GROUP BY A_CENTER_NAME,A_TOT_CONS,B_CENTER_NAME,B_TOT_CONS
ORDER BY 1



SELECT  L.CENTER_NAME A_CENTER_NAME, COUNT(*) A_TOT_CONS FROM EPAY_UTILITY_BILL@NESCO_RAJ B,EPAY_LOCATION_MASTER@NESCO_RAJ L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND  B.BILL_MONTH ='201901'
GROUP BY L.CENTER_NAME
UNION
SELECT  'Total Consumer :', SUM(COUNT(*)) A_TOT_CONS FROM EPAY_UTILITY_BILL@NESCO_RAJ B,EPAY_LOCATION_MASTER@NESCO_RAJ L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND  B.BILL_MONTH ='201901'
GROUP BY L.CENTER_NAME





SELECT  L.CENTER_NAME B_CENTER_NAME, COUNT(*) B_TOT_CONS FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER@NESCO_RAJ L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND  B.BILL_MONTH ='201901'
GROUP BY L.CENTER_NAME
UNION
SELECT  'Total Consumer :', SUM(COUNT(*)) B_TOT_CONS FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER@NESCO_RAJ L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND  B.BILL_MONTH ='201901'
GROUP BY L.CENTER_NAME








767323

SELECT  L.CENTER_NAME, COUNT(*) TOT_CONS FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND  B.BILL_MONTH ='201901'
AND L.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('5','6'))
GROUP BY L.CENTER_NAME
UNION
SELECT  'Total Consumer :', SUM(COUNT(*)) TOT_CONS FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND  B.BILL_MONTH ='201901'
AND L.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('5','6'))
GROUP BY L.CENTER_NAME