 RANGPUR     BILLING_RONG
 NAOGAON     BILLING_NAO
 DINAJPUR    BILLING_DIN
 BOGRA       BILLING_BOG
 RAJSHAHI    BILLING_RAJ
 PABNA       BILLING_PAB


           DELETE FROM EPAY_CUSTOMER_MASTER_DATA_SUP@NESCO_RAJ;

 =======================Change hobe Billing jekhane  Ache=============================

INSERT INTO EPAY_CUSTOMER_MASTER_DATA_SUP@NESCO_RAJ
(COMPANY_CODE,ACCOUNT_NO,NAME,LOCATION_CODE,AREAR_CODE,ACTIVATION_DATE,STATUS,CREATED_ON ,DUMPING_FOR, CREATED_BY)
SELECT 'NESCO', CUSTOMER_NUM||CHECK_DIGIT,CUSTOMER_NAME,LOCATION_CODE,AREA_CODE,  TO_DATE(START_BILL_CYCLE,'rrrrmm'),
DECODE (CUSTOMER_STATUS_CODE,'C','A','S','A','I') STATUS,  SYSDATE,    'U',USER
    FROM BC_CUSTOMERS@BILLING_RAJ
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MST_NESCO_RAJ);


COMMIT;

INSERT INTO EPAY_CUSTOMER_MASTER_DATA@NESCO_RAJ
SELECT * FROM EPAY_CUSTOMER_MASTER_DATA_SUP@NESCO_RAJ
WHERE (ACCOUNT_NO) IN (
SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA_SUP@NESCO_RAJ
MINUS
SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA@NESCO_RAJ)

COMMIT;


DELETE FROM EPAY_UTILITY_BILL_SUP@NESCO_RAJ
WHERE BILL_month=:P_Bill_Month;

COMMIT;


 ===================Change hobe Billing jekhane  Ache  =============================

INSERT INTO EPAY_UTILITY_BILL_SUP@NESCO_RAJ
SELECT 'NESCO' COMPANY_CODE, 
    CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
    INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
    INVOICE_DATE GENERATED_DATE, 
    'N' BILL_STATUS, 
    INVOICE_DUE_DATE BILL_DUE_DATE, 
    NULL BILLAMT_AFTERDUEDATE, 
    INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
    SYSDATE CREATED_ON    , 
    USER CREATED_BY   , 
    NULL  MODIFIED_ON , 
    NULL MODIFIED_BY, 
    'N' NOTIFICATION_SENT_STATUS, 
        (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0)+NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
        NVL(DEMAND_CHRG,0)+NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+
        NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
    NVL(CURRENT_VAT,0) CURRENT_GOVT_DUTY, 
    NVL(ARR_ADV_ADJ_PRN,0)  ARREAR_PRINCIPLE, 
    NVL(ARR_ADV_ADJ_VAT,0) ARREAR_GOVT_DUTY, 
    0 LATE_PAYMENT_SURCHARGE, 
    NVL(TOTAL_BILL,0) TOTAL_BILL_AMOUNT, 
    LOCATION_CODE, 
    BILL_CYCLE_CODE BILL_MONTH, 
    TARIFF, CUST_STATUS CUSTOMER_TYPE, 
    NVL(CURRENT_LPS,0) CURRENT_SURCHARGE, 
    NVL(ARR_ADV_ADJ_LPS,0) ARREAR_SURCHARGE, 
    NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
    NVL(ADJUSTED_VAT,0) ADJUSTED_GOVT_DUTY, 
    0 ADVANCE_AMOUNT,0 ADJ_ADV_GOVT_DUTY
               FROM  BC_BILL_IMAGE@BILLING_RAJ
WHERE BILL_CYCLE_CODE=:P_Bill_Month
AND INVOICE_NUM IS NOT NULL
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MST_NESCO_RAJ);


COMMIT;

DELETE FROM EPAY_UTILITY_BILL_SUP@NESCO_RAJ
WHERE ROWID IN (
SELECT ROWID FROM EPAY_UTILITY_BILL_SUP@NESCO_RAJ
MINUS
SELECT MAX(ROWID) FROM EPAY_UTILITY_BILL_SUP@NESCO_RAJ
GROUP BY ACCOUNT_NUMBER, BILL_NUMBER, LOCATION_CODE,BILL_MONTH);


INSERT INTO EPAY_UTILITY_BILL@NESCO_RAJ
(COMPANY_CODE, ACCOUNT_NUMBER, BILL_NUMBER, GENERATED_DATE, BILL_STATUS, BILL_DUE_DATE, 
BILLAMT_AFTERDUEDATE, BILLENDDATE_FORPAYMENT, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, 
NOTIFICATION_SENT_STATUS, CURRENT_PRINCIPLE, CURRENT_GOVT_DUTY, ARREAR_PRINCIPLE, ARREAR_GOVT_DUTY, 
LATE_PAYMENT_SURCHARGE, TOTAL_BILL_AMOUNT, LOCATION_CODE, BILL_MONTH, TARIFF, CUSTOMER_TYPE, 
CURRENT_SURCHARGE, ARREAR_SURCHARGE, ADJUSTED_PRINCIPLE, ADJUSTED_GOVT_DUTY,
 ADVANCE_AMOUNT, ADJ_ADV_GOVT_DUTY,DATA_TRANS_LOG)
SELECT COMPANY_CODE, ACCOUNT_NUMBER, BILL_NUMBER, GENERATED_DATE, BILL_STATUS, BILL_DUE_DATE, 
BILLAMT_AFTERDUEDATE, BILLENDDATE_FORPAYMENT, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, 
NOTIFICATION_SENT_STATUS, CURRENT_PRINCIPLE, CURRENT_GOVT_DUTY, ARREAR_PRINCIPLE, ARREAR_GOVT_DUTY, 
LATE_PAYMENT_SURCHARGE, TOTAL_BILL_AMOUNT, LOCATION_CODE, BILL_MONTH, TARIFF, CUSTOMER_TYPE, 
CURRENT_SURCHARGE, ARREAR_SURCHARGE, ADJUSTED_PRINCIPLE, ADJUSTED_GOVT_DUTY,
 ADVANCE_AMOUNT, ADJ_ADV_GOVT_DUTY,'N' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL_SUP@NESCO_RAJ A
WHERE (ACCOUNT_NUMBER, BILL_NUMBER, LOCATION_CODE, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_NUMBER, LOCATION_CODE, BILL_MONTH FROM EPAY_UTILITY_BILL_SUP@NESCO_RAJ
WHERE BILL_MONTH='201904'
MINUS
SELECT ACCOUNT_NUMBER, BILL_NUMBER, LOCATION_CODE, BILL_MONTH FROM EPAY_UTILITY_BILL@NESCO_RAJ
WHERE BILL_MONTH='201904');

*******************

INSERT INTO EPAY_UTILITY_BILL@NESCO_RAJ
SELECT COMPANY_CODE, ACCOUNT_NUMBER, BILL_NUMBER, GENERATED_DATE, BILL_STATUS, BILL_DUE_DATE, 
BILLAMT_AFTERDUEDATE, BILLENDDATE_FORPAYMENT, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, 
NOTIFICATION_SENT_STATUS, CURRENT_PRINCIPLE, CURRENT_GOVT_DUTY, ARREAR_PRINCIPLE, ARREAR_GOVT_DUTY, 
LATE_PAYMENT_SURCHARGE, TOTAL_BILL_AMOUNT, LOCATION_CODE, BILL_MONTH, TARIFF, CUSTOMER_TYPE, 
CURRENT_SURCHARGE, ARREAR_SURCHARGE, ADJUSTED_PRINCIPLE, ADJUSTED_GOVT_DUTY,
 ADVANCE_AMOUNT, ADJ_ADV_GOVT_DUTY,'N' status FROM EPAY_UTILITY_BILL_SUP@NESCO_RAJ A
WHERE (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL_SUP@NESCO_RAJ
WHERE BILL_MONTH='201904'
MINUS
SELECT ACCOUNT_NUMBER,  BILL_MONTH FROM EPAY_UTILITY_BILL@NESCO_RAJ
WHERE BILL_MONTH='201904');


COMMIT;