
----------tot payment data trns chk srl to nesco billing

select a.STATUS,a.pay_date,a.TOT_CONS tot_srl,b.COLLECTION_DATE,b.TOT_CONS tot_billing,sum(a.TOT_CONS-b.TOT_CONS) tot_diff from (
select pay_date,count(*) TOT_CONS,decode(M.STATUS,'T','Transfer','N','UnTransfer') STATUS from epay_payment_mst@desco_nesco m,epay_payment_dtl@desco_nesco d
where m.batch_no=d.batch_no
and org_bank_code='94'
and org_code='NESCO'
AND TO_CHAR(PAY_DATE,'RRRRMM')='202107'
--(SELECT TO_CHAR (ADD_MONTHS (SYSDATE,0), 'RRRRMM')   FROM DUAL)
and org_br_code in (
select location_code from EPAY.EPAY_NESCO_LOC_MAP@DESCO_NESCO
)
group by pay_date,decode(M.STATUS,'T','Transfer','N','UnTransfer'))a,(
--order by 1 desc
select COLLECTION_DATE,COUNT(*) TOT_CONS from NEPAY.SRL_BILL_COLLECTION@BILLING_DESCO
WHERE TO_CHAR(COLLECTION_DATE,'RRRRMM')='202107'
AND BANK_CODE='BK'
GROUP BY COLLECTION_DATE)b
where a.pay_date=b.COLLECTION_DATE(+)
group by a.STATUS,a.pay_date,a.TOT_CONS,b.COLLECTION_DATE,b.TOT_CONS
ORDER BY 2 DESC

----bill data check

209210

SELECT COUNT(*)
FROM BILL_CALCULATION@BILLING_DESCO_NESCO_NEW B,
NEW_CONSUMER_INFORMATION@BILLING_DESCO_NESCO_NEW C,
BILL_COLLECTION@BILLING_DESCO_NESCO_NEW BC
WHERE B.ACCOUNT_NO=C.ACCOUNT_NO
AND B.BILL_NO=BC.BILL_NO
AND YEAR=SUBSTR(:P_Bill_Month,1,4)
AND MONTH=TO_NUMBER(SUBSTR(:P_Bill_Month,5,6))
AND B.IS_PDB='0'
AND BC.SRL_STATUS='0'
AND BC.IS_PDB='0'


SELECT BILL_MONTH,COUNT(*) FROM EPAY_UTILITY_bILL@desco_nesco
WHERE COMPANY_CODE='NESCO'
AND BILL_MONTH>=(TO_CHAR(ADD_MONTHS(SYSDATE,-1),'rrrrmm'))
GROUP BY BILL_MONTH
ORDER BY 1 DESC

select 767092-503063 from dual


SELECT COUNT(*)
FROM BILL_CALCULATION@BILLING_DESCO_NESCO_NEW B,
NEW_CONSUMER_INFORMATION@BILLING_DESCO_NESCO_NEW C,
BILL_COLLECTION@BILLING_DESCO_NESCO_NEW BC
WHERE B.ACCOUNT_NO=C.ACCOUNT_NO
AND B.BILL_NO=BC.BILL_NO
AND YEAR=SUBSTR(:P_Bill_Month,1,4)
AND MONTH=TO_NUMBER(SUBSTR(:P_Bill_Month,5,6))
AND B.IS_PDB='0'
AND BC.SRL_STATUS='0'
AND BC.IS_PDB='0'
and DIVISION_ID='12'




SELECT b.*,c.DIVISION_ID ,bc.DUE_DATE,bc.LPC,BC.TOTAL_PAYABLE_AMOUNT,bc.c_tariff
FROM BILL_CALCULATION@BILLING_DESCO_NESCO_NEW B,
NEW_CONSUMER_INFORMATION@BILLING_DESCO_NESCO_NEW C,
BILL_COLLECTION@BILLING_DESCO_NESCO_NEW BC
WHERE B.ACCOUNT_NO=C.ACCOUNT_NO
AND B.BILL_NO=BC.BILL_NO
AND YEAR=SUBSTR(:P_Bill_Month,1,4)
AND MONTH=TO_NUMBER(SUBSTR(:P_Bill_Month,5,6))
--AND DIVISION_ID=LOC_LIST.LOCATION_CODE
--AND B.SRL_STATUS='0'
AND B.IS_PDB='0'
AND BC.SRL_STATUS='0'
AND BC.IS_PDB='0'


select COUNT(*) from epay.epay_utility_Bill@DESCO_NESCO
where bill_month='202012'
and company_code='NESCO'
and location_code in (
select location_code from EPAY.EPAY_NESCO_LOC_MAP@DESCO_NESCO
)

--1592270  202010

--1381470  202009

SELECT * FROM DESCOPST_BATCH_CONTROL
where data_type='BILLINFO'
ORDER BY RUN_DATE DESC

select location_code,nc,sc,(nc-sc) diff from (
select location_code,count(*) sc from epay_customer_master_data@desco_nesco
where  company_code='NESCO'
and LOCATION_CODE in (select LOCATION_CODE  from EPAY_NESCO_LOC_MAP@DESCO_NESCO)
group by location_code)a,(
select DIVISION_ID,count(*) nc from NEW_CONSUMER_INFORMATION@BILLING_DESCO_NESCO_NEW
where DIVISION_ID in (select LOCATION_CODE  from EPAY_NESCO_LOC_MAP@DESCO_NESCO)
group by DIVISION_ID)b
where a.LOCATION_CODE=b.DIVISION_ID
and a.sc <> b.nc
order by 4 desc


select 
'delete DESCOPST_ERR_LOG
where data_type=''CUSTINFO''
and location_code='''||loc||''''||';'||chr(10)||chr(10)||'COMMIT;'||chr(10) from(
select LOCATION_CODE loc from EPAY_NESCO_LOC_MAP@DESCO_NESCO
)



select * from DESCOPST_RUN_LOG
where ORG_CODE='NESCO'
and trunc(run_date)=trunc(sysdate)
ORDER BY RUN_DATE DESC

select * from DESCOPST_BATCH_CONTROL
where ORG_CODE='NESCO'
and trunc(run_date)=trunc(sysdate)
ORDER BY RUN_DATE DESC

select * from DESCOPST_ERR_LOG
where ORG_CODE='NESCO'
and data_type='BILLINFO'
and trunc(run_date)=trunc(sysdate)
ORDER BY RUN_DATE DESC


select b.DIVISION_ID,nes,srl,sum(nes-srl) diff from (
select location_code,COUNT(*) srl from epay.epay_customer_master_data@DESCO_NESCO
where  company_code='NESCO'
and location_code in ('91','92','93','94','95','96','97','98')
group by location_code)a,(
select DIVISION_ID,count(*) nes from new_consumer_information@BILLING_DESCO_NESCO_NEW
where DIVISION_ID in (
'91','92','93','94','95','96','97','98'
)
group by DIVISION_ID
order by 1)b
where a.LOCATION_CODE(+)=b.DIVISION_ID
group by b.DIVISION_ID,srl,nes
order by 1


SELECT *
FROM BILL_CALCULATION@BILLING_DESCO_NESCO_NEW B,
NEW_CONSUMER_INFORMATION@BILLING_DESCO_NESCO_NEW C,
BILL_COLLECTION@BILLING_DESCO_NESCO_NEW BC
WHERE B.ACCOUNT_NO=C.ACCOUNT_NO
AND B.BILL_NO=BC.BILL_NO
AND YEAR=SUBSTR(:P_Bill_Month,1,4)
AND MONTH=TO_NUMBER(SUBSTR(:P_Bill_Month,5,6))
--AND B.IS_PDB='0'
--AND BC.SRL_STATUS='0'
--AND BC.IS_PDB='0'
--and B.ACCOUNT_NO='28001197'
AND DIVISION_ID='80'

group by DIVISION_ID
order by 1

select * from NEPAY.SRL_BILL_COLLECTION@BILLING_DESCO
where account_No='28001197'

----------------MANUAL DATA UPLOAD
 
--INSERT INTO EPAY.EPAY_UTILITY_BILL@DESCO_NESCO


INSERT INTO EPAY.EPAY_UTILITY_BILL@DESCO_NESCO
 select 'NESCO',CUR_BILL.ACCOUNT_NO,CUR_BILL.BILL_NO,TO_DATE(TO_CHAR(CUR_BILL.ISSUE_DATE,'MM/DD/RRRR'),'MM/DD/RRRR'),'N',TO_DATE(TO_CHAR(CUR_BILL.DUE_DATE,'MM/DD/RRRR'),'MM/DD/RRRR'),0,
    TO_DATE(TO_CHAR(CUR_BILL.DUE_DATE,'MM/DD/RRRR'),'MM/DD/RRRR'),SYSDATE,USER,NULL,NULL,'N',/*CUR_BILL.NET_AMOUNT*/NVL(CUR_BILL.TOTAL_PAYABLE_AMOUNT,0)-NVL(CUR_BILL.VAT_TOTAL,0),
    NVL(CUR_BILL.VAT_TOTAL,0),0,0,0,NVL(CUR_BILL.TOTAL_PAYABLE_AMOUNT,0),CUR_BILL.DIVISION_ID,CUR_BILL.YEAR||LPAD(CUR_BILL.MONTH,2,'0'),
    CUR_BILL.C_TARIFF,NULL,NVL(CUR_BILL.LPC,0),0,0,0,0,0,'N' from (
 SELECT b.*,c.DIVISION_ID ,bc.DUE_DATE,bc.LPC,BC.TOTAL_PAYABLE_AMOUNT,bc.c_tariff
                                                    FROM BILL_CALCULATION@BILLING_DESCO_NESCO_NEW B,
                                                    NEW_CONSUMER_INFORMATION@BILLING_DESCO_NESCO_NEW C,
                                                    BILL_COLLECTION@BILLING_DESCO_NESCO_NEW BC
                                            WHERE B.ACCOUNT_NO=C.ACCOUNT_NO
                                            AND B.BILL_NO=BC.BILL_NO
                                            AND YEAR=SUBSTR(:P_Bill_Month,1,4)
                                            AND MONTH=TO_NUMBER(SUBSTR(:P_Bill_Month,5,6))
                                            --AND DIVISION_ID=LOC_LIST.LOCATION_CODE
                                            --AND B.SRL_STATUS='0'
                                            AND B.IS_PDB='0'
                                            AND BC.SRL_STATUS='0'
                                            AND BC.IS_PDB='0'
                                           and B.ACCOUNT_NO='28001197') CUR_BILL


     INSERT INTO EPAY.EPAY_UTILITY_BILL@DESCO_NESCO
    (COMPANY_CODE, ACCOUNT_NUMBER, BILL_NUMBER, GENERATED_DATE, BILL_STATUS, BILL_DUE_DATE, BILLAMT_AFTERDUEDATE,
    BILLENDDATE_FORPAYMENT, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, NOTIFICATION_SENT_STATUS, CURRENT_PRINCIPLE,
    CURRENT_GOVT_DUTY, ARREAR_PRINCIPLE, ARREAR_GOVT_DUTY, LATE_PAYMENT_SURCHARGE, TOTAL_BILL_AMOUNT, LOCATION_CODE, BILL_MONTH, 
    TARIFF, CUSTOMER_TYPE, CURRENT_SURCHARGE, ARREAR_SURCHARGE, ADJUSTED_PRINCIPLE, ADJUSTED_GOVT_DUTY, ADVANCE_AMOUNT, ADJ_ADV_GOVT_DUTY, DATA_TRANS_LOG) VALUES
    (vchCompID,CUR_BILL.ACCOUNT_NO,CUR_BILL.BILL_NO,TO_DATE(TO_CHAR(CUR_BILL.ISSUE_DATE,'MM/DD/RRRR'),'MM/DD/RRRR'),'N',TO_DATE(TO_CHAR(CUR_BILL.DUE_DATE,'MM/DD/RRRR'),'MM/DD/RRRR'),0,
    TO_DATE(TO_CHAR(CUR_BILL.DUE_DATE,'MM/DD/RRRR'),'MM/DD/RRRR'),SYSDATE,USER,NULL,NULL,'N',/*CUR_BILL.NET_AMOUNT*/NVL(CUR_BILL.TOTAL_PAYABLE_AMOUNT,0)-NVL(CUR_BILL.VAT_TOTAL,0),
    NVL(CUR_BILL.VAT_TOTAL,0),0,0,0,NVL(CUR_BILL.TOTAL_PAYABLE_AMOUNT,0),CUR_BILL.DIVISION_ID,CUR_BILL.YEAR||LPAD(CUR_BILL.MONTH,2,'0'),
    CUR_BILL.C_TARIFF,NULL,NVL(CUR_BILL.LPC,0),0,0,0,0,0,'N');