
SELECT L.CENTER_NAME,COUNT(*) FROM EPAY_CUSTOMER_MASTER_DATA A,EPAY_LOCATION_MASTER@EPAY_SRL L
WHERE A.LOCATION_CODE=L.LOCATION_CODE
GROUP BY L.CENTER_NAME



SELECT COUNT(*) FROM EPAY_UTILITY_BILL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_SRL_DCC
 WHERE CENTER_NAME IN ('BOGRA','RAJSHAHI','RANGPUR','DINAJPUR','NAOGAON'))
 AND BILL_MONTH='201801'
 
 
 SELECT U.BILL_MONTH, L.CENTER_NAME,COUNT(*) FROM EPAY_UTILITY_BILL U,EPAY_LOCATION_MASTER@EPAY_SRL_DCC L
 WHERE U.LOCATION_CODE=L.LOCATION_CODE
 AND U.LOCATION_CODE  IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_SRL_DCC
 WHERE CENTER_NAME IN ('BOGRA','RAJSHAHI','RANGPUR','DINAJPUR','NAOGAON','PABNA'))
 --AND U.BILL_MONTH='201801'
 GROUP BY U.BILL_MONTH,L.CENTER_NAME
 
 
  SELECT U.BILL_MONTH, L.CENTER_NAME,COUNT(*) FROM EPAY_UTILITY_BILL U,EPAY_LOCATION_MASTER@EPAY_SRL_DCC L
 WHERE U.LOCATION_CODE=L.LOCATION_CODE
 AND U.LOCATION_CODE  IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_SRL_DCC
 WHERE CENTER_NAME IN ('BOGRA','RAJSHAHI','RANGPUR','DINAJPUR','NAOGAON','PABNA'))
 --AND U.BILL_MONTH='201801'
 GROUP BY U.BILL_MONTH,L.CENTER_NAME
 
 ------OK----
  SELECT U.BILL_MONTH, L.CENTER_NAME,COUNT(*) FROM EPAY_UTILITY_BILL U,EPAY_LOCATION_MASTER@EPAY_SRL_DCC L
 WHERE U.LOCATION_CODE=L.LOCATION_CODE
 AND U.LOCATION_CODE  IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_SRL_DCC
 WHERE CENTER_NAME ='BOGRA')
 --AND U.BILL_MONTH='201801'
 GROUP BY U.BILL_MONTH,L.CENTER_NAME
 order by 1 
 
  ------OK----
  SELECT U.BILL_MONTH, L.CENTER_NAME,COUNT(*) FROM EPAY_UTILITY_BILL U,EPAY_LOCATION_MASTER@EPAY_SRL_DCC L
 WHERE U.LOCATION_CODE=L.LOCATION_CODE
 AND U.LOCATION_CODE  IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_SRL_DCC
 WHERE CENTER_NAME ='RAJSHAHI')
 --AND U.BILL_MONTH='201801'
 GROUP BY U.BILL_MONTH,L.CENTER_NAME
 order by 1 
 
  SELECT U.BILL_MONTH, L.CENTER_NAME,COUNT(*) FROM EPAY_UTILITY_BILL U,EPAY_LOCATION_MASTER@EPAY_SRL_DCC L
 WHERE U.LOCATION_CODE=L.LOCATION_CODE
 AND U.LOCATION_CODE  IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_SRL_DCC
 WHERE CENTER_NAME ='RANGPUR')
 --AND U.BILL_MONTH='201801'
 GROUP BY U.BILL_MONTH,L.CENTER_NAME
 order by 1 
 
  SELECT U.BILL_MONTH, L.CENTER_NAME,COUNT(*) FROM EPAY_UTILITY_BILL U,EPAY_LOCATION_MASTER@EPAY_SRL_DCC L
 WHERE U.LOCATION_CODE=L.LOCATION_CODE
 AND U.LOCATION_CODE  IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_SRL_DCC
 WHERE CENTER_NAME ='DINAJPUR')
 --AND U.BILL_MONTH='201801'
 GROUP BY U.BILL_MONTH,L.CENTER_NAME
  order by 1 
 
 ------OK---- 
   SELECT U.BILL_MONTH, L.CENTER_NAME,COUNT(*) FROM EPAY_UTILITY_BILL U,EPAY_LOCATION_MASTER@EPAY_SRL_DCC L
 WHERE U.LOCATION_CODE=L.LOCATION_CODE
 AND U.LOCATION_CODE  IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_SRL_DCC
 WHERE CENTER_NAME ='NAOGAON')
 --AND U.BILL_MONTH='201801'
 GROUP BY U.BILL_MONTH,L.CENTER_NAME
 order by 1 
 
 
 SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER@EPAY_SRL_DCC
 WHERE CENTER_NAME IN ('BOGRA','RAJSHAHI','RANGPUR','DINAJPUR','NAOGAON','PABNA')
 
 ('BOGRA','RAJSHAHI','RANGPUR','DINAJPUR','NAOGAON')
 
SELECT COUNT(*) FROM EPAY_UTILITY_BILL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
WHERE CENTER_NAME IN ('BOGRA','RAJSHAHI','RANGPUR','DINAJPUR','NAOGAON','PABNA'))
AND BILL_MONTH <>'201802'
 
10249801  PDB
5423723

select 10249801-5423723 from dual
 
SELECT COUNT(*) FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
WHERE CENTER_NAME IN ('BOGRA','RAJSHAHI','RANGPUR','DINAJPUR','NAOGAON','PABNA'))
AND BILL_MONTH <>'201802'