


SELECT DFN_GP_RECONCILED_MISMATCH (:P_PAY_DATE ,:P_LOCATION_CODE,:P_BANK_CODE) FROM DUAL


SELECT * FROM EPAY_PAYMENT_DTL_ONLINE
WHERE PAY_DATE='05-MAR-2020'
AND ORG_BR_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE BILLING_DBLINK='BILLING_BOG')


SELECT PAY_BANK_CODE,ORG_BR_CODE,COUNT(*) FROM EPAY_PAYMENT_DTL_ONLINE
WHERE PAY_DATE='05-MAR-2020'
AND ORG_BR_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE BILLING_DBLINK='BILLING_BOG')
GROUP BY PAY_BANK_CODE,ORG_BR_CODE


SELECT PAY_BANK_CODE,ORG_BR_CODE,COUNT(*) FROM EPAY_PAYMENT_DTL_ONLINE_HIST
WHERE PAY_DATE='05-MAR-2020'
AND ORG_BR_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE BILLING_DBLINK='BILLING_BOG')
--AND ORG_BR_CODE='Q4'
GROUP BY PAY_BANK_CODE,ORG_BR_CODE

SELECT * FROM EPAY_PAYMENT_MST
WHERE PAY_DATE='05-MAR-2020'
AND ORG_BR_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE BILLING_DBLINK='BILLING_BOG')
AND STATUS<>'T'



SELECT SUM(NVL(PRN_AMOUNT,0)+NVL(VAT_AMOUNT,0)) TOTAL FROM EPAY_PAYMENT_DTL_ONLINE
WHERE PAY_DATE='19-AUG-2019'
AND ORG_BR_CODE='P2'




SELECT 'SELECT DFN_GP_RECONCILED_MISMATCH ('''||P_PAY_DATE||''','''||P_LOCATION_CODE||''','''||P_BANK_CODE||''') FROM DUAL' ||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY" 
FROM(SELECT PAY_DATE P_PAY_DATE,ORG_BR_CODE P_LOCATION_CODE,PAY_BANK_CODE P_BANK_CODE FROM  EPAY_PAYMENT_DTL_ONLINE
WHERE PAY_DATE='05-MAR-2020'
AND ORG_BR_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE BILLING_DBLINK='BILLING_BOG')
GROUP BY PAY_DATE,ORG_BR_CODE,PAY_BANK_CODE
)





SELECT * FROM EPAY_PAYMENT_DTL_ONLINE
WHERE ORG_BR_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
WHERE CENTER_NAME='RAJSHAHI'
)
AND PAY_DATE='19-AUG-2019'











SELECT * FROM EPAY_PAYMENT_DTL_ONLINE
WHERE PAY_DATE='09-AUG-2019'

AND ORG_BR_CODE='U3'

AND ORG_BR_CODE<>'V4'

SELECT PAY_DATE,ORG_BR_CODE FROM EPAY_PAYMENT_DTL_ONLINE
WHERE PAY_DATE='07-AUG-2019'
AND ORG_BR_CODE<>'V4'
GROUP BY PAY_DATE,ORG_BR_CODE


SELECT * FROM EPAY_PAYMENT_DTL_ONLINE
WHERE PAY_DATE='19-AUG-2019'
AND ORG_BR_CODE='V3'



SELECT * FROM EPAY_PAYMENT_DTL_ONLINE_HIST
WHERE PAY_DATE='19-AUG-2019'
AND ORG_BR_CODE='U1'

SELECT * FROM EPAY_PAYMENT_DTL_ONLINE
WHERE ORG_BR_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
WHERE CENTER_NAME='DINAJPUR'
)



SELECT * FROM EPAY_PAYMENT_DTL_ONLINE_HIST
WHERE ORG_BR_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
WHERE CENTER_NAME='DINAJPUR'
)
AND PAY_DATE='09-AUG-2019'


SELECT * FROM EPAY_PAYMENT_MST
WHERE PAY_DATE='09-AUG-2019'
AND ORG_BR_CODE='Q2'


ORG_BR_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER
WHERE CENTER_NAME='DINAJPUR'
)
AND STATUS<>'T'
AND ORG_BANK_CODE='96'