
SELECT * FROM EPAY_PAYMENT_DTL_ONLINE
WHERE PAY_DATE='17-MAR-2019'
AND BANK_CODE='96'


SELECT * FROM EPAY_PAYMENT_DTL_ONLINE_HIST
WHERE PAY_DATE='17-MAR-2019'
AND BANK_CODE='96'
AND ORG_BR_CODE='Q2'


SELECT * FROM EPAY_PAYMENT_MST
WHERE PAY_DATE='17-MAR-2019'
AND ORG_BANK_CODE='96'
AND ORG_BR_CODE='Q2'