

SELECT 
'INSERT INTO EPAY_UTILITY_BILL@EPAY_SRL
SELECT 
CASE WHEN(SELECT COUNT(*) FROM EPAY_LOC_ONLINE_OPT_NESCO WHERE LOCATION_CODE='''||LOC||''')=0 THEN COMPANY_CODE ELSE ''NESCO'' END AS COMPANY_CODE,
ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,''N'' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA@EPAY_SRL WHERE LOCATION_CODE='''||LOC||''') 
AND DATA_TRANS_LOG3=''N''
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH <>'''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||'''
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH <>'''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''')
and BILL_MONTH <>'''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('6'))
AND DATA_TRANS_LOG3='N')
ORDER BY LOC



SELECT 
'UPDATE EPAY_UTILITY_BILL
SET DATA_TRANS_LOG3=''T''
WHERE DATA_TRANS_LOG3=''N''
AND  BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE ZONE_CODE IN ('2','3','4','7'))
AND DATA_TRANS_LOG3='N')
ORDER BY LOC