
SELECT *  FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO IN (
SELECT BATCH_NO FROM EPAY_PAYMENT_MST
WHERE ORG_BANK_CODE='96'
AND PAY_DATE='29-MAY-2019'
AND STATUS='N'
AND ORG_BR_CODE ='Q2'
)

SELECT *  FROM EPAY_PAYMENT_MST
WHERE ORG_BANK_CODE='96'
AND PAY_DATE='29-MAY-2019'
AND STATUS='N'
AND ORG_BR_CODE ='Q2'


SELECT * FROM EPAY_PAYMENT_DTL_ONLINE
WHERE ORG_BR_CODE ='Q2'
AND PAY_DATE='29-MAY-2019'

INSERT INTO EPAY_PAYMENT_DTL_ONLINE
SELECT * FROM EPAY_PAYMENT_DTL_ONLINE_HIST
WHERE ORG_BR_CODE ='Q2'
AND PAY_DATE='29-MAY-2019'

SELECT *  FROM EPAY_PAYMENT_DTL_ONLINE_HIST
WHERE ORG_BR_CODE ='Q2'
AND PAY_DATE='29-MAY-2019'