
SELECT B.BANK_NAME,TO_CHAR(RECEIPT_DATE,'Mon') MONTH,COUNT(1) TRANSACTION_COUNT,SUM(NVL(RECEIPT_AMT,0)+NVL(VAT_AMT,0)) TOTAL_AMOUNT 
FROM BC_BANKS@BILLING_pab B,BC_RECEIPT_HDR@BILLING_pab P
WHERE B.BANK_CODE=P.BANK_CODE
AND TO_CHAR(RECEIPT_DATE,'RRRRMM') BETWEEN '201804' AND '201806'
AND RECEIPT_TYPE_CODE='REC'
GROUP BY TO_CHAR(RECEIPT_DATE,'Mon'),B.BANK_NAME
ORDER BY 1