
DELETE EPAY_UTILITY_BILL_GPR_X;

INSERT INTO EPAY_UTILITY_BILL_GPR_X
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 
 FROM BC_BILL_IMAGE@BILLING_CTG
 WHERE INVOICE_NUM IN (
SELECT SUBSTR(BILL_NUMBER,1,8) A FROM VW_EPAY_PAYMENT_MST_DTL
WHERE STATUS in ('M','E')
AND TO_CHAR(PAY_DATE,'RRRRMM')=:PAY_MONTH
AND  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER  WHERE CENTER_NAME LIKE '%CHITTAGONG%'   )
MINUS
SELECT SUBSTR(BILL_NUMBER,1,8) A  FROM EPAY_UTILITY_BILL
WHERE  LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER  WHERE CENTER_NAME LIKE '%CHITTAGONG%'   )
);

COMMIT;

DELETE FROM EPAY_UTILITY_BILL
WHERE (ACCOUNT_NUMBER) IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL_GPR_X
);


DELETE FROM EPAY_CUSTOMER_MASTER_DATA
WHERE ACCOUNT_NO IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL_GPR_X
)

COMMIT;
    
INSERT INTO EPAY_CUSTOMER_MASTER_DATA
(COMPANY_CODE,ACCOUNT_NO,NAME,LOCATION_CODE,AREAR_CODE,ACTIVATION_DATE,STATUS,CREATED_ON ,DUMPING_FOR, CREATED_BY)
SELECT 'BPDB', CUSTOMER_NUM||CHECK_DIGIT,CUSTOMER_NAME,LOCATION_CODE,AREA_CODE,  TO_DATE(START_BILL_CYCLE,'rrrrmm'),
DECODE (CUSTOMER_STATUS_CODE,'C','A','S','A','I') STATUS,  SYSDATE,    'U','ROBIBPDB' 
FROM BC_CUSTOMERS@BILLING_CTG
WHERE CUSTOMER_NUM IN (SELECT SUBSTR(ACCOUNT_NUMBER,1,7) FROM EPAY_UTILITY_BILL_GPR_X);

COMMIT;


INSERT INTO EPAY_UTILITY_BILL
SELECT A.*,'T' AS DATA_TRANS_LOG FROM EPAY_UTILITY_BILL_GPR_X A


COMMIT;