

SELECT SYS_CONTEXT ('USERENV','SESSION_USER')   FROM DUAL;
   
   
   
SELECT SYS_CONTEXT('USERENV','TERMINAL') FROM dual;

SELECT SYS_CONTEXT('USERENV','HOST') FROM dual;

SELECT SYS_CONTEXT('USERENV','IP_ADDRESS') FROM dual;

SELECT SYS_CONTEXT('USERENV','SERVER_HOST') FROM dual;

