
SELECT * FROM EPAY_BANKS
--WHERE BANK_CODE='24'
ORDER BY 2

SELECT * FROM EPAY_BANK_BRANCHES
WHERE BANK_CODE='24'
AND LOCATION_CODE='M2'

SELECT * FROM EPAY_PAYMENT_MST
WHERE PAY_DATE BETWEEN '01-MAR-2019' AND '31-MAR-2019'
AND PAY_BANK_CODE='58'
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='JAMALPUR')
ORDER BY PAY_DATE DESC


SELECT * FROM EPAY_PAYMENT_MST@EPAY_SRL
WHERE PAY_DATE BETWEEN '01-MAR-2019' AND '31-MAR-2019'
AND ORG_BANK_CODE='58'
AND ORG_BR_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='JAMALPUR')
ORDER BY PAY_DATE DESC


SELECT * FROM EPAY_PAYMENT_MST_INT
WHERE  PAY_DATE BETWEEN '01-MAR-2019' AND '31-MAR-2019'
AND PAY_BANK_CODE='24'
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='MYMENSING')
ORDER BY PAY_DATE DESC

SELECT * FROM EPAY_PAYMENT_MST_INT@EPAYMENT
WHERE  PAY_DATE BETWEEN '01-MAR-2019' AND '31-MAR-2019'
AND PAY_BANK_CODE='24'
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='MYMENSING')
ORDER BY PAY_DATE DESC

SELECT * FROM VW_BNK_DAYEND_COM_BTCH_NOT_GEN@EPAY_SRL


SELECT * FROM VW_BNK_DAYEND_UNCOMPLITE@EPAY_SRL

