

SELECT * FROM EPAY.EPAY_PAYMENT_MST
WHERE PAY_DATE='15-APR-2022'
AND PAY_BANK_CODE='97'

SELECT * FROM EPAY.EPAY_RECEIPT_BATCH_HDR_PDB
WHERE RECEIPT_DATE='15-APR-2022'
AND BANK_CODE='97'


SELECT A.BATCH_NO,A.LOCATION_CODE,PAY_BANK_CODE,PAY_BRANCH_CODE,A.CREATED_ON,B.TRANS_DATE FROM (
SELECT BATCH_NO,LOCATION_CODE,CREATED_ON ,PAY_BANK_CODE,PAY_BRANCH_CODE FROM EPAY.EPAY_PAYMENT_MST
WHERE PAY_DATE='15-APR-2022'
AND PAY_BANK_CODE='94')A,(
SELECT BATCH_NUM_EPAY,LOCATION_CODE,BANK_CODE,BRANCH_CODE,TRUNC(CREATED_ON) TRANS_DATE FROM EPAY.EPAY_RECEIPT_BATCH_HDR_PDB
WHERE RECEIPT_DATE='15-APR-2022'
AND BANK_CODE='94')B
WHERE A.BATCH_NO=B.BATCH_NUM_EPAY
AND A.LOCATION_CODE=B.LOCATION_CODE