

SELECT A.BILL_MONTH,A.LOCATION_CODE,B.ORG_BANK_CODE BANK_CODE,A.ACCOUNT_NUMBER,A.BILL_NUMBER,A.BILL_DUE_DATE,B.PAY_DATE,A.TOTAL_BILL_AMOUNT TOTAL_BILL,B.TOT_AMT TOTAL_PAYMENT FROM (
SELECT U.BILL_MONTH,U.LOCATION_CODE,U.ACCOUNT_NUMBER,U.BILL_NUMBER,U.BILL_DUE_DATE,U.TOTAL_BILL_AMOUNT  
FROM EPAY_UTILITY_bILL@EPAY_SRL U
WHERE U.ACCOUNT_NUMBER='52636541')A,(
--ORDER BY BILL_MONTH DESC
SELECT D.BILL_MONTH,M.ORG_BR_CODE,M.ORG_BANK_CODE,M.PAY_DATE,D.ACCOUNT_NUMBER,D.BILL_NUMBER,SUM(D.ORG_PRN_AMOUNT+D.VAT_AMOUNT) TOT_AMT FROM EPAY_PAYMENT_DTL@EPAY_SRL D,EPAY_PAYMENT_MST@EPAY_SRL M
WHERE D.BATCH_NO = M.BATCH_NO
AND D.ACCOUNT_NUMBER='52636541'
GROUP BY D.BILL_MONTH,M.ORG_BR_CODE,M.ORG_BANK_CODE,M.PAY_DATE,D.ACCOUNT_NUMBER,D.BILL_NUMBER
ORDER BY D.BILL_MONTH DESC)B
WHERE A.ACCOUNT_NUMBER=B.ACCOUNT_NUMBER(+)
AND A.BILL_NUMBER = B.BILL_NUMBER(+)
ORDER BY A.BILL_MONTH DESC



SELECT A.LOCATION_CODE,B.pay_BANK_CODE BANK_CODE,A.BILL_NUMBER,A.BILL_DUE_DATE,B.PAY_DATE,A.TOTAL_BILL_AMOUNT TOTAL_BILL,B.TOT_AMT TOTAL_PAYMENT FROM (
SELECT U.LOCATION_CODE,U.BILL_NUMBER,U.BILL_DUE_DATE,U.TOTAL_BILL_AMOUNT  
FROM EPAY_UTILITY_bILL U
WHERE U.ACCOUNT_NUMBER='44794342')A,(
--ORDER BY BILL_MONTH DESC
SELECT M.LOCATION_CODE,M.pay_BANK_CODE,M.PAY_DATE,D.BILL_NUMBER,SUM(D.PDB_AMOUNT+D.GOVT_DUTY) TOT_AMT FROM EPAY_PAYMENT_DTL D,EPAY_PAYMENT_MST M
WHERE D.BATCH_NO = M.BATCH_NO
GROUP BY M.LOCATION_CODE,M.pay_BANK_CODE,M.PAY_DATE,D.BILL_NUMBER
)B
WHERE  A.BILL_NUMBER = B.BILL_NUMBER
ORDER BY B.PAY_DATE DESC