

--------NOT DAY_END-------

SELECT A.ORG_CODE,A.PAY_DATE,B.BANK_NAME,A.PAY_BANK_CODE,BR.BRANCH_NAME,A.PAY_BANK_BR_CODE,COUNT(*) TOT_CONSUMER
FROM  EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE A,EPAYONLINE.EPAY_BANK_BRANCH BR,EPAYONLINE.EPAY_BANK_MST B
WHERE A.PAY_BANK_CODE=B.BANK_CODE
AND BR.BANK_CODE=A.PAY_BANK_CODE
AND BR.BRANCH_CODE=A.PAY_BANK_BR_CODE
AND (PAY_DATE,PAY_BANK_CODE,PAY_BANK_BR_CODE) IN (
SELECT PAY_DATE,PAY_BANK_CODE,PAY_BANK_BR_CODE FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE
GROUP BY PAY_DATE,PAY_BANK_CODE,PAY_BANK_BR_CODE
MINUS
SELECT PAY_DATE,PAY_BANK_CODE,PAY_BANK_BR_CODE FROM  EPAYONLINE.EPAY_DAY_END_LOG
GROUP BY PAY_DATE,PAY_BANK_CODE,PAY_BANK_BR_CODE
)GROUP BY A.ORG_CODE,A.PAY_DATE,B.BANK_NAME,A.PAY_BANK_CODE,BR.BRANCH_NAME,A.PAY_BANK_BR_CODE
ORDER BY 1 DESC, 2 ASC


------BATCH NOT GENERAL------

SELECT ORG_CODE,PAY_DATE,B.BANK_NAME, PAY_BANK_CODE,BR.BRANCH_NAME, PAY_BANK_BR_CODE,ORG_BR_CODE,COUNT(*) TOT_CONSUMER
FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE A,EPAYONLINE.EPAY_BANK_MST B,EPAYONLINE.EPAY_BANK_BRANCH BR
WHERE A.PAY_BANK_CODE=B.BANK_CODE
AND A.PAY_BANK_CODE=BR.BANK_CODE
AND A.PAY_BANK_BR_CODE=BR.BRANCH_CODE
AND A.PAY_DATE<TRUNC(SYSDATE)
--AND A.ORG_CODE='WZPDCL'
GROUP BY ORG_CODE,PAY_DATE,B.BANK_NAME,PAY_BANK_CODE,BR.BRANCH_NAME,PAY_BANK_BR_CODE,ORG_BR_CODE
ORDER BY 1 DESC, 2 ASC


----------------------------------------

SELECT A.ORG_CODE,A.PAY_DATE,B.BANK_NAME,A.PAY_BANK_CODE,BR.BRANCH_NAME,A.PAY_BANK_BR_CODE,SUM(VAT_AMOUNT) VAT,SUM(PRN_AMOUNT+VAT_AMOUNT) TOTAL_AMOUNT,COUNT(*) TOT_CONSUMER
FROM  EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE A,EPAYONLINE.EPAY_BANK_BRANCH BR,EPAYONLINE.EPAY_BANK_MST B
WHERE A.PAY_BANK_CODE=B.BANK_CODE
AND BR.BANK_CODE=A.PAY_BANK_CODE
AND BR.BRANCH_CODE=A.PAY_BANK_BR_CODE
AND (PAY_DATE,PAY_BANK_CODE,PAY_BANK_BR_CODE) IN (
SELECT PAY_DATE,PAY_BANK_CODE,PAY_BANK_BR_CODE FROM EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE
GROUP BY PAY_DATE,PAY_BANK_CODE,PAY_BANK_BR_CODE
MINUS
SELECT PAY_DATE,PAY_BANK_CODE,PAY_BANK_BR_CODE FROM  EPAYONLINE.EPAY_DAY_END_LOG
GROUP BY PAY_DATE,PAY_BANK_CODE,PAY_BANK_BR_CODE
)GROUP BY A.ORG_CODE,A.PAY_DATE,B.BANK_NAME,A.PAY_BANK_CODE,BR.BRANCH_NAME,A.PAY_BANK_BR_CODE
ORDER BY 1 DESC, 2 ASC



SELECT A.ORG_CODE,A.PAY_DATE,B.BANK_NAME,A.PAY_BANK_CODE,BR.BRANCH_NAME, A.PAY_BANK_BR_CODE,sum(A.PRN_AMOUNT+A.VAT_AMOUNT) TOT_AMT,COUNT(*) TOT_CONSUMER
FROM  EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE_HIST A,EPAYONLINE.EPAY_BANK_BRANCH BR,EPAYONLINE.EPAY_BANK_MST B
WHERE A.PAY_BANK_CODE=B.BANK_CODE
AND BR.BANK_CODE=A.PAY_BANK_CODE
AND BR.BRANCH_CODE=A.PAY_BANK_BR_CODE
AND A.PAY_DATE='27-DEC-2017'
AND ORG_CODE='WZPDCL'
GROUP BY A.ORG_CODE,A.PAY_DATE,B.BANK_NAME,A.PAY_BANK_CODE,BR.BRANCH_NAME,A.PAY_BANK_BR_CODE
