
SELECT COMP_CNTR_CODE,COMP_CNTR_NAME FROM V_Z_C_C_L
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='GP')
GROUP BY COMP_CNTR_CODE,COMP_CNTR_NAME
ORDER BY COMP_CNTR_CODE ASC      

SELECT COUNT(1) FROM VW_EPAY_PAYMENT_MST_DTL D, V_Z_C_C_L V
WHERE D.LOCATION_CODE=V.LOCATION_CODE
AND V.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='GP')
AND V.COMP_CNTR_CODE=:C_CODE
AND TO_CHAR(D.PAY_DATE,'RRRRMM')='201605'
AND PAY_BANK_CODE='96'

SELECT B.COMPANY_CODE SERVER_NAME,V.COMP_CNTR_NAME,FN_INWORD_MONTH(TO_CHAR(M.PAY_DATE,'RRRRMM')) PAYMENT_MONTH,M.PAY_DATE,V.LOCATION_CODE,V.LOCATION_NAME,
            B.ACCOUNT_NUMBER CONSUMER_NO,C.NAME CONSUMER_NAME,C.AREAR_CODE,SUBSTR(C.AREAR_CODE,4,5) BILL_GROUP,D.BILL_NUMBER,B.BILL_DUE_DATE,
            D.REF_BATCH_NO BATCH_NO,NVL(D.GOVT_DUTY,0) VAT,NVL(D.PDB_AMOUNT,0) PDB_AMOUNT,NVL(D.GOVT_DUTY,0)+NVL(D.PDB_AMOUNT,0) TOTAL_AMOUNT,
            CASE WHEN NVL(D.GOVT_DUTY,0)+NVL(D.PDB_AMOUNT,0)>=500 THEN  5  ELSE  0  END AS REVENUE_STAMP_AMOUNT
    FROM EPAY_UTILITY_BILL B,EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D, V_Z_C_C_L V,EPAY_CUSTOMER_MASTER_DATA C
WHERE B.BILL_NUMBER=D.BILL_NUMBER
AND M.BATCH_NO=D.BATCH_NO
AND M.LOCATION_CODE=B.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'RRRRMM')='201605'
AND B.LOCATION_CODE=M.LOCATION_CODE
AND B.LOCATION_CODE=V.LOCATION_CODE
AND M.LOCATION_CODE=V.LOCATION_CODE
AND V.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='GP')
AND V.COMP_CNTR_CODE=:C_CODE
AND M.PAY_BANK_CODE='96'
AND B.ACCOUNT_NUMBER=C.ACCOUNT_NO(+)
AND B.LOCATION_CODE=C.LOCATION_CODE(+)
ORDER BY M.PAY_DATE,V.LOCATION_CODE



SELECT B.COMPANY_CODE SERVER_NAME,V.COMP_CNTR_NAME,FN_INWORD_MONTH(TO_CHAR(M.PAY_DATE,'RRRRMM')) PAYMENT_MONTH,M.PAY_DATE,V.LOCATION_CODE,V.LOCATION_NAME,
            B.ACCOUNT_NUMBER CONSUMER_NO,C.NAME CONSUMER_NAME,C.AREAR_CODE,SUBSTR(C.AREAR_CODE,4,5) BILL_GROUP,D.BILL_NUMBER,B.BILL_DUE_DATE,
            D.BATCH_NO BATCH_NO,NVL(D.GOVT_DUTY,0) VAT,NVL(D.PDB_AMOUNT,0) PDB_AMOUNT,NVL(D.GOVT_DUTY,0)+NVL(D.PDB_AMOUNT,0) TOTAL_AMOUNT,
            CASE WHEN NVL(D.GOVT_DUTY,0)+NVL(D.PDB_AMOUNT,0)>=500 THEN  5  ELSE  0  END AS REVENUE_STAMP_AMOUNT
    FROM EPAY_UTILITY_BILL B,DBERSICE.PAYMENT_MST@EPAY_GP M,DBERSICE.PAYMENT_DTL@EPAY_GP D, V_Z_C_C_L V,EPAY_CUSTOMER_MASTER_DATA C
WHERE B.BILL_NUMBER=D.BILL_NUMBER
AND M.BATCH_NO=D.BATCH_NO
AND M.LOCATION_CODE=B.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'RRRRMM')='201605'
AND B.LOCATION_CODE=M.LOCATION_CODE
AND B.LOCATION_CODE=V.LOCATION_CODE
AND M.LOCATION_CODE=V.LOCATION_CODE
AND V.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='GP')
AND V.COMP_CNTR_CODE=:C_CODE
--AND M.PAY_BANK_CODE='96'
AND B.ACCOUNT_NUMBER=C.ACCOUNT_NO(+)
AND B.LOCATION_CODE=C.LOCATION_CODE(+)
ORDER BY M.PAY_DATE,V.LOCATION_CODE
