
--------------20.24----

SELECT PAY_DATE ,COUNT(*) TOTAL_CONS,SUM(D.ORG_PRN_AMOUNT+D.VAT_AMOUNT) TOTAL FROM EPAY_PAYMENT_MST@EPAY_SRL_24 M,EPAY_PAYMENT_DTL@EPAY_SRL_24 D
WHERE M.BATCH_NO=D.BATCH_NO
AND TO_CHAR(PAY_DATE,'RRRRMM')='201910'
and org_code='WZPDCL'
GROUP BY PAY_DATE
ORDER by 1 desc

-------20.26-----------

SELECT PAY_DATE ,COUNT(*) TOTAL_CONS,SUM(D.ORG_PRN_AMOUNT+D.VAT_AMOUNT) TOTAL FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND TO_CHAR(PAY_DATE,'RRRRMM')='201910'
GROUP BY PAY_DATE
ORDER by 1 desc

-------50.2-----------

SELECT PAY_DATE ,COUNT(*) TOTAL_CONS,SUM(D.ORG_PRN_AMOUNT+D.VAT_AMOUNT) TOTAL FROM EPAY_PAYMENT_MST@EPAY_WZPDCL M,EPAY_PAYMENT_DTL@EPAY_WZPDCL D
WHERE M.BATCH_NO=D.BATCH_NO
AND TO_CHAR(PAY_DATE,'RRRRMM')='201910'
GROUP BY PAY_DATE
ORDER by 1 desc



select * from epay_payment_mst@EPAY_SRL_24
where TO_CHAR(PAY_DATE,'RRRRMM')='201910'
and status<>'T'
and org_code='WZPDCL'


select * from epay_payment_mst
where TO_CHAR(PAY_DATE,'RRRRMM')='201909'
--and status<>'T'
and org_code='WZPDCL'



=====================================


--------------20.24----

SELECT COUNT(*) TOTAL_CONS,SUM(D.ORG_PRN_AMOUNT+D.VAT_AMOUNT) TOTAL FROM EPAY_PAYMENT_MST@EPAY_SRL_24 M,EPAY_PAYMENT_DTL@EPAY_SRL_24 D
WHERE M.BATCH_NO=D.BATCH_NO
AND TO_CHAR(PAY_DATE,'RRRRMM')='201909'
and org_code='WZPDCL'
ORDER by 1 desc

-------20.26-----------

SELECT COUNT(*) TOTAL_CONS,SUM(D.ORG_PRN_AMOUNT+D.VAT_AMOUNT) TOTAL FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND TO_CHAR(PAY_DATE,'RRRRMM')='201909'
ORDER by 1 desc

-------50.2-----------

SELECT COUNT(*) TOTAL_CONS,SUM(D.ORG_PRN_AMOUNT+D.VAT_AMOUNT) TOTAL FROM EPAY_PAYMENT_MST@EPAY_WZPDCL M,EPAY_PAYMENT_DTL@EPAY_WZPDCL D
WHERE M.BATCH_NO=D.BATCH_NO
AND TO_CHAR(PAY_DATE,'RRRRMM')='201909'
ORDER by 1 desc