

SELECT NAME1,CNT_NAME,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,L.CENTER_NAME AS CNT_NAME,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE BILL_MONTH='201603'
AND L.CENTER_NAME='SYLHET'
GROUP BY L.CENTER_NAME
ORDER BY L.CENTER_NAME)A,(
SELECT 'ROBI' NAME2,L.CENTER_NAME,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI B,EPAY_LOCATION_MASTER L
WHERE BILL_MONTH='201603'
AND L.CENTER_NAME='SYLHET'
GROUP BY L.CENTER_NAME
ORDER BY L.CENTER_NAME)B;

COMMIT;


SELECT NAME1,CNT_NAME,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,L.CENTER_NAME AS CNT_NAME,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE BILL_MONTH='201603'
AND L.CENTER_NAME='COMILLA'
GROUP BY L.CENTER_NAME
ORDER BY L.CENTER_NAME)A,(
SELECT 'ROBI' NAME2,L.CENTER_NAME,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI B,EPAY_LOCATION_MASTER L
WHERE BILL_MONTH='201603'
AND L.CENTER_NAME='COMILLA'
GROUP BY L.CENTER_NAME
ORDER BY L.CENTER_NAME)B;
COMMIT;


SELECT NAME1,CNT_NAME,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,L.CENTER_NAME AS CNT_NAME,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE BILL_MONTH='201603'
AND L.CENTER_NAME='CHITTAGONG'
GROUP BY L.CENTER_NAME
ORDER BY L.CENTER_NAME)A,(
SELECT 'ROBI' NAME2,L.CENTER_NAME,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI B,EPAY_LOCATION_MASTER L
WHERE BILL_MONTH='201603'
AND L.CENTER_NAME='CHITTAGONG'
GROUP BY L.CENTER_NAME
ORDER BY L.CENTER_NAME)B;

COMMIT;

SELECT NAME1,CNT_NAME,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,L.CENTER_NAME AS CNT_NAME,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE BILL_MONTH='201603'
AND L.CENTER_NAME='TANGAIL'
GROUP BY L.CENTER_NAME
ORDER BY L.CENTER_NAME)A,(
SELECT 'ROBI' NAME2,L.CENTER_NAME,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI B,EPAY_LOCATION_MASTER L
WHERE BILL_MONTH='201603'
AND L.CENTER_NAME='TANGAIL'
GROUP BY L.CENTER_NAME
ORDER BY L.CENTER_NAME)B;

COMMIT;

SELECT NAME1,CNT_NAME,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,L.CENTER_NAME AS CNT_NAME,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE BILL_MONTH='201603'
AND L.CENTER_NAME='PABNA'
GROUP BY L.CENTER_NAME
ORDER BY L.CENTER_NAME)A,(
SELECT 'ROBI' NAME2,L.CENTER_NAME,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI B,EPAY_LOCATION_MASTER L
WHERE BILL_MONTH='201603'
AND L.CENTER_NAME='PABNA'
GROUP BY L.CENTER_NAME
ORDER BY L.CENTER_NAME)B;

COMMIT;


SELECT NAME1,CNT_NAME,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,L.CENTER_NAME AS CNT_NAME,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE BILL_MONTH='201603'
AND L.CENTER_NAME='JAMALPUR'
GROUP BY L.CENTER_NAME
ORDER BY L.CENTER_NAME)A,(
SELECT 'ROBI' NAME2,L.CENTER_NAME,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI B,EPAY_LOCATION_MASTER L
WHERE BILL_MONTH='201603'
AND L.CENTER_NAME='JAMALPUR'
GROUP BY L.CENTER_NAME
ORDER BY L.CENTER_NAME)B;

COMMIT;

SELECT NAME1,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='KISHOREGANJ'))A,(
SELECT 'ROBI' NAME2,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='KISHOREGANJ'))B;

COMMIT;

SELECT NAME1,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='MYMENSING'))A,(
SELECT 'ROBI' NAME2,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='MYMENSING'))B;

COMMIT;

SELECT NAME1,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='RAJSHAHI'))A,(
SELECT 'ROBI' NAME2,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='RAJSHAHI'))B;

COMMIT;

SELECT NAME1,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='NAOGAON'))A,(
SELECT 'ROBI' NAME2,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='NAOGAON'))B;

COMMIT;


SELECT NAME1,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='BOGRA'))A,(
SELECT 'ROBI' NAME2,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='BOGRA'))B;

COMMIT;

SELECT NAME1,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='DINAJPUR'))A,(
SELECT 'ROBI' NAME2,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='DINAJPUR'))B;

COMMIT;

SELECT NAME1,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='MOULAVIBAZAR'))A,(
SELECT 'ROBI' NAME2,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='MOULAVIBAZAR'))B;

COMMIT;

SELECT NAME1,CNT_PDB,NAME2,CNT_ROBI ,CNT_PDB-CNT_ROBI AS MISSING_ROBI FROM (
SELECT 'BPDB' NAME1,COUNT(*) AS CNT_PDB FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='RANGPUR'))A,(
SELECT 'ROBI' NAME2,COUNT(*) AS CNT_ROBI FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN(SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='RANGPUR'))B;

COMMIT;