

EXECUTE EPAY.DPD_EPAY_PDB_CORT_BILL(:P_LOC_CODE,:P_ACCOUNT_NUMBER,:P_BILL_NUMBER,:P_PDB_AMT,:P_VAT,:P_BILL_TYPE);
 

SELECT B.LOCATION_CODE LOC,BILL_MONTH,C.NAME AS CUSTOMER_NAME, ACCOUNT_NUMBER,BILL_NUMBER, BILL_DUE_DATE,
BILL_STATUS,NVL (  NVL (TOTAL_BILL_AMOUNT, 0)- NVL (  NVL (CURRENT_GOVT_DUTY, 0)+ NVL (ARREAR_GOVT_DUTY, 0)+ NVL (ADJUSTED_GOVT_DUTY, 0),0),0) PDB_AMOUNT,
NVL (  NVL (CURRENT_GOVT_DUTY, 0)+ NVL (ARREAR_GOVT_DUTY, 0)+ NVL (ADJUSTED_GOVT_DUTY, 0),0) VAT_AMOUNT,TOTAL_BILL_AMOUNT
FROM EPAY_UTILITY_BILL B,EPAY_CUSTOMER_MASTER_DATA C
WHERE B.ACCOUNT_NUMBER=C.ACCOUNT_NO
AND B.COMPANY_CODE=C.COMPANY_CODE
AND B.LOCATION_CODE=C.LOCATION_CODE
AND ( BILL_NUMBER=:P_BILL_NUMBER OR B.ACCOUNT_NUMBER =:P_ACCOUNT_NUMBER)
--AND B.BILL_MONTH =:P_BILL_MONTH
AND B.LOCATION_CODE=:P_LOC_CODE
AND BILL_DUE_DATE>=TRUNC(SYSDATE-30)
AND B.COMPANY_CODE=UPPER('BPDB');


SELECT * FROM EPAY_UTILITY_BILL
WHERE bill_NUMBER=:P_BILL_NUMBER

select INVOICE_NUM||INVOICE_CHK_DGT from bc_bill_image@billing_ctg
WHERE invoice_num='44303348'