

SELECT A.AREA_CODE BOOK_NO,A.LOCATION_CODE||'-'||L.DESCR LOCATION_NAME, A.CUSTOMER_NUM,A.WALKING_SEQUENCE WALK_ORDER,CM.METER_NUM,
A.CUSTOMER_NAME,B.ADDR_DESCR1||','||B.ADDR_DESCR3 ADDRESS,null MOBIL_NO 
FROM BC_CUSTOMERS A,BC_CUSTOMER_ADDR B,BC_LOCATION_MASTER L,BC_CUSTOMER_METER CM
WHERE A.CUST_ID=B.CUST_ID
AND B.ADDR_TYPE='B'
AND B.ADDR_EXP_DATE IS NULL
AND A.LOCATION_CODE=L.LOCATION_CODE
AND A.CUST_ID=CM.CUST_ID
AND CM.METER_STATUS='2'
and PRIMARY_METER_ID is null
AND AREA_CODE LIKE DECODE(:P_BOOK_NO,'ALL','%',:P_BOOK_NO)
AND A.LOCATION_CODE=:P_LOCATION_CODE
GROUP BY AREA_CODE,L.DESCR ,A.LOCATION_CODE, A.CUSTOMER_NUM,CM.METER_NUM,A.WALKING_SEQUENCE ,A.CUSTOMER_NAME,B.ADDR_DESCR1||','||B.ADDR_DESCR3
ORDER BY A.AREA_CODE,A.WALKING_SEQUENCE



SELECT AREA_CODE book_no,L.DESCR location_name, A.CUSTOMER_NUM,A.WALKING_SEQUENCE Walk_Order,A.CUSTOMER_NAME,'Blank' Mobil_NO 
FROM BC_CUSTOMERS A,BC_CUSTOMER_ADDR B,BC_LOCATION_MASTER L
WHERE A.CUST_ID=B.CUST_ID
and A.LOCATION_CODE=L.LOCATION_CODE

group by AREA_CODE