SELECT DISTINCT B.CUSTOMER_NAME,B.F_H_NAME,C.ADDR_DESCR1||' '||C.ADDR_DESCR2 ADDR,D.METER_CONNECT_DATE,B.CONS_EXTG_NUM,B.CUSTOMER_NUM,B.CUST_ID,
D.METER_NUM,A.LOCATION_CODE, B.AREA_CODE,B.WALKING_SEQUENCE,(SELECT (NVL(SUM(NVL(PRINCIPAL_AMT,0)+NVL(PRINCIPAL_ADJ,0)-NVL(PRINCIPAL_APPL,0)+NVL(LPS_AMT,0)+NVL(LPS_ADJ,0)-NVL(LPS_APPL,0))+NVL(SUM(NVL(vat_AMT,0)+NVL(vat_ADJ,0)-NVL(vat_APPL,0)),0),0)) arr
FROM BC_INVOICE_HDR
WHERE CUST_ID=A.CUST_ID
AND REC_STATUS='D'
AND BILL_CYCLE_CODE<='201609') CUST_ARR_300916,(SELECT (NVL(SUM(NVL(PRINCIPAL_AMT,0)+NVL(PRINCIPAL_ADJ,0)-NVL(PRINCIPAL_APPL,0)+NVL(LPS_AMT,0)+NVL(LPS_ADJ,0)-NVL(LPS_APPL,0))+NVL(SUM(NVL(vat_AMT,0)+NVL(vat_ADJ,0)-NVL(vat_APPL,0)),0),0)) arr
FROM BC_INVOICE_HDR
WHERE CUST_ID=A.GOVT_CUST_ID
AND REC_STATUS='D'
AND BILL_CYCLE_CODE<='201609') GOVT_CUST_ARR_300916,
(SELECT (NVL(SUM(NVL(PRINCIPAL_AMT,0)+NVL(PRINCIPAL_ADJ,0)-NVL(PRINCIPAL_APPL,0)+NVL(LPS_AMT,0)+NVL(LPS_ADJ,0)-NVL(LPS_APPL,0))+NVL(SUM(NVL(vat_AMT,0)+NVL(vat_ADJ,0)-NVL(vat_APPL,0)),0),0)) arr
FROM BC_INVOICE_HDR
WHERE CUST_ID=A.CUST_ID
AND REC_STATUS='D'
AND BILL_CYCLE_CODE>'201609') CUST_ARR_AFTER_300916,(SELECT (NVL(SUM(NVL(PRINCIPAL_AMT,0)+NVL(PRINCIPAL_ADJ,0)-NVL(PRINCIPAL_APPL,0)+NVL(LPS_AMT,0)+NVL(LPS_ADJ,0)-NVL(LPS_APPL,0))+NVL(SUM(NVL(vat_AMT,0)+NVL(vat_ADJ,0)-NVL(vat_APPL,0)),0),0)) arr
FROM BC_INVOICE_HDR
WHERE CUST_ID=A.GOVT_CUST_ID
AND REC_STATUS='D'
AND BILL_CYCLE_CODE>'201609') GOVT_CUST_ARR_AFTER_300916
FROM BC_REBATE_CUSTOMERS A,BC_CUSTOMERS B,BC_CUSTOMER_ADDR C,BC_CUSTOMER_METER D,BC_CUSTOMER_CATEGORY CC,BC_CATEGORY_MASTER CM
WHERE A.CUST_ID=B.CUST_ID
AND B.CUST_ID=C.CUST_ID
AND B.CUST_ID=CC.CUST_ID
AND CC.EXP_DATE IS NULL
AND CC.CAT_ID=CM.CATEGORY_ID
AND CM.USAGE_CATEGORY_CODE='LT-C1'
AND C.ADDR_TYPE = 'B'
AND C.ADDR_EXP_DATE IS NULL
AND A.BUS_TYPE_CODE='PP'
AND B.CUST_ID=D.CUST_ID
AND METER_STATUS=2