SELECT DISTINCT BATCH_NO FROM (
SELECT BATCH_NO,SCROLL_NO,COUNT(1) FROM EPAY_PAYMENT_DTL
--WHERE BATCH_NO IN (SELECT BATCH_NO FROM VW_EPAY_UNTRANSFER_PYMT WHERE BANK_CODE='96') 
GROUP BY BATCH_NO,SCROLL_NO HAVING COUNT(1)>1
)

SELECT MIN_A - 1 + LEVEL FROM ( 
SELECT MIN(SCROLL_NO) MIN_A , MAX(SCROLL_NO) MAX_A
FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO=:b
                            )
CONNECT BY LEVEL <= MAX_A - MIN_A + 1
      MINUS
SELECT SCROLL_NO  FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO=:b


SELECT BATCH_NO,SCROLL_NO,COUNT(1) FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO=:b 
GROUP BY BATCH_NO,SCROLL_NO HAVING COUNT(1)>1

update EPAY_PAYMENT_DTL
set SCROLL_NO=rownum
WHERE BATCH_NO=:b 


order by bill_number