
SELECT P_CNM,PDB_CON,G_CNM,GP_CON,R_CNM,RB_CON FROM (
SELECT 'PDB' BPDB,CENTER_NAME P_CNM,COUNT(*) PDB_CON FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201704'
GROUP BY CENTER_NAME
ORDER BY CENTER_NAME ASC)A,(
SELECT 'ROBI' ROBI, CENTER_NAME R_CNM,COUNT(*) RB_CON FROM UTILITY_BILL_PDB@EPAY_ROBI B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201704'
GROUP BY CENTER_NAME
ORDER BY CENTER_NAME ASC
)B,(
SELECT 'GP' GP, CENTER_NAME G_CNM,COUNT(*) GP_CON FROM UTILITY_BILL_PDB@EPAY_GP B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201704'
GROUP BY CENTER_NAME
ORDER BY CENTER_NAME ASC
)C
WHERE A.P_CNM=B.R_CNM
AND B.R_CNM=C.G_CNM


-----pdb---robi--missmas----

SELECT P_CNM,PDB_CON,R_CNM,RB_CON,PDB_CON-RB_CON MISS_ROBI FROM (
SELECT 'PDB' BPDB,CENTER_NAME P_CNM,COUNT(*) PDB_CON FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201706'
GROUP BY CENTER_NAME
ORDER BY CENTER_NAME ASC)A,(
SELECT 'ROBI' ROBI, CENTER_NAME R_CNM,COUNT(*) RB_CON FROM UTILITY_BILL_PDB@EPAY_ROBI B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201706'
GROUP BY CENTER_NAME
ORDER BY CENTER_NAME ASC
)B
WHERE A.P_CNM=B.R_CNM


-----pdb---gp--missmas----

SELECT P_CNM,PDB_CON,G_CNM,GP_CON,PDB_CON-GP_CON MISS_GP FROM (
SELECT 'PDB' BPDB,CENTER_NAME P_CNM,COUNT(*) PDB_CON FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201705'
GROUP BY CENTER_NAME
ORDER BY CENTER_NAME ASC)A,(
SELECT 'GP' GP, CENTER_NAME G_CNM,COUNT(*) GP_CON FROM UTILITY_BILL_PDB@EPAY_GP B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201705'
GROUP BY CENTER_NAME
ORDER BY CENTER_NAME ASC
)B
WHERE A.P_CNM=B.G_CNM





CHITTAGONG

SELECT P_LOC,PDB_CON,R_LOC,RB_CON,PDB_CON-RB_CON MISS_ROBI FROM (
SELECT 'PDB' BPDB,L.LOCATION_CODE P_LOC, COUNT(*) PDB_CON FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201706'
AND L.CENTER_NAME='KISHOREGANJ'
GROUP BY L.LOCATION_CODE
ORDER BY L.LOCATION_CODE ASC)A,(
SELECT 'ROBI' ROBI, L.LOCATION_CODE R_LOC, COUNT(*) RB_CON FROM UTILITY_BILL_PDB@EPAY_ROBI B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201706'
AND L.CENTER_NAME='KISHOREGANJ'
GROUP BY L.LOCATION_CODE
ORDER BY L.LOCATION_CODE ASC
)B
WHERE A.P_LOC=B.R_LOC




SELECT P_LOC,PDB_CON,G_LOC,RB_CON,PDB_CON-RB_CON MISS_ROBI FROM (
SELECT 'PDB' BPDB,L.LOCATION_CODE P_LOC, COUNT(*) PDB_CON FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201705'
AND L.CENTER_NAME='RANGPUR'
GROUP BY L.LOCATION_CODE
ORDER BY L.LOCATION_CODE ASC)A,(
SELECT 'GP' ROBI, L.LOCATION_CODE G_LOC, COUNT(*) RB_CON FROM UTILITY_BILL_PDB@EPAY_GP B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='201705'
AND L.CENTER_NAME='RANGPUR'
GROUP BY L.LOCATION_CODE
ORDER BY L.LOCATION_CODE ASC
)B
WHERE A.P_LOC=B.G_LOC
