
---ARRAY-----1

SELECT 'TYPE Array_'||COLUMN_NAME||' IS TABLE OF '||TABLE_NAME||'.'||COLUMN_NAME||' %TYPE index by BINARY_INTEGER;' FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='PAYROLL_EMP_MON_SALARY'
AND OWNER='SRLERP'
ORDER BY COLUMN_ID

--------2-----

SELECT 'P_'||COLUMN_NAME||' IN Array_'||COLUMN_NAME||',' FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='PAYROLL_EMP_MON_SALARY'
AND OWNER='SRLERP'
ORDER BY COLUMN_ID

-----3---------------

SELECT COLUMN_NAME||',' FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='PMIS_SUB_GRADE_DTL'
AND OWNER='SRLERP'
ORDER BY COLUMN_ID

-------------4--------------

SELECT 'p_'||COLUMN_NAME||'(AL),' FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='SERVEY_FORM14_DWNLD_UPLOAD_DTL'
AND OWNER='SRLERP'
ORDER BY COLUMN_ID

----------5------------------


SELECT COLUMN_NAME||'=p_'||COLUMN_NAME||'(I),' FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='PMIS_SUB_GRADE_DTL'
AND OWNER='SRLERP'
ORDER BY COLUMN_ID

/*
SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='SERVEY_FORM9_DOWNLOAD_UPLOAD'


SELECT 'D.'||COLUMN_NAME||',' FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='SERVEY_FORM9_DOWNLOAD_UPLOAD'
AND OWNER='SFS'
ORDER BY COLUMN_ID

*/

--------single-----------

SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='CBPRO_CUSTOMERS'
ORDER BY COLUMN_ID

-------1

SELECT 'P_'||INITCAP(COLUMN_NAME)||'  '||DATA_TYPE||',' FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='BC_CONSUMER_INTERFACE'
AND OWNER='EBC'
ORDER BY COLUMN_ID

-----2

SELECT COLUMN_NAME||',' FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='BC_CONSUMER_INTERFACE'
AND OWNER='EBC'
ORDER BY COLUMN_ID

------3

SELECT 'P_'||INITCAP(COLUMN_NAME)||',' FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='BC_CONSUMER_INTERFACE'
AND OWNER='EBC'
ORDER BY COLUMN_ID

-----4

SELECT COLUMN_NAME||'=P_'||INITCAP(COLUMN_NAME)||',' FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='BC_CONSUMER_INTERFACE'
AND OWNER='EBC'
ORDER BY COLUMN_ID


SELECT DISTINCT *
  FROM DBA_OBJECTS
 WHERE OBJECT_TYPE = 'TABLE'
 and owner='EPAY'
 
 
 SELECT *  from all_tables where owner = 'EPAY'