
SELECT DFN_BILLING_BTCH_REMOVE (:P_Batch_No,:P_Location_Code ) FROM DUAL


SELECT 'SELECT DFN_BILLING_BTCH_REMOVE ('''||BATCH_NO||''','''||LOCATION_CODE||''' ) FROM DUAL;'||CHR(10)  FROM EPAY_PAYMENT_MST_X
WHERE PAY_BANK_CODE='96'
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='CHITTAGONG')