
SELECT  ' '||Z.ZONE_NAME AS ZONE_NAME,Z.RAO_DESC,
IM.PAY_BANK_CODE||'-'||B.BANK_NAME AS BANK_NAME,TO_CHAR(IM.PAY_DATE,'RRRRMM') AS PAY_DATE,
SUM(NVL(ID.PDB_AMOUNT,0)+NVL(ID.GOVT_DUTY,0)) AS TOTAL_AMOUNT,
SUM(NVL(ID.PDB_AMOUNT,0)) AS PDB_AMOUNT,SUM(NVL(ID.GOVT_DUTY,0)) VAT,COUNT(1) AS NO_OF_CON 
FROM EPAY_PAYMENT_MST IM,
EPAY_PAYMENT_DTL ID,
EPAY_LOCATION_MASTER L,
EPAY_BANKS B,
EPAY_BANK_BRANCHES BR,
VW_RAO_WISE_LOC_LIST Z,
EPAY_USER_MST U, 
EPAY_ACCESS_ALLOW_MAP M
WHERE IM.BATCH_NO=ID.BATCH_NO
AND IM.LOCATION_CODE=L.LOCATION_CODE
AND IM.LOCATION_CODE=Z.LOCATION_CODE
AND L.LOCATION_CODE=Z.LOCATION_CODE
AND IM.LOCATION_CODE=BR.LOCATION_CODE
AND IM.PAY_BANK_CODE=B.BANK_CODE
AND IM.STATUS IN ('P','T')
AND L.STATUS='A'
AND M.STATUS='A'
AND B.BANK_CODE=BR.BANK_CODE
AND IM.PAY_BANK_CODE=BR.BANK_CODE
AND B.BANK_CODE=M.BANK_CODE
AND M.BANK_CODE=BR.BANK_CODE
AND B.BANK_CODE= :P_BANK_CODE
AND UPPER(U.USER_NAME)=UPPER(M.USER_DESC)
AND U.USER_NAME=UPPER(:APP_USER)
AND Z.ZONE_CODE=M.ZONE_CODE
AND Z.ZONE_CODE LIKE DECODE(:P_ZONE_CODE,'ALL','%',:P_ZONE_CODE)
AND TO_CHAR(IM.PAY_DATE,'RRRRMM')>=:P_START_PAY_MONTH
AND TO_CHAR(IM.PAY_DATE,'RRRRMM')<=:P_END_PAY_MONTH
GROUP BY  ' '||Z.ZONE_NAME,Z.RAO_DESC,IM.PAY_BANK_CODE||'-'||B.BANK_NAME,TO_CHAR(IM.PAY_DATE,'RRRRMM')
UNION
SELECT  ' '||Z.ZONE_NAME AS ZONE_NAME,Z.RAO_DESC,
IM.PAY_BANK_CODE||'-'||B.BANK_NAME AS BANK_NAME,TO_CHAR(IM.PAY_DATE,'RRRRMM') AS PAY_DATE,
SUM(NVL(ID.PDB_AMOUNT,0)+NVL(ID.GOVT_DUTY,0)) AS TOTAL_AMOUNT,
SUM(NVL(ID.PDB_AMOUNT,0)) AS PDB_AMOUNT,SUM(NVL(ID.GOVT_DUTY,0)) VAT,COUNT(1) AS NO_OF_CON 
FROM EPAY_PAYMENT_MST_HSTR IM,
EPAY_PAYMENT_DTL_HSTR ID,
EPAY_LOCATION_MASTER L,
EPAY_BANKS B,
EPAY_BANK_BRANCHES BR,
VW_RAO_WISE_LOC_LIST Z,
EPAY_USER_MST U, 
EPAY_ACCESS_ALLOW_MAP M
WHERE IM.BATCH_NO=ID.BATCH_NO
AND IM.LOCATION_CODE=L.LOCATION_CODE
AND IM.LOCATION_CODE=Z.LOCATION_CODE
AND L.LOCATION_CODE=Z.LOCATION_CODE
AND IM.LOCATION_CODE=BR.LOCATION_CODE
AND IM.PAY_BANK_CODE=B.BANK_CODE
AND IM.STATUS IN ('P','T')
AND L.STATUS='A'
AND M.STATUS='A'
AND B.BANK_CODE=BR.BANK_CODE
AND IM.PAY_BANK_CODE=BR.BANK_CODE
AND B.BANK_CODE=M.BANK_CODE
AND M.BANK_CODE=BR.BANK_CODE
AND B.BANK_CODE= :P_BANK_CODE
AND UPPER(U.USER_NAME)=UPPER(M.USER_DESC)
AND U.USER_NAME=UPPER(:APP_USER)
AND Z.ZONE_CODE=M.ZONE_CODE
AND Z.ZONE_CODE LIKE DECODE(:P_ZONE_CODE,'ALL','%',:P_ZONE_CODE)
AND TO_CHAR(IM.PAY_DATE,'RRRRMM')>=:P_START_PAY_MONTH
AND TO_CHAR(IM.PAY_DATE,'RRRRMM')<=:P_END_PAY_MONTH
GROUP BY  ' '||Z.ZONE_NAME,Z.RAO_DESC,IM.PAY_BANK_CODE||'-'||B.BANK_NAME,TO_CHAR(IM.PAY_DATE,'RRRRMM')
ORDER BY 3 