

SELECT  IM.PAY_BANK_CODE||'-'||B.BANK_NAME AS BANK_NAME,Z.ZONE_CODE||'-'||Z.ZONE_NAME ZONE_NAME,
                Z.RAO_CODE||'-'||INITCAP(Z.RAO_DESC) AS RAO_OFFICE,Z.LOCATION_CODE||'-'||Z.LOCATION_NAME LOCATION_NAME,
                TO_CHAR(IM.PAY_DATE,'RRRRMM') AS PAY_date,
                SUM(NVL(ID.PDB_AMOUNT,0)+NVL(ID.GOVT_DUTY,0)) AS UTILITY_AMOUNT,
                SUM(NVL(ID.PDB_AMOUNT,0)) AS PDB_AMOUNT,SUM(NVL(ID.GOVT_DUTY,0)) VAT,COUNT(1) AS NO_OF_CON 
                FROM EPAY_PAYMENT_MST IM,EPAY_PAYMENT_DTL ID,EPAY_LOCATION_MASTER L,EPAY_BANKS B,
                EPAY_BANK_BRANCHES BR,EPAY_USER_MST U,vw_rao_wise_loc_list Z
                WHERE IM.BATCH_NO=ID.BATCH_NO
                AND IM.LOCATION_CODE=L.LOCATION_CODE
                AND IM.LOCATION_CODE=Z.LOCATION_CODE
                AND L.LOCATION_CODE=Z.LOCATION_CODE
                AND IM.LOCATION_CODE=BR.LOCATION_CODE
                AND IM.PAY_BANK_CODE=B.BANK_CODE
--                AND IM.PAY_BANK_CODE=U.BANK_CODE
                 AND IM.STATUS IN ('P','T')
                AND L.STATUS='A'
                AND B.BANK_CODE=BR.BANK_CODE
                AND Z.ZONE_CODE=:P_ZONE_CODE
                AND Z.RAO_CODE LIKE DECODE(:P_RAO_CODE,'ALL','%',:P_RAO_CODE)
                AND B.BANK_CODE=:P_BANK_CODE
                AND U.USER_NAME=:app_user
                AND TO_CHAR(IM.PAY_DATE,'RRRRMM')>=:P_START_MONTH
                AND TO_CHAR(IM.PAY_DATE,'RRRRMM')<=:P_END_MONTH
                GROUP BY IM.PAY_BANK_CODE||'-'||B.BANK_NAME,Z.ZONE_CODE||'-'||Z.ZONE_NAME,
                Z.RAO_CODE||'-'||INITCAP(Z.RAO_DESC),Z.LOCATION_CODE||'-'||Z.LOCATION_NAME,TO_CHAR(IM.PAY_DATE,'RRRRMM')
                ORDER BY 4 ASC,3 ASC