

SELECT EPAY.DFN_EPAY_BANK_RECON_ERR_SLOV (:P_BATCH_NO ,:P_LOCATION_CODE) FROM DUAL

--/*
SELECT 'SELECT EPAY.DFN_EPAY_BANK_RECON_ERR_SLOV ('''|| BATCH_NO||''','''||LOC ||''') FROM DUAL'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) 
AS "RETURN_QUERY"    FROM (
SELECT BATCH_NO,LOCATION_CODE LOC FROM  EPAY_PAYMENT_MST
WHERE STATUS='E'
--AND LOCATION_CODE='M3'
)

--*/

SELECT ''''||BILL_NUMBER||''''||',' FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO ='600770'
MINUS
SELECT ''''||BILL_NUMBER||''''||',' FROM EPAY_UTILITY_BILL
WHERE BILL_NUMBER IN (
SELECT BILL_NUMBER FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO ='600770'
)
AND LOCATION_CODE='T3'

--------

SELECT * FROM utility_bill_pdb@epay_gp
where bill_month='202101'
and location_code='T3'
and BILL_NUMBER IN (
'4745292177',
'4745292214',
'4745327781',
'4745327798',
'4745327841'
)


SELECT * FROM bc_bill_image@billing_tang
where bill_cycle_code='202101'
and location_code='T5'
---------

DELETE FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202101'
AND ACCOUNT_NUMBER IN (
'76253941',
'76253988',
'76251841',
'76251854',
'76251905'
)

COMMIT;

INSERT INTO EPAY_UTILITY_BILL
SELECT COMPANY_CODE, ACCOUNT_NUMBER, BILL_NUMBER, GENERATED_DATE, BILL_STATUS, BILL_DUE_DATE, 
BILLAMT_AFTERDUEDATE, BILLENDDATE_FORPAYMENT, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, 
NOTIFICATION_SENT_STATUS, CURRENT_PRINCIPLE, CURRENT_GOVT_DUTY, ARREAR_PRINCIPLE, ARREAR_GOVT_DUTY, 
LATE_PAYMENT_SURCHARGE, TOTAL_BILL_AMOUNT, LOCATION_CODE, BILL_MONTH, TARIFF, CUSTOMER_TYPE, 
CURRENT_SURCHARGE, ARREAR_SURCHARGE, ADJUSTED_PRINCIPLE, ADJUSTED_GOVT_DUTY, ADVANCE_AMOUNT, 
ADJ_ADV_GOVT_DUTY, 'N', 'T', 'N', 'T', 'T', 'N'
FROM utility_bill_pdb@epay_gp
where bill_month='202101'
and location_code='T3'
and BILL_NUMBER IN (
'4745292177',
'4745292214',
'4745327781',
'4745327798',
'4745327841'
)


COMMIT;

===========================HISTORY===================================================

INSERT INTO EPAY_UTILITY_BILL
SELECT * FROM EPAYMENT.EPAY_UTILITY_BILL_HSTR
WHERE BILL_NUMBER IN (
SELECT BILL_NUMBER FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO='391056'
--WHERE BATCH_NO IN ('362572','362572')
MINUS
SELECT BILL_NUMBER FROM EPAY_UTILITY_BILL
WHERE BILL_NUMBER IN (
SELECT BILL_NUMBER FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO='391056' 
--WHERE BATCH_NO IN ('362572','362572')
)
AND LOCATION_CODE='B6'
)
AND LOCATION_CODE='B6'

COMMIT;


SELECT * FROM EPAY_PAYMENT_MST
WHERE LOCATION_CODE='B6'
AND BATCH_NO='391056'
AND STATUS='E'


UPDATE EPAY_PAYMENT_MST
SET STATUS='N'
WHERE LOCATION_CODE='B6'
AND BATCH_NO='391056'
AND STATUS='E'

COMMIT;


==========================BILLING================================================


28000401231018

SELECT BILL_NUMBER FROM EPAY_PAYMENT_DTL_INT
WHERE BATCH_NO='28000401231018'
--where batch_no in ('365176','364555')
MINUS
SELECT BILL_NUMBER FROM EPAY_UTILITY_BILL
WHERE BILL_NUMBER IN (
SELECT BILL_NUMBER FROM EPAY_PAYMENT_DTL_INT
WHERE BATCH_NO='28000401231018' 
--where batch_no in  ('365176','364555')
)
AND LOCATION_CODE='M6'


DELETE EPAY_UTILITY_BILL_INT;

COMMIT;

INSERT INTO EPAY_UTILITY_BILL_INT
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
  NVL(DEMAND_CHRG,0) 
  +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
 TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0,'N' AS DATA_TRANS_LOG,'T' AS DATA_TRANS_LOG1,'N' AS DATA_TRANS_LOG2,
 'T' AS DATA_TRANS_LOG3,'T' AS DATA_TRANS_LOG4,'N' AS DATA_TRANS_LOG5 
 FROM BC_BILL_IMAGE@BILLING_MYMEN
 WHERE location_code='M3'
 AND BILL_CYCLE_CODE=:P_BILL_CYCLE_CODE
 and INVOICE_NUM||INVOICE_CHK_DGT in (
'498613195'
)

INSERT INTO EPAY_UTILITY_BILL
SELECT * FROM EPAY_UTILITY_BILL_INT


------------------------------------------------
--ERROR THEN BELOW SQL EXEXUTE

DELETE FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=:BILL_MONTH
AND  (ACCOUNT_NUMBER) IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL_INT)

COMMIT; 
 


SELECT ''''||BILL_NUMBER||''''||',' FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO ='415829'
MINUS
SELECT ''''||BILL_NUMBER||''''||',' FROM EPAY_UTILITY_BILL
WHERE BILL_NUMBER IN (
SELECT BILL_NUMBER FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO ='415829'
)
AND LOCATION_CODE='T5'

 

 COMMIT;
 
 



------------------------------------------------------------------
select * from epay_payment_dtl
where batch_no ='330430'
--in ('330636','330226','329833')


SELECT BILL_NUMBER FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO='28000401230918'
--where batch_no in ('365176','364555')
MINUS
SELECT BILL_NUMBER FROM EPAY_UTILITY_BILL
WHERE BILL_NUMBER IN (
SELECT BILL_NUMBER FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO='28000401230918' 
--where batch_no in  ('365176','364555')
)
AND LOCATION_CODE='C6'

------------------------------------------------------------------------------------

SELECT ''''||BILL_NUMBER||''''||',' FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO ='391047'
MINUS
SELECT ''''||BILL_NUMBER||''''||',' FROM EPAY_UTILITY_BILL
WHERE BILL_NUMBER IN (
SELECT BILL_NUMBER FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO ='391047'
)
AND LOCATION_CODE='M3'
