

EPAY_LOCATION_MASTER
EPAY_PAYMENT_DTL

DELETE FROM EPAY_UTILITY_BILL_INT

INSERT INTO EPAY_UTILITY_BILL_INT
SELECT * FROM EPAY_UTILITY_BILL
WHERE  NVL(CURRENT_SURCHARGE,0)>0
AND BILL_MONTH='201507'
AND ACCOUNT_NUMBER IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201506' 
AND (LOCATION_CODE,BILL_NUMBER) IN (
SELECT M.LOCATION_CODE,D.BILL_NUMBER FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER)))




INSERT INTO EPAY_UTILITY_BILL_INT
SELECT * FROM EPAY_UTILITY_BILL
WHERE  NVL(CURRENT_SURCHARGE,0)>0
AND BILL_MONTH='201507'
AND ACCOUNT_NUMBER IN (
SELECT ACCOUNT_NUMBER FROM UTILITY_BILL_PDB@AKRECON
WHERE BILL_MONTH='201506' 
AND (LOCATION_CODE,BILL_NUMBER) IN (
SELECT M.LOCATION_CODE,D.BILL_NUMBER FROM PAYMENT_MST@AKRECON M,PAYMENT_DTL@AKRECON D
WHERE M.BATCH_NO=D.BATCH_NO
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE STATUS='A')))
