
SELECT * FROM  EPAY_PAYMENT_MST--@epay_srl
WHERE TO_CHAR(PAY_DATE,'RRRRMM')='202004'
AND org_BANK_CODE='94'
--and org_code='BPDB'
and status<>'T'
ORDER BY PAY_DATE DESC


SELECT * FROM  EPAY_PAYMENT_MST
WHERE TO_CHAR(PAY_DATE,'RRRRMM')='202004'
AND PAY_BANK_CODE='94'
ORDER BY PAY_DATE DESC
--and pay_date='24-


AND LOCATION_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE BILLING_DBLINK='BILLING_BOG')



SELECT * FROM PAYMENT_MST@EPAY_ROBI
WHERE TO_CHAR(PAY_DATE,'RRRRMM')='202004'
--AND PAY_BANK_CODE='97'
AND STATUS<>'T'

AND LOCATION_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE BILLING_DBLINK='BILLING_BOG')
ORDER BY PAY_DATE DESC


SELECT sum(nvl(PDB_AMOUNT,0)+nvl(GOVT_DUTY,0)),count(*) FROM PAYMENT_DTL@EPAY_ROBI
WHERE BATCH_NO IN (
SELECT BATCH_NO FROM PAYMENT_MST@EPAY_ROBI
WHERE TO_CHAR(PAY_DATE,'RRRRMM')='202002'
--AND PAY_BANK_CODE='97'
AND LOCATION_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE BILLING_DBLINK='BILLING_BOG')
)


SELECT * FROM EPAY_UTILITY_bILL
WHERE ACCOUNT_NUMBER='65582529'
ORDER BY BILL_MONTH DESC



SELECT *  FROM BC_RECEIPT_BATCH_HDR@billing_bog
where batch_num in (
SELECT BATCH_NUM_PDB  FROM EPAY_RECEIPT_BATCH_HDR_PDB
WHERE TO_CHAR(RECEIPT_DATE,'RRRRMM')='202002'
and bank_code='97'
AND LOCATION_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE BILLING_DBLINK='BILLING_BOG')
)



SELECT *  FROM BC_RECEIPT1_INT_DTL@BILLING_RONG
WHERE REC_INT_ID IN (SELECT REC_INT_ID FROM BC_RECEIPT1_INT_HDR@BILLING_RONG
WHERE BATCH_NUM in (
SELECT BATCH_NUM_PDB  FROM EPAY_RECEIPT_BATCH_HDR_PDB
WHERE TO_CHAR(RECEIPT_DATE,'RRRRMM')='202002'
and bank_code='97'
AND LOCATION_CODE IN (
SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE BILLING_DBLINK='BILLING_RONG')
)
)