


SELECT 1 M,COUNT(1) AS CNT,'ROBI' AS NAME FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L Z
WHERE M.BATCH_NO=D.BATCH_NO
AND Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')='201411' 
AND Z.ZONE_CODE='6'

SELECT 1 M,COUNT(1) AS CNT,'ROBI' AS NAME FROM VW_EPAY_PAYMENT_MST_DTL M,V_Z_C_C_L Z
WHERE Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')='201411'
AND Z.ZONE_CODE='6'
AND M.PAY_BANK_CODE='97'


-----

SELECT NAME1,CNT_ROBI,NAME2,CNT_PDB ,CNT_ROBI-CNT_PDB AS ROBI_UP,CNT_PDB-CNT_ROBI AS PDB_UP FROM (
SELECT COUNT(1) AS CNT_ROBI,'ROBI' AS NAME1 FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L Z
WHERE M.BATCH_NO=D.BATCH_NO
AND Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')='201412' 
AND Z.ZONE_CODE='6') A,(
SELECT COUNT(1) AS CNT_PDB,'PDB' AS NAME2 FROM VW_EPAY_PAYMENT_MST_DTL M,V_Z_C_C_L Z
WHERE Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')='201412'
AND Z.ZONE_CODE='6'
AND M.PAY_BANK_CODE='97') B


SELECT BILL_NUMBER FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L Z
WHERE M.BATCH_NO=D.BATCH_NO
AND Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')='201411' 
AND Z.ZONE_CODE='6'
MINUS
SELECT BILL_NUMBER FROM VW_EPAY_PAYMENT_MST_DTL M,V_Z_C_C_L Z
WHERE Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')='201411'
AND Z.ZONE_CODE='6'
AND M.PAY_BANK_CODE='97'



SELECT 'ROBI' AS SERVER_NAME,TO_CHAR(M.PAY_DATE,'dd-mm-rrrr') PAY_DATE,M.BATCH_NO,D.BILL_NUMBER,M.LOCATION_CODE,Z.LOCATION_NAME,D.PDB_AMOUNT,D.GOVT_DUTY VAT,D.TRANSACTION_ID FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L Z
WHERE M.BATCH_NO=D.BATCH_NO
AND Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:M 
AND Z.ZONE_CODE=:Z
AND (D.BILL_NUMBER,M.LOCATION_CODE,M.PAY_DATE) IN (
SELECT D.BILL_NUMBER,M.LOCATION_CODE,M.PAY_DATE FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L Z
WHERE M.BATCH_NO=D.BATCH_NO
AND Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:M 
AND Z.ZONE_CODE=:Z
GROUP BY  D.BILL_NUMBER,M.LOCATION_CODE,M.PAY_DATE HAVING COUNT(1)>1
) ORDER BY 4


SELECT 'BPDB' AS SERVER_NAME,TO_CHAR(M.PAY_DATE,'dd-mm-rrrr') PAY_DATE,M.BATCH_NO,M.BILL_NUMBER,M.LOCATION_CODE,Z.LOCATION_NAME,PDB_AMOUNT,GOVT_DUTY VAT,TRANSACTION_ID
 FROM VW_EPAY_PAYMENT_MST_DTL M,V_Z_C_C_L Z
WHERE Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:m
AND Z.ZONE_CODE=:z
AND M.PAY_BANK_CODE='97'
AND (M.BILL_NUMBER,M.LOCATION_CODE,M.PAY_DATE) IN (
SELECT D.BILL_NUMBER,M.LOCATION_CODE,M.PAY_DATE FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L Z
WHERE M.BATCH_NO=D.BATCH_NO
AND Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:m
AND Z.ZONE_CODE=:z
GROUP BY  D.BILL_NUMBER,M.LOCATION_CODE,M.PAY_DATE HAVING COUNT(1)>1
) ORDER BY 4



SELECT 'ROBI' AS SERVER_NAME,TO_CHAR(M.PAY_DATE,'dd-mm-rrrr') PAY_DATE,M.BATCH_NO,d.BILL_NUMBER,M.LOCATION_CODE,Z.LOCATION_NAME,PDB_AMOUNT,GOVT_DUTY VAT,TRANSACTION_ID,'BPDB Payment Missing' AS STATUS 
FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L Z
WHERE M.BATCH_NO=D.BATCH_NO
AND Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:M
AND Z.ZONE_CODE=:Z
AND (D.BILL_NUMBER,M.LOCATION_CODE,M.PAY_DATE) IN (
SELECT BILL_NUMBER,Z.LOCATION_CODE,M.PAY_DATE FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L Z
WHERE M.BATCH_NO=D.BATCH_NO
AND Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:M
AND Z.ZONE_CODE=:Z
MINUS
SELECT BILL_NUMBER,Z.LOCATION_CODE,M.PAY_DATE FROM VW_EPAY_PAYMENT_MST_DTL M,V_Z_C_C_L Z
WHERE Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:M
AND Z.ZONE_CODE=:Z
AND M.PAY_BANK_CODE='97')


SELECT 'BPDB' AS SERVER_NAME,TO_CHAR(M.PAY_DATE,'dd-mm-rrrr') PAY_DATE,M.BATCH_NO,m.BILL_NUMBER,M.LOCATION_CODE,Z.LOCATION_NAME,PDB_AMOUNT,GOVT_DUTY VAT,TRANSACTION_ID,'ROBI Payment Missing' AS STATUS FROM VW_EPAY_PAYMENT_MST_DTL M,V_Z_C_C_L Z
WHERE Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:M
AND Z.ZONE_CODE=:Z
AND M.PAY_BANK_CODE='97'
AND (M.BILL_NUMBER,M.LOCATION_CODE,M.PAY_DATE) IN (
SELECT BILL_NUMBER,Z.LOCATION_CODE,M.PAY_DATE FROM VW_EPAY_PAYMENT_MST_DTL M,V_Z_C_C_L Z
WHERE Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:M
AND Z.ZONE_CODE=:Z
AND M.PAY_BANK_CODE='97'
MINUS
SELECT BILL_NUMBER,Z.LOCATION_CODE,M.PAY_DATE FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L Z
WHERE M.BATCH_NO=D.BATCH_NO
AND Z.LOCATION_CODE=M.LOCATION_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:M 
AND Z.ZONE_CODE=:Z
)