
SELECT * FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201706'
AND ACCOUNT_NUMBER ='63231670'



SELECT * FROM UTILITY_BILL_pdb@epay_robi
WHERE BILL_MONTH='201706'
AND ACCOUNT_NUMBER ='63231670'

SELECT * FROM customer_master_data_pdb@epay_robi
WHERE ACCOUNT_NO ='63231670' 


SELECT * FROM epay_customer_master_data
WHERE ACCOUNT_NO ='63231670' 

BILL_MONTH='201706'

AND ACCOUNT_NO ='63231670'


INSERT INTO CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI
SELECT * FROM EPAY_CUSTOMER_MASTER_DATA
WHERE LOCATION_CODE=UPPER(:P_LOC)
AND ACCOUNT_NO IN (
SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA
WHERE LOCATION_CODE=UPPER(:P_LOC)
MINUS
SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI
WHERE LOCATION_CODE=UPPER(:P_LOC)
) 

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
SYSDATE CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE=UPPER(:P_LOC)) 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE=UPPER(:P_LOC)
AND DATA_TRANS_LOG1='T'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE=UPPER(:P_LOC))
AND BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE=UPPER(:P_LOC);

COMMIT;