
DELETE FROM   X ;

COMMIT;
  
INSERT INTO X  
 SELECT ACCOUNT_NUMBER,TOTAL_BILL_AMOUNT FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE=UPPER(:P_LOC)
AND DATA_TRANS_LOG1='T'
--AND DATA_TRANS_LOG2='T'
--AND DATA_TRANS_LOG3='T'
--AND DATA_TRANS_LOG4='T'
AND BILL_DUE_DATE>=TRUNC(SYSDATE)
MINUS
 SELECT ACCOUNT_NUMBER,TOTAL_BILL_AMOUNT FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE=UPPER(:P_LOC)

COMMIT;


DELETE  FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE=UPPER(:P_LOC)
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NUMBER FROM X)


COMMIT;


INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE=UPPER(:P_LOC)
AND DATA_TRANS_LOG1='T'
--AND DATA_TRANS_LOG2='T'
--AND DATA_TRANS_LOG3='T'
--AND DATA_TRANS_LOG4='T'
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NUMBER FROM X)


COMMIT;


COMMIT;





 SELECT * FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE=UPPER(:P_LOC)
AND ACCOUNT_NUMBER='61579989'


COMMIT;
