--2	Chittagong Zone
--3	Comilla Zone
--4	Sylhet Zone
--7	Mymensing Zone





select a.CENTER_NAME,TRANS_robi,ROBI_SRVR,(TRANS_robi-ROBI_SRVR) DIFF,UN_TRANS_robi from (
SELECT L.COMP_CNTR_NAME CENTER_NAME,
COUNT(DATA_TRANS_LOG1) TRANS_robi,
COUNT(DECODE(DATA_TRANS_LOG1,'N','1')) UN_TRANS_robi
FROM EPAY_UTILITY_BILL B,V_Z_C_C_L L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
--AND L.COMP_CNTR_CODE =:COMP_CNTR_CODE
AND L.ZONE_CODE =:ZONE_CODE
AND B.BILL_MONTH='202107'
GROUP BY L.COMP_CNTR_NAME)a,(
SELECT L.COMP_CNTR_NAME CENTER_NAME,COUNT(*) ROBI_SRVR
FROM UTILITY_BILL_PDB@EPAY_ROBI B,V_Z_C_C_L L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
--AND L.COMP_CNTR_CODE =:COMP_CNTR_CODE
AND L.ZONE_CODE =:ZONE_CODE
AND B.BILL_MONTH='202107'
GROUP BY L.COMP_CNTR_NAME)b
where a.CENTER_NAME = b.CENTER_NAME



Sylhet Computer Center	196623	196623	0	0
Moulovibazar Computer Center	53450	53450	0	0



SELECT P.CENTER_NAME,PDB_TOT_CONS,UN_TRANS_24,UN_TRANS_gp,UN_TRANS_robi,UN_TRANS_169,
TOT_CONS_24,TOT_CONS_169,TOT_CONS_ROBI,TOT_CONS_GP
 FROM (
SELECT L.COMP_CNTR_NAME CENTER_NAME,COUNT(*) PDB_TOT_CONS,
COUNT(DECODE(DATA_TRANS_LOG3,'N','1')) UN_TRANS_24,
COUNT(DECODE(DATA_TRANS_LOG2,'N','1')) UN_TRANS_gp,
COUNT(DECODE(DATA_TRANS_LOG1,'N','1')) UN_TRANS_robi,
COUNT(DECODE(DATA_TRANS_LOG4,'N','1')) UN_TRANS_169    
FROM EPAY_UTILITY_BILL B,V_Z_C_C_L L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND L.ZONE_CODE =:COMP_CNTR_CODE
--AND LO.ONLINE_OPT='GP'
AND B.BILL_MONTH='202107'
GROUP BY L.COMP_CNTR_NAME)P,(
SELECT L.COMP_CNTR_NAME CENTER_NAME,COUNT(*) TOT_CONS_24  
FROM EPAY_UTILITY_BILL@EPAY_SRL B,V_Z_C_C_L L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND L.ZONE_CODE =:COMP_CNTR_CODE
--AND LO.ONLINE_OPT='GP'
AND B.BILL_MONTH='202107'
GROUP BY L.COMP_CNTR_NAME) S,(
SELECT L.COMP_CNTR_NAME CENTER_NAME,COUNT(*) TOT_CONS_169  
FROM EPAY_UTILITY_BILL@EPAYMENT B,V_Z_C_C_L L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND L.ZONE_CODE =:COMP_CNTR_CODE
--AND LO.ONLINE_OPT='GP'
AND B.BILL_MONTH='202107'
GROUP BY L.COMP_CNTR_NAME)E,(
SELECT L.COMP_CNTR_NAME CENTER_NAME,COUNT(*) TOT_CONS_ROBI  
FROM UTILITY_BILL_PDB@EPAY_ROBI B,V_Z_C_C_L L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND L.ZONE_CODE =:COMP_CNTR_CODE
--AND LO.ONLINE_OPT='GP'
AND B.BILL_MONTH='202107'
GROUP BY L.COMP_CNTR_NAME) R,(
SELECT L.COMP_CNTR_NAME CENTER_NAME,COUNT(*) TOT_CONS_GP  
FROM UTILITY_BILL_PDB@EPAY_GP B,V_Z_C_C_L L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND L.ZONE_CODE =:COMP_CNTR_CODE
--AND LO.ONLINE_OPT='GP'
AND B.BILL_MONTH='202107'
GROUP BY L.COMP_CNTR_NAME)G
WHERE P.CENTER_NAME=S.CENTER_NAME
AND P.CENTER_NAME=E.CENTER_NAME
AND P.CENTER_NAME=R.CENTER_NAME
AND P.CENTER_NAME=G.CENTER_NAME
AND S.CENTER_NAME=E.CENTER_NAME
AND S.CENTER_NAME=R.CENTER_NAME
AND S.CENTER_NAME=G.CENTER_NAME
AND E.CENTER_NAME=R.CENTER_NAME
AND E.CENTER_NAME=G.CENTER_NAME
AND G.CENTER_NAME=R.CENTER_NAME












------------------robi---------------------

SELECT A.CENTER_NAME,PDB_TRANS,ROBI_CONS,NVL(PDB_TRANS,0)-NVL(ROBI_CONS,0) DIFF,UN_TRANS FROM (
SELECT L.CENTER_NAME CENTER_NAME,COUNT(DECODE(DATA_TRANS_LOG1,'T','1')) PDB_TRANS,COUNT(DECODE(DATA_TRANS_LOG1,'N','1')) UN_TRANS FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L,EPAY_LOC_ONLINE_OPT_MAP LO
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.LOCATION_CODE=LO.LOCATION_CODE
AND L.LOCATION_CODE = LO.LOCATION_CODE
AND LO.STATUS='A'
--AND L.CENTER_NAME='COMILLA'
--AND L.CENTER_NAME in ('CHITTAGONG','COMILLA')
--AND L.CENTER_NAME in ('TANGAIL','MYMENSING','KISHOREGANJ','JAMALPUR')
--AND L.CENTER_NAME in ('SYLHET','MOULAVIBAZAR')
AND LO.ONLINE_OPT='ROBI'
AND B.BILL_MONTH='202107'
GROUP BY L.CENTER_NAME)A,(
SELECT L.CENTER_NAME CENTER_NAME,count(*) ROBI_CONS FROM UTILITY_BILL_pdb@epay_robi B,EPAY_LOCATION_MASTER L 
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='202107'
--AND L.CENTER_NAME='COMILLA'
--AND L.CENTER_NAME in ('CHITTAGONG','COMILLA')
--AND L.CENTER_NAME in ('TANGAIL','MYMENSING','KISHOREGANJ','JAMALPUR')
--AND L.CENTER_NAME in ('SYLHET','MOULAVIBAZAR')
group by L.CENTER_NAME)B
WHERE A.CENTER_NAME = B.CENTER_NAME
ORDER BY 1

/*


SELECT A.CENTER_NAME,PDB_TRANS,GP_CONS,NVL(PDB_TRANS,0)-NVL(GP_CONS,0) DIFF,UN_TRANS FROM (
SELECT L.CENTER_NAME CENTER_NAME,COUNT(DECODE(DATA_TRANS_LOG2,'T','1')) PDB_TRANS,COUNT(DECODE(DATA_TRANS_LOG2,'N','1')) UN_TRANS 
FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L,EPAY_LOC_ONLINE_OPT_MAP LO
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.LOCATION_CODE=LO.LOCATION_CODE
AND L.LOCATION_CODE = LO.LOCATION_CODE
AND LO.STATUS='A'
AND LO.ONLINE_OPT='GP'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM V_Z_C_C_L WHERE ZONE_CODE=:ZONE)
AND B.BILL_MONTH='202012'
GROUP BY L.CENTER_NAME)A,(
SELECT L.CENTER_NAME CENTER_NAME,count(*) GP_CONS FROM UTILITY_BILL_pdb@epay_GP B,EPAY_LOCATION_MASTER L 
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='202012'
AND B.LOCATION_CODE IN (SELECT LOCATION_CODE FROM V_Z_C_C_L WHERE ZONE_CODE=:ZONE)
--L.CENTER_NAME in ('COMILLA')
group by L.CENTER_NAME)B
WHERE A.CENTER_NAME = B.CENTER_NAME
--ORDER BY 1
*/

CHITTAGONG	238994	239004	-10	52328
COMILLA	77834	77835	-1	15910

-------------------------gp-------------------------


SELECT A.CENTER_NAME,PDB_TRANS,GP_CONS,NVL(PDB_TRANS,0)-NVL(GP_CONS,0) DIFF,UN_TRANS FROM (
SELECT L.CENTER_NAME CENTER_NAME,COUNT(DECODE(DATA_TRANS_LOG2,'T','1')) PDB_TRANS,COUNT(DECODE(DATA_TRANS_LOG2,'N','1')) UN_TRANS FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L,EPAY_LOC_ONLINE_OPT_MAP LO
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.LOCATION_CODE=LO.LOCATION_CODE
AND L.LOCATION_CODE = LO.LOCATION_CODE
AND LO.STATUS='A'
AND LO.ONLINE_OPT='GP'
AND B.BILL_MONTH='202107'
GROUP BY L.CENTER_NAME)A,(
SELECT L.CENTER_NAME CENTER_NAME,count(*) GP_CONS FROM UTILITY_BILL_pdb@epay_GP B,EPAY_LOCATION_MASTER L 
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='202107'
group by L.CENTER_NAME)B
WHERE A.CENTER_NAME = B.CENTER_NAME
ORDER BY 1

---------------SRL-NESCO-------
--11	Dinajpur Computer Center
--09	Rangpur Computer Center
--05	Bogra Computer Center
--06	Naogaon Computer Center

SELECT A.CENTER_NAME,PDB_TRANS,SRL_CONS,NVL(PDB_TRANS,0)-NVL(SRL_CONS,0) DIFF,UN_TRANS FROM (
SELECT L.CENTER_NAME CENTER_NAME,COUNT(DECODE(DATA_TRANS_LOG3,'T','1')) PDB_TRANS,COUNT(DECODE(DATA_TRANS_LOG3,'N','1')) UN_TRANS FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
--AND L.CENTER_NAME in ('DINAJPUR','RANGPUR')
--AND L.CENTER_NAME='COMILLA'
--AND L.CENTER_NAME in ('CHITTAGONG','TANGAIL','SYLHET','MOULAVIBAZAR','MYMENSING','KISHOREGANJ','COMILLA','JAMALPUR')
AND B.BILL_MONTH='202107'
GROUP BY L.CENTER_NAME)A,(
SELECT L.CENTER_NAME CENTER_NAME,count(*) SRL_CONS FROM EPAY_UTILITY_BILL@epay_SRL B,EPAY_LOCATION_MASTER L 
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='202107'
--AND L.CENTER_NAME in ('DINAJPUR','RANGPUR')
--AND L.CENTER_NAME='COMILLA'
--AND L.CENTER_NAME in ('CHITTAGONG','TANGAIL','SYLHET','MOULAVIBAZAR','MYMENSING','KISHOREGANJ','COMILLA','JAMALPUR')
group by L.CENTER_NAME)B
WHERE A.CENTER_NAME = B.CENTER_NAME
ORDER BY 1

----------------EPAYMENT-------------

SELECT A.CENTER_NAME,PDB_TRANS,EPY169_CONS,NVL(PDB_TRANS,0)-NVL(EPY169_CONS,0) DIFF,UN_TRANS FROM (
SELECT L.CENTER_NAME CENTER_NAME,COUNT(DECODE(DATA_TRANS_LOG4,'T','1')) PDB_TRANS,COUNT(DECODE(DATA_TRANS_LOG4,'N','1')) UN_TRANS FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
--AND L.CENTER_NAME='COMILLA'-- in ('CHITTAGONG','TANGAIL','SYLHET','MOULAVIBAZAR','MYMENSING','KISHOREGANJ','COMILLA','JAMALPUR')
AND B.BILL_MONTH='202103'
GROUP BY L.CENTER_NAME)A,(
SELECT L.CENTER_NAME CENTER_NAME,count(*) EPY169_CONS FROM EPAY_UTILITY_BILL@epayMENT B,EPAY_LOCATION_MASTER L 
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='202103'
--AND L.CENTER_NAME='COMILLA'-- in ('CHITTAGONG','TANGAIL','SYLHET','MOULAVIBAZAR','MYMENSING','KISHOREGANJ','COMILLA','JAMALPUR')
group by L.CENTER_NAME)B
WHERE A.CENTER_NAME = B.CENTER_NAME
ORDER BY 1


-----------------------------PDB---------------


SELECT A.CENTER_NAME,PDB_TRANS,SRL_CONS,NVL(PDB_TRANS,0)-NVL(SRL_CONS,0) DIFF,UN_TRANS FROM (
SELECT L.CENTER_NAME CENTER_NAME,COUNT(DECODE(DATA_TRANS_LOG3,'T','1')) PDB_TRANS,COUNT(DECODE(DATA_TRANS_LOG3,'N','1')) UN_TRANS FROM EPAY_UTILITY_BILL B,EPAY_LOCATION_MASTER L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND L.CENTER_NAME NOT in ('DINAJPUR','RANGPUR','BOGRA','NAOGAON')
--AND LO.ONLINE_OPT='GP'
AND B.BILL_MONTH='202012'
GROUP BY L.CENTER_NAME)A,(
SELECT L.CENTER_NAME CENTER_NAME,count(*) SRL_CONS FROM EPAY_UTILITY_BILL@epay_SRL B,EPAY_LOCATION_MASTER L 
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='202012'
AND L.CENTER_NAME NOT in ('DINAJPUR','RANGPUR','BOGRA','NAOGAON')
group by L.CENTER_NAME)B
WHERE A.CENTER_NAME = B.CENTER_NAME
ORDER BY 1






select count(*) from epay_utility_bill
where bill_month='202012'
and location_code in (select location_code from epay_location_master where billing_dblink='BILLING_TANG')
and data_trans_log1='N'


select count(*) from utility_bill_pdb@epay_robi
where bill_month='202012'
and location_code in (select location_code from epay_location_master where billing_dblink='BILLING_TANG')

------------------

SELECT 'ROBI',A.CENTER_NAME,PDB_TRANS,ROBI_CONS,NVL(PDB_TRANS,0)-NVL(ROBI_CONS,0) DIFF,UN_TRANS FROM (
SELECT L.COMP_CNTR_NAME CENTER_NAME,COUNT(DECODE(DATA_TRANS_LOG1,'T','1')) PDB_TRANS,COUNT(DECODE(DATA_TRANS_LOG1,'N','1')) UN_TRANS FROM EPAY_UTILITY_BILL B,V_Z_C_C_L L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND L.COMP_CNTR_CODE='04'
AND B.BILL_MONTH='202012'
GROUP BY L.COMP_CNTR_NAME)A,(
SELECT L.COMP_CNTR_NAME CENTER_NAME,count(*) ROBI_CONS FROM UTILITY_BILL_pdb@epay_robi B,V_Z_C_C_L L 
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='202012'
AND L.COMP_CNTR_CODE='04'
group by L.COMP_CNTR_NAME)B
WHERE A.CENTER_NAME = B.CENTER_NAME
UNION
SELECT 'SRL',A.CENTER_NAME,PDB_TRANS,ROBI_CONS,NVL(PDB_TRANS,0)-NVL(ROBI_CONS,0) DIFF,UN_TRANS FROM (
SELECT L.COMP_CNTR_NAME CENTER_NAME,COUNT(DECODE(DATA_TRANS_LOG1,'T','1')) PDB_TRANS,COUNT(DECODE(DATA_TRANS_LOG1,'N','1')) UN_TRANS FROM EPAY_UTILITY_BILL B,V_Z_C_C_L L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND L.COMP_CNTR_CODE='04'
AND B.BILL_MONTH='202012'
GROUP BY L.COMP_CNTR_NAME)A,(
SELECT L.COMP_CNTR_NAME CENTER_NAME,count(*) ROBI_CONS FROM EPAY_UTILITY_BILL@EPAY_SRL B,V_Z_C_C_L L 
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='202012'
AND L.COMP_CNTR_CODE='04'
group by L.COMP_CNTR_NAME)B
WHERE A.CENTER_NAME = B.CENTER_NAME
UNION
SELECT 'EPAYMENT',A.CENTER_NAME,PDB_TRANS,ROBI_CONS,NVL(PDB_TRANS,0)-NVL(ROBI_CONS,0) DIFF,UN_TRANS FROM (
SELECT L.COMP_CNTR_NAME CENTER_NAME,COUNT(DECODE(DATA_TRANS_LOG1,'T','1')) PDB_TRANS,COUNT(DECODE(DATA_TRANS_LOG1,'N','1')) UN_TRANS FROM EPAY_UTILITY_BILL B,V_Z_C_C_L L
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND L.COMP_CNTR_CODE='04'
AND B.BILL_MONTH='202012'
GROUP BY L.COMP_CNTR_NAME)A,(
SELECT L.COMP_CNTR_NAME CENTER_NAME,count(*) ROBI_CONS FROM EPAY_UTILITY_BILL@EPAYMENT B,V_Z_C_C_L L 
WHERE B.LOCATION_CODE=L.LOCATION_CODE
AND B.BILL_MONTH='202012'
AND L.COMP_CNTR_CODE='04'
group by L.COMP_CNTR_NAME)B
WHERE A.CENTER_NAME = B.CENTER_NAME
ORDER BY 1

