

SELECT ERROR_TXT,BILL_NUMBER,LOCATION_CODE FROM VW_EPAY_RECON_UNSUC_OPT_ERR
WHERE BANK_CODE='96'
and location_code=upper('t3')
and trunc(run_date)=trunc(sysdate)
GROUP BY ERROR_TXT,BILL_NUMBER,LOCATION_CODE
ORDER BY LOCATION_CODE


---------------Payment data is less than bill data--------------


SELECT EPAY.DFN_PAYMENT_DATA_LESS (:P_BILL_MONTH ,:P_BILL_NO ,:P_LOC_CODE ,:P_BANK_CODE ) FROM DUAL

-------------OR----------

SELECT 'SELECT EPAY.DFN_PAYMENT_DATA_LESS ('''||BILL_MONTH||''','''||BILL_NUMBER||''','''||LOCATION_CODE||''','''||bank_code||''' )'||' FROM DUAL'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"  
FROM (
select '202104' BILL_MONTH, BILL_NUMBER,LOCATION_CODE,bank_code from VW_EPAY_RECON_UNSUC_OPT_ERR
where bank_code='96' 
--and location_code='H4'
and ERROR_TXT like '%Payment data is less than bill data%'
group by bill_number,LOCATION_CODE,bank_code
)


-------------------------This bill no does not exist on BPDB----------------


select EPAY.DFN_ThisBill_DoesNot_Exist (:P_LOC_CODE,:P_BATCH_NO ) from dual

SELECT 'SELECT EPAY.DFN_ThisBill_DoesNot_Exist ('''||LOCATION_CODE||''','''||BATCH_NO||''')'||' FROM DUAL'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"  
FROM (
select LOCATION_CODE, BATCH_NO from VW_EPAY_RECON_UNSUC_OPT_ROBI
group by LOCATION_CODE, BATCH_NO
)


SELECT CENTER_NAME,COUNT(1) FROM VW_EPAY_RECON_UNSUC_OPT_ERR
WHERE ERROR_TYPE='PAYMVALD'
AND ERROR_TXT LIKE '%This bill no does not exist on BPDB%'
--AND CENTER_NAME<>'TANGAIL' 
--AND BANK_CODE='96'
GROUP BY CENTER_NAME

TANGAIL	
MYMENSING	

CHITTAGONG

DELETE EPAY_UTILITY_BILL_INT;


COMMIT;

INSERT INTO EPAY_UTILITY_BILL_INT
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  NULL BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0,'N' AS DATA_TRANS_LOG,'T' AS DATA_TRANS_LOG1,'N' AS DATA_TRANS_LOG2,
 'T' AS DATA_TRANS_LOG3,'T' AS DATA_TRANS_LOG4,'N' AS DATA_TRANS_LOG5 
 FROM BC_BILL_IMAGE@BILLING_COM
 WHERE --BILL_CYCLE_CODE=:P_BILL_MONTH AND 
--TARIFF IN ('A','C','B','D','E','J')
--AND 
INVOICE_NUM IN (
SELECT SUBSTR(BILL_NUMBER,1,9) FROM VW_EPAY_RECON_UNSUC_OPT_ERR
WHERE ERROR_TYPE='PAYMVALD'
AND ERROR_TXT LIKE '%This bill no does not exist on BPDB%'
AND CENTER_NAME='COMILLA'
)


COMMIT;

INSERT INTO EPAY_UTILITY_BILL
SELECT * FROM EPAY_UTILITY_BILL_INT


COMMIT;

------------------------------------------------
ERROR THEN BELOW SQL EXEXUTE

DELETE FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH=:BILL_MONTH
AND  (ACCOUNT_NUMBER) IN (
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL_INT)

commit;

