               SELECT * FROM (
                SELECT  Z.ZONE_CODE||'-'||Z.ZONE_NAME AS ZONE_NAME,
                IM.PAY_BANK_CODE||'-'||B.BANK_NAME AS BANK_NAME,TO_CHAR(IM.PAY_DATE,'dd-mm-yyyy') AS PAY_DATE,
                TO_CHAR(SUM(NVL(ID.GOVT_DUTY,0)),'999999999.99') VAT_AMOUNT,TO_CHAR(SUM(NVL(ID.PDB_AMOUNT,0)),'999999999.99') AS TOTAL_AMOUNT,
                TO_CHAR(SUM(NVL(ID.PDB_AMOUNT,0)+NVL(ID.GOVT_DUTY,0)),'999999999.99') AS TOTAL_UTILITY,         COUNT(1) AS NO_OF_CON 
                FROM EPAY_PAYMENT_MST IM,EPAY_PAYMENT_DTL ID,EPAY_LOCATION_MASTER L,EPAY_BANKS B,EPAY_BANK_BRANCHES BR,V_Z_C_C_L Z,EPAY_USER_MST U, EPAY_ACCESS_ALLOW_MAP M
                WHERE IM.BATCH_NO=ID.BATCH_NO
                AND IM.LOCATION_CODE=L.LOCATION_CODE
                AND IM.LOCATION_CODE=Z.LOCATION_CODE
                AND L.LOCATION_CODE=Z.LOCATION_CODE
                AND IM.LOCATION_CODE=BR.LOCATION_CODE
                AND IM.PAY_BANK_CODE=B.BANK_CODE
                 AND IM.STATUS IN ('P','T')
                AND L.STATUS='A'
                AND M.STATUS='A'
                AND B.BANK_CODE=BR.BANK_CODE
                AND IM.PAY_BANK_CODE=BR.BANK_CODE
                AND B.BANK_CODE=M.BANK_CODE
                AND M.BANK_CODE=BR.BANK_CODE
                --AND B.BANK_CODE=U.BANK_CODE
                --AND IM.PAY_BANK_CODE=U.BANK_CODE
                AND B.BANK_CODE='97'
                AND UPPER(U.USER_NAME)=UPPER(M.USER_DESC)
                AND U.USER_NAME='FARUQ'
                AND Z.ZONE_CODE=M.ZONE_CODE
                AND Z.ZONE_CODE LIKE DECODE(:P_ZONE_CODE,'ALL','%',:P_ZONE_CODE)
--                AND IM.PAY_DATE>=:P_START_PAY_DATE
--                AND IM.PAY_DATE<=:P_END_PAY_DATE
                AND TO_CHAR(IM.PAY_DATE,'yyyymm')=:P_PAYMENT_MONTH
                GROUP BY  Z.ZONE_CODE||'-'||Z.ZONE_NAME ,IM.PAY_BANK_CODE||'-'||B.BANK_NAME,IM.PAY_DATE
                --ORDER BY to_char(IM.PAY_DATE,'dd-mm-yyyy')
                UNION
                                SELECT  'Total : ' AS ZONE_NAME,
                NULL AS BANK_NAME,NULL PAY_DATE,
                TO_CHAR(SUM(NVL(ID.GOVT_DUTY,0)),'999999999.99') VAT_AMOUNT,TO_CHAR(SUM(NVL(ID.PDB_AMOUNT,0)),'999999999.99') AS TOTAL_AMOUNT,
                TO_CHAR(SUM(NVL(ID.PDB_AMOUNT,0)+NVL(ID.GOVT_DUTY,0)),'999999999.99') AS TOTAL_UTILITY,         COUNT(1) AS NO_OF_CON 
                FROM EPAY_PAYMENT_MST IM,EPAY_PAYMENT_DTL ID,EPAY_LOCATION_MASTER L,EPAY_BANKS B,EPAY_BANK_BRANCHES BR,V_Z_C_C_L Z,EPAY_USER_MST U, EPAY_ACCESS_ALLOW_MAP M
                WHERE IM.BATCH_NO=ID.BATCH_NO
                AND IM.LOCATION_CODE=L.LOCATION_CODE
                AND IM.LOCATION_CODE=Z.LOCATION_CODE
                AND L.LOCATION_CODE=Z.LOCATION_CODE
                AND IM.LOCATION_CODE=BR.LOCATION_CODE
                AND IM.PAY_BANK_CODE=B.BANK_CODE
                 AND IM.STATUS IN ('P','T')
                AND L.STATUS='A'
                AND M.STATUS='A'
                AND B.BANK_CODE=BR.BANK_CODE
                AND IM.PAY_BANK_CODE=BR.BANK_CODE
                AND B.BANK_CODE=M.BANK_CODE
                AND M.BANK_CODE=BR.BANK_CODE
                --AND B.BANK_CODE=U.BANK_CODE
                --AND IM.PAY_BANK_CODE=U.BANK_CODE
                AND B.BANK_CODE='97'
                AND UPPER(U.USER_NAME)=UPPER(M.USER_DESC)
                AND U.USER_NAME='FARUQ'
                AND Z.ZONE_CODE=M.ZONE_CODE
                AND Z.ZONE_CODE LIKE DECODE(:P_ZONE_CODE,'ALL','%',:P_ZONE_CODE)
--                AND IM.PAY_DATE>=:P_START_PAY_DATE
--                AND IM.PAY_DATE<=:P_END_PAY_DATE
                AND TO_CHAR(IM.PAY_DATE,'yyyymm')=:P_PAYMENT_MONTH
                --GROUP BY  Z.ZONE_CODE||'-'||Z.ZONE_NAME ,IM.PAY_BANK_CODE||'-'||B.BANK_NAME,IM.PAY_DATE
                )
                ORDER BY PAY_DATE