
SELECT RM.RI_MST_ID, 'R'||'&'||'I Sys No: '||RM.RI_NO||CHR(10)||'R'||'&'||'I User No: '||RM.RI_USER_NO AS RI_SYS_RI_USER,'RI Date'||RM.RI_DATE||CHR(10)||'Pur. Date'||PM.PO_DATE AS RI_PUR_DATE,
PM.PO_NO,'Supplier '||SM.SUP_DESC||CHR(10)||'Pur. User. No.'||PM.PO_USER_NO AS SUP_PUR_USE_NO,RS.LEDG_NO,(IM.ITEM_DESC||'-'||RD.ITEM_CODE||', '||M.MSR_UNIT_DESC)||
'Part No,  Size:'||IM.ITEM_PART_NO||IM.ITEM_SIZE ITEM_PART_NO_SIZ,RD.RI_ACCEPT_QTY,RD.UNIT_COST,(RD.RI_ACCEPT_QTY*RD.UNIT_COST) AS TOTAL
FROM ST_RI_MST RM,ST_RI_DTL RD,ST_PO_MST PM,SFS.SUPPLIER_MST SM,ST_RI_STORAGE RS,ST_ITEM_MST IM,MEASURE_UNIT M
WHERE RM.RI_MST_ID=RD.RI_MST_ID
AND RD.PO_NO=PM.PO_NO
AND RM.SUP_CODE=SM.SUP_CODE
AND RM.RI_MST_ID=RS.RI_MST_ID
AND RD.RI_DTL_ID=RS.RI_DTL_ID
AND RD.ITEM_CODE=IM.ITEM_CODE
AND RD.MSR_UNIT_CODE=M.MSR_UNIT_CODE