Feb-18    126955    114325997.93
Jan-18    128206    129881284.94

70312    74389895.06
67834    80326878.51

SELECT A.*,B.* --A.MONTH,A.no_of_consumer_GP,B.no_of_consumer_ROBI,A.BPDB_AMOUNT_GP,B.BPDB_AMOUNT_ROBI,A.no_of_consumer_GP+B.no_of_consumer_ROBI TOTAL_CUSTOMERS,SUM(A.BPDB_AMOUNT_GP+B.BPDB_AMOUNT_ROBI) TOTAL_AMOUNT_BPDB 
FROM (
SELECT 1 SOURCE,TO_CHAR(M.PAY_DATE,'Mon-RR')  MONTH,COUNT(*) NO_OF_CONSUMER_GP,SUM(NVL(D.PDB_AMOUNT,0)) BPDB_AMOUNT_GP FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND TO_CHAR(M.PAY_DATE,'RRRRMM')>=:P_START_MONTH
AND TO_CHAR(M.PAY_DATE,'RRRRMM')<=:P_END_MONTH
AND M.PAY_BANK_CODE='96'
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC WHERE ZONE_CODE='2')
GROUP BY TO_CHAR(M.PAY_DATE,'Mon-RR')
)A,(

SELECT 1 SOURCE, TO_CHAR(M.PAY_DATE,'Mon-RR')  MONTH,COUNT(*) NO_OF_CONSUMER_ROBI,SUM(NVL(D.PDB_AMOUNT,0)) BPDB_AMOUNT_ROBI FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND TO_CHAR(M.PAY_DATE,'RRRRMM')>=:P_START_MONTH
AND TO_CHAR(M.PAY_DATE,'RRRRMM')<=:P_END_MONTH
AND M.PAY_BANK_CODE='97'
AND M.LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC WHERE ZONE_CODE='2')
GROUP BY TO_CHAR(M.PAY_DATE,'Mon-RR')


) B WHERE A.SOURCE=B.SOURCE





GROUP BY A.MONTH,A.no_of_consumer_GP,B.no_of_consumer_ROBI,A.BPDB_AMOUNT_GP,B.BPDB_AMOUNT_ROBI

--------date--between----

SELECT C.ZONE_NAME,C.COMP_CNTR_NAME,TO_CHAR(M.PAY_DATE,'Mon-RR')  MONTH, 
SUM(DECODE(M.PAY_BANK_CODE,'96',1,M.PAY_BANK_CODE,0)) NO_OF_CONSUMER_GP,SUM(DECODE(M.PAY_BANK_CODE,'96',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))  BPDB_AMOUNT_GP,
SUM(DECODE(M.PAY_BANK_CODE,'97',1,M.PAY_BANK_CODE,0)) NO_OF_CONSUMER_ROBI,SUM(DECODE(M.PAY_BANK_CODE,'97',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))  BPDB_AMOUNT_ROBI,
SUM(DECODE(M.PAY_BANK_CODE,'96',1,M.PAY_BANK_CODE,0))+SUM(DECODE(M.PAY_BANK_CODE,'97',1,M.PAY_BANK_CODE,0)) TOTAL_CUSTOMER,
SUM(DECODE(M.PAY_BANK_CODE,'96',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))+SUM(DECODE(M.PAY_BANK_CODE,'97',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0)) TOTAL_AMOUNT_BPDB
FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D,V_Z_C_C_L C
WHERE M.BATCH_NO=D.BATCH_NO
AND M.LOCATION_CODE=C.LOCATION_CODE
AND C.ZONE_CODE=:P_ZONE_CODE
AND C.COMP_CNTR_CODE=:P_COMP_CNTR_CODE
AND TO_CHAR(M.PAY_DATE,'RRRRMM')>=:P_START_MONTH
AND TO_CHAR(M.PAY_DATE,'RRRRMM')<=:P_END_MONTH
AND M.PAY_BANK_CODE IN ('96','97')
GROUP BY  C.ZONE_NAME,C.COMP_CNTR_NAME,TO_CHAR(M.PAY_DATE,'Mon-RR')
UNION
SELECT C.ZONE_NAME,C.COMP_CNTR_NAME,TO_CHAR(M.PAY_DATE,'Mon-RR')  MONTH, 
SUM(DECODE(M.PAY_BANK_CODE,'97',1,M.PAY_BANK_CODE,0)) NO_OF_CONSUMER_ROBI,SUM(DECODE(M.PAY_BANK_CODE,'97',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))  BPDB_AMOUNT_ROBI,
SUM(DECODE(M.PAY_BANK_CODE,'96',1,M.PAY_BANK_CODE,0)) NO_OF_CONSUMER_GP,SUM(DECODE(M.PAY_BANK_CODE,'96',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))  BPDB_AMOUNT_GP,
SUM(DECODE(M.PAY_BANK_CODE,'96',1,M.PAY_BANK_CODE,0))+SUM(DECODE(M.PAY_BANK_CODE,'97',1,M.PAY_BANK_CODE,0)) TOTAL_CUSTOMER,
SUM(DECODE(M.PAY_BANK_CODE,'96',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))+SUM(DECODE(M.PAY_BANK_CODE,'97',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0)) TOTAL_AMOUNT_BPDB
FROM EPAYMENT.EPAY_PAYMENT_MST_HSTR M,EPAYMENT.EPAY_PAYMENT_DTL_HSTR D,V_Z_C_C_L C
WHERE M.BATCH_NO=D.BATCH_NO
AND M.LOCATION_CODE=C.LOCATION_CODE
AND C.ZONE_CODE=:P_ZONE_CODE
AND C.COMP_CNTR_CODE=:P_COMP_CNTR_CODE
AND TO_CHAR(M.PAY_DATE,'RRRRMM')>=:P_START_MONTH
AND TO_CHAR(M.PAY_DATE,'RRRRMM')<=:P_END_MONTH
AND M.PAY_BANK_CODE IN ('96','97')
GROUP BY  C.ZONE_NAME,C.COMP_CNTR_NAME,TO_CHAR(M.PAY_DATE,'Mon-RR')
ORDER BY 3 asc








SELECT * FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND TO_CHAR(M.PAY_DATE,'RRRRMM')=:p_Month



SELECT * FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND TO_CHAR(M.PAY_DATE,'RRRRMM')=:p_Month



SELECT A.MONTH,A.NO_OF_CONSUMER_GP,B.NO_OF_CONSUMER_ROBI,A.BPDB_AMOUNT_GP,B.BPDB_AMOUNT_ROBI,SUM( A.NO_OF_CONSUMER_GP+B.NO_OF_CONSUMER_ROBI) TOT_CONS,
SUM(A.BPDB_AMOUNT_GP+B.BPDB_AMOUNT_ROBI) TOT_PDB_AMT FROM (
SELECT C.ZONE_NAME,C.COMP_CNTR_NAME,TO_CHAR(M.PAY_DATE,'Mon-RR')  MONTH, 
SUM(DECODE(M.PAY_BANK_CODE,'96',1,M.PAY_BANK_CODE,0)) NO_OF_CONSUMER_GP,SUM(DECODE(M.PAY_BANK_CODE,'96',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))  BPDB_AMOUNT_GP,
SUM(DECODE(M.PAY_BANK_CODE,'97',1,M.PAY_BANK_CODE,0)) NO_OF_CONSUMER_ROBI,SUM(DECODE(M.PAY_BANK_CODE,'97',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))  BPDB_AMOUNT_ROBI,
SUM(DECODE(M.PAY_BANK_CODE,'96',1,M.PAY_BANK_CODE,0))+SUM(DECODE(M.PAY_BANK_CODE,'97',1,M.PAY_BANK_CODE,0)) TOTAL_CUSTOMER,
SUM(DECODE(M.PAY_BANK_CODE,'96',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))+SUM(DECODE(M.PAY_BANK_CODE,'97',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0)) TOTAL_AMOUNT_BPDB
FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D,V_Z_C_C_L C
WHERE M.BATCH_NO=D.BATCH_NO
AND M.LOCATION_CODE=C.LOCATION_CODE
AND C.ZONE_CODE=:P_ZONE_CODE
AND C.COMP_CNTR_CODE=:P_COMP_CNTR_CODE
AND TO_CHAR(M.PAY_DATE,'RRRRMM')>=:P_START_MONTH
AND TO_CHAR(M.PAY_DATE,'RRRRMM')<=:P_END_MONTH
AND M.PAY_BANK_CODE IN ('96','97')
GROUP BY  C.ZONE_NAME,C.COMP_CNTR_NAME,TO_CHAR(M.PAY_DATE,'Mon-RR'))A,(
SELECT C.ZONE_NAME,C.COMP_CNTR_NAME,TO_CHAR(M.PAY_DATE,'Mon-RR')  MONTH, 
SUM(DECODE(M.PAY_BANK_CODE,'97',1,M.PAY_BANK_CODE,0)) NO_OF_CONSUMER_ROBI,SUM(DECODE(M.PAY_BANK_CODE,'97',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))  BPDB_AMOUNT_ROBI,
SUM(DECODE(M.PAY_BANK_CODE,'96',1,M.PAY_BANK_CODE,0)) NO_OF_CONSUMER_GP,SUM(DECODE(M.PAY_BANK_CODE,'96',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))  BPDB_AMOUNT_GP,
SUM(DECODE(M.PAY_BANK_CODE,'96',1,M.PAY_BANK_CODE,0))+SUM(DECODE(M.PAY_BANK_CODE,'97',1,M.PAY_BANK_CODE,0)) TOTAL_CUSTOMER,
SUM(DECODE(M.PAY_BANK_CODE,'96',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))+SUM(DECODE(M.PAY_BANK_CODE,'97',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0)) TOTAL_AMOUNT_BPDB
FROM EPAYMENT.EPAY_PAYMENT_MST_HSTR M,EPAYMENT.EPAY_PAYMENT_DTL_HSTR D,V_Z_C_C_L C
WHERE M.BATCH_NO=D.BATCH_NO
AND M.LOCATION_CODE=C.LOCATION_CODE
AND C.ZONE_CODE=:P_ZONE_CODE
AND C.COMP_CNTR_CODE=:P_COMP_CNTR_CODE
AND TO_CHAR(M.PAY_DATE,'RRRRMM')>=:P_START_MONTH
AND TO_CHAR(M.PAY_DATE,'RRRRMM')<=:P_END_MONTH
AND M.PAY_BANK_CODE IN ('96','97')
GROUP BY  C.ZONE_NAME,C.COMP_CNTR_NAME,TO_CHAR(M.PAY_DATE,'Mon-RR'))B
GROUP BY A.MONTH,A.NO_OF_CONSUMER_GP,B.NO_OF_CONSUMER_ROBI,A.BPDB_AMOUNT_GP,B.BPDB_AMOUNT_ROBI
ORDER BY 1 asc

----------divition wise--------------


SELECT C.ZONE_NAME,C.COMP_CNTR_NAME,C.LOCATION_NAME, TO_CHAR(M.PAY_DATE,'RRRRMM')  MONTH, 
SUM(DECODE(M.PAY_BANK_CODE,'96',1,M.PAY_BANK_CODE,0)) NO_OF_CONSUMER_GP,SUM(DECODE(M.PAY_BANK_CODE,'96',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))  BPDB_AMOUNT_GP,
SUM(DECODE(M.PAY_BANK_CODE,'97',1,M.PAY_BANK_CODE,0)) NO_OF_CONSUMER_ROBI,SUM(DECODE(M.PAY_BANK_CODE,'97',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))  BPDB_AMOUNT_ROBI,
SUM(DECODE(M.PAY_BANK_CODE,'96',1,M.PAY_BANK_CODE,0))+SUM(DECODE(M.PAY_BANK_CODE,'97',1,M.PAY_BANK_CODE,0)) TOTAL_CUSTOMER,
SUM(DECODE(M.PAY_BANK_CODE,'96',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))+SUM(DECODE(M.PAY_BANK_CODE,'97',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0)) TOTAL_AMOUNT_BPDB
FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D,V_Z_C_C_L C
WHERE M.BATCH_NO=D.BATCH_NO
AND M.LOCATION_CODE=C.LOCATION_CODE
AND C.ZONE_CODE=:P_ZONE_CODE
AND C.COMP_CNTR_CODE=:P_COMP_CNTR_CODE
AND TO_CHAR(M.PAY_DATE,'RRRRMM')=:P_START_MONTH
--AND TO_CHAR(M.PAY_DATE,'RRRRMM')<=:P_END_MONTH
AND M.PAY_BANK_CODE IN ('96','97')
GROUP BY  C.ZONE_NAME,C.COMP_CNTR_NAME,C.LOCATION_NAME,TO_CHAR(M.PAY_DATE,'RRRRMM')
UNION
SELECT C.ZONE_NAME,C.COMP_CNTR_NAME,C.LOCATION_NAME,TO_CHAR(M.PAY_DATE,'RRRRMM')  MONTH, 
SUM(DECODE(M.PAY_BANK_CODE,'97',1,M.PAY_BANK_CODE,0)) NO_OF_CONSUMER_ROBI,SUM(DECODE(M.PAY_BANK_CODE,'97',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))  BPDB_AMOUNT_ROBI,
SUM(DECODE(M.PAY_BANK_CODE,'96',1,M.PAY_BANK_CODE,0)) NO_OF_CONSUMER_GP,SUM(DECODE(M.PAY_BANK_CODE,'96',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))  BPDB_AMOUNT_GP,
SUM(DECODE(M.PAY_BANK_CODE,'96',1,M.PAY_BANK_CODE,0))+SUM(DECODE(M.PAY_BANK_CODE,'97',1,M.PAY_BANK_CODE,0)) TOTAL_CUSTOMER,
SUM(DECODE(M.PAY_BANK_CODE,'96',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0))+SUM(DECODE(M.PAY_BANK_CODE,'97',NVL(D.PDB_AMOUNT,0),M.PAY_BANK_CODE,0)) TOTAL_AMOUNT_BPDB
FROM EPAYMENT.EPAY_PAYMENT_MST_HSTR M,EPAYMENT.EPAY_PAYMENT_DTL_HSTR D,V_Z_C_C_L C
WHERE M.BATCH_NO=D.BATCH_NO
AND M.LOCATION_CODE=C.LOCATION_CODE
AND C.ZONE_CODE=:P_ZONE_CODE
AND C.COMP_CNTR_CODE=:P_COMP_CNTR_CODE
AND TO_CHAR(M.PAY_DATE,'RRRRMM')=:P_START_MONTH
--AND TO_CHAR(M.PAY_DATE,'RRRRMM')<=:P_END_MONTH
AND M.PAY_BANK_CODE IN ('96','97')
GROUP BY  C.ZONE_NAME,C.COMP_CNTR_NAME,C.LOCATION_NAME,TO_CHAR(M.PAY_DATE,'RRRRMM')
ORDER BY 3 asc

----------------TOT_ROBI & GP------------


SELECT O.BANK_CODE||'-'||O.ONLINE_OPT_DESCR ONLINE_OPARATOR,TO_CHAR(M.PAY_DATE,'RRRRMM') PAY_MONTH, SUM(NVL(PDB_AMOUNT,0)+NVL(GOVT_DUTY,0)) TOTAL_AMT,COUNT(*) TOT_CONS 
FROM EPAY.EPAY_PAYMENT_MST M,EPAY.EPAY_PAYMENT_DTL D,EPAY.EPAY_ONLINE_OPERATOR O
WHERE M.BATCH_NO=D.BATCH_NO
AND M.PAY_BANK_CODE=O.BANK_CODE
AND TO_CHAR(M.PAY_DATE,'RRRRMM')>=:P_START_MONTH
AND TO_CHAR(M.PAY_DATE,'RRRRMM')<=:P_END_MONTH
--AND PAY_BANK_CODE LIKE NVL(:PAY_BANK_CODE,'%')
AND PAY_BANK_CODE LIKE DECODE(:PAY_BANK_CODE,'ALL','%',:PAY_BANK_CODE)
--AND PAY_BANK_CODE IN ('96','97')
AND LOCATION_CODE NOT IN (SELECT LOCATION_CODE FROM  EPAY.EPAY_LOC_ONLINE_OPT_NESCO)
GROUP BY O.BANK_CODE,O.ONLINE_OPT_DESCR,TO_CHAR(M.PAY_DATE,'RRRRMM')
UNION
SELECT O.BANK_CODE||'-'||O.ONLINE_OPT_DESCR ONLINE_OPARATOR,TO_CHAR(M.PAY_DATE,'RRRRMM') PAY_MONTH, SUM(NVL(PDB_AMOUNT,0)+NVL(GOVT_DUTY,0)) TOTAL_AMT,COUNT(*) TOT_CONS 
FROM EPAYMENT.EPAY_PAYMENT_MST_HSTR M,EPAYMENT.EPAY_PAYMENT_DTL_HSTR D,EPAY.EPAY_ONLINE_OPERATOR O
WHERE M.BATCH_NO=D.BATCH_NO
AND M.PAY_BANK_CODE=O.BANK_CODE
AND TO_CHAR(M.PAY_DATE,'RRRRMM')>=:P_START_MONTH
AND TO_CHAR(M.PAY_DATE,'RRRRMM')<=:P_END_MONTH
--AND PAY_BANK_CODE LIKE NVL(:PAY_BANK_CODE,'%')
AND PAY_BANK_CODE LIKE DECODE(:PAY_BANK_CODE,'ALL','%',:PAY_BANK_CODE)
--AND PAY_BANK_CODE IN ('96','97')
AND LOCATION_CODE NOT IN (SELECT LOCATION_CODE FROM  EPAY.EPAY_LOC_ONLINE_OPT_NESCO)
GROUP BY O.BANK_CODE,O.ONLINE_OPT_DESCR,TO_CHAR(M.PAY_DATE,'RRRRMM')







select O.ONLINE_OPT_DESCR, SUM(NVL(PDB_AMOUNT,0)+NVL(GOVT_DUTY,0)) TOTAL_AMT,COUNT(*) TOT_CONS from epay_payment_mst M,epay_payment_DTL D,EPAY_ONLINE_OPERATOR O
where M.BATCH_NO=D.BATCH_NO
AND M.PAY_BANK_CODE=O.BANK_CODE
AND  to_char(pay_date,'RRRRMM')=:pay_MONTH
and pay_bank_code LIKE NVL(:pay_bank_code,'%')
AND PAY_BANK_CODE IN ('96','97')
AND LOCATION_CODE NOT IN (SELECT LOCATION_CODE FROM  EPAY_LOC_ONLINE_OPT_NESCO)
GROUP BY O.ONLINE_OPT_DESCR
