
---IC--PO_LIST

SELECT id.DEG_NO PO_NO,'DegNo:'||id.DEG_NO||',AgreDate:'||to_char(AGREEMENT_DATE,'dd/mm/yy')||',DelDate:'||to_char(DELEVERED_DATE,'dd/mm/yy')|| 
',Item:'||id.ITEM_NAME||',Customer:'||c.CUST_NAME||',Person:'||ID.PERSON_NAME||',SupName:'||SP.SUP_DESC||',MakeStatus:'||do.MAKE_STATUS||
',CylQuentity:'||do.CYLINDER_QUANTITY PO_DESC
FROM SBPA_CUSTOMIZE_ITEM_DEG ID,SBPA_CUSTOMIZE_ITEM_DEG_ORDER DO,SBPA_CUSTOMERS C,SBPA_SUPPLIER_MST SP
WHERE ID.DEG_NO = DO.DEG_NO
AND DO.CUST_NO = C.CUST_NO
AND DO.SUP_NO = SP.SUP_NO
AND DO.ITEM_STATUS='A'
AND (ID.DEG_NO,do.DEG_ORDER_ID) IN (
SELECT DEG_NO,DEG_ORDER_ID FROM (
SELECT ID.DEG_NO,to_char(do.DEG_ORDER_ID)DEG_ORDER_ID,SUM(CYLINDER_QUANTITY) FROM SBPA_CUSTOMIZE_ITEM_DEG ID,SBPA_CUSTOMIZE_ITEM_DEG_ORDER DO
WHERE ID.DEG_NO = DO.DEG_NO
AND do.AUTHO_STATUS='Y'
AND DO.ITEM_STATUS='A'
GROUP BY ID.DEG_NO,do.DEG_ORDER_ID
MINUS
SELECT RM.PO_NO,ITEM_CODE,SUM(RI_ACCEPT_QTY) FROM SBPA_RI_MST RM,SBPA_RI_DTL RD
WHERE RM.RI_NO=RD.RI_NO
GROUP BY RM.PO_NO,ITEM_CODE
))

---IC--SUP_LIST
SELECT DO.SUP_NO,SP.SUP_DESC
    FROM SBPA_CUSTOMIZE_ITEM_DEG_ORDER DO,SBPA_SUPPLIER_MST SP
WHERE DO.SUP_NO=SP.SUP_NO
AND DO.ITEM_STATUS='A'
AND do.AUTHO_STATUS='Y'
AND DEG_NO=:P_Po_No
ORDER BY SUP_NO ASC


--IC-ITEM_LIST

SELECT do.DEG_ORDER_ID ITEM_CODE,ITEM_NAME ITEM_DESC FROM SBPA_CUSTOMIZE_ITEM_DEG id,SBPA_CUSTOMIZE_ITEM_DEG_ORDER do
WHERE id.DEG_NO=do.DEG_NO
and id.DEG_NO =:P_Po_No
AND do.AUTHO_STATUS='Y'



SELECT ID.DEG_NO,ITEM_NAME,SUM(CYLINDER_QUANTITY) 
FROM SBPA_CUSTOMIZE_ITEM_DEG ID,SBPA_CUSTOMIZE_ITEM_DEG_ORDER DO
WHERE ID.DEG_NO = DO.DEG_NO
AND do.AUTHO_STATUS='Y'
GROUP BY ID.DEG_NO,ITEM_NAME


SELECT id.DEG_NO PO_NO,'DegNo:'||id.DEG_NO||',AgreDate:'||to_char(AGREEMENT_DATE,'dd/mm/yy')||',DelDate:'||to_char(DELEVERED_DATE,'dd/mm/yy')|| 
',Item:'||id.ITEM_NAME||',Customer:'||c.CUST_NAME||',SupName:'||SP.SUP_DESC||',MakeStatus:'||do.MAKE_STATUS||'CylQuentity'||do.CYLINDER_QUANTITY PO_DESC
FROM SBPA_CUSTOMIZE_ITEM_DEG ID,SBPA_CUSTOMIZE_ITEM_DEG_ORDER DO,SBPA_CUSTOMERS C,SBPA_SUPPLIER_MST SP
WHERE ID.DEG_NO = DO.DEG_NO
AND DO.CUST_NO = C.CUST_NO
AND DO.SUP_NO = SP.SUP_NO
AND (ID.DEG_NO,ID.ITEM_NAME) IN (
SELECT DEG_NO,ITEM_NAME FROM (
SELECT ID.DEG_NO,ITEM_NAME,SUM(CYLINDER_QUANTITY) 
FROM SBPA_CUSTOMIZE_ITEM_DEG ID,SBPA_CUSTOMIZE_ITEM_DEG_ORDER DO
WHERE ID.DEG_NO = DO.DEG_NO
AND do.AUTHO_STATUS='Y'
GROUP BY ID.DEG_NO,ITEM_NAME
MINUS
SELECT RM.PO_NO,ITEM_CODE,SUM(RI_ACCEPT_QTY) FROM SBPA_RI_MST RM,SBPA_RI_DTL RD
WHERE RM.RI_NO=RD.RI_NO
GROUP BY RM.PO_NO,ITEM_CODE
))




SELECT ID.DEG_NO,ITEM_NAME,SUM(CYLINDER_QUANTITY) 
FROM SBPA_CUSTOMIZE_ITEM_DEG ID,SBPA_CUSTOMIZE_ITEM_DEG_ORDER DO
WHERE ID.DEG_NO = DO.DEG_NO
AND do.AUTHO_STATUS='Y'
GROUP BY ID.DEG_NO,ITEM_NAME
MINUS
SELECT RM.PO_NO,ITEM_CODE,SUM(RI_ACCEPT_QTY) FROM SBPA_RI_MST RM,SBPA_RI_DTL RD
WHERE RM.RI_NO=RD.RI_NO
GROUP BY RM.PO_NO,ITEM_CODE