
SELECT * FROM EPAY.EPAY_DATA_TRANS_LOG@EPAY_jam
WHERE DATA_TYPE IN ('CUSTINFO','BILLINFO')
ORDER BY RUN_DATE DESC


SELECT JOB_NAME,STATE,LAST_START_DATE,LAST_RUN_DURATION  
FROM DBA_SCHEDULER_JOBS@EPAY_MYMEN
WHERE OWNER='EPAY'

EXEC SYS.DBMS_SCHEDULER.STOP_JOB@EPAY_com (job_name => 'JOB_EPAY_PYMT_DATA_TRNS', force => TRUE);

EXEC SYS.DBMS_SCHEDULER.RUN_JOB@EPAY_tang (job_name => 'JOB_EPAY_PYMT_DATA_TRNS',USE_CURRENT_SESSION => FALSE);

SELECT * FROM EPAY.EPAY_DATA_TRANS_ERR_LOG@EPAY_tang
WHERE DATA_TYPE IN ('PAYMPOST')--,'CUSTINFO','BILLINFO')
ORDER BY RUN_DATE DESC

--,'CUSTINFO','BILLINFO',PAYMPOST


EXECUTE DBMS_SCHEDULER.DISABLE@EPAY_RONG ('EPAY.JOB_EPAY_PYMT_DATA_TRNS');

EXECUTE DBMS_SCHEDULER.ENABLE@EPAY_MYMEN ('EPAY.JOB_EPAY_PYMT_DATA_TRNS');


SELECT * FROM EPAY_DATA_TRANS_BATCH_CONTROL@EPAY_MYMEN
WHERE DATA_TYPE ='PAYMPOST'--in ('CUSTINFO','BILLINFO')
ORDER BY RUN_DATE DESC


SELECT * FROM EPAY_DATA_TRANS_ERR_LOG@EPAY_TANG
WHERE DATA_TYPE ='PAYMPOST'
--AND RUN_DATE =TRUNC(SYSDATE)
ORDER BY RUN_DATE DESC


SELECT JOB_NAME,STATE,LAST_START_DATE,LAST_RUN_DURATION  
FROM DBA_SCHEDULER_JOBS@mbp_23
WHERE OWNER='MBP'

EXEC SYS.DBMS_SCHEDULER.RUN_JOB@mbp_23 (job_name => 'JOB_MBP_BATCH_GENERATE',USE_CURRENT_SESSION => FALSE);


SELECT TABLE_NAME
FROM ALL_TABLES@EPAY_CTG
WHERE OWNER = 'EPAY'
ORDER BY TABLE_NAME;

SELECT * FROM EPAY_LOCATION_MASTER@EPAY_MYMEN
WHERE LOCATION_CODE<>'M3'


UPDATE EPAY_LOCATION_MASTER@EPAY_MYMEN
SET STATUS='I'
WHERE LOCATION_CODE<>'M3'