
SELECT  SCRAP_STOR_ID,SCRAP_MST_ID, SCRAP_DTL_ID,a.SCRAP_NO,SCRAP_DATE, REFERANCE_TYPE,REFERANCE_ITEM,
        SCRAP_ITEM||'-'||b.ITEM_DESC SCRAP_ITEM,REFERANCE_MSR_UNIT, a.SCRAP_MSR_UNIT||'-'||b.MSR_UNIT_DESC SCRAP_MSR_UNIT,
        QUANTITY,SCRAP_LOCATION_STORE,   AUTHO_STATUS, AUTHORIZE_BY, AUTHORIZE_DT, UNAUTHORIZE_BY,UNAUTHORIZE_DT,LEDGER_NUM, LEDGER_PAGE_NUM,REMARKS
        from (
          SELECT SCRAP_STOR_ID,SD.SCRAP_MST_ID,SD.SCRAP_DTL_ID,SD.SCRAP_NO,TO_CHAR(SM.SCRAP_DATE,'DD/MM/RRRR') SCRAP_DATE,SD.REF_TYPE REFERANCE_TYPE,
          SD.REF_ITEM_CODE||'-'||IM.ITEM_DESC REFERANCE_ITEM, SD.SCRAP_ITEM_CODE SCRAP_ITEM,
          SD.REF_MSR_UNIT||'-'||MU.MSR_UNIT_DESC REFERANCE_MSR_UNIT,SD.SCRAP_MSR_UNIT ,QUANTITY,
          'Section-('||SEC_DESC||')'||',Rack-('||RACK_DESC||'),'||'Bin-('||BIN_DESC||')' AS SCRAP_LOCATION_STORE,
          DECODE(AUTHO_STATUS,'Y','Authorize','Unauthorize') AUTHO_STATUS, AUTHORIZE_BY,TO_CHAR(AUTHORIZE_DT,'DD/MM/RRRR') AUTHORIZE_DT, UNAUTHORIZE_BY,
                TO_CHAR(UNAUTHORIZE_DT,'DD/MM/RRRR') UNAUTHORIZE_DT,LEDGER_NUM, LEDGER_PAGE_NUM,SD.REMARKS
        FROM  SBPA_SCRAP_MST SM,SBPA_SCRAP_DTL SD,SBPA_ITEM_MST IM,SBPA_MEASUREMENT_UNIT MU,SBPA_SCRAP_STORAGE SS,
        SBPA_SECTION S,SBPA_RACK R,SBPA_BIN B
        where SM.SCRAP_NO = SD.SCRAP_NO
        AND SD.REF_ITEM_CODE=IM.ITEM_CODE
        AND SD.REF_MSR_UNIT=MU.MSR_UNIT_CODE
        and SD.SCRAP_DTL_ID = SS.SCRAP_DTL_ID
        and SD.SCRAP_MST_ID = SS.SCRAP_MST_ID
        and SD.SCRAP_NO = SS.SCRAP_NO
        and SS.SEC_CODE = S.SEC_CODE
        and SS.RACK_CODE = R.RACK_CODE
        and SS.BIN_CODE = B.BIN_CODE
        AND B.SEC_CODE=R.SEC_CODE
        AND B.RACK_CODE=R.RACK_CODE
        AND B.SEC_CODE=S.SEC_CODE
        AND R.SEC_CODE=S.SEC_CODE
        and SM.SCRAP_NO=:P_Scrap_No
    AND SM.SCRAP_DATE=TO_DATE(:P_Scrap_Date,'DD/MM/RRRR')
    )a,(
           select SCRAP_NO,sd.SCRAP_ITEM_CODE,im.ITEM_DESC,sd.SCRAP_MSR_UNIT,MU.MSR_UNIT_DESC from SBPA_SCRAP_DTL sd,SBPA_ITEM_MST im,SBPA_MEASUREMENT_UNIT MU
    where sd.SCRAP_ITEM_CODE=im.ITEM_CODE
    and sd.SCRAP_MSR_UNIT=MU.MSR_UNIT_CODE
    and sd.SCRAP_NO in (
    select SCRAP_NO from SBPA_SCRAP_mst       where  SCRAP_NO=:P_Scrap_No
    AND SCRAP_DATE=TO_DATE(:P_Scrap_Date,'DD/MM/RRRR')
    )
    )b
    where a.SCRAP_NO = b.SCRAP_NO
    and a.SCRAP_ITEM=b.SCRAP_ITEM_CODE
    and a.SCRAP_MSR_UNIT=b.SCRAP_MSR_UNIT
    
    -----------------------old
    
    SELECT SCRAP_STOR_ID,SD.SCRAP_MST_ID,SD.SCRAP_DTL_ID,SD.SCRAP_NO,TO_CHAR(SM.SCRAP_DATE,'DD/MM/RRRR') SCRAP_DATE,
        SD.REF_TYPE REFERANCE_TYPE,SD.REF_ITEM_CODE||'-'||RIM.ITEM_DESC REFERANCE_ITEM, SD.SCRAP_ITEM_CODE||'-'||IM.ITEM_DESC SCRAP_ITEM,
        SD.REF_MSR_UNIT||'-'||RMU.MSR_UNIT_DESC REFERANCE_MSR_UNIT,SS.MSR_UNIT_CODE||'-'||MU.MSR_UNIT_DESC SCRAP_MSR_UNIT,QUANTITY, 
        'Section-('||SEC_DESC||')'||',Rack-('||RACK_DESC||'),'||'Bin-('||BIN_DESC||')' AS SCRAP_LOCATION_STORE,
        DECODE(AUTHO_STATUS,'Y','Authorize','Unauthorize') AUTHO_STATUS, AUTHORIZE_BY,TO_CHAR(AUTHORIZE_DT,'DD/MM/RRRR') AUTHORIZE_DT, UNAUTHORIZE_BY,
        TO_CHAR(UNAUTHORIZE_DT,'DD/MM/RRRR') UNAUTHORIZE_DT,LEDGER_NUM, LEDGER_PAGE_NUM,SD.REMARKS
    FROM  SBPA_SCRAP_MST SM,SBPA_SCRAP_DTL SD,SBPA_SCRAP_STORAGE SS,SBPA_ITEM_MST IM,SBPA_MEASUREMENT_UNIT MU,
    SBPA_SECTION S,SBPA_RACK R,SBPA_BIN B,SBPA_ITEM_MST RIM,SBPA_MEASUREMENT_UNIT RMU
    WHERE SM.SCRAP_NO = SD.SCRAP_NO
    AND SM.SCRAP_NO=SS.SCRAP_NO
    AND SD.SCRAP_NO = SS.SCRAP_NO
    AND SD.SCRAP_DTL_ID = SS.SCRAP_DTL_ID
    AND SD.SCRAP_ITEM_CODE=SS.ITEM_CODE
    AND SD.SCRAP_MSR_UNIT=SS.MSR_UNIT_CODE
    AND SD.SCRAP_ITEM_CODE=IM.ITEM_CODE
    AND SS.ITEM_CODE = IM.ITEM_CODE
    AND SD.SCRAP_MSR_UNIT=MU.MSR_UNIT_CODE
    AND SS.MSR_UNIT_CODE=MU.MSR_UNIT_CODE
    AND SS.SEC_CODE = S.SEC_CODE
    AND SS.RACK_CODE = R.RACK_CODE
    AND SS.SEC_CODE = R.SEC_CODE
    AND SS.BIN_CODE = B.BIN_CODE
    AND B.RACK_CODE=R.RACK_CODE
    AND B.SEC_CODE=R.SEC_CODE
    AND B.SEC_CODE=S.SEC_CODE
    AND R.SEC_CODE=S.SEC_CODE
    AND SD.REF_ITEM_CODE=RIM.ITEM_CODE(+)
    AND SD.REF_MSR_UNIT=RMU.MSR_UNIT_CODE(+)
    AND SM.SCRAP_NO=:P_SCRAP_NO
    AND SM.SCRAP_DATE=TO_DATE(:P_SCRAP_DATE,'DD/MM/RRRR')