
--INSERT INTO EPAY_UTILITY_BILL@EPAY_SRL
INSERT INTO EPAY_UTILITY_BILL
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  0 BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0, 'N' DATA_TRANS_LOG,'T' DATA_TRANS_LOG1,'N' DATA_TRANS_LOG2,'T' DATA_TRANS_LOG3,'T' DATA_TRANS_LOG4,'N' DATA_TRANS_LOG5
 FROM BC_BILL_IMAGE@BILLING_TANG
 WHERE BILL_CYCLE_CODE=:P_BILL_MONTH
--AND CUSTOMER_NUM||CONS_CHK_DIGIT='36295858'
AND INVOICE_NUM||INVOICE_CHK_DGT ='4720652265'
--IN ('4720588905','4720588911','4720587780','4720587811')
AND LOCATION_CODE='T7'

75916376

SELECT *

DELETE FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201905'
AND ACCOUNT_NUMBER='75916376'

COMMIT

---------------------------24-----------NESCO-----BPDB---

INSERT INTO EPAY_UTILITY_BILL@EPAY_SRL
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  0 BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 ,'N' DATA_TRANS_LOG
 FROM BC_BILL_IMAGE@BILLING_SYL
 WHERE BILL_CYCLE_CODE=:P_BILL_MONTH
AND CUSTOMER_NUM||CONS_CHK_DIGIT='41944611'
AND LOCATION_CODE='H1'

SELECT * FROM EPAY_CUSTOMER_MASTER_DATA@EPAYment
WHERE ACCOUNT_NO='78691934'

select * from epay_utility_bill@EPAYment
where bill_number='8476752581'

bill_month='201905'
--and account_number='78691934'
and bill_number='8476752581'

SELECT * FROM BC_BILL_IMAGE@BILLING_CTG
WHERE INVOICE_NUM='214160291'
AND LOCATION_CODE='W4'

-------------------------169-----------------------------

INSERT INTO EPAY_UTILITY_BILL@epayment
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  0 BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 ,'N' DATA_TRANS_LOG
 FROM BC_BILL_IMAGE@BILLING_COM
 --WHERE BILL_CYCLE_CODE=:P_BILL_MONTH
--AND CUSTOMER_NUM||CONS_CHK_DIGIT='72410129'
WHERE INVOICE_NUM='58656225'
AND LOCATION_CODE='B5'

SELECT * FROM EPAY_UTILITY_BILL@EPAYMENT
WHERE BILL_NUMBER='586562254'

SELECT * FROM EPAY_CUSTOMER_MASTER_DATA@EPAYMENT
WHERE ACCOUNT_NO='586562254'




BILL_MONTH='201811'
AND ACCOUNT_NUMBER='76250803'


SELECT * FROM BC_CUSTOMERS@BILLING_TANG
WHERE CUSTOMER_NUM='7625080'

SELECT * FROM EPAY_CUSTOMER_MASTER_DATA@EPAY_SRL
WHERE ACCOUNT_NO='76250803'

                

UPDATE EPAY_CUSTOMER_MASTER_DATA@EPAY_SRL
SET NAME='MD.MOTIAR RAHMAN',LOCATION_CODE='T3',AREAR_CODE='V1110'
WHERE ACCOUNT_NO='76250803'

COMMIT;


SELECT * FROM EPAY_CUSTOMER_MASTER_DATA
WHERE ACCOUNT_NO='47341605'

SELECT * FROM EPAY_CUSTOMER_MASTER_DATA@EPAY_SRL
WHERE ACCOUNT_NO='47332023'

INSERT INTO EPAY_CUSTOMER_MASTER_DATA@EPAY_SRL
SELECT COMPANY_CODE, ACCOUNT_NO, NAME, LOCATION_CODE, AREAR_CODE, ACTIVATION_DATE, STATUS, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, DUMPING_FOR,'POST',NULL,NULL
FROM EPAY_CUSTOMER_MASTER_DATA
WHERE ACCOUNT_NO='47341605'


------------------------------------DATA INSERT ROBI--------------



INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE, ACCOUNT_NUMBER, BILL_NUMBER, GENERATED_DATE, BILL_STATUS, BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE, BILLENDDATE_FORPAYMENT, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY,
NOTIFICATION_SENT_STATUS, CURRENT_PRINCIPLE, CURRENT_GOVT_DUTY, ARREAR_PRINCIPLE, ARREAR_GOVT_DUTY,
LATE_PAYMENT_SURCHARGE, TOTAL_BILL_AMOUNT, LOCATION_CODE, BILL_MONTH, TARIFF, CUSTOMER_TYPE,
CURRENT_SURCHARGE, ARREAR_SURCHARGE, ADJUSTED_PRINCIPLE, ADJUSTED_GOVT_DUTY, ADVANCE_AMOUNT, ADJ_ADV_GOVT_DUTY
FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201812'
AND ACCOUNT_NUMBER IN  ('75288595')

COMMIT;


INSERT INTO EPAY_CUST_MASTER_DATA_GPR_X
(COMPANY_CODE,ACCOUNT_NO,NAME,LOCATION_CODE,AREAR_CODE,ACTIVATION_DATE,STATUS,CREATED_ON ,DUMPING_FOR, CREATED_BY)
SELECT 'BPDB', CUSTOMER_NUM||CHECK_DIGIT,CUSTOMER_NAME,LOCATION_CODE,AREA_CODE,  TO_DATE(START_BILL_CYCLE,'rrrrmm'),
DECODE (CUSTOMER_STATUS_CODE,'C','A','S','A','I') STATUS,  SYSDATE,    'U',USER
FROM BC_CUSTOMERS@BILLING_TANG
WHERE CUSTOMER_NUM IN ('7530171','7530175','7530161','7530162')


-------------------------------SRL------------------------------------------------------
SELECT * FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE ACCOUNT_NUMBER='81934748'
AND BILL_MONTH='201607'



--------------------------PDB-----------------------------------------------------------
SELECT * FROM EPAY_UTILITY_BILL
WHERE ACCOUNT_NUMBER='81934748'
AND BILL_MONTH='201607'


SELECT * FROM VW_SEBL_ERR_LOG@EPAY_SRL 
WHERE (ACCOUNT_NUMBER,LOCATION_CODE) NOT IN (
SELECT ACCOUNT_NUMBER,LOCATION_CODE FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH=:P_BILL_MONTH
AND LOCATION_CODE IN ('E2','E3','N1','W3')
)



SELECT CUSTOMER_NUM,CONS_CHK_DIGIT,LOCATION_CODE,TOTAL_BILL FROM BC_BILL_IMAGE@BILLING_CTG
WHERE CUSTOMER_NUM='8021539'
AND BILL_CYCLE_CODE='201608'


UPDATE EPAY_ERR_LOG@EPAY_SRL
SET STATUS='C'
WHERE LTRIM (SUBSTR (ERROR_TXT, 8, 8))='20548721'
AND LOCATION_CODE='W3'
and STATUS='E'


COMMIT;




select * from EPAY_ERR_LOG
