INSERT INTO EPAY_UTILITY_BILL@EPAY_SRL
--INSERT INTO EPAY_UTILITY_BILL
SELECT 'BPDB' AS COMPANY_CODE, 
CUSTOMER_NUM||CONS_CHK_DIGIT AS ACCOUNT_NUMBER, 
INVOICE_NUM||INVOICE_CHK_DGT BILL_NUMBER, 
INVOICE_DATE GENERATED_DATE, 
'N' BILL_STATUS, 
 INVOICE_DUE_DATE BILL_DUE_DATE, 
  0 BILLAMT_AFTERDUEDATE, 
  INVOICE_DUE_DATE BILLENDDATE_FORPAYMENT, 
  SYSDATE CREATED_ON    , 
  'SYSADMIN' CREATED_BY   , 
  NULL  MODIFIED_ON , 
  NULL MODIFIED_BY, 
  'N' NOTIFICATION_SENT_STATUS, 
 (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0) 
  +NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+ 
   NVL(DEMAND_CHRG,0) 
   +NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)+ 
  NVL(ENG_CHRG_MR1,0)+NVL(ENG_CHRG_MR2,0)+NVL(ENG_CHRG_MR3,0)+NVL(ENG_CHRG_MR4,0)) CURRENT_PRINCIPLE, 
  CURRENT_VAT CURRENT_GOVT_DUTY, 
  ARR_ADV_ADJ_PRN  ARREAR_PRINCIPLE, 
  ARR_ADV_ADJ_VAT ARREAR_GOVT_DUTY, 
  0 LATE_PAYMENT_SURCHARGE, 
  TOTAL_BILL TOTAL_BILL_AMOUNT, 
 LOCATION_CODE, 
 BILL_CYCLE_CODE BILL_MONTH, 
 TARIFF, 
 CUST_STATUS CUSTOMER_TYPE, 
 CURRENT_LPS CURRENT_SURCHARGE, 
 ARR_ADV_ADJ_LPS ARREAR_SURCHARGE, 
 NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJUSTED_PRINCIPLE, 
 ADJUSTED_VAT ADJUSTED_GOVT_DUTY, 
 0 /*NVL(UNADJUSTED_PRN,0)+NVL(UNADJUSTED_VAT,0)*/ ADVANCE_AMOUNT,0 ,'N' DATA_TRANS_LOG
 FROM BC_BILL_IMAGE@BILLING_CTG
 WHERE BILL_CYCLE_CODE=:P_BILL_MONTH
AND CUSTOMER_NUM in
 (
'2082607',
'2088197',
'2091846',
'2091847',
'2409525',
'2436425',
'2478338',
'2495004',
'2500784',
'8188429',
'8192106')
AND LOCATION_CODE IN ('E2','E3','N1','W3')


DELETE FROM EPAY_UTILITY_BILL
WHERE  account_number='24783579'
AND LOCATION_CODE='N1'
and bill_month='201603'

DELETE FROM EPAY_UTILITY_BILL
--DELETE FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE LOCATION_CODE IN ('E2','E3','N1','W3')
AND BILL_MONTH='201603'
AND SUBSTR(ACCOUNT_NUMBER,1,7) IN (
'2082607',
'2088197',
'2091846',
'2091847',
'2409525',
'2436425',
'2478338',
'2495004',
'2500784',
'8188429',
'8192106')

commit;

SELECT ''''||CUSTOMER_NUM||''''||',' FROM (
SELECT CUSTOMER_NUM,TOTAL_BILL FROM BC_BILL_IMAGE@BILLING_CTG
 WHERE BILL_CYCLE_CODE=:P_BILL_MONTH
AND LOCATION_CODE IN ('E2','E3','N1','W3')
AND  INVOICE_DUE_DATE>=TRUNC(SYSDATE)
MINUS
SELECT SUBSTR(ACCOUNT_NUMBER,1,7) CUSTOMER_NUM,TOTAL_BILL_AMOUNT FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN ('E2','E3','N1','W3')
AND BILL_DUE_DATE>=TRUNC(SYSDATE)
)

commit;



select CUSTOMER_NUM from (
SELECT CUSTOMER_NUM,TOTAL_BILL FROM BC_BILL_IMAGE@BILLING_CTG
 WHERE BILL_CYCLE_CODE=:P_BILL_MONTH
AND LOCATION_CODE IN ('E2','E3','N1','W3')
AND  INVOICE_DUE_DATE>=TRUNC(SYSDATE)
MINUS
SELECT SUBSTR(ACCOUNT_NUMBER,1,7) CUSTOMER_NUM,TOTAL_BILL_AMOUNT FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201603'
AND LOCATION_CODE IN ('E2','E3','N1','W3')
AND BILL_DUE_DATE>=TRUNC(SYSDATE)
)
