

SELECT * FROM EPAY_PAYMENT_MST
WHERE ORG_BR_CODE='E3'
AND PAY_DATE IN ('29-MAY-2017')


DELETE FROM EPAY_BATCH_REMOVE;


INSERT INTO EPAY_BATCH_REMOVE 
SELECT BATCH_NO,ORG_BR_CODE,PAY_DATE FROM EPAY_PAYMENT_MST
WHERE ORG_BR_CODE='E3'
AND PAY_DATE IN ('29-MAY-2017')


COMMIT;


SELECT * FROM EPAY_PAYMENT_MST
WHERE BATCH_NO IN (SELECT BATCH_NO FROM EPAY_BATCH_REMOVE)

SELECT COUNT(*) FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO IN (SELECT BATCH_NO FROM EPAY_BATCH_REMOVE)



SELECT * FROM EPAY_PAYMENT_MST@EPAY_SRL_DCC
WHERE (REF_BATCH_NO,LOCATION_CODE,PAY_DATE) IN (
SELECT BATCH_NO,ORG_BR_CODE,PAY_DATE FROM EPAY_BATCH_REMOVE
)


SELECT COUNT(*) FROM EPAY_PAYMENT_DTL@EPAY_SRL_DCC
WHERE BATCH_NO IN (
SELECT BATCH_NO FROM EPAY_PAYMENT_MST@EPAY_SRL_DCC
WHERE (REF_BATCH_NO,LOCATION_CODE,PAY_DATE) IN (
SELECT BATCH_NO,ORG_BR_CODE,PAY_DATE FROM EPAY_BATCH_REMOVE
))


SELECT COUNT(*) FROM MBP_PAYMENT_DTL_OVC@MBP_23
WHERE ORG_BR_CODE='E3'
AND PAY_DATE IN ('29-MAY-2017')


DELETE FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO IN (SELECT BATCH_NO FROM EPAY_BATCH_REMOVE)


DELETE FROM EPAY_PAYMENT_MST
WHERE BATCH_NO IN (SELECT BATCH_NO FROM EPAY_BATCH_REMOVE)


DELETE FROM EPAY_PAYMENT_DTL@EPAY_SRL_DCC
WHERE BATCH_NO IN (
SELECT BATCH_NO FROM EPAY_PAYMENT_MST@EPAY_SRL_DCC
WHERE (REF_BATCH_NO,LOCATION_CODE,PAY_DATE) IN (
SELECT BATCH_NO,ORG_BR_CODE,PAY_DATE FROM EPAY_BATCH_REMOVE
))


DELETE FROM EPAY_PAYMENT_MST@EPAY_SRL_DCC
WHERE (REF_BATCH_NO,LOCATION_CODE,PAY_DATE) IN (
SELECT BATCH_NO,ORG_BR_CODE,PAY_DATE FROM EPAY_BATCH_REMOVE
)


COMMIT;


INSERT INTO MBP_PAYMENT_DTL_OVC@MBP_23
SELECT * FROM MBP_PAYMENT_DTL_OVC_HIST@MBP_23
WHERE ORG_BR_CODE='E3'
AND PAY_DATE IN ('28-MAY-2017')


DELETE FROM MBP_PAYMENT_DTL_OVC_HIST@MBP_23
WHERE ORG_BR_CODE='E3'
AND PAY_DATE IN ('28-MAY-2017')


COMMIT;



SELECT EPAY.DFN_MBP_BTCH_REMOVE (:P_Bank_Code,:P_Pay_Date,UPPER(:P_Location_Code)) FROM DUAL;


EXECUTE MBP.DPG_MBP_BTCH_GEN.DPD_MBP_BTCH_GEN_CONT@MBP_23;


SELECT * FROM VW_EPAY_UNTRNS_DATA_MBP


EXECUTE DPG_EPAY_MBP_PYMT_VALIDATION.DPD_EPAY_MBP_PYMT_VALID_CONT;


EXECUTE DPG_EPAY_PYMT_DATA_TRNS_SRL.DPD_EPAY_PY_DATA_TRNS_SRL_CON@EPAY_SRL_DCC;


SELECT * FROM VW_EPAY_UNTRNS_DATA_MBP

