
select  BILL_CYCLE_CODE, TARIFF,sum(TOTAL_CON) TOTAL_CON, sum(SLAB_0) SLAB_0, sum(SLAB_1) SLAB_1, sum(SLAB_2) SLAB_2, sum(SLAB_3) SLAB_3, sum(SLAB_4) SLAB_4, sum(SLAB_5) SLAB_5, sum(SLAB_6) SLAB_6 
from emp.BC_SLAB_WISE_CONSUMPTION
group by  BILL_CYCLE_CODE, TARIFF
order by 1,2,3