

SELECT B.LOCATION_CODE office_code,C.DESCR office_name,A.BILL_CYCLE_CODE month,
 COUNT(DISTINCT A.CUST_ID) NO_OF_CUST
 FROM BC_BILL_IMAGE@BILLING_COM A,BC_CUSTOMERS@BILLING_COM B,BC_LOCATION_MASTER@BILLING_COM C
WHERE A.BILL_CYCLE_CODE=:bill_cycle
AND A.CUST_ID=B.CUST_ID
AND A.MRS_STATUS='M'
AND B.LOCATION_CODE=C.LOCATION_CODE
GROUP BY B.LOCATION_CODE,C.DESCR,A.BILL_CYCLE_CODE
order BY B.LOCATION_CODE,C.DESCR;

--------------

SELECT A.BILL_CYCLE_CODE BILL_MONTH,
 COUNT(DISTINCT A.CUST_ID) NO_OF_CUST
 FROM EBC.BC_BILL_IMAGE A,EBC.BC_CUSTOMERS B,EBC.BC_LOCATION_MASTER C
--WHERE A.BILL_CYCLE_CODE=:bill_cycle
WHERE A.BILL_CYCLE_CODE  BETWEEN '202006' AND '202105'
AND A.CUST_ID=B.CUST_ID
AND A.MRS_STATUS='M'
AND B.LOCATION_CODE=C.LOCATION_CODE
GROUP BY A.BILL_CYCLE_CODE
order BY A.BILL_CYCLE_CODE;