
---------------------24------------

--01	Chittagong Computer Center
--02	Comilla Computer Center
--03	Sylhet Computer Center
--04	Moulovibazar Computer Center
--12	Mymenshing Computer Center
--13	Tangail Computer Center
--14	Khisorgonj Computer Center
--15	Jamalpur Computer Center

SELECT 
'INSERT INTO EPAY_UTILITY_BILL@EPAY_SRL
SELECT 
''BPDB'' AS COMPANY_CODE,
ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,''N'' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA@EPAY_SRL WHERE LOCATION_CODE='''||LOC||''') 
AND  DATA_TRANS_LOG3=''N''
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||'''
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''')
and BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='SRL' )
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC 
WHERE COMP_CNTR_CODE IN ('12')
--WHERE ZONE_CODE IN ('2')
--AND LOCATION_CODE=''
))
ORDER BY LOC

--WHERE COMP_CNTR_CODE ='06'
-------------------------------
--('7','3','2','4') BPDB
--('5','6') NESCO

SELECT 
'UPDATE EPAY_UTILITY_BILL
SET DATA_TRANS_LOG3=''T''
WHERE DATA_TRANS_LOG3=''N''
AND  BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
WHERE COMP_CNTR_CODE IN ('12')
--WHERE ZONE_CODE IN ('2')
)
AND DATA_TRANS_LOG3='N')
ORDER BY LOC


---------------------169-----------

SELECT 
'INSERT INTO EPAY_UTILITY_BILL@EPAYMENT
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,''N'' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL
WHERE  DATA_TRANS_LOG4=''N'' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA@EPAYMENT WHERE LOCATION_CODE='''||LOC||''') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||'''
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL@EPAYMENT
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''')
and BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='EPAY_SRL' AND STATUS='A')
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC 
WHERE ZONE_CODE IN ('2')
--AND LOCATION_CODE=''
))
ORDER BY LOC


SELECT 
'UPDATE EPAY_UTILITY_BILL
SET DATA_TRANS_LOG4=''T''
WHERE DATA_TRANS_LOG4=''N''
AND  BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC
--WHERE COMP_CNTR_CODE IN ('11')
WHERE ZONE_CODE IN ('2')
)
AND DATA_TRANS_LOG4='N')
ORDER BY LOC

--------------GP--------


SELECT 
'INSERT INTO UTILITY_BILL_PDB@EPAY_GP
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE  DATA_TRANS_LOG2=''N'' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_GP WHERE LOCATION_CODE='''||LOC||''') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||'''
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_GP
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''')
and BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='GP' AND STATUS='A')
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC 
--WHERE ZONE_CODE IN ('4')
WHERE COMP_CNTR_CODE IN ('02')
--AND LOCATION_CODE=''
))
ORDER BY LOC


SELECT 
'UPDATE EPAY_UTILITY_BILL
SET DATA_TRANS_LOG2=''T''
WHERE DATA_TRANS_LOG2=''N''
AND  BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='GP' AND STATUS='A')
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC 
WHERE COMP_CNTR_CODE IN ('02')
))
ORDER BY LOC



--------------ROBI--------


SELECT 
'INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1=''N'' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='''||LOC||''') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||'''
AND DATA_TRANS_LOG1=''N''
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''')
and BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='ROBI' AND STATUS='A')
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC 
--WHERE ZONE_CODE IN ('4')
--AND LOCATION_CODE=''
where COMP_CNTR_CODE='14'
))
ORDER BY LOC


--('7','3','2','4') BPDB
--('5','6') NESCO

SELECT 
'UPDATE EPAY_UTILITY_BILL
SET DATA_TRANS_LOG1=''T''
WHERE DATA_TRANS_LOG1=''N''
AND  BILL_MONTH='''||BILL_MONTH||'''
AND LOCATION_CODE='''||LOC||''';'||CHR(10)||CHR(10)||'COMMIT;'||CHR(10) AS "RETURN_QUERY"
FROM (SELECT DISTINCT LOCATION_CODE AS LOC,:P_BILL_MONTH BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOC_ONLINE_OPT_MAP WHERE ONLINE_OPT='ROBI' AND STATUS='A')
AND LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_ZONE_COMP_CNTR_LOC 
WHERE ZONE_CODE IN ('4')
--AND LOCATION_CODE=''
--where center_name='KISHOREGANJ'
))
ORDER BY LOC




INSERT INTO EPAY_UTILITY_BILL@EPAY_SRL
SELECT 
CASE WHEN(SELECT COUNT(*) FROM EPAY_LOC_ONLINE_OPT_NESCO WHERE LOCATION_CODE='C1')=0 THEN COMPANY_CODE ELSE 'NESCO' END AS COMPANY_CODE,
ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,'N' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA@EPAY_SRL WHERE LOCATION_CODE='C1') 
AND  DATA_TRANS_LOG3='T'
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202106'
AND LOCATION_CODE='C1'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL@EPAY_SRL
WHERE BILL_MONTH='202106'
AND LOCATION_CODE='C1')
and BILL_MONTH='202106'
AND LOCATION_CODE='C1';

COMMIT;


UPDATE EPAY_UTILITY_BILL
SET DATA_TRANS_LOG3='T'
WHERE DATA_TRANS_LOG3='N'
AND  BILL_MONTH='201901'
AND LOCATION_CODE='B2';

COMMIT;



INSERT INTO EPAY_UTILITY_BILL@EPAYMENT
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY,'N' DATA_TRANS_LOG FROM EPAY_UTILITY_BILL
WHERE  DATA_TRANS_LOG4='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA@EPAYMENT WHERE LOCATION_CODE='C1') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202106'
AND LOCATION_CODE='C1'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL@EPAYMENT
WHERE BILL_MONTH='202106'
AND LOCATION_CODE='C1')
and BILL_MONTH='202106'
AND LOCATION_CODE='C1';

COMMIT;

UPDATE EPAY_UTILITY_BILL
SET DATA_TRANS_LOG4='T'
WHERE DATA_TRANS_LOG4='N'
AND  BILL_MONTH='201804'
AND LOCATION_CODE='C7';

COMMIT;


INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL--_GPR_X
WHERE DATA_TRANS_LOG1='N'
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL--_GPR_X
WHERE BILL_MONTH='202105'
--AND ACCOUNT_nUMBER='33083395'
AND LOCATION_CODE='K4'
AND DATA_TRANS_LOG1='N'
--AND BILL_DUE_DATE>=TRUNC(SYSDATE)
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='K4')



COMMIT;

UPDATE EPAY_UTILITY_BILL
SET DATA_TRANS_LOG1='T'
WHERE DATA_TRANS_LOG1='N'
AND  BILL_MONTH='202105'
AND LOCATION_CODE='K4';

COMMIT;


INSERT INTO UTILITY_BILL_PDB@EPAY_GP
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL--_GPR_X
WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_GP WHERE LOCATION_CODE='W4') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL--_GPR_X
WHERE BILL_MONTH='201906'
AND DATA_TRANS_LOG2='T'
--AND BILL_DUE_DATE>=TRUNC(SYSDATE)
AND LOCATION_CODE='W4'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_GP
WHERE BILL_MONTH='201906'
AND LOCATION_CODE='W4')
and BILL_MONTH='201906'
AND LOCATION_CODE='W4';

COMMIT;