
SELECT * FROM BC_BANKS@BILLING_TANG

-------BILING

SELECT A.RECEIPT_DATE,A.LOCATION_CODE,SUM(B.RECEIPT_AMT) PDB_AMOUNT,SUM(B.VAT_AMT) VAT,SUM(B.RECEIPT_AMT+B.VAT_AMT) TOT_AMOUNT,COUNT(*) TOT_CONSUMER
FROM BC_RECEIPT_BATCH_HDR@BILLING_TANG A,BC_RECEIPT_HDR@BILLING_TANG B
WHERE A.BATCH_NUM=B.BATCH_NUM
AND TO_CHAR(A.RECEIPT_DATE,'RRRRMM')=:P_MNTH
AND A.LOCATION_CODE='T1'
AND A.BANK_CODE='97'
GROUP BY A.RECEIPT_DATE,A.LOCATION_CODE
ORDER BY 1 ASC


SELECT * FROM BC_RECEIPT_HDR@BILLING_TANG


SELECT * FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D
WHERE M.BATCH_NO=D.BATCH_NO
AND M.LOCATION_CODE='T7'
AND TO_CHAR(M.PAY_DATE,'RRRRMM')='201710'
ORDER BY M.PAY_DATE ASC


---ROBI----

SELECT M.PAY_DATE,M.LOCATION_CODE,SUM(D.PDB_AMOUNT) PDB_AMOUNT,SUM(D.GOVT_DUTY) VAT,SUM(D.PDB_AMOUNT+D.GOVT_DUTY) TOT_AMOUNT,COUNT(*) TOT_CONSUMER 
FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D
WHERE M.BATCH_NO=D.BATCH_NO
AND M.LOCATION_CODE='T1'
AND TO_CHAR(M.PAY_DATE,'RRRRMM')=:P_MNTH
GROUP  BY M.PAY_DATE,M.LOCATION_CODE
ORDER BY 1 ASC

---PDB----

SELECT M.PAY_DATE,M.LOCATION_CODE,SUM(D.PDB_AMOUNT) PDB_AMOUNT,SUM(D.GOVT_DUTY) VAT,SUM(D.PDB_AMOUNT+D.GOVT_DUTY) TOT_AMOUNT,COUNT(*) TOT_CONSUMER 
FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND M.LOCATION_CODE='T1'
AND TO_CHAR(M.PAY_DATE,'RRRRMM')=:P_MNTH
GROUP  BY M.PAY_DATE,M.LOCATION_CODE
ORDER BY 1 ASC