
--1. MOVE INDEX

SELECT 'ALTER INDEX '||OBJECT_NAME||' REBUILD TABLESPACE SDAINDEX;' FROM DBA_OBJECTS
WHERE OWNER='SDA'
AND OBJECT_TYPE='INDEX'


--2. MOVE TABLESPACE

SELECT 'ALTER TABLE '||OBJECT_NAME||' MOVE TABLESPACE SDADATA;'  FROM DBA_OBJECTS 
WHERE OWNER='SDA'
AND OBJECT_TYPE='TABLE'




SELECT 'ALTER TABLE '||OWNER||'.'||OBJECT_NAME||'  MOVE TABLESPACE EPAYHISTDATA;'  FROM DBA_OBJECTS
WHERE OWNER='EPAYMENT'
AND OBJECT_TYPE='TABLE'
AND OBJECT_NAME='EPAY_UTILITY_BILL_HSTR'


ALTER TABLE EPAYMENT.EPAY_UTILITY_BILL_HSTR  MOVE TABLESPACE EPAYHISTDATA;

SELECT 'ALTER INDEX '||OWNER||'.'||OBJECT_NAME||'  REBUILD TABLESPACE EPAYHISTINDX;'  FROM DBA_OBJECTS A
WHERE OWNER='EPAYMENT'
AND OBJECT_TYPE='INDEX'
AND UPPER(OBJECT_NAME) IN  ('EPAY_UTILITY_BILL_HSTR_INDX1')


SELECT *  FROM DBA_OBJECTS 
WHERE OWNER='SDA'
AND OBJECT_TYPE='TABLE'


SELECT 'ALTER TABLE '||OBJECT_NAME||' MOVE TABLESPACE SDADATA;'  FROM DBA_OBJECTS 
WHERE OWNER='SDA'
AND OBJECT_TYPE='TABLE'