
SELECT * FROM EPAY_PAYMENT_MST
WHERE STATUS='P'

SELECT L.CENTER_NAME,COUNT(*) FROM EPAY_PAYMENT_MST M,EPAY_LOCATION_MASTER L
WHERE M.LOCATION_CODE=L.LOCATION_CODE
AND M.STATUS='P'
GROUP BY L.CENTER_NAME
ORDER BY 1 


SELECT L.CENTER_NAME,M.BATCH_NO,M.PAY_DATE,M.LOCATION_CODE LOC_CODE,M.TOTAL_PDB_AMOUNT, M.REVENUE_STAMP_AMOUNT, M.NET_PDB_AMOUNT, M.TOTAL_GOVT_DUTY 
FROM EPAY_PAYMENT_MST M,EPAY_LOCATION_MASTER L
WHERE M.LOCATION_CODE=L.LOCATION_CODE
AND M.STATUS='P'
ORDER BY 3


