INSERT INTO EPAY_USER_MST
SELECT NULL,BANK_CODE||BRANCH_CODE||'02','123456','67',BANK_CODE,BRANCH_CODE,SYSDATE,'ePayment Ofline',NULL,NULL,'N',LOCATION_CODE,NULL FROM EPAY_BANK_BRANCHES
WHERE LOCATION_CODE IN (SELECT LOCATION_CODE FROM EPAY_LOCATION_MASTER WHERE CENTER_NAME='MOULAVIBAZAR')
and bank_code not in ('96','97');



