
select 
"CUST_ENT_ID",
"METER_NUM",
"METER_COND",
"METER_LOCATION",
to_number("OPN_KWH_RDNG") OPN_KWH_RDNG,
to_number("CLS_KWH_SR_RDNG") CLS_KWH_SR_RDNG,
to_number("CONS_KWH_SR") CONS_KWH_SR,
"CF",
"OMF",
"OMF_KVARH",
"LINE_LOSS",
to_number("TOTAL_ENERGY_KWH") TOTAL_ENERGY_KWH,
"EQUIP_ID_KVARH",
"METER_SRL_NO_KVARH",
"METER_NUM_KVARH",
"METER_COND_KVARH",
"METER_LOCATION_KVARH",
to_number("OPN_KVARH_RDNG") OPN_KVARH_RDNG,
to_number("CLS_KVARH_RDNG") CLS_KVARH_RDNG,
to_number("CONS_KVARH_SR") CONS_KVARH_SR,
to_number("TOTAL_KVARH") TOTAL_KVARH,
"UPDATE_BY",
"REC_STATUS",
to_number("ADJUST_UNIT") ADJUST_UNIT,
"BUS_LOSS"
from ubill.BC_UTILITY_BILL_ENTRY_DTL
where ENTRY_ID in (
select  ENTRY_ID  from ubill.BC_UTILITY_BILL_ENTRY_HDR
where bill_cycle_code LIKE NVL(:P2_BILL_CYCLE,'%')
and grid_id=:P2_GRID_ID) 
