

select ed.METER_NUM,ed.OPN_KWH_RDNG,ed.CLS_KWH_SR_RDNG,ed.CONS_KWH_SR, ed.METER_NUM_KVARH,ed.OPN_KVARH_RDNG,ed.CLS_KVARH_RDNG,ed.CONS_KVARH_SR
from ubill.BC_UTILITY_BILL_ENTRY_DTL ed,ubill.BC_UTILITY_BILL_ENTRY_hdr eh,ubill.BC_METER_GRID_CK_COMB_BILL_MST mg,ubill.BC_DIV_CODE_MST dm--,BC_CUSTOMERS C
where ed.ENTRY_ID=eh.ENTRY_ID
and eh.GRID_ID = mg.GRID_ID
and mg.DIV_CODE = dm.DIV_CODE
and eh.BILL_CYCLE_CODE='202010'  
--and mg.DIV_CODE='311D99'
and eh.GRID_ID=3



select ed.METER_NUM,ed.OPN_KWH_RDNG,ed.CLS_KWH_SR_RDNG,(ed.CLS_KWH_SR_RDNG-ed.OPN_KWH_RDNG) diff,ed.CONS_KWH_SR, 
ed.METER_NUM_KVARH,ed.OPN_KVARH_RDNG,ed.CLS_KVARH_RDNG,(ed.CLS_KVARH_RDNG-ed.OPN_KVARH_RDNG) diff,ed.CONS_KVARH_SR
from ubill.BC_UTILITY_BILL_ENTRY_DTL ed,ubill.BC_UTILITY_BILL_ENTRY_hdr eh,ubill.BC_METER_GRID_CK_COMB_BILL_MST mg,ubill.BC_DIV_CODE_MST dm--,BC_CUSTOMERS C
where ed.ENTRY_ID=eh.ENTRY_ID
and eh.GRID_ID = mg.GRID_ID
and mg.DIV_CODE = dm.DIV_CODE
and eh.BILL_CYCLE_CODE='202010'  
--and mg.DIV_CODE='311D99'
--and eh.GRID_ID=3
and ed.METER_NUM like '%50148679%'