

select l.DESCR,INVOICE_DUE_DATE,count(*) from bc_bill_image bi,bc_location_master l
where bi.LOCATION_CODE = l.LOCATION_CODE
and bi.bill_cycle_code='202104'
and invoice_num is not null
group by l.DESCR,INVOICE_DUE_DATE
order by 2

----BILL CHECK
SELECT BI.CUSTOMER_NUM,C.CUSTOMER_NAME, DECODE((SELECT COUNT(*) FROM BC_RECEIPT_HDR WHERE INVOICE_NUM=BI.INVOICE_NUM
AND  TO_CHAR(RECEIPT_DATE,'RRRRMM')='202106'),'0','Not Complite','1','Complite') PAYMENT_STATUS,
DECODE((SELECT COUNT(*) FROM BC_INVOICE_HDR WHERE CUST_ID=BI.CUST_ID AND BILL_CYCLE_CODE='202105'),'0','Not Complite','1','Complite') BILL_STATUS
FROM BC_BILL_IMAGE BI,BC_CUSTOMERS C
WHERE BI.CUST_ID=C.CUST_ID
AND BI.LOCATION_CODE = C.LOCATION_CODE 
AND bill_cycle_code='202104'
AND INVOICE_NUM IS NOT NULL
ORDER BY BI.LOCATION_CODE ASC

SELECT * FROM BC_BILL_IMAGE
WHERE bill_cycle_code='202103'
AND INVOICE_NUM IS NOT NULL