

SELECT LOCATON_DESCR,a.CUSTOMER_NAME,
A.GRID_NAME "Grid Name",A.METER_NUM "Meter Num KWH",
a.Voltage_Level "Voltage Level",a.TIME_CYCLE_CODE "Time Cycle",
A.Previous_Reading "Previous Reading",A.Closing_Reading "Closing Reading",
 to_number(A.Consumption) "Consumption",A.CF CF,A.OMF OMF,
 to_number(A.Total_Energy+decode(sign(ADJ_KWHR),1,ADJ_KWHR,0)) "Total Energy",
 B.METER_NUM "Meter Num KVAR",B.Previous_Reading "Previous Reading KVAR",B.Closing_Reading "Closing Reading KVAR", B.Consumption "Consumption KVAR",
A.Bus_Loss "Bus Loss",A.Line_Loss "Line Loss",A.PF,
decode(a.location_code,'GM',A.Export_Enery_KWHR+decode(sign(ADJ_KWHR),-1,ADJ_KWHR,0),A.Export_Enery_KWHR) "Export Energy KWHR",
ADJ_KWHR 
FROM
(SELECT BC.CUSTOMER_NAME, B.GRID_NAME,C.METER_NUM METER_NUM,DECODE(C.VOLTAGE_CATEGORY_CODE,'V01','0.4 KV','V02','11 KV','V03','33 KV','V04','132 KV') Voltage_Level,
DECODE(D.TIME_CYCLE_CODE,'1','SR','2','OFPK','3','PK') TIME_CYCLE_CODE,bc.location_code,
D.OPN_KWH_RDNG Previous_Reading,D.CLS_KWH_SR_RDNG Closing_Reading,D.CONS_KWH_SR Consumption,D.CF CF,D.OMF OMF,
decode(METER_FLOW_TYPE,'IMP',nvl(D.TOTAL_ENERGY_KWH,0)+NVL(CD.LOSS_CONSUMPTION,0),nvl(D.TOTAL_ENERGY_KWH,0)) Total_Energy,
nvl(CD.BUS_LOSS,0) +nvl(CD.BUS_LOSS_ADJ,0) Bus_Loss,NVL(CD.LINE_LOSS,0) +NVL(CD.LINE_LOSS_ADJ,0)  Line_Loss,CD.POWER_FACTOR PF,
decode(METER_FLOW_TYPE,'IMP',NVL(CD.LOSS_CONSUMPTION,0),0) Export_Enery_KWHR,
decode(METER_FLOW_TYPE,'IMP',0,NVL(CD.LOSS_CONSUMPTION,0)) ADJ_KWHR,
D.METER_SRL_NO KWH_SRL_NO
--Round(nvl(CD.NET_POWER_FACTOR,0)*nvl(D.TOTAL_ENERGY_KWH,0)) Energy_PFC
---Round(nvl(cd.pfc_Unit,0)+nvl(cd.pfc_adj_unit,0)) Energy_PFC
FROM BC_UTILITY_BILL_ENTRY_HDR A,BC_METER_GRID_CK_COMB_BILL_MST B,BC_METER_GRID_CK_COMB_BILL_DTL C,BC_UTILITY_BILL_ENTRY_DTL D,ebc.BC_METER_READING_CARD_DTL
 CD,ebc.BC_CUSTOMERS
 BC
WHERE A.GRID_ID=B.GRID_ID
AND A.BILL_CYCLE_CODE=:p_BILL_CYCLE
AND C.CUST_ID=BC.CUST_ID
AND C.CUST_NUM=:p_CUST_NUM
AND A.ENTRY_ID=D.ENTRY_ID
AND C.EQUIP_ID=D.EQUIP_ID
AND D.TIME_CYCLE_CODE=CD.TIME_CYCLE_CODE
AND D.TOD_CODE=CD.TOD_CODE
AND D.READING_TYPE_CODE=CD.READING_TYPE_CODE
AND CD.BILL_CYCLE_CODE=:p_BILL_CYCLE
--AND B.DIV_CODE='311799'
AND CD.METER_ID=D.EQUIP_ID
--and METER_FLOW_TYPE<>'IMP'
ORDER BY B.GRID_NAME,C.METER_NUM 
) A,
(
SELECT LOCATON_DESCR, B.GRID_NAME,D.METER_NUM_KVARH METER_NUM,DECODE(C.VOLTAGE_CATEGORY_CODE,'V01','0.4 KV','V02','11 KV','V03','33 KV','V04','132 KV') Voltage_Level,
DECODE(D.TIME_CYCLE_CODE,'1','SR','2','OFPK','3','PK') TIME_CYCLE_CODE,
D.OPN_KVARH_RDNG Previous_Reading,D.CLS_KVARH_RDNG Closing_Reading,D.CONS_KVARH_SR Consumption,D.CF CF,D.OMF OMF,TOTAL_KVARH Total_Energy,
D.METER_SRL_NO_KVARH KVAR_SRL_NO
FROM BC_UTILITY_BILL_ENTRY_HDR A,BC_METER_GRID_CK_COMB_BILL_MST B,BC_METER_GRID_CK_COMB_BILL_DTL C,BC_UTILITY_BILL_ENTRY_DTL D,BC_CUSTOMERS
 BC, BC_METER_LOCATION loc
WHERE A.GRID_ID=B.GRID_ID
AND A.BILL_CYCLE_CODE=:p_BILL_CYCLE
AND C.CUST_NUM=:p_CUST_NUM
--AND B.DIV_CODE='311799'
AND C.CUST_ID=BC.CUST_ID
AND A.ENTRY_ID=D.ENTRY_ID
AND C.EQUIP_ID=D.EQUIP_ID
and A.GRID_ID=loc.GRID_ID
and b.GRID_ID=loc.GRID_ID
and c.METER_LOCATION=loc.METER_LOCATION_CODE
) B
WHERE A.KWH_SRL_NO=B.KVAR_SRL_NO
AND A.TIME_CYCLE_CODE=B.TIME_CYCLE_CODE
--ORDER BY LOCATON_DESCR
---and A.GRID_NAME like 'Ha%'