
select * from bc_customers
where CUSTOMER_NAME like '%Nao%'

SELECT a.METER_NUM,a.TOTAL_ENERGY_KWH,a.BUS_LOSS,a.LINE_LOSS,a.ADJUST_UNIT FROM UBILL.BC_UTILITY_BILL_ENTRY_DTL a,UBILL.BC_METER_GRID_CK_COMB_BILL_DTL b
WHERE a.METER_NUM=b.METER_NUM
and a.EQUIP_ID=b.EQUIP_ID
and b.CUST_ID=cid(9113122)
and a.BILL_CYCLE_CODE='202003'
--AND b.METER_NUM    like '%50499709%'
