

--v02---11kv
--v03---33kv
--v04---132kv

--power factore find 
select 54720/sqrt(POWER(54720,2)+POWER(0,2)) from dual

select * from bc_customers
where CUSTOMER_NAME like '%Pab%'


select BUS_LOSS_ADJ,LINE_LOSS_ADJ,b.METER_NUM,a.METER_READING_ID,a.OPN_READING,a.CLS_READING,
a.NET_POWER_FACTOR, BILLED_VALUE,NET_VALUE,LOSS_CONSUMPTION,BUS_LOSS,LINE_LOSS 
FROM BC_METER_READING_CARD_DTL a,bc_customer_meter b
 WHERE a.CUST_ID=b.CUST_ID
 and a.METER_SIDE = b.METER_SIDE
 and a.METER_STATUS = b.METER_STATUS
 and a.METER_ID=b.EQUIP_ID
-- and a.READING_TYPE_CODE=2
--and a.cust_id=cid(9113143)
 and a.bill_cycle_code='202206'
and b.METER_NUM like '%50147692E%'

--dpdc--33kv
1957563

--1957465,1957451,1957881,1957874

update BC_METER_READING_CARD_DTL
set NET_VALUE = null
where bill_cycle_code='202103'
and METER_READING_ID=1957465

commit;

select * from bc_customer_meter cm,bc_meter_reading_card_dtl cd
where cm.CUST_ID = cd.CUST_ID
and cm.EQUIP_ID=cd.METER_ID
and cd.BILL_CYCLE_CODE='202008'
and cm.METER_NUM like '%50136098%'

--42686037
--1927418,1927206,1927140,1927168,1927362,1927289,1927444,1927259,1927313,1927160,1927333,1927454,1927430,
--1927445,1927219,1927464,1927307,1927452,1927279,1927436,1927396,1927391,1927466
--1927367 0.81 -->T-1 Auxilary -->BD004913-->ruppur grid




select LOSS_CONSUMPTION,BUS_LOSS_ADJ,LINE_LOSS_ADJ,b.METER_NUM,a.METER_READING_ID,a.OPN_READING,a.CLS_READING,a.POWER_FACTOR,a.NET_POWER_FACTOR, BILLED_VALUE,NET_VALUE,BUS_LOSS,LINE_LOSS 
FROM BC_METER_READING_CARD_DTL a,bc_customer_meter b
 WHERE a.CUST_ID=b.CUST_ID
 and a.METER_SIDE = b.METER_SIDE
 and a.METER_STATUS = b.METER_STATUS
 and a.METER_ID=b.EQUIP_ID
-- and a.READING_TYPE_CODE=2
and a.cust_id=cid(9113125)
 and a.bill_cycle_code='202006'
--and b.METER_NUM like '%3100064%'



 
-6321850
 --50149041E	1922725 golahat  50148461E	1922795
 --------------------------------------------------------
 
 select d.METER_NUM,e.LOCATON_DESCR,d.OPN_KWH_RDNG,d.OMF,d.OPN_KVARH_RDNG,d.OMF_KVARH,c.CUSTOMER_NAME,c.CUSTOMER_NUM,d.BILL_CYCLE_CODE 
from BC_METER_GRID_CK_COMB_BILL_DTL a,BC_METER_GRID_CK_COMB_BILL_MST b,bc_customers c,BC_METER_LOCATION e,BC_UTILITY_BILL_ENTRY_DTL d
where a.GRID_ID = b.GRID_ID
and a.CUST_ID = c.CUST_ID
and a.GRID_ID=e.GRID_ID
and a.METER_LOCATION=e.METER_LOCATION_CODE
and b.GRID_ID = e.GRID_ID
and a.EQUIP_ID = d.EQUIP_ID
and a.METER_NUM = d.METER_NUM
and d.METER_NUM like '%50136098%'
and d.BILL_CYCLE_CODE between '202005' and '202006'
and a.GRID_ID=127
order by d.BILL_CYCLE_CODE desc
 
 
 
 
 
 
 
 
 
 
 
 
 
 select LOSS_CONSUMPTION,BUS_LOSS,BUS_LOSS_ADJ,LINE_LOSS_ADJ,LINE_LOSS,b.METER_NUM,a.* FROM BC_METER_READING_CARD_DTL a,bc_customer_meter b
 WHERE a.CUST_ID=b.CUST_ID
 and a.METER_SIDE = b.METER_SIDE
 and a.METER_STATUS = b.METER_STATUS
 and a.METER_ID=b.EQUIP_ID
 --and a.READING_TYPE_CODE=2
and a.cust_id=cid(9113048)
 and a.bill_cycle_code='202005'
 --and a.VOLTAGE_CATEGORY_CODE='V03'
 --and b.METER_NUM like '%50146912%'
  --AND A.METER_READING_ID=1911246
   --and a.POWER_FACTOR<'0.90'
 --3414777
 
 
 
 SELECT  VCM.VOLTAGE_CATEGORY_CODE VC, DECODE(VCM.VOLTAGE_CATEGORY_CODE,'V02','V03',VCM.VOLTAGE_CATEGORY_CODE) VOLTAGE_CATEGORY_CODE ,
  DECODE(VCM.VOLTAGE_CATEGORY_CODE,'V02','33 KV', CODE_DESCR)  CODE_DESCR, 
  B.GRID_ID,BC.CUSTOMER_NAME, DECODE(VCM.VOLTAGE_CATEGORY_CODE,'V02', B.GRID_NAME ||'('||CODE_DESCR||')',B.GRID_NAME) GRID_NAME,
TO_NUMBER(ROUND(SUM(NVL(CD.NET_VALUE,0)+DECODE(SIGN(CD.LOSS_CONSUMPTION),1,CD.LOSS_CONSUMPTION,0))) ) " Import Energy KWHR" ,
ROUND(SUM(NVL(CD.BUS_LOSS,0))) "Bus Loss",ROUND(SUM(NVL(CD.LINE_LOSS,0))) "Line Loss",
ABS(ROUND(SUM(DECODE(SIGN(CD.LOSS_CONSUMPTION),-1,CD.LOSS_CONSUMPTION,0)))) "Export Energy KWHR ",
--to_number(Round(SUM(nvl(CD.pfc,0)*(NVL(CD.LOSS_CONSUMPTION,0)+nvl( cD.net_value,0))))) "Energy for PFC"
---ROUND(SUM(NVL(pfc_unit,0) +nvl(PFC_ADJ_UNIT,0))) "Energy for PFC",
SUM(NVL(ADJUST_UNIT,0)) ADJUST_UNIT,
TO_NUMBER(ROUND(SUM(NVL(CD.NET_VALUE,0))))+
ROUND(SUM(NVL(CD.BUS_LOSS,0)))+
ROUND(SUM(NVL(CD.LINE_LOSS,0)))+
ROUND(SUM(NVL(CD.LOSS_CONSUMPTION,0))) NET
FROM UBILL.BC_UTILITY_BILL_ENTRY_HDR A,
UBILL.BC_METER_GRID_CK_COMB_BILL_MST B,
UBILL.BC_METER_GRID_CK_COMB_BILL_DTL C,
UBILL.BC_UTILITY_BILL_ENTRY_DTL D,
EBC.BC_VOLTAGE_CATEGORY_CODE  VCM,
(SELECT CUST_ID,BILL_CYCLE_CODE,METER_ID,TIME_CYCLE_CODE,MAX(PFC) PFC,SUM(NET_VALUE) NET_VALUE,SUM(NVL(LINE_LOSS,0)+NVL(LINE_LOSS_ADJ,0)) LINE_LOSS,SUM(PFC_UNIT) PFC_UNIT,
SUM(NVL(BUS_LOSS,0)+NVL(BUS_LOSS_ADJ,0)) BUS_LOSS,SUM(LOSS_CONSUMPTION) LOSS_CONSUMPTION 
FROM BC_METER_READING_CARD_DTL 
 WHERE READING_TYPE_CODE=2
GROUP BY CUST_ID,BILL_CYCLE_CODE,METER_ID,TIME_CYCLE_CODE) CD,
BC_CUSTOMERS BC
WHERE A.GRID_ID=B.GRID_ID
AND A.BILL_CYCLE_CODE=:P_BILL_CYCLE
--and b.grid_id=113
AND CD.CUST_ID=EBC.CID(:P_CUST_NUM)
--AND CD.CUST_ID='63224'
---AND C.CUST_NUM=:P_CUST_NUM
AND C.CUST_ID=BC.CUST_ID
AND VCM.VOLTAGE_CATEGORY_CODE=C.VOLTAGE_CATEGORY_CODE
AND A.ENTRY_ID=D.ENTRY_ID
AND C.EQUIP_ID=D.EQUIP_ID
AND CD.BILL_CYCLE_CODE=:P_BILL_CYCLE
AND CD.METER_ID=D.EQUIP_ID
AND CD.TIME_CYCLE_CODE=D.TIME_CYCLE_CODE
GROUP BY VCM.VOLTAGE_CATEGORY_CODE,DECODE(VCM.VOLTAGE_CATEGORY_CODE,'V02','V03',VCM.VOLTAGE_CATEGORY_CODE)  ,
  DECODE(VCM.VOLTAGE_CATEGORY_CODE,'V02','33 KV', CODE_DESCR)  , 
  B.GRID_ID,BC.CUSTOMER_NAME, DECODE(VCM.VOLTAGE_CATEGORY_CODE,'V02', B.GRID_NAME ||'('||CODE_DESCR||')',B.GRID_NAME)  
ORDER BY DECODE(VCM.VOLTAGE_CATEGORY_CODE,'V02','V03',VCM.VOLTAGE_CATEGORY_CODE) ASC,VCM.VOLTAGE_CATEGORY_CODE  DESC
 
