

SELECT BILL_CYCLE_CODE month,CUSTOMER_NUM||CONS_CHK_DIGIT CUST_NUM,INVOICE_NUM INV_NUM,INVOICE_DUE_DATE DUE_DATE,RCPT_DATE_1 rcp_1,RCPT_DATE_2 rcp_2,RCPT_DATE_3 rcp_3,
    CONS_KWH_SR UNIT, (NVL(ENG_CHRG_SR,0)+ NVL(ENG_CHRG_OFPK,0)+NVL(ENG_CHRG_PK,0)+NVL(MINIMUM_CHRG,0) +NVL(SERVICE_CHRG,0)+NVL(DEMAND_CHRG,0)+
       NVL(XF_RENT,0)+NVL(XF_LOSS_CHRG,0)+NVL(PFC_CHARGE,0)) CURR_BILL,CURRENT_LPS cur_lps,ARR_ADV_ADJ_PRN arr_prn,ARR_ADV_ADJ_LPS arr_lps,NVL(ADJUSTED_PRN,0)+NVL(ADJUSTED_LPS,0) ADJ_PRN,TOTAL_BILL,
       nvl(RCPT_PRN_1,0)+nvl(RCPT_PRN_2,0)+nvl(RCPT_PRN_3,0)+nvl(RCPT_VAT_1,0)+nvl(RCPT_VAT_2,0)+nvl(RCPT_VAT_3,0) total_receipt,RCPT_PRN_1 rc_pr1,RCPT_PRN_2 rc_pr2,RCPT_PRN_3 rc_pr3
FROM   BC_BILL_IMAGE
WHERE cust_id =cid(:p_cust_id)
AND INVOICE_NUM IS NOT  NULL
and bill_cycle_code between '201610' and '201908'
--AND CONS_KWH_SR='100'
ORDER BY BILL_CYCLE_CODE DESC