
select * from bc_location_master
order by DESCR

SELECT * FROM BC_BILL_CYCLE_CODE
WHERE BILL_CYCLE_CODE='202008'
AND LOCATION_CODE='Z1'


select * from bc_customers
where location_code='X8'


SELECT B.CUSTOMER_NAME,RH.CUST_NUM,RH.RECEIPT_DATE,B.BANK_CODE||'-'||B.BANK_NAME BANK_NAME,BR.BRANCH_CODE||'-'||BR.BRANCH_NAME BRANCH_NAME,SUM(RH.RECEIPT_AMT+RH.VAT_AMT) TOTAL_AMT, 
SUM(RH.RECEIPT_OFFSET+RH.VAT_OFFSET) TOT_OFFSET,SUM(RH.RECEIPT_AMT+RH.VAT_AMT)-SUM(RH.RECEIPT_OFFSET+RH.VAT_OFFSET) DIIFF,RH.LPS_AMT,RH.LPS_OFFSET,BATCH_NUM
FROM BC_RECEIPT_HDR RH,BC_BANKS B,BC_BANK_BRANCHES BR,BC_CUSTOMERS B
WHERE RH.BANK_CODE=B.BANK_CODE
AND RH.BANK_CODE=BR.BANK_CODE
AND RH.BRANCH_CODE=BR.BRANCH_CODE
AND RH.CUST_ID=B.CUST_ID
AND RH.LOCATION_CODE=B.LOCATION_CODE
AND TO_CHAR(RH.RECEIPT_DATE,'rrrrmm')='202204'
--and RH.CUST_ID=cid(91130401)
and rh.location_code='X9'
AND RECEIPT_TYPE_CODE='REC'
GROUP BY B.CUSTOMER_NAME,RH.CUST_NUM,RH.RECEIPT_DATE,B.BANK_CODE||'-'||B.BANK_NAME,BR.BRANCH_CODE||'-'||BR.BRANCH_NAME,RH.LPS_AMT,RH.LPS_OFFSET,BATCH_NUM
ORDER BY 1



select * from bc_receipt_hdr
where TO_CHAR(RECEIPT_DATE,'rrrrmm')='202102'
and CUST_ID=cid(91131268)
AND location_code='X8'
order by receipt_date desc

select * from bc_receipt_hdr
where BATCH_NUM='555511123'

select c.CUSTOMER_NAME,bi.INVOICE_NUM,bi.ENG_CHRG_SR, bi.TOTAL_BILL,bi.INVOICE_DUE_DATE,bi.PFC_CHARGE,bi.invoice_date,bi.CUSTOMER_NUM  from bc_bill_image bi,bc_customers c
where bi.CUST_ID=c.CUST_ID
and bi.LOCATION_CODE = c.LOCATION_CODE
and  bi.bill_cycle_code='202007'
and c.LOCATION_CODE='X3'
and bi.invoice_num is not null
order by 1



select * from bc_banks

select * from bc_bank_branches