

SELECT --(SELECT CR_QNTY FROM SBPA_RM_ITEM_LEDGER WHERE TRANS_TYPE='WP' AND ITEM_CODE=L.ITEM_CODE ) CR_QNTY,
TO_CHAR(TRANS_DATE,'DD/MM/RRRR') TRANS_DATE_C2, 
    DPG_SBPA_ALL_VAT_REPORT.DFN_VAT_6_POINT_1_OPN_QUANTITY(L.ITEM_LEDGER_ID,TO_DATE(:P_START_DATE,'DD/MM/RRRR'),L.ITEM_CODE) OPNEING_QNTY_C3,
    DPG_SBPA_ALL_VAT_REPORT.DFN_VAT_6_POINT_1_OPN_AMOUNT(L.ITEM_LEDGER_ID,TO_DATE(:P_START_DATE,'DD/MM/RRRR'),L.ITEM_CODE) OPENING_RATE_C4,
    CHALLAN_NO CHALLAN_NO_C5,TO_CHAR(PO.PO_DATE,'DD/MM/RRRR') PO_DATE_C6,S.SUP_DESC SUP_NAME_C7,
    S.SUP_ADD1 SUP_ADD_C8,
    CASE WHEN VAT_REG_NO IS NULL AND NID IS NULL         THEN NULL
         WHEN VAT_REG_NO IS NULL AND NID IS NOT NULL     THEN 'Nid:'||NID
         WHEN VAT_REG_NO IS NOT NULL AND NID IS NULL     THEN 'VatRegNo:'||VAT_REG_NO
         WHEN VAT_REG_NO IS NOT NULL AND NID IS NOT NULL THEN 'Nid:'||NID||',VatRegNo:'||VAT_REG_NO
    END SUP_REG_NID_C9,
    ITEM_DESC RI_ITEM_DESC_C10,DB_QNTY||'('||MSR_UNIT_DESC||')' RI_QNTY_C11,DB_QNTY*PR_RATE RI_AMOUNT_C12,
    DB_SD_AMT SUPPLEMENTARY_DUTY_AMT_C13,DB_VAT_AMT VAT_AMT_C14,
    DPG_SBPA_ALL_VAT_REPORT.DFN_VAT_6_POINT_1_OPN_QUANTITY(L.ITEM_LEDGER_ID,TO_DATE(:P_START_DATE,'DD/MM/RRRR'),L.ITEM_CODE)+DB_QNTY TOTAL_STOCK_QNTY_C15,
    DPG_SBPA_ALL_VAT_REPORT_X.DFN_VAT_6_POINT_1_OPN_AMOUNT(L.ITEM_LEDGER_ID,TO_DATE(:P_START_DATE,'DD/MM/RRRR'),L.ITEM_CODE)+DB_QNTY*PR_RATE TOTAL_STOCK_RATE_C16,
    (SELECT CR_QNTY FROM SBPA_RM_ITEM_LEDGER WHERE TRANS_TYPE='WP' AND ITEM_CODE=L.ITEM_CODE ) WP_QNTY_C17,
    (SELECT CR_QNTY FROM SBPA_RM_ITEM_LEDGER WHERE TRANS_TYPE='WP' AND ITEM_CODE=L.ITEM_CODE )*PR_RATE WP_RATE_C18,
   (DPG_SBPA_ALL_VAT_REPORT_X.DFN_VAT_6_POINT_1_OPN_QUANTITY(L.ITEM_LEDGER_ID,TO_DATE(:P_START_DATE,'DD/MM/RRRR'),L.ITEM_CODE)+DB_QNTY)-CR_QNTY CLOSING_BAL_QNTY_C19,
   (DPG_SBPA_ALL_VAT_REPORT_X.DFN_VAT_6_POINT_1_OPN_AMOUNT(L.ITEM_LEDGER_ID,TO_DATE(:P_START_DATE,'DD/MM/RRRR'),L.ITEM_CODE)+DB_QNTY*PR_RATE)-(CR_QNTY*PR_RATE) CLOSING_AMOUNT_C20,
    L.REMARKS REMARKS_C21
     FROM SBPA_RM_ITEM_LEDGER L,
          SBPA_ITEM_MST I,
          SBPA_MEASUREMENT_UNIT M,
          SBPA_PO_MST PO,
          SBPA_RI_MST RI,
          SBPA_SUPPLIER_MST S
    WHERE L.ITEM_CODE = I.ITEM_CODE
    AND L.MSR_UNIT_CODE = I.MSR_UNIT_CODE
    AND I.MSR_UNIT_CODE = M.MSR_UNIT_CODE
    AND L.PO_NO = PO.PO_NO
    AND PO.PO_NO = RI.PO_NO
    AND L.RI_NO=RI.RI_NO
    AND L.SUP_NO = S.SUP_NO
    AND TRUNC(TRANS_DATE)>=TO_DATE(:P_START_DATE,'DD/MM/RRRR')
    AND TRUNC(TRANS_DATE)<=TO_DATE(:P_END_DATE,'DD/MM/RRRR')
    ORDER BY ITEM_LEDGER_ID;