INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='J1') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='J1'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='J1')
and BILL_MONTH='202105'
AND LOCATION_CODE='J1';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='J2') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='J2'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='J2')
and BILL_MONTH='202105'
AND LOCATION_CODE='J2';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='J3') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='J3'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='J3')
and BILL_MONTH='202105'
AND LOCATION_CODE='J3';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='J4') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='J4'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='J4')
and BILL_MONTH='202105'
AND LOCATION_CODE='J4';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='J5') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='J5'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='J5')
and BILL_MONTH='202105'
AND LOCATION_CODE='J5';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='J8') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='J8'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='J8')
and BILL_MONTH='202105'
AND LOCATION_CODE='J8';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='K6') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='K6'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='K6')
and BILL_MONTH='202105'
AND LOCATION_CODE='K6';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='K7') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='K7'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='K7')
and BILL_MONTH='202105'
AND LOCATION_CODE='K7';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='K8') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='K8'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='K8')
and BILL_MONTH='202105'
AND LOCATION_CODE='K8';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='M1') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M1'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M1')
and BILL_MONTH='202105'
AND LOCATION_CODE='M1';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='M2') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M2'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M2')
and BILL_MONTH='202105'
AND LOCATION_CODE='M2';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='M3') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M3'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M3')
and BILL_MONTH='202105'
AND LOCATION_CODE='M3';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='M4') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M4'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M4')
and BILL_MONTH='202105'
AND LOCATION_CODE='M4';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='M5') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M5'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M5')
and BILL_MONTH='202105'
AND LOCATION_CODE='M5';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='M6') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M6'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M6')
and BILL_MONTH='202105'
AND LOCATION_CODE='M6';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='M7') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M7'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M7')
and BILL_MONTH='202105'
AND LOCATION_CODE='M7';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='M8') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M8'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M8')
and BILL_MONTH='202105'
AND LOCATION_CODE='M8';

COMMIT;

INSERT INTO UTILITY_BILL_PDB@EPAY_ROBI
SELECT COMPANY_CODE,ACCOUNT_NUMBER,BILL_NUMBER,
GENERATED_DATE,BILL_STATUS,BILL_DUE_DATE,
BILLAMT_AFTERDUEDATE,BILLENDDATE_FORPAYMENT,
CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY,
NOTIFICATION_SENT_STATUS,CURRENT_PRINCIPLE,
CURRENT_GOVT_DUTY,ARREAR_PRINCIPLE,
ARREAR_GOVT_DUTY,LATE_PAYMENT_SURCHARGE,
TOTAL_BILL_AMOUNT,LOCATION_CODE,BILL_MONTH,
TARIFF,CUSTOMER_TYPE,CURRENT_SURCHARGE,
ARREAR_SURCHARGE,ADJUSTED_PRINCIPLE,ADJUSTED_GOVT_DUTY,
ADVANCE_AMOUNT,ADJ_ADV_GOVT_DUTY FROM EPAY_UTILITY_BILL
WHERE DATA_TRANS_LOG1='N' 
AND ACCOUNT_NUMBER IN (SELECT ACCOUNT_NO FROM CUSTOMER_MASTER_DATA_PDB@EPAY_ROBI WHERE LOCATION_CODE='M9') 
AND (ACCOUNT_NUMBER, BILL_MONTH) IN (
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M9'
AND DATA_TRANS_LOG1='N'
MINUS
SELECT ACCOUNT_NUMBER, BILL_MONTH FROM UTILITY_BILL_PDB@EPAY_ROBI
WHERE BILL_MONTH='202105'
AND LOCATION_CODE='M9')
and BILL_MONTH='202105'
AND LOCATION_CODE='M9';

COMMIT;
