
SELECT 'WZ_50_2' SERVER_NAME, COUNT(*) TOTAL_CON FROM EPAY_UTILITY_BILL@EPAY_WZPDCL
where  BILL_MONTH='201801'
UNION
SELECT 'SRL_26' SERVER_NAME, COUNT(*) TOTAL_CON FROM EPAY_UTILITY_BILL
where  BILL_MONTH='201801'
UNION
SELECT 'SRL_24' SERVER_NAME,COUNT(*) TOTAL_CON  FROM EPAY_UTILITY_BILL@EPAY_SRL_24
where  BILL_MONTH='201801'
AND COMPANY_CODE='WZPDCL'


SELECT 913047-913029 FROM DUAL



select * from EPAYONLINE.EPAY_PAYMENT_DTL_ONLINE@EPAY_SRL_24


EPAY_PAYMENT_DTL_ONLINE_HIST
EPAY_PAYMENT_DTL_ONLINE_REV

