
---------201411----------------

SELECT D.BILL_NUMBER FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,EPAY_ZONE_CIRCLE_LOC Z,EPAY_ZONE_MASTER ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND Z.LOCATION_CODE=M.LOCATION_CODE
AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND M.PAY_DATE BETWEEN '01-NOV-2014' AND '30-NOV-2014'
AND ZZ.ZONE_CODE='6'
MINUS
SELECT M.BILL_NUMBER FROM VW_EPAY_PAYMENT_MST_DTL M,EPAY_ZONE_CIRCLE_LOC Z,EPAY_ZONE_MASTER ZZ
WHERE Z.LOCATION_CODE=M.LOCATION_CODE
AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND M.PAY_DATE BETWEEN '01-NOV-2014' AND '30-NOV-2014'
AND M.PAY_BANK_CODE='97'
AND ZZ.ZONE_CODE='6'


226329481
226400207
226429625
226488238
252795662
252795966


SELECT 142794-142759,164831-164833 FROM DUAL

SELECT ROBI_CONS_COUNT,PDB_CONS_COUNT,ROBI_CONS_COUNT-PDB_CONS_COUNT AS DIFFERENCE,DECODE(SIGN(ROBI_CONS_COUNT-PDB_CONS_COUNT),-1,'Up to pdb',1,'Up to robi') AS STATUS FROM (
SELECT COUNT(*) AS ROBI_CONS_COUNT FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
--AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:P_MONTH--'201412'-- BETWEEN '01-NOV-2014' AND '30-NOV-2014'
AND ZZ.ZONE_CODE=:P_ZONE_CODE--'6'
) A,(
SELECT COUNT(*) AS PDB_CONS_COUNT FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
--AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:P_MONTH--'201412'-- BETWEEN '01-NOV-2014' AND '30-NOV-2014'
AND ZZ.ZONE_CODE=:P_ZONE_CODE--'6'
AND PAY_BANK_CODE='97'
) B


UP TO PDB 

SELECT D.BILL_NUMBER,M.LOCATION_CODE FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
--AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')='201412'-- BETWEEN '01-NOV-2014' AND '30-NOV-2014'
AND ZZ.ZONE_CODE='6'
AND PAY_BANK_CODE='97'
MINUS
SELECT D.BILL_NUMBER,M.LOCATION_CODE FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
--AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')='201412'-- BETWEEN '01-NOV-2014' AND '30-NOV-2014'
AND ZZ.ZONE_CODE='6'



UP TO ROBI 

SELECT D.BILL_NUMBER,M.LOCATION_CODE FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
--AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:P_MONTH-- BETWEEN '01-NOV-2014' AND '30-NOV-2014'
AND ZZ.ZONE_CODE=:P_ZONE_CODE
group by d.BILL_NUMBER,m.LOCATION_CODE
--having count(d.BILL_NUMBER)>1
MINUS
SELECT D.BILL_NUMBER,M.LOCATION_CODE FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
--AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:P_MONTH-- BETWEEN '01-NOV-2014' AND '30-NOV-2014'
AND ZZ.ZONE_CODE=:P_ZONE_CODE
AND PAY_BANK_CODE='97'

SELECT D.BILL_NUMBER,count(*),M.LOCATION_CODE FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
--AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:P_MONTH-- BETWEEN '01-NOV-2014' AND '30-NOV-2014'
AND ZZ.ZONE_CODE=:P_ZONE_CODE
group by d.BILL_NUMBER,m.LOCATION_CODE
having count(d.BILL_NUMBER)>1



SELECT * FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
and M.location_code='L4'
and m.batch_no in ('15700' )--,'6817')
--AND D.BILL_NUMBER='267624106'


SELECT * FROM epay_PAYMENT_MST M,epay_PAYMENT_DTL D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
and M.location_code='L4'
--AND D.BILL_NUMBER='267624106'
and m.ref_batch_no='15700'

6817
15700

SELECT m.pay_date,m.batch_no,D.BILL_NUMBER,M.LOCATION_CODE FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
--AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:P_MONTH-- BETWEEN '01-NOV-2014' AND '30-NOV-2014'
AND ZZ.ZONE_CODE=:P_ZONE_CODE
and (D.BILL_NUMBER,M.LOCATION_CODE) in (
SELECT D.BILL_NUMBER,M.LOCATION_CODE FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
--AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:P_MONTH-- BETWEEN '01-NOV-2014' AND '30-NOV-2014'
AND ZZ.ZONE_CODE=:P_ZONE_CODE
group by d.BILL_NUMBER,m.LOCATION_CODE
having count(d.BILL_NUMBER)>1) order by D.BILL_NUMBER



SELECT d.BILL_NUMBER,m.pay_date,count(*),M.LOCATION_CODE FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
--AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:P_MONTH
AND ZZ.ZONE_CODE=:P_ZONE_CODE
group by m.pay_date,m.LOCATION_CODE,d.BILL_NUMBER
having count(*)>1


SELECT D.BILL_NUMBER,M.LOCATION_CODE FROM PAYMENT_MST@EPAY_ROBI M,PAYMENT_DTL@EPAY_ROBI D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
--AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:P_MONTH-- BETWEEN '01-NOV-2014' AND '30-NOV-2014'
AND ZZ.ZONE_CODE=:P_ZONE_CODE
group by d.BILL_NUMBER,m.LOCATION_CODE
--having count(d.BILL_NUMBER)>1
MINUS
SELECT D.BILL_NUMBER,M.LOCATION_CODE FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D,V_Z_C_C_L ZZ
WHERE M.BATCH_NO=D.BATCH_NO
AND ZZ.LOCATION_CODE=M.LOCATION_CODE
--AND Z.ZONE_CODE=ZZ.ZONE_CODE
AND TO_CHAR(M.PAY_DATE,'rrrrmm')=:P_MONTH-- BETWEEN '01-NOV-2014' AND '30-NOV-2014'
AND ZZ.ZONE_CODE=:P_ZONE_CODE
AND PAY_BANK_CODE='97'
