
select gm.LOCATION_CODE,l.DESCR LOCATION_name,b.BANK_CODE,b.BANK_NAME,br.BRANCH_CODE,br.BRANCH_NAME,gm.BANK_ACCOUNT_NUM  from bc_banks b,bc_bank_branches br,BC_ACCOUNTID_GLCODE_MAP gm,bc_location_master l
where b.BANK_CODE = br.BANK_CODE
and b.BANK_CODE = gm.BANK_CODE
and br.BANK_CODE = gm.BANK_CODE
and br.BRANCH_CODE = gm.BRANCH_CODE
and gm.LOCATION_CODE = l.LOCATION_CODE
and b.STATUS='A'
order by 1


SELECT LOCATION_CODE,TO_CHAR(RECEIPT_DATE,'RRRRMM') PAY_MONTH,DECODE(BANK_CODE,'96','GP','97','ROBI') BANK,SUM(NVL(RECEIPT_AMT,0)) PRENCIPLE_AMOUNT,SUM(NVL(VAT_AMT,0)) VAT_AMT,
SUM(NVL(RECEIPT_AMT,0)+NVL(VAT_AMT,0)) TOTAL_AMOUNT,COUNT(*) TOTAL_CONSUMER FROM BC_RECEIPT_HDR
WHERE TO_CHAR(RECEIPT_DATE,'RRRRMM')>='202107'
AND TO_CHAR(RECEIPT_DATE,'RRRRMM')<='202201'
AND BANK_CODE IN ('96','97')
AND LOCATION_CODE='E5'
GROUP BY LOCATION_CODE,TO_CHAR(RECEIPT_DATE,'RRRRMM'),DECODE(BANK_CODE,'96','GP','97','ROBI')
ORDER BY 2