


SELECT  * FROM EPAY_PAYMENT_MST
WHERE BATCH_NO='250900'

SELECT * FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201705'
AND BILL_NUMBER IN (
SELECT  BILL_NUMBER FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO='252180')


SELECT * FROM EPAY_UTILITY_BILL
WHERE --BILL_MONTH='201705'
 BILL_NUMBER IN ('595381251','595941163')
 
 
 select * from epay_payment_mst
 where pay_date='21-May-2017'
 and location_code='H1'
 and pay_bank_code='54'
 
 SELECT  * FROM EPAY_PAYMENT_MST
WHERE BATCH_NO='251577'
 
 
 SELECT SUM(CNT)  FROM (
   SELECT COUNT(1) CNT FROM EPAY_RECEIPT_BATCH_HDR_PDB
    WHERE BATCH_NUM_EPAY=:BATCH_NUM_EPAY
        UNION ALL
      SELECT COUNT(1) CNT FROM EPAY_RECEIPT_BATCH_HDR_PDB
    WHERE LOCATION_CODE=:LOCATION_CODE
    AND RECEIPT_DATE=:RECEIPT_DATE
    AND BANK_CODE=:BANK_CODE
    AND BRANCH_CODE=:BRANCH_CODE)
 
    SELECT COUNT(1) CNT FROM EPAY_RECEIPT_BATCH_HDR_PDB
    WHERE BATCH_NUM_EPAY=:BATCH_NUM_EPAY
    
    UNION ALL
    
    SELECT COUNT(1) CNT FROM EPAY_RECEIPT_BATCH_HDR_PDB
    WHERE BATCH_NUM_EPAY=:BATCH_NUM_EPAY
    AND LOCATION_CODE=:LOCATION_CODE
    AND RECEIPT_DATE=:RECEIPT_DATE
    AND BANK_CODE=:BANK_CODE
    AND BRANCH_CODE=:BRANCH_CODE
    
    
    
    SELECT RECEIPT_DATE,LOCATION_CODE,BANK_CODE,BRANCH_CODE,COUNT(*) FROM EPAY_RECEIPT_BATCH_HDR_PDB
    GROUP BY RECEIPT_DATE,LOCATION_CODE,BANK_CODE,BRANCH_CODE
    
    
    WHERE  LOCATION_CODE=:LOCATION_CODE
    AND RECEIPT_DATE=:RECEIPT_DATE
    AND BANK_CODE=:BANK_CODE
    AND BRANCH_CODE=:BRANCH_CODE
    
    
     SELECT * FROM EPAY_RECEIPT_BATCH_HDR_PDB
     WHERE BANK_CODE='02'
        AND LOCATION_CODE='H1'