

select b.BANK_NAME,TO_CHAR(m.PAY_DATE,'RRRRMM') PAY_MONTH,SUM(d.ORG_PRN_AMOUNT+d.VAT_AMOUNT) TOTAL_COLLECTION from epay_payment_mst m,epay_payment_dtl d,epay_banks b
where m.BATCH_NO=d.BATCH_NO
and m.ORG_BANK_CODE=b.BANK_CODE
AND m.ORG_BANK_CODE='05'
and TO_CHAR(m.PAY_DATE,'RRRRMM') BETWEEN '201806' AND '201905'
GROUP BY b.BANK_NAME,TO_CHAR(m.PAY_DATE,'RRRRMM')
ORDER BY 1

SELECT * FROM VW_MBP_BATCH_NOT_GEN@EPAY_SRL_24 

SELECT * FROM VW_BNK_DAYEND_UNCOMPLITE@EPAY_SRL_24

SELECT * FROM VW_BNK_DAYEND_COM_BTCH_NOT_GEN@EPAY_SRL_24  

select * from epay_payment_mst@EPAY_SRL_24 
where PAY_DATE between '01-APR-2019' and '07-APR-2019'
AND ORG_CODE='WZPDCL'
ORDER BY STATUS


select STATUS,COUNT(*) from epay_payment_mst@EPAY_SRL_24 
where TO_CHAR(PAY_DATE,'RRRRMM')='201906'
AND ORG_CODE='WZPDCL'
GROUP BY STATUS
ORDER BY STATUS


select STATUS,COUNT(*) from epay_payment_mst 
where TO_CHAR(PAY_DATE,'RRRRMM')='201906'
AND ORG_CODE='WZPDCL'
GROUP BY STATUS
ORDER BY STATUS


select STATUS,COUNT(*) from epay_payment_mst@EPAY_WZPDCL 
where TO_CHAR(PAY_DATE,'RRRRMM')='201906'
AND ORG_CODE='WZPDCL'
GROUP BY STATUS
ORDER BY STATUS





