
SELECT B.BANK_NAME,L.LOCATION_CODE, L.LOCATION_CODE||'-'||L.LOCATION_NAME LOCATION_NAME,SUM (D.PRINCIPLE_AMOUNT) PRINCIPLE_AMOUNT,SUM (VAT_AMOUNT) VAT_AMOUNT,
    SUM (TOTAL_COLL_AMOUNT) TOTAL_COLL_AMOUNT,SUM (D.REV_STAMP_AMOUNT) REV_STAMP_AMOUNT,SUM (TOTAL_COLL_AMOUNT) - SUM (D.REV_STAMP_AMOUNT) NET_AMOUNT,
    SUM (NO_OF_TRNS) NO_OF_TRNS
    FROM EPAY.EPAY_PAYMENT_MST M,
              EPAY.V_Z_C_C_L L,
              EPAY.EPAY_BANKS B,
    (SELECT BATCH_NO,SUM (NVL (ORG_PRN_AMOUNT, 0)) PRINCIPLE_AMOUNT,SUM (NVL (VAT_AMOUNT, 0)) VAT_AMOUNT,
       SUM (NVL (ORG_PRN_AMOUNT, 0)) + SUM (NVL (VAT_AMOUNT, 0))TOTAL_COLL_AMOUNT, SUM (NVL (REV_STAMP_AMOUNT, 0)) REV_STAMP_AMOUNT,
       COUNT (1) NO_OF_TRNS
    FROM EPAY_PAYMENT_DTL
    GROUP BY BATCH_NO) D
    WHERE M.ORG_BR_CODE = L.LOCATION_CODE
    AND M.BATCH_NO = D.BATCH_NO
    AND M.ORG_BANK_CODE=B.BANK_CODE
    AND ORG_CODE=:P_Org_Code    
     AND M.PAY_DATE>=TO_DATE(:P_Start_Date,'DD-MM-YYYY')
    AND M.PAY_DATE<=TO_DATE(:P_End_Date,'DD-MM-YYYY')
    AND M.ORG_BANK_CODE=:P_Bank_Code
      GROUP BY B.BANK_NAME,L.LOCATION_CODE,L.LOCATION_CODE||'-'||L.LOCATION_NAME
MINUS
SELECT B.BANK_NAME,L.LOCATION_CODE, L.LOCATION_CODE||'-'||L.LOCATION_NAME LOCATION_NAME,SUM (D.PRINCIPLE_AMOUNT) PRINCIPLE_AMOUNT,SUM (VAT_AMOUNT) VAT_AMOUNT,
    SUM (TOTAL_COLL_AMOUNT) TOTAL_COLL_AMOUNT,SUM (D.REV_STAMP_AMOUNT) REV_STAMP_AMOUNT,SUM (TOTAL_COLL_AMOUNT) - SUM (D.REV_STAMP_AMOUNT) NET_AMOUNT,
    SUM (NO_OF_TRNS) NO_OF_TRNS
    FROM EPAY.EPAY_PAYMENT_MST M,
              EPAY.V_Z_C_C_L L,
              EPAY.EPAY_BANKS B,
    (SELECT BATCH_NO,SUM (NVL (ORG_PRN_AMOUNT, 0)) PRINCIPLE_AMOUNT,SUM (NVL (VAT_AMOUNT, 0)) VAT_AMOUNT,
       SUM (NVL (ORG_PRN_AMOUNT, 0)) + SUM (NVL (VAT_AMOUNT, 0))TOTAL_COLL_AMOUNT, SUM (NVL (REV_STAMP_AMOUNT, 0)) REV_STAMP_AMOUNT,
       COUNT (1) NO_OF_TRNS
    FROM EPAY_PAYMENT_DTL
    GROUP BY BATCH_NO) D
    WHERE M.ORG_BR_CODE = L.LOCATION_CODE
    AND M.BATCH_NO = D.BATCH_NO
    AND M.ORG_BANK_CODE=B.BANK_CODE
    AND ORG_CODE=:P_Org_Code    
     AND M.PAY_DATE>=TO_DATE(:P_Start_Date,'DD-MM-YYYY')
    AND M.PAY_DATE<=TO_DATE(:P_End_Date,'DD-MM-YYYY')
    AND M.ORG_BANK_CODE=:P_Bank_Code
    AND (M.ORG_BANK_CODE,M.ORG_BANK_BRANCH_CODE) IN (SELECT BANK_CODE,BRANCH_CODE FROM VW_EPAY_USER_ACCESS_DATA 
                                                                                                WHERE ORG_CODE=:P_Org_Code
                                                                                                AND USER_ID=:P_User_Id
                                                                                                AND BANK_CODE= :P_Bank_Code)
    AND ORG_BR_CODE IN (SELECT LOCATION_CODE FROM VW_EPAY_USER_ACCESS_DATA 
                                         WHERE ORG_CODE=:P_Org_Code
                                         AND USER_ID=:P_User_Id
                                         AND BANK_CODE= :P_Bank_Code)
    GROUP BY B.BANK_NAME,L.LOCATION_CODE,L.LOCATION_CODE||'-'||L.LOCATION_NAME
    --ORDER BY  L.LOCATION_CODE;