
26725

select count(*) from epay_payment_dtl
where batch_no in (
select batch_no from epay_payment_mst
where TO_CHAR(PAY_DATE,'RRRRMM')='201906'
)



-----24----

select status,COUNT(*) from epay_payment_mst
where status<>'T'
AND ORG_CODE='WZPDCL'
AND TO_CHAR(PAY_DATE,'RRRRMM')='201906'
GROUP BY status


select PAY_DATE,COUNT(*) from epay_payment_mst
where status<>'T'
AND ORG_CODE='WZPDCL'
AND TO_CHAR(PAY_DATE,'RRRRMM')='201906'
GROUP BY PAY_DATE 
order by 1 desc



01    National Bank Ltd
03    Mercantile Bank Ltd
04    NRB Bank Ltd
05    Trust Bank Ltd.
400    Dutch Bangla Bank Limited

SELECT * FROM EPAY_PAYMENT_MST
WHERE PAY_DATE  BETWEEN '01-MAR-2019' AND '31-MAR-2019'
AND ORG_BANK_CODE='03'
ORDER BY PAY_DATE DESC

SELECT * FROM PAYMENT_DTL@WZ
WHERE TRANSACTION_DATE BETWEEN '01-MAR-2019' AND '31-MAR-2019'


-----------------

SELECT COUNT(*) FROM PAYMENT_DTL@WZ
WHERE TRANSACTION_DATE BETWEEN '01-MAR-2019' AND '31-MAR-2019'

SELECT * FROM EPAY_PAYMENT_MST
WHERE PAY_DATE='20-MAR-2019'

SELECT COUNT(*) FROM EPAY_PAYMENT_DTL
WHERE BATCH_NO IN (
SELECT BATCH_NO FROM EPAY_PAYMENT_MST
WHERE PAY_DATE  BETWEEN '01-MAR-2019' AND '31-MAR-2019'
)

29239

-------------


SELECT * FROM PAYMENT_DTL@WZ
WHERE TRANSACTION_DATE BETWEEN '20-MAR-2019' AND '31-MAR-2019'
ORDER BY TRANSACTION_DATE DESC

SELECT * FROM EPAY_PAYMENT_MST
WHERE PAY_DATE='20-MAR-2019'