
SELECT TRANSACTION_ID, SUM(ORG_PRN_AMOUNT),SUM(VAT_AMOUNT),SUM(ORG_PRN_AMOUNT+VAT_AMOUNT) TOTAL,COUNT(*) FROM EPAY_PAYMENT_DTL--@EPAY_WZPDCL
WHERE BATCH_NO IN (
SELECT BATCH_NO FROM EPAY_PAYMENT_MST--@EPAY_WZPDCL
WHERE PAY_DATE BETWEEN '01-FEB-2019' AND '28-FEB-2019'
AND ORG_BR_CODE='603'
AND ORG_BANK_CODE='400'
)

)GROUP BY ORG_BANK_CODE


SELECT D.TRANSACTION_ID,M.PAY_DATE,D.ACCOUNT_NUMBER, ORG_PRN_AMOUNT PRN_AMOUNT,VAT_AMOUNT ,SUM(ORG_PRN_AMOUNT+VAT_AMOUNT) TOTAL_AMOUNT,'Rocket' Bank_Name
FROM EPAY_PAYMENT_MST M,EPAY_PAYMENT_DTL D
WHERE M.BATCH_NO=D.BATCH_NO
AND M.PAY_DATE BETWEEN '01-nov-2018' AND '28-nov-2018'
AND M.ORG_BR_CODE='603'
and M.ORG_BANK_CODE='03'
GROUP BY D.TRANSACTION_ID,M.PAY_DATE,D.ACCOUNT_NUMBER,ORG_PRN_AMOUNT,VAT_AMOUNT
order by pay_date