



SELECT * FROM EPAY_PAYMENT_MST
WHERE 
ORG_BANK_CODE='03'
and PAY_DATE='26-SEP-2017'


SELECT * FROM EPAY_PAYMENT_dtl
where batch_no in (
SELECT batch_no FROM EPAY_PAYMENT_MST
WHERE  ORG_BANK_CODE='03'
and PAY_DATE='26-SEP-2017'
)


select * from payment_dtl@wz
where TRANSACTION_DATE='26-SEP-2017'
and (account_no,bill_num,bill_month) in (
SELECT account_number,bill_number,bill_month FROM EPAY_PAYMENT_dtl
where batch_no in (
SELECT batch_no FROM EPAY_PAYMENT_MST
WHERE ORG_BANK_CODE='03'
and PAY_DATE='26-SEP-2017'
))

SELECT * FROM EPAY_PAYMENT_dtl


update EPAY_PAYMENT_MST
set status ='T'
WHERE status <>'T'
AND ORG_BANK_CODE='03'
and PAY_DATE='19-SEP-2017'

SELECT account_number,bill_number,bill_month FROM EPAY_PAYMENT_dtl
where batch_no in (
SELECT batch_no FROM EPAY_PAYMENT_MST
WHERE ORG_BANK_CODE='03'
and PAY_DATE='26-SEP-2017'
)
minus
select account_no,bill_num,bill_month from payment_dtl@wz
where TRANSACTION_DATE='26-SEP-2017'
and (account_no,bill_num,bill_month) in (
SELECT account_number,bill_number,bill_month FROM EPAY_PAYMENT_dtl
where batch_no in (
SELECT batch_no FROM EPAY_PAYMENT_MST
WHERE  ORG_BANK_CODE='03'
and PAY_DATE='26-SEP-2017'
))


SELECT * FROM EPAY_PAYMENT_dtl d,EPAY_PAYMENT_mst m
where d.batch_no=m.batch_no
and  ( account_number,bill_number,bill_month ) in (
SELECT account_number,bill_number,bill_month FROM EPAY_PAYMENT_dtl
where batch_no in (
SELECT batch_no FROM EPAY_PAYMENT_MST
WHERE status <>'T'
AND ORG_BANK_CODE='03'
and PAY_DATE='19-SEP-2017'
)
minus
select account_no,bill_num,bill_month from payment_dtl@wz
where TRANSACTION_DATE='19-SEP-2017'
and (account_no,bill_num,bill_month) in (
SELECT account_number,bill_number,bill_month FROM EPAY_PAYMENT_dtl
where batch_no in (
SELECT batch_no FROM EPAY_PAYMENT_MST
WHERE status <>'T'
AND ORG_BANK_CODE='03'
and PAY_DATE='19-SEP-2017'
)))


INSERT INTO PAYMENT_DTL@WZ 
(COMPANY_CODE,BILL_MONTH,LOCATION_CODE,ACCOUNT_NO,BILL_NUM,
TRANSACTION_ID,TRANSACTION_DATE,BL_CUST_ID,RETAILER_ID,
TOTAL_BILL,TOTAL_VAT,NET_AMOUNT,STAMP_FEE,NET_PAYMENT_TO_GOV,TRANSACTION_CHARGES_RETAINED,
BATCH_ID,REMARKS,STATUS,SCRL_NO,ACCOUNT_CD,CHECK_DIGIT,LATE_PAYMENT_CHARGES,EXCISE,PAID_AMOUNT,BATCH_BL,
CREATE_DATE,CREATE_BY,UPDATE_DATE,UPDATE_BY) VALUES 


(CUR_MST.ORG_CODE,CUR_DTL.BILL_MONTH,CUR_MST.ORG_BR_CODE,CUR_DTL.ACCOUNT_NUMBER ,CUR_DTL.BILL_NUMBER,
CUR_DTL.TRANSACTION_ID,CUR_MST.PAY_DATE,NULL,NULL,
NVL(CUR_DTL.ORG_PRN_AMOUNT,0)+NVL(CUR_DTL.VAT_AMOUNT,0),NVL(CUR_DTL.VAT_AMOUNT,0),NVL(CUR_DTL.ORG_PRN_AMOUNT,0),'400',NVL(CUR_DTL.VAT_AMOUNT,0),NULL,
CUR_MST.BATCH_NO,NULL,'A',CUR_DTL.SCROLL_NO,NULL,NULL,NULL,NULL,NVL(CUR_DTL.ORG_PRN_AMOUNT,0)+NVL(CUR_DTL.VAT_AMOUNT,0),NULL,
SYSDATE,USER,NULL,NULL);

INSERT INTO PAYMENT_DTL@WZ 
(COMPANY_CODE,BILL_MONTH,LOCATION_CODE,ACCOUNT_NO,BILL_NUM,
TRANSACTION_ID,TRANSACTION_DATE,BL_CUST_ID,RETAILER_ID,
TOTAL_BILL,TOTAL_VAT,NET_AMOUNT,STAMP_FEE,NET_PAYMENT_TO_GOV,TRANSACTION_CHARGES_RETAINED,
BATCH_ID,REMARKS,STATUS,SCRL_NO,ACCOUNT_CD,CHECK_DIGIT,LATE_PAYMENT_CHARGES,EXCISE,PAID_AMOUNT,BATCH_BL,
CREATE_DATE,CREATE_BY,UPDATE_DATE,UPDATE_BY)
SELECT CUR_MST.ORG_CODE,CUR_DTL.BILL_MONTH,CUR_MST.ORG_BR_CODE,CUR_DTL.ACCOUNT_NUMBER ,CUR_DTL.BILL_NUMBER,
CUR_DTL.TRANSACTION_ID,CUR_MST.PAY_DATE,NULL,NULL,
NVL(CUR_DTL.ORG_PRN_AMOUNT,0)+NVL(CUR_DTL.VAT_AMOUNT,0),NVL(CUR_DTL.VAT_AMOUNT,0),NVL(CUR_DTL.ORG_PRN_AMOUNT,0),'400',NVL(CUR_DTL.VAT_AMOUNT,0),NULL,
CUR_MST.BATCH_NO,NULL,'A',CUR_DTL.SCROLL_NO,NULL,NULL,NULL,NULL,NVL(CUR_DTL.ORG_PRN_AMOUNT,0)+NVL(CUR_DTL.VAT_AMOUNT,0),NULL,
SYSDATE,USER,NULL,NULL FROM EPAY_PAYMENT_dtl CUR_DTL,EPAY_PAYMENT_mst CUR_MST
where CUR_MST.batch_no=CUR_DTL.batch_no
and  ( account_number,bill_number,bill_month ) in (
SELECT account_number,bill_number,bill_month FROM EPAY_PAYMENT_dtl
where batch_no in (
SELECT batch_no FROM EPAY_PAYMENT_MST
WHERE status <>'T'
AND ORG_BANK_CODE='03'
and PAY_DATE='26-SEP-2017'
)
minus
select account_no,bill_num,bill_month from payment_dtl@wz
where TRANSACTION_DATE='26-SEP-2017'
and (account_no,bill_num,bill_month) in (
SELECT account_number,bill_number,bill_month FROM EPAY_PAYMENT_dtl
where batch_no in (
SELECT batch_no FROM EPAY_PAYMENT_MST
WHERE status <>'T'
AND ORG_BANK_CODE='03'
and PAY_DATE='26-SEP-2017'
)))