
----BILL MONTH THIK KORE DITE HOBE------

INSERT INTO EPAY_UTILITY_BILL_X

SELECT 'WZPDCL' COMPANY_CODE,ACCOUNT_NUM ACCOUNT_NUMBER,BILL_NUM BILL_NUMBER,INVOICE_DATE GENERATED_DATE,'N' BILL_STATUS,
LAST_PAY_DATE BILL_DUE_DATE,NULL BILLAMT_AFTERDUEDATE,LAST_PAY_DATE BILLAMT_AFTERDUEDATE,SYSDATE CREATED_ON,USER CREATED_BY,
null MODIFIED_ON,null MODIFIED_BY,'N' NOTIFICATION_SENT_STATUS,nvl(TOTAL_BILL_AMOUNT,0)-nvl(VAT_AMT,0) CURRENT_PRINCIPLE,VAT_AMT CURRENT_GOVT_DUTY,
0 ARREAR_PRINCIPLE,0 ARREAR_GOVT_DUTY,0 LATE_PAYMENT_SURCHARGE,TOTAL_BILL_AMOUNT, LOCATION_CODE,(SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'YYYYMM') FROM DUAL) AS BILL_MONTH,
NULL TARIFF,NULL CUSTOMER_TYPE,0 CURRENT_SURCHARGE,0 ARREAR_SURCHARGE,0 ADJUSTED_PRINCIPLE,0 ADJUSTED_GOVT_DUTY,0 ADVANCE_AMOUNT,0 ADJ_ADV_GOVT_DUTY,'T' DATA_TRANS_LOG
FROM BC_INVOICE_HDR@WZ
WHERE BILL_MONTH='1802'
AND ACCOUNT_NUM='101110107'
AND LOCATION_CODE='101'


COMMIT;

INSERT INTO  EPAY_UTILITY_BILL
SELECT *  FROM EPAY_UTILITY_BILL_X


SELECT *  FROM EPAY_UTILITY_BILL
where  BILL_MONTH='201802'
AND ACCOUNT_NUMBER='101110107'
AND LOCATION_CODE='101'


SELECT * FROM BC_CUSTOMERS@WZ

SELECT *  FROM EPAY_CUSTOMER_MASTER_DATA

SELECT * FROM BC_INVOICE_HDR@WZ
WHERE BILL_MONTH='1802'
AND ACCOUNT_NUM='101110107'
AND LOCATION_CODE='101'


SELECT TO_CHAR(ADD_MONTHS(SYSDATE,-1),'YYYYMM') FROM DUAL

