
SELECT * FROM BC_INVOICE_HDR@WZ

WHERE SUBSTR(BILL_NUM,1,4)='1909'

and account_num IN ('501130252','501120493')


-----shedual chk--

 SELECT OWNER, JOB_NAME, ELAPSED_TIME FROM DBA_SCHEDULER_RUNNING_JOBS;

  


SELECT * FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201909'
AND ACCOUNT_NUMBER IN ('501130252','501120493')


SELECT COUNT(*) FROM BC_INVOICE_HDR@WZ
WHERE SUBSTR(BILL_NUM,1,4)='1909'
AND NVL(TOTAL_BILL_AMOUNT,0)>=0

--2.10--190351

--50.2---588564


SELECT COUNT(*) FROM EPAY_UTILITY_BILL
where  BILL_MONTH='201909'

select 360208-359538 from dual

select PAY_DATE,count(*),SUM(D.ORG_PRN_AMOUNT+D.VAT_AMOUNT) total from epay_payment_dtl D,epay_payment_mst M
where M.batch_no =D.batch_no 
AND  TO_CHAR(PAY_DATE,'RRRRMM')='201910'
GROUP BY PAY_DATE
ORDER BY 1 DESC


select TRANSACTION_DATE,count(*),sum(TOTAL_VAT+NET_AMOUNT) total from payment_dtl@wz
where  TO_CHAR(TRANSACTION_DATE,'RRRRMM')='201910'
GROUP BY TRANSACTION_DATE 
ORDER BY 1 DESC

201

select pay_date,count(*) from epay_payment_dtl
where batch_no in (
select batch_no from epay_payment_mst
where TO_CHAR(PAY_DATE,'RRRRMM')='201909'
)

201

select TRUNC(TRANSACTION_DATE),count(*) from payment_dtl@wz
where  TO_CHAR(TRANSACTION_DATE,'RRRRMM')='201909'
GROUP BY TRUNC(TRANSACTION_DATE)
ORDER BY 1 DESC

select * from payment_dtl@wz

MISSING--669

911306

INSERT INTO EPAY_CUSTOMER_MASTER_DATA(COMPANY_CODE,ACCOUNT_NO,NAME,LOCATION_CODE,STATUS,CREATED_ON,CREATED_BY,DUMPING_FOR)
SELECT 'WZPDCL' COMPANY_CODE,ACCOUNT_NUM,'UNKHOWN' NAME,LOCATION_CODE,'A' STATUS,SYSDATE CREATED_ON,'EPAY' CREATED_BY,'I' DUMPING_FOR FROM BC_INVOICE_HDR@WZ
WHERE ACCOUNT_NUM IN(
SELECT ACCOUNT_NUM FROM BC_INVOICE_HDR@WZ
WHERE SUBSTR(BILL_NUM,1,4)='1909'
MINUS
SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA)
AND  SUBSTR(BILL_NUM,1,4)='1909'
AND ACCOUNT_NUM NOT IN(SELECT ACCOUNT_NO FROM EPAY_CUSTOMER_MASTER_DATA)

COMMIT;





-------------------50.2

select sum(ORG_PRN_AMOUNT),sum(VAT_AMOUNT),sum(ORG_PRN_AMOUNT+VAT_AMOUNT)total, count(*) from epay_payment_dtl
where batch_no in (
select batch_no from epay_payment_mst
where TO_CHAR(PAY_DATE,'RRRRMM')='201910'
)

4312679.9	214334.1	4527014	3817

----------------------------2.10

4312679.9	214334.1	4527014	3817

select sum(NET_AMOUNT),sum(TOTAL_VAT),sum(NET_AMOUNT+TOTAL_VAT)total, count(*) from payment_dtl@wz
where  TO_CHAR(TRANSACTION_DATE,'RRRRMM')='201910'





SELECT ACCOUNT_NUM  FROM BC_INVOICE_HDR@WZ
WHERE BILL_MONTH='1801'
AND NVL(TOTAL_BILL_AMOUNT,0)>=0
MINUS
SELECT ACCOUNT_NUMBER FROM EPAY_UTILITY_BILL
WHERE BILL_MONTH='201801'

102126411
102132984
102137623
102163593

SELECT * FROM BC_customers@WZ
WHERE ACCOUNT_NUM =:ACCOUNT_NUM

select * from epay_customer_master_data
where ACCOUNT_NO=:ACCOUNT_NUM

select *
 from epay_utility_bill
where account_number='305152659'
and bill_month='201801'


SELECT *  FROM BC_INVOICE_HDR@WZ
WHERE ACCOUNT_NUM='305152659'
and  BILL_MONTH='1711'
and ACCOUNT_NUM='305152659'




select M.PAY_DATE,sum(ORG_PRN_AMOUNT+VAT_AMOUNT)total, count(*) from epay_payment_dtl D,epay_payment_mst M
where D.BATCH_NO=M.BATCH_NO
AND TO_CHAR(PAY_DATE,'RRRRMM')='201910'            
GROUP BY M.PAY_DATE
ORDER BY 1 DESC


16562

select TRANSACTION_DATE,sum(NET_AMOUNT+TOTAL_VAT)total, count(*) from payment_dtl@wz
where  TO_CHAR(TRANSACTION_DATE,'RRRRMM')='201910'
group by TRANSACTION_DATE
order by 1 desc



select LOCATION_CODE,count(*),sum(NET_AMOUNT+TOTAL_VAT)total from payment_dtl@wz
where  --TO_CHAR(TRANSACTION_DATE,'RRRRMM')='201909'
TRANSACTION_DATE BETWEEN '01-SEP-2019' AND '17-SEP-2019'
GROUP BY LOCATION_CODE
ORDER BY 1 DESC


select TRANSACTION_DATE,count(*),sum(NET_AMOUNT+TOTAL_VAT)total from payment_dtl@wz
where  --TO_CHAR(TRANSACTION_DATE,'RRRRMM')='201909'
TRANSACTION_DATE BETWEEN '01-SEP-2019' AND '30-SEP-2019'
GROUP BY TRANSACTION_DATE
ORDER BY 1 DESC


select M.ORG_BR_CODE,sum(ORG_PRN_AMOUNT+VAT_AMOUNT)total, count(*) from epay_payment_dtl D,epay_payment_mst M
where D.BATCH_NO=M.BATCH_NO
AND PAY_DATE BETWEEN '01-SEP-2019' AND '30-SEP-2019'
GROUP BY M.ORG_BR_CODE
ORDER BY 1 DESC

/*
SELECT WZ_BLNG_LOC,WZ_BLNG_CON,WZ_SRL_LOC,WZ_SRL_CON,WZ_BLNG_CON-WZ_SRL_CON AS MISSING_CON FROM( 
SELECT LOCATION_CODE WZ_BLNG_LOC ,COUNT(*) WZ_BLNG_CON FROM BC_INVOICE_HDR@wz
where bill_month='1708'
GROUP BY LOCATION_CODE)A,(
SELECT LOCATION_CODE  WZ_SRL_LOC,COUNT(*) WZ_SRL_CON FROM EPAY_UTILITY_bill
where  bill_month='201708'
GROUP BY LOCATION_CODE)B
WHERE WZ_BLNG_LOC=WZ_SRL_LOC
AND A.WZ_BLNG_CON<>B.WZ_SRL_CON*/



